Repository apache/hive, pull requests merged in 2020-06, with the labels that each got.

#1051 HIVE-23404 schq past
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  ql/src/java/org/apache/hadoop/hive/ql/scheduled/ScheduledQueryExecutionService.java
  ql/src/test/org/apache/hadoop/hive/ql/schq/TestScheduledQueryService.java
  ql/src/test/queries/clientpositive/schq_past.q
  ql/src/test/results/clientpositive/llap/schq_past.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-3.2.0-to-4.0.0.derby.sql
Labels: tests passed

#1045 HIVE-23587: Remove JODA Time From LlapServiceDriver
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/LlapServiceDriver.java
Labels: tests passed

#1058 HIVE-23607: Permission Issue: Create view on another view succeeds but alter view fails
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/plan/TestViewEntity.java
Labels: tests passed

#1065 HIVE-23626: Build failure is incorrectly reported as tests passed
  Jenkinsfile
Labels: tests unstable

#1049 HIVE-23590 stale prs
  .asf.yaml
  .github/workflows/stale.yml
Labels: tests unstable

#946 [HIVE-23000] Improve travis.yml
  .travis.yml
Labels: stale, tests pending

#1062 HIVE-23621: Enforce ASF headers on source files
  Jenkinsfile
  common/src/java/org/apache/hive/http/JMXJsonServlet.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestTransactionalValidationListener.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  itests/qtest-druid/src/main/java/org/apache/hive/kafka/SingleNodeKafkaCluster.java
  itests/qtest-druid/src/main/java/org/apache/hive/kafka/Wikipedia.java
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/MiniDruidLlapLocalCliDriver.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/SplitSupport.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/qoption/QTestReplaceHandler.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/scheduled/QTestScheduledQueryCleaner.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/scheduled/QTestScheduledQueryServiceProvider.java
  itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/SplitSupportDummy.java
  itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/split0/SplitSupportDummy.java
  itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/split125/SplitSupportDummy.java
  pom.xml
Labels: tests passed

#1068 HIVE-23628: Add Default Message for Github PRs
  .github/pull_request_template.md
Labels: tests unstable

#1043 HIVE-23482 junit5
  beeline/pom.xml
  cli/pom.xml
  common/pom.xml
  contrib/pom.xml
  hbase-handler/pom.xml
  hcatalog/server-extensions/pom.xml
  hcatalog/webhcat/svr/pom.xml
  hplsql/pom.xml
  jdbc-handler/pom.xml
  jdbc/pom.xml
  kudu-handler/pom.xml
  llap-client/pom.xml
  llap-common/pom.xml
  llap-ext-client/pom.xml
  llap-server/pom.xml
  llap-tez/pom.xml
  metastore/pom.xml
  pom.xml
  ql/pom.xml
  service-rpc/pom.xml
  service/pom.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-tools/metastore-benchmarks/pom.xml
  standalone-metastore/metastore-tools/pom.xml
  standalone-metastore/metastore-tools/tools-common/pom.xml
  standalone-metastore/pom.xml
  storage-api/pom.xml
  streaming/pom.xml
  testutils/pom.xml
Labels: tests passed

#1074 HIVE-23630: stabilize allocateWriteId test in TestTxnHandler by incre…
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
Labels: tests passed

#1075 HIVE-23625: use html file extension for HS2 web UI query_page
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  service/src/resources/hive-webapps/hiveserver2/hiveserver2.jsp
Labels: tests passed

#1031 HIVE-23462 rewrite cume_dist
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/DataSketchesFunctions.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRewriteToDataSketchesRules.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/HiveFunctionHelper.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestDataSketchesFunctions.java
  ql/src/test/queries/clientpositive/sketches_materialized_view_cume_dist.q
  ql/src/test/queries/clientpositive/sketches_rewrite_cume_dist.q
  ql/src/test/queries/clientpositive/sketches_rewrite_cume_dist_partition_by.q
  ql/src/test/results/clientpositive/llap/cbo_rp_windowing_2.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_cume_dist.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_cume_dist.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_cume_dist_partition_by.q.out
Labels: tests passed

#1089 HIVE-23563: Early abort the build in case new commits are added to the PR
  Jenkinsfile
Labels: tests passed

#1054 HIVE-23601: Hive Statement Clear Statement Handle on Error
  jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
Labels: tests passed

#1069 HIVE-23629: Enforce clean findbugs in PRs
  Jenkinsfile
  shims/common/src/main/java/org/apache/hadoop/fs/ProxyFileSystem.java
  shims/common/src/main/java/org/apache/hadoop/fs/ProxyLocalFileSystem.java
  shims/common/src/main/java/org/apache/hadoop/hive/io/HdfsUtils.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/CombineHiveKey.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShimsSecure.java
Labels: tests passed

#839 HIVE-21894: Hadoop credential password storage for the Kafka Storage handler when security is SSL
  kafka-handler/README.md
  kafka-handler/src/java/org/apache/hadoop/hive/kafka/KafkaTableProperties.java
  kafka-handler/src/java/org/apache/hadoop/hive/kafka/KafkaUtils.java
  kafka-handler/src/test/org/apache/hadoop/hive/kafka/KafkaUtilsTest.java
  ql/src/test/results/clientpositive/kafka/kafka_storage_handler.q.out
Labels: stale, tests passed

#1091 HIVE-23615: Null pointers should not be dereferenced
  beeline/src/java/org/apache/hive/beeline/Commands.java
Labels: tests passed

#1070 HIVE-19653: Incorrect predicate pushdown for groupby with grouping sets.
  ql/src/java/org/apache/hadoop/hive/ql/ppd/OpProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/ppd/PredicatePushDown.java
  ql/src/test/queries/clientpositive/groupby_grouping_sets_pushdown1.q
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets_pushdown1.q.out
Labels: tests passed

#992 HIVE-23269: Unsafe comparing bigints and strings
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/type/TestBigIntCompareValidation.java
Labels: tests passed

#1063 HIVE-23617: Fixing storage-api FindBug issues
  Jenkinsfile
  storage-api/src/java/org/apache/hadoop/hive/common/ValidReadTxnList.java
  storage-api/src/java/org/apache/hadoop/hive/common/ValidReaderWriteIdList.java
  storage-api/src/java/org/apache/hadoop/hive/common/io/DataCache.java
  storage-api/src/java/org/apache/hadoop/hive/common/io/DiskRangeList.java
  storage-api/src/java/org/apache/hadoop/hive/common/io/encoded/EncodedColumnBatch.java
  storage-api/src/java/org/apache/hadoop/hive/common/type/FastHiveDecimal.java
  storage-api/src/java/org/apache/hadoop/hive/common/type/FastHiveDecimalImpl.java
  storage-api/src/java/org/apache/hadoop/hive/common/type/HiveIntervalDayTime.java
  storage-api/src/java/org/apache/hadoop/hive/common/type/RandomTypeUtil.java
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/BytesColumnVector.java
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/TimestampColumnVector.java
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatch.java
  storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/SearchArgumentImpl.java
  storage-api/src/java/org/apache/hadoop/hive/serde2/io/HiveDecimalWritable.java
  storage-api/src/java/org/apache/hadoop/hive/serde2/io/HiveDecimalWritableV1.java
  storage-api/src/java/org/apache/hive/common/util/BloomFilter.java
  storage-api/src/java/org/apache/hive/common/util/BloomKFilter.java
  storage-api/src/java/org/apache/hive/common/util/Murmur3.java
  storage-api/src/java/org/apache/hive/common/util/SuppressFBWarnings.java
  storage-api/src/test/org/apache/hive/common/util/TestMurmur3.java
Labels: tests passed

#1066 HIVE-23620: Moving to SpotBugs that is actively maintained
  Jenkinsfile
  pom.xml
  ql/pom.xml
  spotbugs/spotbugs-exclude.xml
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-common/spotbugs/spotbugs-exclude.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/spotbugs/spotbugs-exclude.xml
  standalone-metastore/spotbugs/spotbugs-exclude.xml
Labels: tests passed

#1076 HIVE-21790: Build Hive2 with JDK 1.8
  Jenkinsfile
  hcatalog/webhcat/svr/pom.xml
  itests/hive-jmh/pom.xml
  itests/hive-unit/pom.xml
  pom.xml
  storage-api/pom.xml
  testutils/ptest2/pom.xml
Labels: tests unstable

#1078 HIVE-23266: Remove QueryWrapper from ObjectStore
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/MetaToolTaskExecuteJDOQLQuery.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/VerifyingObjectStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/tools/metatool/TestMetaToolTaskExecuteJDOQLQuery.java
Labels: tests passed

#1104 HIVE-23686: Fix spotbugs issues in hive-shims
  Jenkinsfile
  pom.xml
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Labels: tests passed

#1092 HIVE-23499: REPL: Immutable repl dumps should be reusable across mult…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Labels: tests passed

#1097 HIVE-23495: AcidUtils.getAcidState cleanup
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcRawRecordMerger.java
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Labels: tests passed

#1094 HIVE-19545: Enable TestCliDriver#fouter_join_ppr.q
  ql/src/test/queries/clientpositive/fouter_join_ppr.q
  ql/src/test/results/clientpositive/llap/fouter_join_ppr.q.out
Labels: tests passed

#1101 HIVE-23683: Add queue time to compaction
  metastore/scripts/upgrade/hive/hive-schema-4.0.0.hive.sql
  metastore/scripts/upgrade/hive/upgrade-3.1.0-to-4.0.0.hive.sql
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/queries/clientpositive/dbtxnmgr_showlocks.q
  ql/src/test/queries/clientpositive/sysdb.q
  ql/src/test/results/clientpositive/llap/dbtxnmgr_showlocks.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionInfoStruct.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactResponseElement.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Types.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-3.2.0-to-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-3.2.0-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-3.2.0-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-3.2.0-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-3.2.0-to-4.0.0.postgres.sql
Labels: tests passed

#1052 HIVE-23592: Routine makeIntPair is Not Correct
  common/src/java/org/apache/hadoop/hive/common/NumberUtils.java
  common/src/test/org/apache/hadoop/hive/common/TestNumberUtils.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/BuddyAllocator.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/encoded/IoTrace.java
Labels: tests passed

#1124 HIVE-23493: Rewrite plan to join back tables with many projected columns joined multiple times
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveDefaultRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveDefaultTezModelRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinOptimization.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFieldTrimmerRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelFieldTrimmer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/results/clientpositive/llap/constraints_optimization.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query11.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query4.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query74.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query11.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query4.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query74.q.out
Labels: tests passed

#1123 HIVE-23702: Add metastore metrics to show age of the oldest initiated compaction
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Labels: tests passed

#1108 HIVE-23689: Bump Tez version to 0.9.2
  pom.xml
Labels: tests passed

#1136 HIVE-23711: Some IDE generated files should not be checked for licens…
  pom.xml
Labels: tests passed

#1128 HIVE-23418 : Add test.local.warehouse.dir for TestMiniLlapLocalDriver tests (Miklos Gergely, reviewed by Zoltan Haindrich)
  itests/src/test/resources/testconfiguration.properties
  pom.xml
  ql/src/test/queries/clientpositive/input44.q
  ql/src/test/queries/clientpositive/msck_repair_0.q
  ql/src/test/queries/clientpositive/msck_repair_1.q
  ql/src/test/queries/clientpositive/msck_repair_2.q
  ql/src/test/queries/clientpositive/msck_repair_3.q
  ql/src/test/queries/clientpositive/msck_repair_4.q
  ql/src/test/queries/clientpositive/msck_repair_5.q
  ql/src/test/queries/clientpositive/msck_repair_acid.q
  ql/src/test/queries/clientpositive/msck_repair_batchsize.q
  ql/src/test/queries/clientpositive/msck_repair_drop.q
  ql/src/test/queries/clientpositive/nullformat.q
  ql/src/test/queries/clientpositive/nullformatCTAS.q
  ql/src/test/queries/clientpositive/partition_discovery.q
  ql/src/test/queries/clientpositive/repair.q
  ql/src/test/queries/clientpositive/symlink_text_input_format.q
  ql/src/test/results/clientpositive/llap/input44.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_0.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_1.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_2.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_3.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_4.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_5.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_6.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_acid.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_batchsize.q.out
  ql/src/test/results/clientpositive/llap/msck_repair_drop.q.out
  ql/src/test/results/clientpositive/llap/nullformat.q.out
  ql/src/test/results/clientpositive/llap/nullformatCTAS.q.out
  ql/src/test/results/clientpositive/llap/partition_discovery.q.out
  ql/src/test/results/clientpositive/llap/repair.q.out
  ql/src/test/results/clientpositive/llap/symlink_text_input_format.q.out
Labels: tests pending

#1082 HIVE-23026: Allow for custom YARN application name for TEZ queries
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
Labels: tests pending

#1080 HIVE-23026: Allow for custom YARN application name for TEZ queries (branch-2)
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
Labels: tests pending

#1067 HIVE-23627: Review of GroupByOperator
  ql/src/java/org/apache/hadoop/hive/ql/exec/GroupByOperator.java
Labels: tests passed

#1121 HIVE-23612: Option for HiveStrictManagedMigration to impersonate a user for FS operations
  ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
  ql/src/test/org/apache/hadoop/hive/ql/util/TestHiveStrictManagedMigration.java
Labels: tests passed

#1113 HIVE-23697 : Fix errors in the metastore upgrade script
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-2.3.0-to-3.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-3.2.0-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-3.2.0-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-3.2.0-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/DatabaseRule.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java
Labels: tests passed

#1055 HIVE-23602: Use Java Concurrent Package for Operation Handle Set
  service/src/java/org/apache/hive/service/cli/session/HiveSessionImpl.java
Labels: tests passed

#1137 HIVE-23593: Schemainit fails with NoSuchFieldError
  Jenkinsfile
  itests/hive-jmh/pom.xml
  packaging/src/main/assembly/bin.xml
  standalone-metastore/metastore-tools/metastore-benchmarks/pom.xml
Labels: tests passed

#1141 HIVE-23715: Fix zookeeper ssl keystore password handling issues
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-client/src/java/org/apache/hadoop/hive/registry/impl/ZkRegistryBase.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/ZooKeeperTokenStore.java
Labels: tests passed

#807 HIVE-19261: Avro SerDe's InstanceCache should not be synchronized on retrieve
  serde/src/java/org/apache/hadoop/hive/serde2/avro/InstanceCache.java
Labels: tests passed

#1127 HIVE-23704: Decode Base-64 String from HTTP Header
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
Labels: tests passed

#1134 HIVE-23703: Major QB compaction with multiple FileSinkOperators results in data loss and one original file
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnMr.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnMr.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/AbstractFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/FileMergeDesc.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveCopyFiles.java
Labels: tests passed

#1150 HIVE-23729
  data/files/csv/00000.csv
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/SerDeLowLevelCacheImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/SerDeEncodedDataReader.java
  ql/src/java/org/apache/hadoop/hive/llap/LlapHiveUtils.java
  ql/src/java/org/apache/hadoop/hive/llap/SchemaAwareCacheKey.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
  ql/src/test/queries/clientpositive/csv_llap.q
  ql/src/test/results/clientpositive/llap/csv_llap.q.out
Labels: tests passed

#1166 HIVE-20890: ACID: Allow whole table ReadLocks to skip all partition l…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  ql/src/test/results/clientpositive/llap/explain_locks.q.out
Labels: tests passed

#1183 HIVE-23762: ignore flaky tests
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/hbase/TestPigHBaseStorageHandler.java
Labels: tests pending

#1146 HIVE-23619: Add new reexecute plugin to rerun queries in case AM is down due to lost node
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/reexec/TestReExecuteKilledTezAMQueryPlugin.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java
Labels: tests pending

#1170 HIVE-23444: Concurrent ACID direct inserts may fail with FileNotFound…
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/exec/AbstractFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/test/queries/clientpositive/acid_multiinsert_static_parts.q
  ql/src/test/results/clientpositive/llap/acid_multiinsert_static_parts.q.out
Labels: tests passed

#1176 HIVE-23759: refactor field order of CommitTxnRequest
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CommitTxnRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Types.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed

#1168 HIVE-23738: DBLockManager::lock() : Move lock request to debug level
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbLockManager.java
Labels: tests passed

#1188 HIVE-19549: Enable TestAcidOnTez#testCtasTezUnion
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
Labels: tests passed

#1085 Hive 22255 : Hive don't trigger Major Compaction automatically if table contains only base files
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
Labels: tests passed
