Repository apache/hive, pull requests merged in 2020-10, with the labels that each got.

#1274 HIVE-23852: add support for Date type in ReduceSink operator for native vector sink
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/keyseries/VectorKeySeriesLongSerialized.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastTableContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/optimized/VectorMapJoinOptimizedLongCommon.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorMapJoinDesc.java
  ql/src/test/queries/clientpositive/probedecode_static_keytype.q
  ql/src/test/results/clientpositive/llap/probedecode_static_keytype.q.out
  ql/src/test/results/clientpositive/llap/vector_partitioned_date_time.q.out
Labels: tests passed

#1541 HIVE-21375 initial commit
  hcatalog/streaming/src/java/org/apache/hive/hcatalog/streaming/HiveEndPoint.java
  hcatalog/streaming/src/test/org/apache/hive/hcatalog/streaming/TestStreaming.java
Labels: tests pending

#1497 HIVE-24157: Strict mode to fail on CAST timestamp <-> numeric
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  data/conf/hive-site.xml
  data/conf/llap/hive-site.xml
  ql/src/java/org/apache/hadoop/hive/ql/udf/TimestampCastRestrictorResolver.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToBoolean.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToByte.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToDouble.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToFloat.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToInteger.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToLong.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToShort.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFBaseCompare.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFTimestamp.java
  ql/src/test/queries/clientnegative/strict_numeric_to_timestamp.q
  ql/src/test/queries/clientnegative/strict_numeric_to_timestamp2.q
  ql/src/test/queries/clientnegative/strict_timestamp_to_numeric.q
  ql/src/test/queries/clientnegative/strict_timestamp_to_numeric2.q
  ql/src/test/queries/clientnegative/strict_timestamp_to_numeric3.q
  ql/src/test/queries/clientnegative/strict_timestamp_to_numeric4.q
  ql/src/test/results/clientnegative/strict_numeric_to_timestamp.q.out
  ql/src/test/results/clientnegative/strict_numeric_to_timestamp2.q.out
  ql/src/test/results/clientnegative/strict_timestamp_to_numeric.q.out
  ql/src/test/results/clientnegative/strict_timestamp_to_numeric2.q.out
  ql/src/test/results/clientnegative/strict_timestamp_to_numeric3.q.out
  ql/src/test/results/clientnegative/strict_timestamp_to_numeric4.q.out
Labels: tests passed

#1536 HIVE-24210: PartitionManagementTask fails if one of tables dropped after fetching TableMeta
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartitionManagementTask.java
Labels: tests passed

#1545 HIVE-24222: Upgrade ORC to 1.5.12
  pom.xml
Labels: tests passed

#1508 HIVE-24178: Add managed location to SHOW CREATE DATABASE (Miklos Gergely)
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/showcreate/ShowCreateDatabaseOperation.java
  ql/src/test/queries/clientpositive/database_location.q
  ql/src/test/results/clientpositive/llap/database_location.q.out
Labels: tests passed

#1520 HIVE-24193 : Select query on renamed hive acid table does not produce any output
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests pending

#1380 Show tables in database with owner policy
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/filtercontext/TableFilterContext.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Labels: tests passed

#1532 HIVE-20137: truncate for transactional tables
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  ql/src/test/results/clientpositive/llap/acid_stats3.q.out
  ql/src/test/results/clientpositive/llap/check_constraint.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/StatsSetupConst.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
  storage-api/src/java/org/apache/hadoop/hive/common/AcidConstants.java
  storage-api/src/java/org/apache/hadoop/hive/common/AcidMetaDataFile.java
Labels: tests passed

#1519 HIVE-24192: Properly log TaskExecutorService eviction details
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java
  llap-server/src/main/resources/llap-daemon-log4j2.properties
Labels: tests passed

#1547 HIVE-24225: Revert HIVE-23158 Optimize S3A recordReader policy for Random IO formats
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapInputFormat.java
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestRandomAccessHiveInputFormat.java
Labels: tests passed

#1543 HIVE-24202: Clean up local HS2 HMS cache code (II)
  cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosIncrementalLoadAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestListPartitions.java
Labels: tests passed

#1552 HIVE-24229. DirectSql fails in case of OracleDB.
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDirectSqlUtils.java
Labels: tests passed

#1525 HIVE-24199: Incorrect result when subquey in exists contains limit
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptMaterializationValidator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttle.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttleImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java
  ql/src/test/queries/clientnegative/offset_in_subquery.q
  ql/src/test/queries/clientpositive/subquery_join_rewrite.q
  ql/src/test/results/clientnegative/offset_in_subquery.q.out
  ql/src/test/results/clientpositive/llap/subquery_join_rewrite.q.out
Labels: tests passed

#1554 HIVE-24232: Incorrect translation of rollup expression from Calcite
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/GroupByDesc.java
  ql/src/test/queries/clientpositive/perf/cbo_query_grouping_sets.q
  ql/src/test/results/clientpositive/llap/annotate_stats_groupby.q.out
  ql/src/test/results/clientpositive/llap/annotate_stats_groupby2.q.out
  ql/src/test/results/clientpositive/llap/auto_join18_multi_distinct.q.out
  ql/src/test/results/clientpositive/llap/cbo_rp_annotate_stats_groupby.q.out
  ql/src/test/results/clientpositive/llap/groupby_cube1.q.out
  ql/src/test/results/clientpositive/llap/groupby_cube_multi_gby.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_id3.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets1.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets2.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets3.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets4.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets5.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets6.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets_grouping.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets_limit.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets_pushdown1.q.out
  ql/src/test/results/clientpositive/llap/groupby_grouping_window.q.out
  ql/src/test/results/clientpositive/llap/groupby_rollup1.q.out
  ql/src/test/results/clientpositive/llap/groupby_rollup_empty.q.out
  ql/src/test/results/clientpositive/llap/groupby_rollup_empty2.q.out
  ql/src/test/results/clientpositive/llap/infer_bucket_sort_grouping_operators.q.out
  ql/src/test/results/clientpositive/llap/join18_multi_distinct.q.out
  ql/src/test/results/clientpositive/llap/limit_pushdown.q.out
  ql/src/test/results/clientpositive/llap/limit_pushdown2.q.out
  ql/src/test/results/clientpositive/llap/limit_pushdown3.q.out
  ql/src/test/results/clientpositive/llap/multi_count_distinct_null.q.out
  ql/src/test/results/clientpositive/llap/offset_limit_ppd_optimizer.q.out
  ql/src/test/results/clientpositive/llap/reduce_deduplicate_distinct.q.out
  ql/src/test/results/clientpositive/llap/topnkey_grouping_sets.q.out
  ql/src/test/results/clientpositive/llap/topnkey_grouping_sets_functions.q.out
  ql/src/test/results/clientpositive/llap/topnkey_grouping_sets_order.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_cube1.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_id1.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_id2.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_id3.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets1.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets2.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets3.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets3_dec.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets4.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets5.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets6.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets_grouping.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_sets_limit.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_grouping_window.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_rollup1.q.out
  ql/src/test/results/clientpositive/llap/vector_grouping_sets.q.out
  ql/src/test/results/clientpositive/llap/view_cbo.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query_grouping_sets.q.out
Labels: tests passed

#1559 HIVE-24236: Fixed possible Connection leaks in TxnHandler (Yongzhi Chen, reviewed by Denys Kuzmenko)
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#1271 HIVE-23851: MSCK REPAIR Command With Partition Filtering Fails While Dropping Partitions
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionExpressionForMetastore.java
  ql/src/test/queries/clientpositive/msck_repair_filter.q
  ql/src/test/results/clientpositive/llap/msck_repair_filter.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/PartitionExpressionProxy.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DefaultPartitionExpressionProxy.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MsckPartitionExpressionProxy.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartFilterExprUtil.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/MockPartitionExpressionForMetastore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestOldSchema.java
Labels: tests passed

#1528 HIVE-22826: ALTER TABLE RENAME COLUMN doesn't update list of bucketed…
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/change/AlterTableChangeColumnAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/change/AlterTableChangeColumnOperation.java
  ql/src/test/queries/clientpositive/alt_bucket_tlb_change_col.q
  ql/src/test/queries/clientpositive/alter_numbuckets_partitioned_table_h23.q
  ql/src/test/results/clientpositive/llap/alt_bucket_tlb_change_col.q.out
  ql/src/test/results/clientpositive/llap/alter_numbuckets_partitioned_table_h23.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
Labels: tests passed

#1430 HIVE-23938: LLAP: JDK11 - some GC log file rotation related jvm arguments cannot be used anymore
  llap-server/bin/runLlapDaemon.sh
Labels: tests passed

#1560 HIVE-24234: Improve checkHashModeEfficiency in VectorGroupByOperator
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorGroupByOperator.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorGroupByOperator.java
Labels: tests passed

#1421 HIVE-24063: SqlFunctionConverter#getHiveUDF handles cast before getin…
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
Labels: tests passed

#1429 HIVE-24069: HiveHistory should log the task that ends abnormally
  ql/src/java/org/apache/hadoop/hive/ql/Executor.java
Labels: tests passed

#1457 HIVE-24107: Fix typo in ReloadFunctionsOperation
  ql/src/java/org/apache/hadoop/hive/ql/ddl/function/reload/ReloadFunctionsOperation.java
Labels: tests passed

#1483 HIVE-24146: Cleanup TaskExecutionException in GenericUDTFExplode
  ql/src/java/org/apache/hadoop/hive/ql/exec/TaskExecutionException.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFExplode.java
Labels: tests passed

#1565 HIVE-24248: TestMiniLlapLocalCliDriver[subquery_join_rewrite] is flaky
  ql/src/test/queries/clientpositive/subquery_join_rewrite.q
  ql/src/test/results/clientpositive/llap/subquery_join_rewrite.q.out
Labels: tests passed

#1568 HIVE-24255: StorageHandler with select-limit query is returning 0 rows
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GlobalLimitOptimizer.java
  ql/src/test/queries/clientpositive/external_jdbc_table4.q
  ql/src/test/results/clientpositive/llap/external_jdbc_table4.q.out
Labels: tests passed

#1456 HIVE-24106: Abort polling on the operation state when the current thr…
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniHS2.java
  jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
Labels: tests passed

#1182 HIVE-23712: metadata-only queries return incorrect results with empty acid partition
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/NullScanTaskDispatcher.java
  ql/src/test/queries/clientpositive/metadataonly_acid_empty_partition.q
  ql/src/test/results/clientpositive/llap/metadataonly_acid_empty_partition.q.out
Labels: stale, tests passed

#1576 HIVE-24266
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
Labels: tests passed

#1558 HIVE-24235: Drop and recreate table during MR compaction leaves behind base/delta directory
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#1512 HIVE-24184: Re-order methods in Driver (Miklos Gergely)
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
Labels: tests passed

#1580 HIVE-24253: HMS and HS2 needs to support keystore/truststores types b…
  common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/main/java/org/hadoop/hive/jdbc/SSLTestUtils.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestSSL.java
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/SecurityUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
Labels: tests passed

#1527 HIVE-23695: [CachedStore] Add check/default constraints in CachedStore
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/TableCacheObjects.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
Labels: tests passed

#1584 HIVE-24282: Show columns shouldn't sort output columns unless explicitly mentioned
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/show/ShowColumnsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/show/ShowColumnsDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/show/ShowColumnsOperation.java
  ql/src/test/queries/clientpositive/show_columns.q
  ql/src/test/results/clientpositive/llap/show_columns.q.out
Labels: tests passed

#1408 HIVE-24044: Implement listPartitionNames on temporary tables
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
  ql/src/test/queries/clientpositive/show_temp_partitions.q
  ql/src/test/results/clientpositive/llap/show_temp_partitions.q.out
Labels: tests passed

#1470 [WIP]HIVE-24120 Plugin for external DatabaseProduct in standalone HMS
  .gitignore
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/SQLGenerator.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnDbUtil.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyCustomRDBMS.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestTxnUtils.java
Labels: tests passed

#1553 HIVE-24231: Enhance shared work optimizer to merge scans with filters on both sides
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemiJoinBranchInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
  ql/src/test/queries/clientpositive/sharedwork_semi.q
  ql/src/test/results/clientpositive/llap/dynamic_partition_pruning.q.out
  ql/src/test/results/clientpositive/llap/sharedwork_semi.q.out
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_1.q.out
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_quotes_1.q.out
  ql/src/test/results/clientpositive/llap/subquery_multi.q.out
  ql/src/test/results/clientpositive/llap/subquery_notin.q.out
  ql/src/test/results/clientpositive/llap/vectorized_dynamic_partition_pruning.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query11.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query14.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query4.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query64.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query74.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query75.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query88.q.out
  ql/src/test/results/clientpositive/perf/tez/query11.q.out
  ql/src/test/results/clientpositive/perf/tez/query14.q.out
  ql/src/test/results/clientpositive/perf/tez/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/query24.q.out
  ql/src/test/results/clientpositive/perf/tez/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/query4.q.out
  ql/src/test/results/clientpositive/perf/tez/query64.q.out
  ql/src/test/results/clientpositive/perf/tez/query74.q.out
  ql/src/test/results/clientpositive/perf/tez/query75.q.out
  ql/src/test/results/clientpositive/perf/tez/query88.q.out
Labels: tests passed

#1569 HIVE-24256: quote NWI_TABLE column in TxnHandler
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#1586 HIVE-24284 : NPE when parsing druid logs using Hive (Mahesh Kumar Behera reviewed Nishant Bangarwa)
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/serde2/TestSysLogSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/log/syslog/SyslogParser.java
Labels: tests pending

#1589 Hive-24287: Using SHA-512 for Cookie signature
  service/src/java/org/apache/hive/service/CookieSigner.java
Labels: tests passed

#1591 HIVE-23962 Make bin/hive pick user defined jdbc url
  bin/hive
Labels: tests passed

#1595 HIVE-24293: Integer overflow in llap collision mask
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
Labels: tests passed

#1594 HIVE-24292: hive webUI should support keystoretype by config (Yongzhi Chen, reviewed by Kevin Risden)
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/java/org/apache/hive/http/HttpServer.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  service/src/test/org/apache/hive/service/server/TestHS2HttpServerPamConfiguration.java
Labels: tests passed

#1460 Hive 24113
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFFromUnixTime.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFToUnixTimeStamp.java
Labels: tests passed

#1600 HIVE-24304: Query containing UNION fails with OOM
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveDefaultRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveTezModelRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveRelMdExpressionLineage.java
  ql/src/test/queries/clientpositive/union_lineage.q
  ql/src/test/results/clientpositive/llap/union_lineage.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query54.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query54.q.out
Labels: tests passed

#1587 HIVE-24258: [CachedStore] Data miss match between cachedstore and rawstore
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CacheUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/InjectableBehaviourObjectStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestCheckConstraint.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestDefaultConstraint.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestForeignKey.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestGetAllTableConstraints.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestNotNullConstraint.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestPrimaryKey.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestUniqueConstraint.java
Labels: tests passed

#1596 HIVE-24294: TezSessionPool sessions can throw AssertionError
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolManager.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezSessionPool.java
Labels: tests passed

#1313 HIVE-23829: Compute Stats Incorrect for Binary Columns
  ql/src/test/queries/clientpositive/acid_vectorization_original_tez.q
  ql/src/test/queries/clientpositive/avro_nullable_fields.q
  ql/src/test/queries/clientpositive/llap_text.q
  ql/src/test/queries/clientpositive/metadata_only_queries.q
  ql/src/test/queries/clientpositive/metadata_only_queries_with_filters.q
  ql/src/test/queries/clientpositive/orc_llap_counters.q
  ql/src/test/queries/clientpositive/orc_llap_counters1.q
  ql/src/test/queries/clientpositive/vector_binary_join_groupby.q
  ql/src/test/queries/clientpositive/vector_windowing_multipartitioning.q
  ql/src/test/queries/clientpositive/vector_windowing_navfn.q
  ql/src/test/queries/clientpositive/windowing_distinct.q
  ql/src/test/queries/clientpositive/windowing_multipartitioning.q
  ql/src/test/queries/clientpositive/windowing_navfn.q
  ql/src/test/results/clientpositive/llap/avro_nullable_fields.q.out
  ql/src/test/results/clientpositive/llap/llap_text.q.out
  ql/src/test/results/clientpositive/llap/metadata_only_queries.q.out
  ql/src/test/results/clientpositive/llap/metadata_only_queries_with_filters.q.out
  ql/src/test/results/clientpositive/llap/orc_llap_counters.q.out
  ql/src/test/results/clientpositive/llap/orc_llap_counters1.q.out
  ql/src/test/results/clientpositive/llap/vector_binary_join_groupby.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing_multipartitioning.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing_navfn.q.out
  ql/src/test/results/clientpositive/llap/windowing_distinct.q.out
  ql/src/test/results/clientpositive/llap/windowing_multipartitioning.q.out
  ql/src/test/results/clientpositive/llap/windowing_navfn.q.out
  ql/src/test/results/clientpositive/tez/acid_vectorization_original_tez.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazySerDeParameters.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/fast/LazySimpleDeserializeRead.java
Labels: stale, tests passed

#1614 HIVE-24297
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
Labels: tests passed

#1622 HIVE-24325: Cardinality preserving join optimization fails when column is backtracked to a constant
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinOptimization.java
  ql/src/test/queries/clientpositive/cardinality_preserving_join_opt2.q
  ql/src/test/results/clientpositive/llap/cardinality_preserving_join_opt2.q.out
Labels: tests passed

#1619 HIVE-24321: Implement Default getSerDeStats in AbstractSerDe
  accumulo-handler/src/java/org/apache/hadoop/hive/accumulo/serde/AccumuloSerDe.java
  contrib/src/java/org/apache/hadoop/hive/contrib/serde2/RegexSerDe.java
  contrib/src/java/org/apache/hadoop/hive/contrib/serde2/TypedBytesSerDe.java
  druid-handler/src/java/org/apache/hadoop/hive/druid/serde/DruidSerDe.java
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseSerDe.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/HCatRecordSerDe.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java
  itests/custom-serde/src/main/java/org/apache/hadoop/hive/serde2/CustomSerDe1.java
  itests/custom-serde/src/main/java/org/apache/hadoop/hive/serde2/CustomSerDe2.java
  itests/test-serde/src/main/java/org/apache/hadoop/hive/serde2/TestSerDe.java
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcSerDe.java
  kudu-handler/src/java/org/apache/hadoop/hive/kudu/KuduSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSerde.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/serde/ParquetHiveSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/io/protobuf/ProtobufSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/log/syslog/SyslogSerDe.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestFileSinkOperator.java
  serde/src/java/org/apache/hadoop/hive/serde2/AbstractSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/JsonSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/MetadataTypedColumnsetSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/NullStructSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
  serde/src/java/org/apache/hadoop/hive/serde2/RegexSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/TypedSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/binarysortable/BinarySortableSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinarySerde.java
  serde/src/java/org/apache/hadoop/hive/serde2/thrift/ThriftJDBCBinarySerDe.java
Labels: tests passed
