Repository apache/hive, pull requests merged in 2020-07, with the labels that each got.

#1142 HIVE-23718 Extract transaction handling from Driver (Miklos Gergely, reviewed by Peter Vary)
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
Labels: tests passed

#1189 HIVE-23774: Reduce log level at aggrColStatsForPartitions in MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#1194 HIVE-23789: Merge ValidTxnManager into DriverTxnHandler (Miklos Gergely)
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/ValidTxnManager.java
Labels: tests passed

#1167 HIVE-23751: QTest: Override #mkdirs() method in ProxyFileSystem To Align After HADOOP-16582
  shims/common/src/main/java/org/apache/hadoop/fs/ProxyFileSystem.java
Labels: tests passed

#1145 HIVE-23722: Show the operation's drilldown link to client
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCliServiceWithInfoMessage.java
  jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
  service/src/java/org/apache/hive/service/cli/operation/OperationManager.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
Labels: tests passed

#1090 HIVE-22676: Replace Base64 in hive-service Package
  jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
  service/src/java/org/apache/hive/service/CookieSigner.java
  service/src/java/org/apache/hive/service/auth/HttpAuthUtils.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
Labels: tests passed

#1186 HIVE-23768: Metastore's update service wrongly strips partition column stats from the cache
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
Labels: tests passed

#1185 HIVE-23764: Remove unnecessary getLastFlushLength when checking delete delta files
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
Labels: tests passed

#1196 HIVE-23791: Optimize ACID stats generation
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
Labels: tests passed

#1204 HIVE-23799: Fix AcidUtils.parseBaseOrDeltaBucketFilename handling of data loaded by LOAD DATA
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidOutputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
Labels: tests passed

#1119 HIVE-23699: Cleanup HIVEQUERYRESULTFILEFORMAT handling
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/java/org/apache/hadoop/hive/conf/Validator.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  service/src/java/org/apache/hive/service/cli/session/HiveSessionImpl.java
Labels: tests passed

#1211 HIVE-23790: The error message length of 2000 is exceeded for scheduled query
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestMetastoreScheduledQueries.java
Labels: tests passed

#1192 HIVE-23780: Fail dropTable if acid cleanup fails
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/MiniHiveKdc.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestAcidTableSetup.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandlerNoConnectionPool.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestUpdateDeleteSemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestCatalogNonDefaultClient.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreSchemaMethods.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreAcidCleanup.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/minihms/RemoteMetaStoreForTests.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/ThrowingTxnHandler.java
Labels: tests passed

#1223 HIVE-23813 : Fix flaky tests due to JDO Exception
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/hbase/TestPigHBaseStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/MetricSink.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ReplicationMetricsMaintTask.java
Labels: tests passed

#929 HIVE-22952 Use LinkedHashMap in TestStandardObjectInspectors.java
  serde/src/test/org/apache/hadoop/hive/serde2/objectinspector/TestStandardObjectInspectors.java
Labels: tests passed

#1219 HIVE-23525: TestAcidTxnCleanerService is unstable
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestAcidTxnCleanerService.java
Labels: tests passed

#1026 HIVE-23509: MapJoin AssertionError: Capacity must be power of 2
  ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/BytesBytesMultiHashMap.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/persistence/TestBytesBytesMultiHashMap.java
Labels: tests passed

#1233 HIVE-23827: Upgrade to DataSketches 1.1.0
  pom.xml
Labels: tests passed

#1216 HIVE-23760: Upgrading to Kafka 2.5 Clients
  itests/qtest-druid/pom.xml
  itests/qtest-druid/src/main/java/org/apache/hive/kafka/SingleNodeKafkaCluster.java
  kafka-handler/pom.xml
  kafka-handler/src/java/org/apache/hadoop/hive/kafka/HiveKafkaProducer.java
  pom.xml
Labels: tests passed

#1236 HIVE-23825: Create a flag to turn off _orc_acid_version file creation
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidOutputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRecordUpdater.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
Labels: tests passed

#1209 HIVE-22412: StatsUtils throw NPE when explain
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
  ql/src/test/queries/clientpositive/analyze_npe.q
  ql/src/test/results/clientpositive/llap/analyze_npe.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/StandardConstantMapObjectInspector.java
Labels: tests passed

#1235 HIVE-23830: Remove shutdownRunner runner after query is committed
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  service/src/test/org/apache/hadoop/util/ShutdownHookManagerInspector.java
  service/src/test/org/apache/hive/service/cli/operation/TestQueryShutdownHooks.java
Labels: tests passed

#1105 HIVE-22957: Support Partition Filtering In MSCK REPAIR TABLE Command
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AbstractDropPartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreChecker.java
  ql/src/test/queries/clientpositive/msck_repair_filter.q
  ql/src/test/results/clientpositive/llap/msck_repair_filter.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/Msck.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MsckInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
Labels: tests passed

#1109 HIVE-22015: Add table constraints in CachedStore
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/TableCacheObjects.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
Labels: tests passed

#1238 HIVE-23824
  llap-client/src/java/org/apache/hadoop/hive/llap/IllegalCacheConfigurationException.java
  llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestOrcMetadataCache.java
Labels: tests passed

#1243 HIVE-23832: Compaction cleaner fails to clean up deltas when using bl…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnExIm.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnNoBuckets.java
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Labels: tests passed

#1234 HIVE-23807 Wrong results with vectorization enabled
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/CastStringToDate.java
  ql/src/test/queries/clientpositive/vectorization_cast_string_to_date.q
  ql/src/test/results/clientpositive/llap/vectorization_cast_string_to_date.q.out
Labels: tests pending

#1231 HIVE-23822 Sorted dynamic partition optimization could remove auto stat task
  itests/hive-blobstore/src/test/results/clientpositive/insert_into_dynamic_partitions.q.out
  itests/hive-blobstore/src/test/results/clientpositive/insert_overwrite_dynamic_partitions.q.out
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SortedDynPartitionOptimizer.java
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_16.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_opt_bucketing.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_opt_vectorization.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_acid.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_acid2.q.out
  ql/src/test/results/clientpositive/llap/llap_smb.q.out
  ql/src/test/results/clientpositive/llap/mm_dp.q.out
Labels: tests passed

#1253 Fix unit tests ( TestHiveMetaStoreChecker and TestMiniLlapLocalCliDriver tests ) in master
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreChecker.java
Labels: tests passed

#1222 HIVE-23814: Clean up Driver (Miklos Gergely)
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverState.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/Executor.java
  ql/src/java/org/apache/hadoop/hive/ql/HiveDriverRunHook.java
  ql/src/java/org/apache/hadoop/hive/ql/HiveDriverRunHookContext.java
  ql/src/java/org/apache/hadoop/hive/ql/IDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
Labels: tests passed

#1125 HIVE-23244 Extract Create View analyzer from SemanticAnalyzer (Miklos Gergely)
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AbstractCreateViewAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AbstractCreateViewDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AlterViewAsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AlterViewAsDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AlterViewAsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateViewAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateViewDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateViewOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseContext.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QB.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/LoadFileDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  ql/src/test/results/clientnegative/create_or_replace_view4.q.out
  ql/src/test/results/clientnegative/create_view_failure10.q.out
  ql/src/test/results/clientnegative/create_view_failure3.q.out
  ql/src/test/results/clientnegative/create_view_failure5.q.out
  ql/src/test/results/clientnegative/create_view_failure6.q.out
  ql/src/test/results/clientnegative/create_view_failure7.q.out
  ql/src/test/results/clientnegative/create_view_failure8.q.out
  ql/src/test/results/clientnegative/create_view_failure9.q.out
  ql/src/test/results/clientnegative/masking_mv.q.out
  ql/src/test/results/clientnegative/selectDistinctStarNeg_1.q.out
  ql/src/test/results/clientpositive/llap/create_view.q.out
  ql/src/test/results/clientpositive/llap/create_view_translate.q.out
  ql/src/test/results/clientpositive/llap/explain_ddl.q.out
  ql/src/test/results/clientpositive/llap/explainuser_1.q.out
  ql/src/test/results/clientpositive/llap/lineage3.q.out
  ql/src/test/results/clientpositive/llap/masking_mv.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_cluster.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_3.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_rebuild_dummy.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_distribute_sort.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partition_cluster.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned_3.q.out
  ql/src/test/results/clientpositive/llap/selectDistinctStar.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_safety.q.out
  ql/src/test/results/clientpositive/llap/union_top_level.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing.q.out
  ql/src/test/results/clientpositive/tez/explainanalyze_3.q.out
  ql/src/test/results/clientpositive/tez/explainuser_3.q.out
Labels: tests passed

#1258 HIVE-23857: Fix HiveParser 'code too large' problem (Miklos Gergely, reviewed by David Mollitor)
  parser/bin/fixHiveParser.sh
  parser/pom.xml
Labels: tests passed

#1261 HIVE-23856: Beeline Should Print Binary Data in Base64
  beeline/src/java/org/apache/hive/beeline/Rows.java
  beeline/src/test/org/apache/hive/beeline/TestIncrementalRows.java
Labels: tests passed

#1244 HIVE-23837: Configure StorageHandlers if FileSinkOperator is child of MergeJoinWork
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/BaseWork.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MergeJoinWork.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ReduceWork.java
Labels: tests passed

#1011 HIVE-23339: SBA does not check permissions for DB location specified …
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/cli/SemanticAnalysis/HCatSemanticAnalyzerBase.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/storagehandler/DummyHCatAuthProvider.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/security/DummyHiveMetastoreAuthorizationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/BitSetCheckedAuthorizationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/HiveAuthorizationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/MetaStoreAuthzAPIAuthorizerEmbedOnly.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/StorageBasedAuthorizationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV1.java
  ql/src/test/queries/clientnegative/authorization_sba_alter_db_loc.q
  ql/src/test/queries/clientnegative/authorization_sba_create_db_with_loc.q
  ql/src/test/results/clientnegative/authorization_sba_alter_db_loc.q.out
  ql/src/test/results/clientnegative/authorization_sba_create_db_with_loc.q.out
Labels: stale, tests passed

#1229 HIVE-23818: Use String Switch-Case Statement in StatUtills
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUtils.java
Labels: tests passed

#1269 HIVE-23868: Windowing function spec: support 0 preceeding/following
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/windowing_windowspec4.q
  ql/src/test/results/clientpositive/llap/windowing_windowspec4.q.out
Labels: tests passed

#1255 HIVE-23850: Allow PPD when subject is not a column with grouping sets…
  ql/src/java/org/apache/hadoop/hive/ql/ppd/OpProcFactory.java
  ql/src/test/queries/clientpositive/groupby_grouping_sets_pushdown1.q
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets_pushdown1.q.out
Labels: tests passed

#1270 HIVE-23869: Move alter statements in parser to new file
  parser/bin/fixHiveParser.sh
  parser/pom.xml
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
Labels: tests passed

#1152 HIVE-23730: TezCompiler tracking the original TS key columnName
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/OperatorUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
  ql/src/test/results/clientpositive/llap/acid_mapjoin.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_13.q.out
  ql/src/test/results/clientpositive/llap/bucket_map_join_tez2.q.out
  ql/src/test/results/clientpositive/llap/bucket_map_join_tez_empty.q.out
  ql/src/test/results/clientpositive/llap/bucketsortoptimize_insert_4.q.out
  ql/src/test/results/clientpositive/llap/bucketsortoptimize_insert_5.q.out
  ql/src/test/results/clientpositive/llap/bucketsortoptimize_insert_8.q.out
  ql/src/test/results/clientpositive/llap/convert_decimal64_to_decimal.q.out
  ql/src/test/results/clientpositive/llap/correlationoptimizer4.q.out
  ql/src/test/results/clientpositive/llap/correlationoptimizer5.q.out
  ql/src/test/results/clientpositive/llap/decimal_join2.q.out
  ql/src/test/results/clientpositive/llap/hashjoin.q.out
  ql/src/test/results/clientpositive/llap/hybridgrace_hashjoin_1.q.out
  ql/src/test/results/clientpositive/llap/join36.q.out
  ql/src/test/results/clientpositive/llap/join_on_varchar.q.out
  ql/src/test/results/clientpositive/llap/join_star.q.out
  ql/src/test/results/clientpositive/llap/llap_vector_nohybridgrace.q.out
  ql/src/test/results/clientpositive/llap/lvj_mapjoin.q.out
  ql/src/test/results/clientpositive/llap/mapjoin_decimal.q.out
  ql/src/test/results/clientpositive/llap/mapjoin_decimal_vectorized.q.out
  ql/src/test/results/clientpositive/llap/murmur_hash_migration.q.out
  ql/src/test/results/clientpositive/llap/orc_llap.q.out
  ql/src/test/results/clientpositive/llap/parquet_join.q.out
  ql/src/test/results/clientpositive/llap/probedecode_mapjoin_simple.q.out
  ql/src/test/results/clientpositive/llap/probedecode_mapjoin_stats.q.out
  ql/src/test/results/clientpositive/llap/skewjoin_mapjoin10.q.out
  ql/src/test/results/clientpositive/llap/tez_bmj_schema_evolution.q.out
  ql/src/test/results/clientpositive/llap/tez_nway_join.q.out
  ql/src/test/results/clientpositive/llap/tez_smb_main.q.out
  ql/src/test/results/clientpositive/llap/vector_binary_join_groupby.q.out
  ql/src/test/results/clientpositive/llap/vector_char_mapjoin1.q.out
  ql/src/test/results/clientpositive/llap/vector_complex_join.q.out
  ql/src/test/results/clientpositive/llap/vector_decimal64_multi_vertex.q.out
  ql/src/test/results/clientpositive/llap/vector_decimal_join.q.out
  ql/src/test/results/clientpositive/llap/vector_decimal_mapjoin.q.out
  ql/src/test/results/clientpositive/llap/vector_inner_join.q.out
  ql/src/test/results/clientpositive/llap/vector_leftsemi_mapjoin.q.out
  ql/src/test/results/clientpositive/llap/vector_llap_text_1.q.out
  ql/src/test/results/clientpositive/llap/vector_mapjoin_reduce.q.out
  ql/src/test/results/clientpositive/llap/vector_varchar_mapjoin1.q.out
  ql/src/test/results/clientpositive/llap/vectorized_context.q.out
  ql/src/test/results/clientpositive/llap/vectorized_mapjoin.q.out
  ql/src/test/results/clientpositive/llap/vectorized_mapjoin2.q.out
  ql/src/test/results/clientpositive/llap/vectorized_mapjoin3.q.out
  ql/src/test/results/clientpositive/llap/vectorized_nested_mapjoin.q.out
  ql/src/test/results/clientpositive/tez/hybridgrace_hashjoin_1.q.out
Labels: tests passed

#1073 HIVE-22869: Add locking benchmark to metastore-tools/metastore-benchmarks
  standalone-metastore/metastore-tools/findbugs/findbugs-exclude.xml
  standalone-metastore/metastore-tools/metastore-benchmarks/pom.xml
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/ACIDBenchmarks.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkUtils.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSConfig.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkSuite.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/Util.java
Labels: tests passed

#1251 HIVE-23840: Use LLAP to get orc metadata
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
  ql/src/java/org/apache/hadoop/hive/llap/LlapHiveUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRecordUpdater.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSplit.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcRawRecordMerger.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
Labels: tests passed

#1239 HIVE-23836: Make 'cols' dependent so that it cascade deletes
  standalone-metastore/metastore-server/src/main/resources/package.jdo
Labels: tests passed

#1284 HIVE-23881 : Deprecate get_open_txns to use get_open_txns_req
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetOpenTxnsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/OpenTxnList.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
Labels: tests passed

#1259 HIVE-23853: CRUD based compaction also should update ACID file version metadata
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcFile.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcOutputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtilities.java
Labels: tests passed

#1169 HIVE-20447: Add JSON Output Format to beeline
  beeline/pom.xml
  beeline/src/java/org/apache/hive/beeline/BeeLine.java
  beeline/src/java/org/apache/hive/beeline/JSONFileOutputFormat.java
  beeline/src/java/org/apache/hive/beeline/JSONOutputFormat.java
  beeline/src/main/resources/BeeLine.properties
  beeline/src/test/org/apache/hive/beeline/TestJSONFileOutputFormat.java
  beeline/src/test/org/apache/hive/beeline/TestJSONOutputFormat.java
Labels: tests passed

#1287 HIVE-23888: Simplify special_character_in_tabnames_1.q
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestSpecialCharacterInTableNames.java
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestSpecialCharacterInTableNamesQuotes.java
  ql/src/test/queries/clientpositive/special_character_in_tabnames_1.q
  ql/src/test/queries/clientpositive/special_character_in_tabnames_quotes_1.q
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_1.q.out
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_quotes_1.q.out
Labels: tests passed

#1155 HIVE-19703: GenericUDTFGetSplits never uses num splits argument
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/AbstractTestJdbcGenericUDTFGetSplits.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcGenericUDTFGetSplits.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcGenericUDTFGetSplits2.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HiveSplitGenerator.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
  ql/src/test/results/clientpositive/llap/mm_all.q.out
  ql/src/test/results/clientpositive/llap/mm_dp.q.out
Labels: tests passed

#1276 HIVE-23875: Add VSCode files to gitignore
  .gitignore
Labels: tests passed

#1201 HIVE-23797: Throw exception when no metastore found in zookeeper
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHMSZKNegative.java
Labels: tests passed

#1203 HIVE-22674: Replace Base64 in serde Package
  ql/src/test/results/clientpositive/llap/compute_stats_binary.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyBinary.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/fast/LazySimpleSerializeWrite.java
  serde/src/test/org/apache/hadoop/hive/serde2/lazy/TestLazySimpleSerDe.java
Labels: tests passed

#1263 HIVE-23849: Hive skips the creation of ColumnAccessInfo when creating a view
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/results/clientpositive/llap/create_view.q.out
  ql/src/test/results/clientpositive/llap/create_view_disable_cbo.q.out
  ql/src/test/results/clientpositive/llap/ppd_deterministic_expr.q.out
  ql/src/test/results/clientpositive/llap/ppd_field_garbage.q.out
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_1.q.out
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_quotes_1.q.out
  ql/src/test/results/clientpositive/llap/strict_managed_tables_sysdb.q.out
Labels: tests pending

#1288 HIVE-23198
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestCacheContentsTracker.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestProactiveEviction.java
  ql/src/java/org/apache/hadoop/hive/llap/ProactiveEviction.java
  storage-api/src/java/org/apache/hadoop/hive/common/io/CacheTag.java
Labels: tests passed

#1267 HIVE-23865: Use More Java Collections Class
  hcatalog/hcatalog-pig-adapter/src/main/java/org/apache/hive/hcatalog/pig/HCatBaseStorer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/DAGSummary.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/FSCountersSummary.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/LLAPioSummary.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/LlapWmSummary.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/PointLookupOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDAFPercentile.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/objectinspector/LazyBinaryObjectInspectorFactory.java
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/MetadataListStructObjectInspector.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/Batchable.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#1295 HIVE-23898: Query fails if identifier contains double quotes or semicolon char
  cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java
  ql/src/test/queries/clientpositive/quotedid_basic.q
  ql/src/test/queries/clientpositive/quotedid_basic_standard.q
  ql/src/test/results/clientpositive/llap/quotedid_basic.q.out
  ql/src/test/results/clientpositive/llap/quotedid_basic_standard.q.out
Labels: tests passed

#1298 HIVE-20771: LazyBinarySerDe fails on empty structs
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinaryNonPrimitive.java
  serde/src/test/org/apache/hadoop/hive/serde2/lazybinary/TestLazyBinaryStruct.java
Labels: tests pending

#1296 HIVE-23899: Replace Base64 in llap Packages
  llap-client/src/java/org/apache/hadoop/hive/registry/impl/TezAmInstance.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
Labels: tests passed

#1300 HIVE-23878: Aggregate after join throws off MV rewrite
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveDefaultRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttleImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveTezModelRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/cost/HiveVolcanoPlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializationRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewBoxing.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/perf/mv_query30.q
  ql/src/test/queries/clientpositive/perf/mv_query45.q
  ql/src/test/queries/clientpositive/perf/mv_query68.q
  ql/src/test/results/clientpositive/llap/schema_evol_text_vec_part_all_primitive.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/mv_query30.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/mv_query45.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/mv_query68.q.out
Labels: tests passed

#1302 HIVE-23908: Rewrite plan to join back tables: handle root input is an Aggregate
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinOptimization.java
  ql/src/test/results/clientpositive/llap/constraints_optimization.q.out
Labels: tests passed

#1290 HIVE-23874: Added debug line for fetchRequest in the HiveQueryResultSet
  jdbc/src/java/org/apache/hive/jdbc/HiveQueryResultSet.java
Labels: tests passed

#1306 HIVE-23917: Reset key access count during eviction in VectorGroupByOp…
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorAggregationBufferRow.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorGroupByOperator.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorGroupByOperator.java
Labels: tests unstable

#1184 HIVE-23750: Rewrite plan to join back tables: support function calls in project
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinOptimization.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinRule.java
  ql/src/test/queries/clientpositive/cardinality_preserving_join_opt.q
  ql/src/test/results/clientpositive/llap/cardinality_preserving_join_opt.q.out
  ql/src/test/results/clientpositive/llap/constraints_optimization.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query11.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query4.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query74.q.out
Labels: tests passed

#1215 HIVE-23806: Avoid clearing column stat states in all partition in case schema is extended
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
Labels: tests passed

#1228 HIVE-23817. Pushing TopN Key operator PKFK inner joins (amagyar)
  parser/src/java/org/apache/hadoop/hive/ql/parse/HintParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/topnkey/TopNKeyPushdownProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBJoinTree.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/JoinDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TopNKeyDesc.java
  ql/src/test/queries/clientpositive/topnkey_inner_join.q
  ql/src/test/queries/clientpositive/topnkey_inner_join2.q
  ql/src/test/results/clientpositive/llap/topnkey_inner_join.q.out
  ql/src/test/results/clientpositive/llap/topnkey_inner_join2.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/mv_query44.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query44.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query65.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query99.q.out
Labels: tests passed

#1305 HIVE-23892: Remove interpretation for character RexLiteral
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ExprNodeConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/RexNodeConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/TypeConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
  ql/src/test/queries/clientpositive/vector_const.q
  ql/src/test/results/clientpositive/llap/subquery_notexists.q.out
  ql/src/test/results/clientpositive/llap/union_assertion_type.q.out
  ql/src/test/results/clientpositive/llap/vector_const.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query5.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query80.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query84.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query91.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query5.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query80.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query84.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query91.q.out
Labels: tests passed

#1272 HIVE-23727: Improve SQLOperation log handling when canceling background
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
Labels: tests passed

#1293 HIVE-23894: SubmitDag should not be retried incase of query cancel
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
Labels: tests passed

#1303 HIVE-23915: Improve Github PR Template
  .github/pull_request_template.md
Labels: tests passed

#1310 HIVE-23911: CBO fails when query has distinct in function and having clause
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/having_distinct_function.q
  ql/src/test/results/clientpositive/llap/having_distinct_function.q.out
Labels: tests passed

#1329 HIVE-23897 : Create a common Retry Interface for replication
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AtlasDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/RangerDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/RangerLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasRestClientBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasRestClientImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/RetryingClientTimeBased.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/NoOpRangerRestClient.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/RangerRestClient.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/RangerRestClientImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/util/Retryable.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/Utils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/FileOperations.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/MetricSink.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestRangerDumpTask.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestRangerLoadTask.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/ranger/TestRangerRestClient.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/util/TestRetryable.java
Labels: tests passed

#1275 HIVE-23324: Parallelise compaction directory cleaning process
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
Labels: tests passed
