Repository apache/hive, pull requests merged in 2020-12, with the labels that each got.

#1705 HIVE-24426. Spark job fails with fixed LlapTaskUmbilicalServer port.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-client/src/java/org/apache/hadoop/hive/llap/tezplugins/helpers/LlapTaskUmbilicalServer.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskCommunicator.java
Labels: tests passed

#1356 HIVE-23980: Shade Guava from hive-exec in Hive 2.3
  common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java
  itests/hive-blobstore/pom.xml
  itests/hive-unit/pom.xml
  itests/qtest-accumulo/pom.xml
  itests/qtest-spark/pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/QueryDisplay.java
Labels: tests failed

#1722 HIVE-24436: Fix Avro NULL_DEFAULT_VALUE compatibility issue
  serde/src/java/org/apache/hadoop/hive/serde2/avro/TypeInfoToSchema.java
Labels: tests passed

#1629 HIVE-24333 Cut long methods in Driver to smaller, more manageable pieces (Miklos Gergely)
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
Labels: tests passed

#1719 HIVE-24453: Direct SQL error when parsing create_time value for database
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#1713 HIVE-24435: Vectorized unix_timestamp is inconsistent with non-vectorized counterpart
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDayOfWeekString.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFTimestampFieldString.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFUnixTimeStampString.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFWeekOfYearString.java
  ql/src/test/queries/clientpositive/vector_unix_timestamp.q
  ql/src/test/queries/clientpositive/vectorized_timestamp_funcs.q
  ql/src/test/results/clientpositive/llap/vector_unix_timestamp.q.out
  ql/src/test/results/clientpositive/llap/vectorized_timestamp_funcs.q.out
Labels: tests passed

#1684 HIVE-21843: UNION query with regular expressions for column name does not work
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rewrite/AlterMaterializedViewRewriteOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/tools/LineageInfo.java
  ql/src/test/org/apache/hadoop/hive/ql/ddl/table/partition/show/TestShowPartitionAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestMacroSemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestParseUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/authorization/AuthorizationTestUtil.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/authorization/PrivilegesTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/authorization/TestHiveAuthorizationTaskFactory.java
  ql/src/test/org/apache/hadoop/hive/ql/tool/TestLineageInfo.java
  ql/src/test/queries/clientpositive/union_regex.q
  ql/src/test/results/clientpositive/llap/union_regex.q.out
Labels: tests passed

#1723 HIVE-21588: Remove HBase dependency from hive-metastore
  metastore/pom.xml
  packaging/src/main/assembly/bin.xml
  pom.xml
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#1688 HIVE-24403: change min_history_level to make it compatible with older versions
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithoutMinHistoryLevel.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnDbUtil.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-3.2.0-to-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-3.2.0-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-3.2.0-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-3.2.0-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-3.2.0-to-4.0.0.postgres.sql
  streaming/src/java/org/apache/hive/streaming/AbstractRecordWriter.java
Labels: tests passed

#1745 HIVE-24489: TPC-DS dockerized tests fail due to stale entries in MIN_HISTORY_LEVEL metastore table
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/PostgresTPCDS.java
Labels: tests passed

#1712 HIVE-24433 - AutoCompaction is not getting triggered for CamelCase Partition Values
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTxns.java
Labels: tests passed

#1717 HIVE-24446: Materialized View plan alters explicit cast type in query
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/RexNodeConverter.java
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_window.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query23.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query28.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query37.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query64.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query82.q.out
Labels: tests passed

#1730 HIVE-24475: Generalize fixacidkeyindex utility
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/FixAcidKeyIndex.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestFixAcidKeyIndex.java
Labels: tests passed

#1760 HIVE-24512. Exclude calcite in packaging
  packaging/src/main/assembly/bin.xml
Labels: tests pending

#1755 HIVE-24497: Node heartbeats from LLAP Daemon to the client are not ma…
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/AMReporter.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskRunnerCallable.java
  llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/comparator/TestAMReporter.java
Labels: tests passed

#1649 HIVE-24245: Vectorized PTF with count and distinct over partition producing incorrect results.
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorBytesCountDistinct.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorCountDistinct.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorDecimalCountDistinct.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorDoubleCountDistinct.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorLongCountDistinct.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorTimestampCountDistinct.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFCount.java
  ql/src/test/queries/clientpositive/vector_ptf_count_distinct.q
  ql/src/test/results/clientpositive/llap/vector_ptf_count_distinct.q.out
Labels: tests passed

#1758 HIVE-24504: VectorFileSinkArrowOperator does not serialize complex types correctly
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
  ql/src/test/org/apache/hadoop/hive/ql/io/arrow/TestSerializer.java
Labels: tests unstable

#1750 HIVE-24388: Enhance swo optimizations to merge EventOperators
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/test/queries/clientpositive/swo_event_merge.q
  ql/src/test/results/clientpositive/llap/swo_event_merge.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query11.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query2.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query23.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query4.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query59.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query74.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query75.q.out
Labels: tests passed

#1556 HIVE-24207: LimitOperator can leverage ObjectCache to bail out quickly
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniTezCliDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/LimitOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorLimitOperator.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestLimitOperator.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorLimitOperator.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/util/FakeVectorRowBatchFromObjectIterables.java
  ql/src/test/queries/clientpositive/authorization_view_1.q
  ql/src/test/queries/clientpositive/authorization_view_disable_cbo_1.q
  ql/src/test/queries/clientpositive/input14_limit.q
  ql/src/test/results/clientpositive/llap/authorization_view_1.q.out
  ql/src/test/results/clientpositive/llap/authorization_view_disable_cbo_1.q.out
Labels: tests passed

#1751 HIVE-24498: add thrift facebook classes to hive-exec jar
  ql/pom.xml
Labels: tests passed

#1766 HIVE-24488: Make tests using docker more comfortable
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/DatabaseRule.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Derby.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mssql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Oracle.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Postgres.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/PostgresTPCDS.java
Labels: tests passed

#1737 Set advanced write Id during add constraint DDL tasks
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/add/AlterTableAddConstraintAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/results/clientnegative/alter_table_constraint_invalid_fk_tbl1.q.out
  ql/src/test/results/clientnegative/alter_table_constraint_invalid_pk_tbl.q.out
  ql/src/test/results/clientpositive/llap/default_constraint.q.out
Labels: tests passed

#1738 HIVE-24481: Skipped compaction can cause data corruption with streaming
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
Labels: tests passed

#1739 HIVE-17709: remove sun.misc.Cleaner references
  common/src/java/org/apache/hive/common/util/CleanerUtil.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/SimpleAllocator.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/encoded/EncodedReaderImpl.java
Labels: tests passed

#1581 HIVE-24276: HiveServer2 loggerconf jsp Cross-Site Scripting (XSS) Vulnerability
  service/src/resources/hive-webapps/static/js/logconf.js
Labels: tests unstable

#1753 HIVE-24503 : Optimize vector row serde by avoiding type check at run time.
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorDeserializeRow.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorSerializeRow.java
Labels: tests passed

#1728 HIVE-24468: Use Event Time instead of Current Time in Notification Lo…
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
Labels: tests passed

#1763 Fix recursive call
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreMethods.java
Labels: tests passed

#1774 HIVE-24322: In case of direct insert, the attempt ID has to be checke…
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestUtilities.java
Labels: tests passed

#1725 HIVE-24460: Refactor Get Next Event ID for DbNotificationListener
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/SQLGenerator.java
Labels: tests passed

#1775 HIVE-24530: Potential NPE in FileSinkOperator.closeRecordwriters method
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
Labels: tests passed

#1735 HIVE-24474: Failed compaction always logs TxnAbortedException (again)
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#1574 HIVE-24264: Fix failed-to-read test results
  Jenkinsfile
  ql/src/java/org/apache/hadoop/hive/ql/hooks/RuntimeStatsPersistenceCheckerHook.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/BucketVersionPopulator.java
  ql/src/java/org/apache/hadoop/hive/ql/ppd/OpProcFactory.java
Labels: tests passed

#1784 HIVE-24542: Prepare Guava for Upgrades
  common/pom.xml
  common/src/java/org/apache/hadoop/hive/common/log/InPlaceUpdate.java
  llap-common/pom.xml
  llap-common/src/java/org/apache/hadoop/hive/llap/AsyncPbRpcProxy.java
  llap-server/pom.xml
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/AMReporter.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapTaskReporter.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/SampleTezSessionState.java
  standalone-metastore/metastore-tools/tools-common/pom.xml
  storage-api/pom.xml
Labels: tests passed

#1710 HIVE-24432: Delete Notification Events in Batches
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Labels: tests passed

#1792 HIVE-24551: Hive should include transitive dependencies from calcite after shading it
  Jenkinsfile
  pom.xml
  ql/pom.xml
Labels: tests unstable

#1796 HIVE-24547: Fix acid_vectorization_original
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/acid_vectorization_original.q
Labels: tests passed

#1731 HIVE-24477: Separate production and test code in TxnDbUtil
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestAcidTableSetup.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithReplication.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  itests/qtest/pom.xml
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestMetaStoreHandler.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandlerNoConnectionPool.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnConcatenate.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestUpdateDeleteSemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithoutMinHistoryLevel.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestFilterHooks.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTxns.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionManagement.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestAcidTxnCleanerService.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestOpenTxn.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestTxnUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
  streaming/pom.xml
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
  streaming/src/test/org/apache/hive/streaming/TestStreamingDynamicPartitioning.java
Labels: tests passed

#1794 HIVE-24553. Exclude calcite from test-jar dependency of hive-exec
  beeline/pom.xml
  hcatalog/core/pom.xml
  hcatalog/hcatalog-pig-adapter/pom.xml
  hcatalog/server-extensions/pom.xml
  hcatalog/webhcat/java-client/pom.xml
  itests/hive-minikdc/pom.xml
  itests/hive-unit-hadoop2/pom.xml
  itests/hive-unit/pom.xml
  itests/qtest-accumulo/pom.xml
  itests/util/pom.xml
  service/pom.xml
Labels: tests pending

#1788 HIVE-24513: Advance write ID during drop constraint
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintDesc.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/results/clientnegative/drop_invalid_constraint2.q.out
  ql/src/test/results/clientpositive/llap/default_constraint.q.out
Labels: tests passed

#1800 HIVE-24554: TestCompactor fails to compile since HIVE-24477
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
Labels: tests pending

#1790 HIVE-24548: CompactionHeartbeater leaks metastore connection
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#1803 HIVE-24556: Optimize DefaultGraphWalker for case with no grandchild
  ql/src/java/org/apache/hadoop/hive/ql/lib/DefaultGraphWalker.java
Labels: tests passed

#1809 HIVE-24562: Deflake TestHivePrivilegeObjectOwnerNameAndType
  ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHivePrivilegeObjectOwnerNameAndType.java
Labels: tests passed

#1808 HIVE-24561: Deflake TestCachedStoreUpdateUsingEvents test
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
Labels: tests passed

#1805 HIVE-24559: Fix some spelling issues
  metastore/src/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
Labels: tests unstable
