Repository apache/hive, pull requests merged in 2020-08, with the labels that each got.

#1252 HIVE-23847: Extracting hive-parser module broke exec jar upload in tez
  ql/pom.xml
Labels: tests passed

#1349 HIVE-23973: Use SQL constraints to improve join reordering algorithm …
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterJoinRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinProjectTransposeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinSwapConstraintsRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSemiJoinProjectTransposeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/results/clientpositive/llap/auto_join28.q.out
  ql/src/test/results/clientpositive/llap/auto_join29.q.out
  ql/src/test/results/clientpositive/llap/correlationoptimizer4.q.out
  ql/src/test/results/clientpositive/llap/join46.q.out
  ql/src/test/results/clientpositive/llap/join_merging.q.out
  ql/src/test/results/clientpositive/llap/mapjoin46.q.out
  ql/src/test/results/clientpositive/llap/sharedwork.q.out
  ql/src/test/results/clientpositive/llap/tez_join_tests.q.out
  ql/src/test/results/clientpositive/llap/tez_joins_explain.q.out
  ql/src/test/results/clientpositive/mapjoin47.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query10.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query35.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query69.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query72.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query10.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query35.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query69.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query72.q.out
Labels: tests passed

#1328 HIVE-23873: Querying Hive JDBCStorageHandler table fails with NPE whe…
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/JdbcRecordIterator.java
  ql/src/test/queries/clientpositive/external_jdbc_table4.q
  ql/src/test/results/clientpositive/llap/external_jdbc_table4.q.out
Labels: tests passed

#1351 [DRAFT] MSC local cache
  cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java
  data/conf/hive-site.xml
  data/conf/llap/hive-site.xml
  data/conf/rlist/hive-site.xml
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosIncrementalLoadAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/test/org/apache/hadoop/hive/metastore/TestMetastoreExpr.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-common/spotbugs/spotbugs-exclude.xml
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/PerfLogger.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestListPartitions.java
  standalone-metastore/pom.xml
  standalone-metastore/spotbugs/spotbugs-exclude.xml
Labels: tests passed

#1326 HIVE-23941: Refactor TypeCheckProcFactory to be database agnostic
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/HiveFunctionInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/FunctionHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/HiveFunctionHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/type/TestBigIntCompareValidation.java
Labels: tests passed

#1230 HIVE-23819: Use ranges in ValidReadTxnList serialization
  storage-api/src/java/org/apache/hadoop/hive/common/ValidReadTxnList.java
  storage-api/src/test/org/apache/hadoop/hive/common/TestValidReadTxnList.java
Labels: tests passed

#1242 HIVE-20441: NPE in GenericUDF when hive.allow.udf.load.on.demand is s…
  ql/src/java/org/apache/hadoop/hive/ql/exec/Registry.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/type/TestExprProcessorGetFuncExpr.java
Labels: tests passed

#1309 HIVE-23929: Run compaction as partition owner
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#1327 HIVE-23763: Query based minor compaction produces wrong files when ro…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ReduceSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/opconventer/HiveOpConverterUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ReduceSinkDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
Labels: tests passed

#1340 HIVE-23953 : Use task counter information to compute keycount during hashtable loading
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HashTableLoader.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTableLoader.java
Labels: tests passed

#1341 HIVE-23959: Provide an option to wipe out column stats for partitioned tables in case of column removal
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  ql/src/test/queries/clientpositive/colstats_remove_on_col_replace.q
  ql/src/test/queries/clientpositive/colstats_remove_on_col_replace2.q
  ql/src/test/results/clientpositive/llap/colstats_remove_on_col_replace.q.out
  ql/src/test/results/clientpositive/llap/colstats_remove_on_col_replace2.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
Labels: tests passed

#1346 HIVE-23966: Minor query-based compaction always results in delta dirs with minWriteId=1
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
Labels: tests passed

#1338 HIVE-23937. Take null ordering into consideration when pushing TNK through inner joins (amagyar)
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/topnkey/TopNKeyPushdownProcessor.java
  ql/src/test/queries/clientpositive/topnkey_inner_join.q
  ql/src/test/queries/clientpositive/topnkey_inner_join2.q
  ql/src/test/results/clientpositive/llap/topnkey_inner_join.q.out
  ql/src/test/results/clientpositive/llap/topnkey_inner_join2.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/mv_query44.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query44.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query65.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query99.q.out
Labels: tests passed

#1339 HIVE-23956: Delete delta fileIds should be pushed execution
  llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestOrcMetadataCache.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/SyntheticFileId.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSplit.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
Labels: tests passed

#1359 HIVE-23988: Remove unused method
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
Labels: tests passed

#1315 [HIVE-23951] Support parameterized queries in WHERE/HAVING clause
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/PrepareStatementParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestSQL11ReservedKeyWordsNegative.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/QueryPlan.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/OperatorUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/lineage/ExprProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/AnnotateRunTimeStatsOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ExecuteStatementAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PrepareStatementAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzerFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprDynamicParamDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
  ql/src/test/queries/clientnegative/execute_mismatched_parameters.q
  ql/src/test/queries/clientnegative/execute_without_prepare.q
  ql/src/test/queries/clientnegative/prepare_execute_1.q
  ql/src/test/queries/clientpositive/prepare_plan.q
  ql/src/test/results/clientnegative/execute_mismatched_parameters.q.out
  ql/src/test/results/clientnegative/execute_without_prepare.q.out
  ql/src/test/results/clientnegative/prepare_execute_1.q.out
  ql/src/test/results/clientpositive/llap/prepare_plan.q.out
  ql/src/test/results/clientpositive/llap/udf_greatest.q.out
  ql/src/test/results/clientpositive/llap/udf_least.q.out
Labels: tests passed

#1371 HIVE-24000: Put exclusive MERGE INSERT under the feature flag
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/queries/clientpositive/explain_locks.q
  ql/src/test/results/clientpositive/llap/explain_locks.q.out
Labels: tests passed

#1357 HIVE-23963: UnsupportedOperationException in queries 74 and 84 while applying HiveCardinalityPreservingJoinRule
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/Bug.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelDistribution.java
Labels: tests passed

#1355 send tableId to get_partition APIs
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/add/AlterTableAddPartitionOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestTxnManager.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreClientApiArgumentsChecker.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreClient.java
Labels: tests passed

#1374 HIVE-24012: Support for rewriting with materialized views containing …
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptMaterializationValidator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/materialized_view_rewrite_ssb_grouping_sets.q
  ql/src/test/queries/clientpositive/materialized_view_rewrite_ssb_grouping_sets_2.q
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_ssb_grouping_sets.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_ssb_grouping_sets_2.q.out
Labels: tests passed

#1383 HIVE-24021: Read insert-only tables truncated by Impala correctly
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
Labels: tests pending

#1364 HIVE-23997: Some logs in ConstantPropagateProcFactory are not straightforward
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConstantPropagateProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/ppd/OpProcFactory.java
Labels: tests passed

#1363 HIVE-23996: Remove unused line to keep code clean
  udf/src/java/org/apache/hadoop/hive/ql/exec/UDFArgumentException.java
Labels: tests passed

#1368 HIVE-24001: Don't cache MapWork in tez/ObjectCache during query-based compaction
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MapRecordProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
Labels: tests passed

#1393 HIVE-24030: Upgrade ORC to 1.5.10
  pom.xml
Labels: tests passed

#1307 HIVE-23922: Improve code quality, UDFArgumentException.getMessage Method requires only two parameters
  udf/src/java/org/apache/hadoop/hive/ql/exec/UDFArgumentException.java
Labels: tests passed

#1390 [HIVE-24025] Add getAggrColStatsFor to the HS2 local cache
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
Labels: tests passed

#1389 HIVE-24024: Improve logging around CompactionTxnHandler
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#1375 HIVE-24015: Disable query-based compaction on MR execution engine
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnMr.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactorFactory.java
Labels: tests passed

#1350 HIVE-23972: Add external client ID to LLAP external client
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
Labels: tests passed

#1404 [HIVE-23979] Resolve spotbugs errors in JsonReporter.java, Metrics.java, and PerfLogger.java
  common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/Executor.java
  ql/src/java/org/apache/hadoop/hive/ql/HookRunner.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MapJoinOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SparkHashTableSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkDynamicPartitionPruner.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkMapRecordHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkPlan.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkPlanGenerator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkReduceRecordHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/status/LocalSparkJobMonitor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/status/RemoteSparkJobMonitor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/status/RenderStrategy.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MapRecordProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MergeFileRecordProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/ReduceRecordProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/ReduceRecordSource.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/RenderStrategy.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
  ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/Transform.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionPruner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/spark/SparkCompiler.java
  ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveProtoLoggingHook.java
  standalone-metastore/metastore-common/spotbugs/spotbugs-exclude.xml
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/JsonReporter.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/PerfLogger.java
  standalone-metastore/spotbugs/spotbugs-exclude.xml
Labels: tests passed

#1050 HIVE-23358: MSCK Repair should remove insignificant 0's from numeric partition values
  ql/src/test/queries/clientpositive/msck_repair_7.q
  ql/src/test/results/clientpositive/llap/msck_repair_7.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java
Labels: stale, tests passed

#1397 HIVE-23980: Shade Guava from hive-exec in Hive branch-2
  common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/QueryDisplay.java
Labels: tests unstable

#1388 HIVE-24023: Hive parquet reader can't read files with length=0
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsNoJobTask.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
Labels: tests passed

#1427 HIVE-23302: Create HiveJdbcDatabaseAccessor for JDBC storage handler
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/DatabaseAccessorFactory.java
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/HiveDatabaseAccessor.java
Labels: tests passed

#1426 HIVE-23649: Spotbugs should ignore generated thrift files
  Jenkinsfile
  spotbugs/spotbugs-exclude.xml
Labels: tests passed

#1405 HIVE-24041: Extend semijoin conversion rules
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSemiJoinRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/auto_sortmerge_join_10.q
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_10.q.out
  ql/src/test/results/clientpositive/llap/bucket_map_join_tez2.q.out
  ql/src/test/results/clientpositive/llap/explainuser_1.q.out
  ql/src/test/results/clientpositive/llap/join_reorder5.q.out
  ql/src/test/results/clientpositive/llap/multiMapJoin2.q.out
  ql/src/test/results/clientpositive/llap/reduce_deduplicate_extended2.q.out
  ql/src/test/results/clientpositive/llap/subquery_in.q.out
  ql/src/test/results/clientpositive/llap/subquery_in_having.q.out
  ql/src/test/results/clientpositive/llap/subquery_multi.q.out
  ql/src/test/results/clientpositive/llap/subquery_scalar.q.out
  ql/src/test/results/clientpositive/llap/subquery_views.q.out
  ql/src/test/results/clientpositive/llap/vector_mapjoin_reduce.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query14.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query23.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query95.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query95.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query95.q.out
  ql/src/test/results/clientpositive/perf/tez/query14.q.out
  ql/src/test/results/clientpositive/perf/tez/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/query95.q.out
Labels: tests passed

#1382 HIVE-24020: Fix Automatic compaction for streaming ingest with dynamic partition
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  streaming/src/java/org/apache/hive/streaming/AbstractRecordWriter.java
Labels: tests passed

#1431 HIVE-24061: Improve llap task scheduling for better cache hit rate
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
Labels: tests passed

#1392 HIVE-24074: Incorrect handling of timestamp in Parquet/Avro when written in certain time zones in versions before Hive 3.x
  common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  data/files/tbl_avro1/000000_0
  data/files/tbl_avro1/000000_0_copy_1
  data/files/tbl_parq1/000000_0
  data/files/tbl_parq1/000000_0_copy_1
  data/files/tbl_parq1/000000_0_copy_2
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapVectorArrowBatch.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/qoption/QTestTimezoneHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/convert/ETypeConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/DataWritableReadSupport.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/BaseVectorizedColumnReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/ParquetDataColumnReaderFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedListColumnReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedPrimitiveColumnReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/convert/TestGetDataColumnReaderByType.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampUtils.java
  ql/src/test/queries/clientpositive/avro_legacy_mixed_timestamp.q
  ql/src/test/queries/clientpositive/avro_timestamp2.q
  ql/src/test/queries/clientpositive/parquet_legacy_mixed_timestamp.q
  ql/src/test/queries/clientpositive/parquet_timestamp.q
  ql/src/test/results/clientpositive/llap/avro_legacy_mixed_timestamp.q.out
  ql/src/test/results/clientpositive/llap/avro_timestamp2.q.out
  ql/src/test/results/clientpositive/llap/parquet_legacy_mixed_timestamp.q.out
  ql/src/test/results/clientpositive/llap/parquet_timestamp.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java
Labels: tests passed
