Repository apache/hive, pull requests merged in 2020-09, with the labels that each got.

#1440 HIVE-24087 FK side join elimination in presence of PK-FK constraint
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterJoinRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinConstraintsRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinSwapConstraintsRule.java
  ql/src/test/queries/clientpositive/join_constraints_optimization.q
  ql/src/test/results/clientpositive/llap/join_constraints_optimization.q.out
Labels: tests passed

#1441 HIVE-24089: Run QB compaction as table directory user with impersonation
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
Labels: tests passed

#1446 HIVE-22622: Hive allows to create a struct with duplicate attribute names
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/test/queries/clientnegative/struct_attribute_uniqueness.q
  ql/src/test/queries/clientnegative/struct_attribute_uniqueness_2.q
  ql/src/test/results/clientnegative/struct_attribute_uniqueness.q.out
  ql/src/test/results/clientnegative/struct_attribute_uniqueness_2.q.out
Labels: tests passed

#1445 HIVE-24093: Remove unused hive.debug.localtask
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests passed

#1437 HIVE-24081: Enable pre-materializing CTEs referenced in scalar subqueries
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  data/conf/perf-reg/tez/hive-site.xml
  ql/src/java/org/apache/hadoop/hive/ql/parse/QB.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBParseInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/cte_3.q
  ql/src/test/queries/clientpositive/cte_4.q
  ql/src/test/queries/clientpositive/cte_mat_3.q
  ql/src/test/queries/clientpositive/cte_mat_4.q
  ql/src/test/queries/clientpositive/cte_mat_5.q
  ql/src/test/queries/clientpositive/cte_mat_6.q
  ql/src/test/queries/clientpositive/cte_mat_7.q
  ql/src/test/results/clientpositive/llap/cte_4.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_6.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_7.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query14.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query14.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query14.q.out
  ql/src/test/results/clientpositive/perf/tez/query14.q.out
Labels: tests passed

#1391 Spark client can create/alter/drop a view
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
Labels: tests passed

#1447 HIVE-24096: Abort failed compaction's txn on TException or IOException
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#1464 [WIP]HIVE-23406: SharedWorkOptimizer should check nullSortOrders when comparing ReduceSink operators
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
Labels: tests passed

#1466 HIVE-24116: LLAP: Provide an opportunity for preempted tasks to get b…
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
Labels: tests passed

#1379 HIVE-23408: Hive on Tez : Kafka storage handler broken in secure envi…
  kafka-handler/pom.xml
  kafka-handler/src/java/org/apache/hadoop/hive/kafka/KafkaUtils.java
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDagUtils.java
Labels: tests passed

#1453 HIVE-24104: NPE due to null key columns in ReduceSink after deduplication
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/ReduceSinkDeDuplicationUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ReduceSinkDesc.java
  ql/src/test/queries/clientpositive/dynamic_semijoin_reduction_on_aggcol.q
  ql/src/test/queries/clientpositive/reduce_deduplicate_null_keys.q
  ql/src/test/results/clientpositive/llap/reduce_deduplicate_null_keys.q.out
Labels: tests passed

#1424 HIVE-24031: Infinite planning time on syntactically big queries
  parser/src/java/org/apache/hadoop/hive/ql/parse/ASTNode.java
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseDriverIntervals.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/skewed/AlterTableSetSkewedLocationAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#1432 HIVE-24072 HiveAggregateJoinTransposeRule may try to create an invalid transformation
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveAggregateJoinTransposeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/ReadTableEvent.java
Labels: tests passed

#1474 Revert "HIVE-23725: ValidTxnManager snapshot outdating causing partia…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/IReExecutionPlugin.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecutionDagSubmitPlugin.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecutionOverlayPlugin.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecutionRetryLockPlugin.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReOptimizePlugin.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CommitTxnRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CommitTxnRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#1480 HIVE-24134 : Revert removal of HiveStrictManagedMigration code
  bin/ext/strictmanagedmigration.sh
  ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
  ql/src/test/org/apache/hadoop/hive/ql/util/TestHiveStrictManagedMigration.java
Labels: tests passed

#1399 HIVE-24036: Kryo Exception while serializing plan for getSplits UDF call
  ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
Labels: tests passed

#1443 Implement jdbc methods invoked by Calcite
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestHiveDatabaseMetaData.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCliServiceWithInfoMessage.java
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/HiveDatabaseMetaData.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
Labels: tests passed

#1482 HIVE-24143: Include convention in JDBC converter operator in Calcite …
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/jdbc/HiveJdbcConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/external_jdbc_auth.q
  ql/src/test/queries/clientpositive/external_jdbc_table.q
  ql/src/test/queries/clientpositive/external_jdbc_table2.q
  ql/src/test/queries/clientpositive/external_jdbc_table3.q
  ql/src/test/queries/clientpositive/external_jdbc_table4.q
  ql/src/test/queries/clientpositive/external_jdbc_table_partition.q
  ql/src/test/queries/clientpositive/external_jdbc_table_perf.q
  ql/src/test/queries/clientpositive/external_jdbc_table_typeconversion.q
  ql/src/test/results/clientpositive/llap/external_jdbc_table.q.out
  ql/src/test/results/clientpositive/llap/external_jdbc_table_perf.q.out
Labels: tests passed

#1403 HIVE-24039 : Update jquery version to mitigate CVE-2020-11023
  service/src/resources/hive-webapps/static/js/jquery.min.js
Labels: tests pending

#1488 HIVE-24149. HiveStreamingConnection doesn't close HMS connection (amagyar)
  streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
Labels: tests passed

#1494 HIVE-24158: Cleanup isn't complete in OrcFileMergeOperator#closeOp
  ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java
Labels: tests passed

#1471 HIVE-23454 : Querying hive table which has Materialized view fails with HiveAccessControlException
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/materialized_view_authorization_sqlstd.q
  ql/src/test/results/clientpositive/llap/materialized_view_authorization_sqlstd.q.out
Labels: tests passed

#1484 HIVE-22290: ObjectStore.cleanWriteNotificationEvents and ObjectStore.cleanupEvents OutOfMemory on large number of pending events
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#1496 HIVE-24160: Scheduled executions must allow state transition EXECUTING->TIMED_OUT
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#1439 HIVE-24084 Push Aggregates thru joins in case it re-groups previously unique columns
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveAggregateJoinTransposeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/tpch18.q
  ql/src/test/results/clientpositive/llap/constraints_optimization.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_part_2.q.out
  ql/src/test/results/clientpositive/llap/subquery_notin.q.out
  ql/src/test/results/clientpositive/llap/tpch18.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query54.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query54.q.out
Labels: tests passed

#1498 HIVE-24162: Query based compaction looses bloom filter
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
Labels: tests passed

#1489 HIVE-24150: Refactor CommitTxnRequest field order
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CommitTxnRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CommitTxnRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed

#1490 HIVE-24151
  data/files/t4_multi_delimit.csv
  ql/src/test/queries/clientpositive/serde_multi_delimit.q
  ql/src/test/results/clientpositive/llap/serde_multi_delimit.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyStruct.java
Labels: tests passed

#1505 HIVE-24077: Streaming Ingest v2 does not send heartbeats
  streaming/src/java/org/apache/hive/streaming/TransactionBatch.java
Labels: tests passed

#1486 HIVE-24147: Table column names are not extracted correctly in Hive JD…
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/HiveDatabaseAccessor.java
Labels: tests passed

#1504 HIVE-24176: Create query-level cache for HMS requests and extend existing local HS2 HMS cache
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
Labels: tests passed

#1495 HIVE-24159: Kafka storage handler broken in secure environment pt2: short-circuit on non-secure environment
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
Labels: tests passed

#1507 HIVE-24163: Dynamic Partitioning Insert fail for MM table fail during…
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/queries/clientpositive/create_transactional_full_acid.q
  ql/src/test/queries/clientpositive/mm_dyn_part.q
  ql/src/test/results/clientpositive/encrypted/encryption_insert_partition_dynamic.q.out
  ql/src/test/results/clientpositive/llap/acid_direct_insert_insert_overwrite.q.out
  ql/src/test/results/clientpositive/llap/acid_no_buckets.q.out
  ql/src/test/results/clientpositive/llap/acid_subquery.q.out
  ql/src/test/results/clientpositive/llap/create_transactional_full_acid.q.out
  ql/src/test/results/clientpositive/llap/insert_overwrite.q.out
  ql/src/test/results/clientpositive/llap/mm_all.q.out
  ql/src/test/results/clientpositive/llap/mm_dyn_part.q.out
Labels: tests passed

#1514 HIVE-24172: Fix TestMmCompactorOnMr
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnMr.java
Labels: tests passed

#1472 HIVE-24009 Support partition pruning, vectorization and other physical transformations for EXECUTE statement
  ql/src/java/org/apache/hadoop/hive/ql/exec/Operator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/TableScanOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ExecuteStatementAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PrepareStatementAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  ql/src/test/queries/clientnegative/prepare_execute_1.q
  ql/src/test/queries/clientpositive/prepare_plan.q
  ql/src/test/queries/clientpositive/prepare_plan_partition_pruning.q
  ql/src/test/results/clientnegative/execute_mismatched_parameters.q.out
  ql/src/test/results/clientnegative/prepare_execute_1.q.out
  ql/src/test/results/clientpositive/llap/constprog_dpp.q.out
  ql/src/test/results/clientpositive/llap/dynamic_semijoin_user_level.q.out
  ql/src/test/results/clientpositive/llap/explainanalyze_2.q.out
  ql/src/test/results/clientpositive/llap/explainuser_2.q.out
  ql/src/test/results/clientpositive/llap/prepare_plan.q.out
  ql/src/test/results/clientpositive/llap/prepare_plan_partition_pruning.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query2.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query5.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query54.q.out
  ql/src/test/results/clientpositive/perf/tez/query2.q.out
  ql/src/test/results/clientpositive/perf/tez/query5.q.out
  ql/src/test/results/clientpositive/perf/tez/query54.q.out
  ql/src/test/results/clientpositive/tez/explainanalyze_1.q.out
  ql/src/test/results/clientpositive/tez/explainanalyze_5.q.out
  ql/src/test/results/clientpositive/tez/tez_union_udtf.q.out
Labels: tests passed

#1516 HIVE-24188: CTLT from MM to External or External to MM are failing with hive.strict.managed.tables & hive.create.as.acid
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/create_like2.q
  ql/src/test/results/clientpositive/llap/create_like2.q.out
Labels: tests passed

#1518 HIVE-24191: Introduce configurable user to run compaction as
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#1398 HIVE-24035: Add Jenkinsfile for branch-2.3
  Jenkinsfile
  pom.xml
Labels: tests unstable

#1511 HIVE-24183: Clean up local HS2 HMS cache code
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
Labels: tests passed

#1438 HIVE-24082: Expose information whether AcidUtils.ParsedDelta contains statementId
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
Labels: tests passed

#1524 HIVE-24198 : Map side SMB join is producing wrong result
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/SplitGrouper.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
  ql/src/test/queries/clientpositive/auto_sortmerge_join_10.q
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_10.q.out
Labels: tests passed

#1517 HIVE-24190: LLAP: ShuffleHandler might return DISK_ERROR_EXCEPTION according to TEZ-4233
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
Labels: tests passed

#1501 HIVE-24168: Disable hdfsEncryptionShims cache during query-based comp…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
Labels: tests passed

#1500 HIVE-24161: Support Oracle CLOB type in beeline
  beeline/src/java/org/apache/hive/beeline/Rows.java
  beeline/src/test/org/apache/hive/beeline/TestBufferedRows.java
  beeline/src/test/org/apache/hive/beeline/TestIncrementalRows.java
  beeline/src/test/org/apache/hive/beeline/TestJSONFileOutputFormat.java
  beeline/src/test/org/apache/hive/beeline/TestJSONOutputFormat.java
  beeline/src/test/org/apache/hive/beeline/TestTableOutputFormat.java
Labels: tests passed

#1492 HIVE-24154: Missing simplification opportunity with IN and EQUALS cla…
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java
  ql/src/test/org/apache/hadoop/hive/ql/plan/mapping/TestCounterMapping.java
  ql/src/test/queries/clientpositive/multi_in_clause.q
  ql/src/test/results/clientpositive/llap/bucketpruning1.q.out
  ql/src/test/results/clientpositive/llap/dynamic_partition_skip_default.q.out
  ql/src/test/results/clientpositive/llap/external_jdbc_table_perf.q.out
  ql/src/test/results/clientpositive/llap/fold_eq_with_case_when.q.out
  ql/src/test/results/clientpositive/llap/join_filters_overlap.q.out
  ql/src/test/results/clientpositive/llap/masking_mv.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_ssb.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_ssb_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_ssb_grouping_sets.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_ssb_grouping_sets_2.q.out
  ql/src/test/results/clientpositive/llap/multi_in_clause.q.out
  ql/src/test/results/clientpositive/llap/pcr.q.out
  ql/src/test/results/clientpositive/llap/ppd_union_view.q.out
  ql/src/test/results/clientpositive/llap/rand_partitionpruner2.q.out
  ql/src/test/results/clientpositive/llap/rand_partitionpruner3.q.out
  ql/src/test/results/clientpositive/llap/union22.q.out
  ql/src/test/results/clientpositive/llap/unionDistinct_1.q.out
  ql/src/test/results/clientpositive/llap/vector_interval_2.q.out
  ql/src/test/results/clientpositive/perf/tez/cbo_query74.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query74.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query74.q.out
  ql/src/test/results/clientpositive/perf/tez/query74.q.out
Labels: tests passed
