Repository apache/hive, pull requests merged in 2020-11, with the labels that each got.

#1641 Disable flaky test: TestCleanupService#testEventualCleanupService_finishesCleanupBeforeExit
  ql/src/test/org/apache/hadoop/hive/ql/cleanup/TestCleanupService.java
Labels: tests unstable

#1642 Disable cardinality_preserving_join_opt2
  ql/src/test/queries/clientpositive/cardinality_preserving_join_opt2.q
Labels: tests pending

#1592 HIVE-24291: Compaction cleaner should wait for all prev txn to commit
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithReplication.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
  ql/src/test/results/clientpositive/llap/cardinality_preserving_join_opt2.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-3.2.0-to-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-3.2.0-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-3.2.0-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-3.2.0-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-3.2.0-to-4.0.0.postgres.sql
Labels: tests passed

#1643 HIVE-24347: Fix failing test: TestMiniLlapLocalCliDriver.testCliDriver[cardinality_preserving_join_opt2]
  ql/src/test/queries/clientpositive/cardinality_preserving_join_opt2.q
  ql/src/test/results/clientpositive/llap/cardinality_preserving_join_opt2.q.out
Labels: tests passed

#1626 HIVE-24331: Add Jenkinsfile for branch-3.1
  Jenkinsfile
Labels: tests unstable

#1608 HIVE-23685: Removing user's extra resources while executing File Merge Task
  ql/src/java/org/apache/hadoop/hive/ql/io/merge/MergeFileTask.java
Labels: tests passed

#1613 HIVE-24314: compactor.Cleaner should not set state mark cleaned if it didn't remove any files
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
Labels: tests passed

#1616 HIVE-24316. Upgrade ORC from 1.5.6 to 1.5.8 in branch-3.1
  pom.xml
Labels: tests unstable

#1621 HIVE-24324: Remove deprecated API usage from Avro
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerdeUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/SchemaToTypeInfo.java
Labels: tests passed

#1639 HIVE-24342: isPathEncrypted should make sure resolved path also from HDFS.
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Labels: tests passed

#1652 HIVE-24355: Implement hashCode/equals for Partition
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Partition.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
  ql/src/test/queries/clientpositive/swo_pruned_merge.q
  ql/src/test/results/clientpositive/llap/swo_pruned_merge.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
Labels: tests passed

#1555 HIVE-24233: Except subquery throws nullpointer
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientnegative/except_cbooff.q
  ql/src/test/results/clientnegative/except_cbooff.q.out
Labels: tests passed

#1644 HIVE-24275: adding support for delayed cleanup of obsolete files/dirs
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-3.2.0-to-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-3.2.0-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-3.2.0-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-3.2.0-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-3.2.0-to-4.0.0.postgres.sql
Labels: tests passed

#1654 HIVE-24360: SharedWorkOptimizer may create incorrect plans with DPPUnion
  data/conf/hive-log4j2.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/DagGraph.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/DiGraph.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/DotExporter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/OperatorGraph.java
  ql/src/test/results/clientpositive/llap/acid_vectorization_original.q.out
  ql/src/test/results/clientpositive/llap/dynamic_partition_pruning.q.out
  ql/src/test/results/clientpositive/llap/vectorized_dynamic_partition_pruning.q.out
Labels: tests passed

#1656 HIVE-24362 : AST tree processing is suboptimal for tree with large number of nodes
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/PointLookupOptimizer.java
Labels: tests passed

#1458 HIVE-23976: Enable vectorization for multi-col semi join reducers
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/MurmurHashExpression.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/MurmurHashIntColIntCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/MurmurHashStringColIntCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/MurmurHashStringColStringCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorExpression.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMurmurHash.java
  ql/src/java/org/apache/hive/benchmark/vectorization/ColumnVectorGenUtil.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/expressions/TestMurmurHashExpression.java
  ql/src/test/queries/clientpositive/vectorized_dynamic_semijoin_reduction.q
  ql/src/test/results/clientpositive/llap/vectorized_dynamic_semijoin_reduction.q.out
Labels: tests passed

#1658 HIVE-24340: Mark phase for proactive cache eviction
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LlapAllocatorBuffer.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LlapCacheableBuffer.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCache.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheMemoryManager.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/SerDeLowLevelCacheImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/SimpleBufferManager.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/metadata/MetadataCache.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/metadata/OrcFileEstimateErrors.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestOrcMetadataCache.java
  storage-api/src/java/org/apache/hadoop/hive/common/io/FileMetadataCache.java
Labels: tests passed

#1618 Do not remove metadata for aborted writes that were batched with valid ones in the same delta file
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#1653 HIVE-24357: Exchange SWO table/algorithm strategy
  ql/src/java/org/apache/hadoop/hive/ql/exec/TableScanOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
  ql/src/test/results/clientpositive/llap/masking_10.q.out
  ql/src/test/results/clientpositive/llap/subquery_in.q.out
  ql/src/test/results/clientpositive/llap/subquery_views.q.out
  ql/src/test/results/clientpositive/llap/swo_pruned_merge.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query14.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query61.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query88.q.out
  ql/src/test/results/clientpositive/perf/tez/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/query61.q.out
  ql/src/test/results/clientpositive/perf/tez/query64.q.out
  ql/src/test/results/clientpositive/perf/tez/query65.q.out
  ql/src/test/results/clientpositive/perf/tez/query88.q.out
  ql/src/test/results/clientpositive/perf/tez/query95.q.out
Labels: tests passed

#1661 HIVE-24365: SWO should not create complex and redundant filter expressions
  ql/src/java/org/apache/hadoop/hive/ql/exec/FilterOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/GroupByOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Operator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ReduceSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SelectOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/DotExporter.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
  ql/src/test/results/clientpositive/perf/tez/constraints/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query88.q.out
  ql/src/test/results/clientpositive/perf/tez/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/query88.q.out
Labels: tests pending

#1562 HIVE-24241: Enable SharedWorkOptimizer to merge downstream operators after an optimization step
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/test/results/clientpositive/llap/explainuser_1.q.out
  ql/src/test/results/clientpositive/llap/explainuser_2.q.out
  ql/src/test/results/clientpositive/llap/masking_10.q.out
  ql/src/test/results/clientpositive/llap/mergejoins_mixed.q.out
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_1.q.out
  ql/src/test/results/clientpositive/llap/special_character_in_tabnames_quotes_1.q.out
  ql/src/test/results/clientpositive/llap/subquery_in.q.out
  ql/src/test/results/clientpositive/llap/subquery_multi.q.out
  ql/src/test/results/clientpositive/llap/subquery_notin.q.out
  ql/src/test/results/clientpositive/llap/subquery_scalar.q.out
  ql/src/test/results/clientpositive/llap/subquery_select.q.out
  ql/src/test/results/clientpositive/llap/subquery_unqualcolumnrefs.q.out
  ql/src/test/results/clientpositive/llap/subquery_views.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/cbo_query54.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query14.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query17.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query25.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query30.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query45.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query54.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query64.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query75.q.out
  ql/src/test/results/clientpositive/perf/tez/constraints/query9.q.out
  ql/src/test/results/clientpositive/perf/tez/query11.q.out
  ql/src/test/results/clientpositive/perf/tez/query14.q.out
  ql/src/test/results/clientpositive/perf/tez/query17.q.out
  ql/src/test/results/clientpositive/perf/tez/query23.q.out
  ql/src/test/results/clientpositive/perf/tez/query25.q.out
  ql/src/test/results/clientpositive/perf/tez/query30.q.out
  ql/src/test/results/clientpositive/perf/tez/query31.q.out
  ql/src/test/results/clientpositive/perf/tez/query4.q.out
  ql/src/test/results/clientpositive/perf/tez/query54.q.out
  ql/src/test/results/clientpositive/perf/tez/query64.q.out
  ql/src/test/results/clientpositive/perf/tez/query74.q.out
  ql/src/test/results/clientpositive/perf/tez/query75.q.out
  ql/src/test/results/clientpositive/perf/tez/query9.q.out
Labels: tests passed

#1666 HIVE-24373 : Wrong predicate is pushed down for view with constant value
  ql/src/java/org/apache/hadoop/hive/ql/ppd/ExprWalkerInfo.java
  ql/src/test/queries/clientpositive/ppd2.q
  ql/src/test/results/clientpositive/llap/ppd2.q.out
Labels: tests passed

#1509 HIVE-24179: Memory leak in HS2 DbTxnManager when compiling SHOW LOCKS statement
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/show/ShowDbLocksAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/show/ShowLocksAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
Labels: tests pending

#1669 HIVE-24379: Backport HIVE-19662 to branch-2.3
  hbase-handler/pom.xml
  pom.xml
Labels: tests unstable

#1671 HIVE-24381 - compressed text input returns 0 rows if skip header/footer is mentioned
  data/files/test.csv.gz
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/SkippingTextInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestSkippingTextInputFormat.java
  ql/src/test/queries/clientpositive/compressed_skip_header_footer_aggr.q
  ql/src/test/results/clientpositive/llap/compressed_skip_header_footer_aggr.q.out
  ql/src/test/results/clientpositive/tez/compressed_skip_header_footer_aggr.q.out
Labels: tests passed

#1665 HIVE-24341
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/CacheContentsTracker.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/EvictionDispatcher.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/EvictionListener.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LlapCacheableBuffer.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LlapDataBuffer.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheMemoryManager.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelFifoCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/ProactiveEvictingCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/SerDeLowLevelCacheImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/metadata/MetadataCache.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/metadata/OrcFileEstimateErrors.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestCacheAllocationsEvictionsCycles.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestOrcMetadataCache.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestProactiveEviction.java
Labels: tests pending

#1667 HIVE-24378 : Leading and trailing spaces are not removed before decimal conversion
  data/files/test_dec_space.csv
  ql/src/test/queries/clientpositive/whroot_external1.q
  ql/src/test/results/clientpositive/llap/whroot_external1.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyHiveDecimal.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazydio/LazyDioHiveDecimal.java
Labels: tests passed

#1672 HIVE-24324: Remove deprecated API usage from Avro
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerdeUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/SchemaToTypeInfo.java
Labels: tests unstable

#1675 HIVE-23197
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/BuddyAllocator.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/EvictionAwareAllocator.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/EvictionDispatcher.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestProactiveEviction.java
Labels: tests passed

#1682 HIVE-24399: Optimize Deserializer creation
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#1683 HIVE-24401: Fix HiveConf description
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests failed

#1673 HIVE-24387: Metastore access through JDBC handler does not use correct database accessor
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/DatabaseAccessorFactory.java
Labels: tests passed

#1687 HIVE-24377
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCache.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/ProactiveEvictingCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/SerDeLowLevelCacheImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/SimpleBufferManager.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/metadata/MetadataCache.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestOrcMetadataCache.java
  storage-api/src/java/org/apache/hadoop/hive/common/io/FileMetadataCache.java
Labels: tests passed

#1647 HIVE-24329: Add Notification event for compaction commit
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreListenerNotifier.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/CommitCompactionEvent.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/CommitCompactionMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/EventMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageBuilder.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/JSONCommitCompactionMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Labels: tests passed

#1491 HIVE-24138. Llap external client flow is broken due to netty shading.
  itests/qtest/pom.xml
  jdbc/pom.xml
  pom.xml
  ql/pom.xml
Labels: tests passed

#1692 HIVE-24408: Upgrade Parquet to 1.11.1
  pom.xml
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/TestHiveSchemaConverter.java
Labels: tests passed

#1413 HIVE-24051 : Hive lineage information exposed in ExecuteWithHookContext
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/Optimizer.java
Labels: tests passed

#1697 HIVE-24412: Extract common parts of HiveDeCorrelator
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelDecorrelator.java
Labels: tests passed

#1696 HIVE-24249: Create View fails if a materialized view exists with the same query
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/create_view_when_mv_exists.q
  ql/src/test/results/clientpositive/llap/create_view_when_mv_exists.q.out
Labels: tests passed

#1698 HIVE-24414: Backport HIVE-19662 to branch-3.1
  hbase-handler/pom.xml
  pom.xml
Labels: tests unstable

#1693 HIVE-24410: Query-based compaction hangs because of doAs
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#1708 HIVE-24409 : Use LazyBinarySerDe2 in PlanUtils::getReduceValueTableDesc
  ql/src/java/org/apache/hadoop/hive/ql/exec/AppMasterEventOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinarySerDe2.java
Labels: tests passed

#1676 HIVE-24389: Trailing zeros of constant decimal numbers are removed
  ql/src/test/queries/clientpositive/decimal_2.q
  ql/src/test/results/clientpositive/llap/cast2.q.out
  ql/src/test/results/clientpositive/llap/decimal_2.q.out
  ql/src/test/results/clientpositive/llap/decimal_precision2.q.out
  ql/src/test/results/clientpositive/llap/insert_nonacid_from_acid.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_window.q.out
  ql/src/test/results/clientpositive/llap/orc_schema_evolution_float.q.out
  ql/src/test/results/clientpositive/llap/parquet_ppd_decimal.q.out
  ql/src/test/results/clientpositive/llap/udf_case.q.out
  ql/src/test/results/clientpositive/llap/udf_least.q.out
  ql/src/test/results/clientpositive/llap/udf_round.q.out
  ql/src/test/results/clientpositive/llap/udf_trunc_number.q.out
  ql/src/test/results/clientpositive/llap/udf_when.q.out
  ql/src/test/results/clientpositive/llap/vectorization_parquet_ppd_decimal.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/primitive/WritableConstantHiveDecimalObjectInspector.java
Labels: tests passed

#1703 HIVE-24423: Improve DbNotificationListener Thread
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
Labels: tests passed

#1704 HIVE-24424: Use PreparedStatements in DbNotificationListener getNextNLId
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
Labels: tests passed

#1487 HIVE-24144: getIdentifierQuoteString in HiveDatabaseMetaData returns …
  jdbc/src/java/org/apache/hive/jdbc/HiveDatabaseMetaData.java
Labels: stale, tests passed
