Repository apache/hive, pull requests merged in 2021-02, with the labels that each got.

#1872 HIVE-24643: Access Operation state directly to avoid TaskStatus serialisation
  service/src/java/org/apache/hive/service/cli/operation/OperationManager.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
  service/src/java/org/apache/hive/service/cli/operation/hplsql/HplSqlOperation.java
Labels: tests passed

#1916 HIVE-24691: Ban commons-logging (again)
  pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/io/TeradataBinaryFileOutputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/TeradataBinaryRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/fallback/FallbackHiveAuthorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AddPartitionEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterDatabaseEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterPartitionEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterTableEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateDatabaseEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateTableEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropDatabaseEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropPartitionEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropTableEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/LoadPartitionDoneEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/ReadDatabaseEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/ReadTableEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/filtercontext/DatabaseFilterContext.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/filtercontext/TableFilterContext.java
  service/src/java/org/apache/hive/service/servlet/QueriesRESTfulAPIServlet.java
Labels: tests passed

#1882 HIVE-24653: Race condition between compactor marker generation and ge…
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
Labels: tests unstable

#1798 HIVE-22944: Upgrade to Kryo5
  itests/hive-jmh/src/main/java/org/apache/hive/benchmark/ql/exec/KryoBench.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/exec/spark/TestSmallTableCacheEviction.java
  kryo-registrator/pom.xml
  kryo-registrator/src/main/java/org/apache/hive/spark/HiveKryoRegistrator.java
  kryo-registrator/src/main/java/org/apache/hive/spark/NoHashCodeKryoSerializer.java
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/KeyValueContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/ObjectContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/HiveKVResultCache.java
  ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestHiveSparkClient.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestSparkInvalidFileFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestSparkPlan.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/spark/session/TestSparkSessionManagerImpl.java
  ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestConvertAstToSearchArg.java
  spark-client/pom.xml
Labels: tests passed

#1767 HIVE-24525: Invite reviewers automatically by file name patterns
  .github/assign-by-files.yml
  .github/workflows/auto-assign.yml
Labels: tests pending

#1732 HIVE-24478: Subquery GroupBy with Distinct SemanticException: Invalid column reference
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/groupby_having_distinct.q
  ql/src/test/results/clientpositive/llap/groupby_having_distinct.q.out
Labels: tests passed

#1787 HIVE-24470: Separate HiveMetaStore Thrift and Driver logic
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreVersion.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionExpressionProxyDefault.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/security/TestDBTokenStore.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestMetaStoreLimitPartitionRequest.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CommitTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/StorageBasedAuthorizationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthzInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/SQLStdHiveAccessController.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetaStoreCompactorThread.java
  ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
  service/src/java/org/apache/hive/service/server/ThreadWithGarbageCleanup.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/IHMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ReplicationMetricsMaintTask.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RuntimeStatsCleanerTask.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ScheduledQueryExecutionsMaintTask.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/TSetIpAddressProcessor.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/EventCleanerTask.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/ListenerEvent.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/IpAddressListener.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestAdminUser.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreMethods.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreConnectionUrlHook.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreEventListenerWithOldConf.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStoreStatementVerify.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestOldSchema.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCatalogCaching.java
Labels: tests passed

#1921 HIVE-24695: Clean up session resources, if TezSession is unable to start
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
Labels: tests passed

#1883 HIVE-24654: Table level replication support for Atlas metadata
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AtlasDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AtlasDumpWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasReplInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasRequestBuilder.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestAtlasDumpTask.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestAtlasLoadTask.java
Labels: tests passed

#1699 HIVE-18728 : Secure webHCat with SSL
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/AppConfig.java
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/Main.java
Labels: stale, tests passed

#1650 HIVE-24353: performance: do not throw exceptions when parsing dates
  common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java
Labels: tests passed

#1920 HIVE-24694: Early connection close to release server resources during creating
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
Labels: tests passed

#1544 HIVE-24221: Use vectorizable expression to combine multiple columns in semijoin bloom filters
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SemiJoinReductionMerge.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
  ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_2.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query17.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query25.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query29.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query50.q.out
Labels: tests passed

#1892 HIVE-24664: Support column aliases in Values clause
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestValuesClause.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckCtx.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java
  ql/src/test/queries/clientpositive/values_alias.q
  ql/src/test/results/clientpositive/llap/values_alias.q.out
Labels: tests passed

#1907 HIVE-24657: Make Beeline Logging Dependencies Explicit
  beeline/pom.xml
Labels: tests passed

#1925 HIVE-24698. Sync ACL's for the table directory during external table replication.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyTask.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/HdfsUtils.java
Labels: tests passed

#1943 HIVE-23036: [TEST] ORC PPD eval with sub-millisecond timestamps
  ql/src/test/queries/clientpositive/orc_ppd_timestamp_precision.q
  ql/src/test/results/clientpositive/llap/orc_ppd_timestamp_precision.q.out
Labels: tests passed

#1957 Skip extra work in Cleaner if queue is empty
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
Labels: tests passed

#1952 HIVE-24747: Backport HIVE-24569 to branch-3.1
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapConstants.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/QueryTracker.java
  llap-server/src/java/org/apache/hadoop/hive/llap/log/LlapRandomAccessFileAppender.java
  llap-server/src/java/org/apache/hadoop/hive/llap/log/LlapRoutingAppenderPurgePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/log/LlapWrappedAppender.java
  llap-server/src/java/org/apache/hadoop/hive/llap/log/Log4jQueryCompleteMarker.java
  llap-server/src/main/resources/llap-daemon-log4j2.properties
Labels: tests unstable

#1752 HIVE-24501: UpdateInputAccessTimeHook should not update stats
  ql/src/java/org/apache/hadoop/hive/ql/hooks/UpdateInputAccessTimeHook.java
Labels: stale, tests passed

#1948 HIVE-24741: get_partitions_ps_with_auth performance improvement
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#1915 HIVE-24682: Collect dynamic partition info in FileSink for direct insert
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/results/clientpositive/llap/acid_multiinsert_dyn_part.q.out
  ql/src/test/results/clientpositive/llap/mm_all.q.out
Labels: tests passed

#1951 HIVE-24736
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/decode/GenericColumnVectorProducer.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/SerDeEncodedDataReader.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/VectorDeserializeOrcWriter.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
Labels: tests passed

#1962 HIVE-24755. Recycle fails if the cm root isn't absolute.
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java
Labels: tests passed

#1855 HIVE-24624: Repl Load should detect the compatible staging dir
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/DumpMetaData.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/load/TestDumpMetaData.java
Labels: tests passed

#1966 HIVE-24763: Incremental rebuild of Materialized view fails
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRule.java
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_one_key_gby.q
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_one_key_gby.q.out
Labels: tests passed

#1949 HIVE-24744: Deletion of previous dump dir fails with NPE for ptests
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#1721 HIVE-24456: Added HiveConf to check if FIPS mode is enabled, if so co…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/test/org/apache/hadoop/hive/conf/TestHiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMaskHash.java
  ql/src/test/queries/clientpositive/udf_mask_hash.q
  ql/src/test/results/clientpositive/llap/udf_mask_hash.q.out
Labels: tests passed

#1611 HIVE-12371 Adding a timeout connection parameter for JDBC
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
Labels: tests passed

#1989 HIVE-24782: Fix in HIVE-22889 introduced NPE when using non-WebHCat HCat components
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/cli/HCatCli.java
Labels: tests pending

#1940 HIVE-24710: Optimise PTF iteration for count(*) to reduce CPU and IO …
  ql/src/java/org/apache/hadoop/hive/ql/exec/PTFPartition.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/PTFRollingPartition.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/BasePartitionEvaluator.java
Labels: tests passed

#1968 HIVE-24715 Increase bucketId range (amagyar)
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidOutputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/BucketCodec.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveFileFormatUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRecordUpdater.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/FileSinkDesc.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestBucketCodec.java
Labels: tests passed

#1983 HIVE-24786: JDBC HttpClient should retry for idempotent and unsent http methods
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
Labels: tests passed

#1942 HIVE-24733: Handle replication when db location and managed location …
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExclusiveReplica.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/LoadDatabase.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/EximUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CreateDatabaseHandler.java
Labels: tests passed

#1979 HIVE-24785: Fix HIVE_COMPACTOR_COMPACT_MM property
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactorFactory.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#1938 HIVE-24693: Convert timestamps to zoned times without string operations
  common/src/java/org/apache/hadoop/hive/common/type/Date.java
  common/src/java/org/apache/hadoop/hive/common/type/Timestamp.java
  common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java
  ql/src/test/results/clientpositive/llap/udf_mask.q.out
  ql/src/test/results/clientpositive/llap/udf_mask_first_n.q.out
  ql/src/test/results/clientpositive/llap/udf_mask_last_n.q.out
  ql/src/test/results/clientpositive/llap/udf_mask_show_first_n.q.out
  ql/src/test/results/clientpositive/llap/udf_mask_show_last_n.q.out
Labels: tests passed

#1947 HIVE-24725: Collect top priority items from llap cache policy
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCachePolicy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java
  llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
Labels: tests passed

#1876 HIVE-24645: Call configure for UDFs after fetch task conversion
  itests/src/test/resources/testconfiguration.properties
  itests/util/src/main/java/org/apache/hadoop/hive/ql/udf/generic/TestConfigureUDF.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ExprNodeGenericFuncEvaluator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MapredContext.java
  ql/src/test/queries/clientpositive/udf_configure.q
  ql/src/test/results/clientpositive/llap/udf_configure.q.out
Labels: tests passed

#1956 HIVE-24743: Send tableId in get_partitions_by_names HMS API
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/add/AlterTableAddPartitionOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreClientApiArgumentsChecker.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreClient.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#1610 HIVE-24259: [CachedStore] Optimise get all constraint api
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CacheUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
Labels: tests passed

#1980 Hive 24764: insert overwrite on a partition resets row count stats in other partitions
  ql/src/java/org/apache/hadoop/hive/ql/stats/fs/FSStatsAggregator.java
  ql/src/test/queries/clientpositive/insert_overwrite_stats.q
  ql/src/test/results/clientpositive/llap/insert_overwrite_stats.q.out
Labels: tests passed

#1976 HIVE-24781: Allow to use custom queue for query based compaction
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveProtoLoggingHook.java
Labels: tests passed

#1985 HIVE-23826: Reuse column vectors in LlapRecordReader for ACID data too
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
Labels: tests passed

#1995 HIVE-24775: Incorrect null handling when rebuilding Materialized view incrementally
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_nulls.q
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_nulls.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_one_key_gby.q.out
Labels: tests passed

#2001 HIVE-24808: Cache Parsed Dates
  common/src/java/org/apache/hadoop/hive/common/type/Date.java
  common/src/java/org/apache/hive/common/util/DateParser.java
  common/src/test/org/apache/hive/common/util/TestDateParser.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/CastStringToDate.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/TruncDateFromString.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/TruncDateFromTimestamp.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateAddColCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateAddColScalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateAddScalarCol.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDate.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateAdd.java
Labels: tests passed

#2003 HIVE-24809: Build failure while resolving javax.el dependency
  itests/pom.xml
  standalone-metastore/metastore-tools/pom.xml
Labels: tests passed

#1969 HIVE-24768: Using jackson bom everywhere, so that it'll be easy to ma…
  itests/qtest-druid/pom.xml
  standalone-metastore/pom.xml
  testutils/ptest2/pom.xml
Labels: tests passed

#1994 HIVE-24797: Disable validate default values when parsing Avro schemas
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerdeUtils.java
Labels: tests unstable

#1971 HIVE-24738: Reuse committed filelist from directinsert manifest during loadPartition
  ql/src/java/org/apache/hadoop/hive/ql/QueryPlan.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/FileSinkDesc.java
Labels: tests passed

#1986 HIVE-24788: Backport HIVE-23338 to branch-3.1
  pom.xml
  standalone-metastore/pom.xml
  testutils/ptest2/pom.xml
Labels: tests pending

#1964 [WIP]HIVE-24751: Add authorization flag check for KillQueryImpl
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestKillQueryWithAuthorizationDisabled.java
  service/src/java/org/apache/hive/service/server/KillQueryImpl.java
Labels: tests passed

#2014 HIVE-24823: Fix ide error in BasePartitionEvaluator
  ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/BasePartitionEvaluator.java
Labels: tests passed

#2007 HIVE-24811: Extend Cached Dates to Other Areas
  common/src/java/org/apache/hadoop/hive/common/type/TimestampUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFDayOfWeek.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFWeekOfYear.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDF.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateDiff.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFTrunc.java
  serde/src/java/org/apache/hadoop/hive/serde2/RandomTypeUtil.java
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/primitive/PrimitiveObjectInspectorUtils.java
Labels: tests passed

#2022 HIVE-24822: Materialized View rebuild loses materializationTime property value
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Labels: tests passed

#2021 HIVE-24829: CorrelationUtilities#replaceReduceSinkWithSelectOperator misses KEY mappings
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/NonBlockingOpDeDupProc.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/CorrelationUtilities.java
Labels: tests passed
