Repository apache/hive, pull requests merged in 2021-07, with the labels that each got.

#2437 HIVE-25297: Refactor GenericUDFDateDiff
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateDiff.java
Labels: tests passed

#2422 HIVE-25252: All new compaction metrics should be lower case
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
Labels: tests passed

#2423 HIVE-25278: HiveProjectJoinTransposeRule may do invalid transformations with windowing expressions
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveProjectJoinTransposeRule.java
  ql/src/test/queries/clientpositive/cbo_proj_join_transpose.q
  ql/src/test/results/clientpositive/llap/cbo_proj_join_transpose.q.out
Labels: tests passed

#2240 HIVE-25086: Create Ranger Deny Policy for replication db in all cases.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/if/queryplan.thrift
  ql/src/gen/thrift/gen-cpp/queryplan_types.cpp
  ql/src/gen/thrift/gen-cpp/queryplan_types.h
  ql/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/ql/plan/api/StageType.java
  ql/src/gen/thrift/gen-php/StageType.php
  ql/src/gen/thrift/gen-py/queryplan/ttypes.py
  ql/src/gen/thrift/gen-rb/queryplan_types.rb
  ql/src/java/org/apache/hadoop/hive/ql/exec/TaskFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/RangerDenyTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/RangerDenyWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/RangerLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/NoOpRangerRestClient.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/RangerRestClient.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/RangerRestClientImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestRangerLoadTask.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/ranger/TestRangerRestClient.java
Labels: tests passed

#2440 HIVE-25301. Expose notification log table through sys db.
  metastore/scripts/upgrade/hive/hive-schema-4.0.0.hive.sql
  metastore/scripts/upgrade/hive/upgrade-3.1.0-to-4.0.0.hive.sql
  ql/src/test/queries/clientpositive/sys_notification_log.q
  ql/src/test/results/clientpositive/llap/resourceplan.q.out
  ql/src/test/results/clientpositive/llap/strict_managed_tables_sysdb.q.out
  ql/src/test/results/clientpositive/llap/sys_notification_log.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
Labels: tests passed

#2443 HIVE-23801. TestMiniLlapLocalCliDriver[replication_metrics_ingest] is flaky.
  ql/src/test/queries/clientpositive/replication_metrics_ingest.q
  ql/src/test/results/clientpositive/llap/replication_metrics_ingest.q.out
Labels: tests passed

#2453 HIVE-25310: Fix local test run problems with Iceberg tests: Socket cl…
  iceberg/iceberg-catalog/pom.xml
  iceberg/iceberg-handler/pom.xml
Labels: tests passed

#2446 HIVE-25308: Use new Tez API to get JobID for Iceberg commits
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
Labels: tests passed

#2447 HIVE-25299: Incorporate timezone while converting timestamp to numeric data types
  common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToBoolean.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToByte.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToDouble.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToFloat.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToInteger.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToLong.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFToShort.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFUtils.java
  ql/src/test/queries/clientpositive/timestamp_1.q
  ql/src/test/queries/clientpositive/timestamp_2.q
  ql/src/test/queries/clientpositive/timestamp_3.q
  ql/src/test/queries/clientpositive/udf_to_boolean.q
  ql/src/test/results/clientpositive/llap/timestamp_1.q.out
  ql/src/test/results/clientpositive/llap/timestamp_2.q.out
  ql/src/test/results/clientpositive/llap/timestamp_3.q.out
  ql/src/test/results/clientpositive/llap/udf_to_boolean.q.out
Labels: tests pending

#2455 HIVE-25312: Upgrade netty to 4.1.65.Final
  pom.xml
Labels: tests passed

#2454 HIVE-25313: Upgrade commons-codec to 1.15
  pom.xml
Labels: tests passed

#2418 HIVE-25255: Add support for replace columns
  hbase-handler/src/test/results/negative/hbase_ddl.q.out
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/replace/AlterTableReplaceColumnsOperation.java
  ql/src/test/results/clientnegative/alter_non_native.q.out
Labels: tests passed

#2428 HIVE-25287
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#2406 HIVE-25263: CAST operation with decimal resulting to NULL
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_window.q.out
  ql/src/test/results/clientpositive/llap/vector_cast_constant.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query23.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/primitive/WritableConstantHiveDecimalObjectInspector.java
Labels: tests passed

#2460 HIVE-25318: Number of initiator hosts metric should ignore manually initiated compactions
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
Labels: tests passed

#2444 HIVE-25267: Fix TestReplicationScenariosAcidTables
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
Labels: tests passed

#2407 HIVE-25264: Add tests to verify Hive can read/write after schema chan…
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Labels: tests passed

#2458 HIVE-25314: Implement SHOW CREATE TABLE command for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/DDLPlanUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransformSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#2469 HIVE-25316: Map partition key columns when pushing TNK op through select
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/topnkey/TopNKeyPushdownProcessor.java
  ql/src/test/queries/clientpositive/external_jdbc_table_perf.q
  ql/src/test/results/clientpositive/llap/external_jdbc_table_perf.q.out
Labels: tests passed

#2373 HIVE-21489: EXPLAIN command throws ClassCastException in Hive
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ExplainSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV1.java
  ql/src/test/queries/clientpositive/explain_defaultauthorizer.q
  ql/src/test/results/clientpositive/llap/explain_defaultauthorizer.q.out
Labels: tests pending

#2211 HIVE-23931: Send ValidWriteIdList and tableId to get_*_constraints HMS APIs
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestReplDumpTask.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AllTableConstraintsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CheckConstraintsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/DefaultConstraintsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ForeignKeysRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/NotNullConstraintsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PrimaryKeysRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/UniqueConstraintsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AllTableConstraintsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CheckConstraintsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/DefaultConstraintsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ForeignKeysRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/NotNullConstraintsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PrimaryKeysRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/UniqueConstraintsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
Labels: tests passed

#2396 HIVE-25246: Fix the clean up of open repl created transactions
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricUpdateOnFailure.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2472 HIVE-25326: Include partitioning info in DESCRIBE TABLE command on Iceberg tables
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/JsonDescTableFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
Labels: tests passed

#2483 HIVE-25290: Stabilize TestTxnHandler
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
Labels: tests passed

#2476 HIVE-25288: Fix TestMmCompactorOnTez
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2401 HIVE-25253: Incremental rebuild of partitioned insert only materialized views
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinOptimization.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregatePartitionIncrementalRewritingRule.java
  ql/src/test/queries/clientpositive/materialized_view_partitioned_create_rewrite_agg.q
  ql/src/test/queries/clientpositive/materialized_view_partitioned_create_rewrite_agg_2.q
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg_2.q.out
Labels: tests passed

#2463 HIVE-25256: Support ALTER TABLE CHANGE COLUMN for Iceberg
  hbase-handler/src/test/results/negative/hbase_ddl.q.out
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractBaseAlterTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/test/results/clientnegative/alter_non_native.q.out
Labels: tests passed

#2456 HIVE-25311: Slow compilation of union operators with >100 branches
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java
Labels: tests passed

#2360 HIVE-25209: SELECT query with SUM function producing unexpected result
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/StatsOptimizer.java
  ql/src/test/queries/clientpositive/select_sum.q
  ql/src/test/results/clientpositive/llap/select_sum.q.out
Labels: tests passed

#2481 HIVE-25336. Use single call to get tables in DropDatabaseAnalyzer.
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/drop/DropDatabaseAnalyzer.java
Labels: tests passed

#2452 HIVE-22626. Fix Replication related tests.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestReplChangeManager.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestMetaStoreEventListenerInRepl.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOfHiveStreaming.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOnHDFSEncryptedZones.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosIncrementalLoadAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenariosACID.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenariosACIDNoAutogather.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenariosMMNoAutogather.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithReplication.java
Labels: tests passed

#2448 Handle Iceberg queries with partition clauses
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AbstractDropPartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
Labels: tests passed

#2419 HIVE-25276: Enable automatic statistics generation for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransformSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
Labels: tests passed

#2505 Revert "HIVE-25276: Enable automatic statistics generation for Iceberg tables"
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransformSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
Labels: tests pending

#2506 HIVE-25358: Remove reviewer pattern
  .github/assign-by-files.yml
Labels: tests failed

#2508 HIVE-25360
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/ExpressionToOrcSearchArgument.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java
  serde/src/java/org/apache/hadoop/hive/serde2/ColumnProjectionUtils.java
Labels: tests passed

#2509 HIVE-25371: Add myself to thrift file reviewers
  .github/assign-by-files.yml
Labels: tests pending

#2471 HIVE-25325: Add TRUNCATE TABLE support for Hive Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/iceberg-handler/src/test/queries/negative/truncate_iceberg_table_external_purge_false.q
  iceberg/iceberg-handler/src/test/queries/negative/truncate_iceberg_table_with_partition_spec.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_force_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_partitioned_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/negative/truncate_iceberg_table_external_purge_false.q.out
  iceberg/iceberg-handler/src/test/results/negative/truncate_iceberg_table_with_partition_spec.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/TruncateTableRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/TruncateTableRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#2497 HIVE-25348: Skip metrics collection about writes to tables with tblproperty no_auto_compaction=true if CTAS
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
Labels: tests passed

#2510 HIVE-25276: Enable automatic statistics generation for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransformSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
Labels: tests passed

#1998 HIVE-24802: Show operation log at webui
  common/src/java/org/apache/hadoop/hive/common/LogUtils.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/log/LogDivertAppender.java
  ql/src/java/org/apache/hadoop/hive/ql/session/OperationLog.java
  service/src/jamon/org/apache/hive/tmpl/QueryProfileTmpl.jamon
  service/src/java/org/apache/hive/service/cli/operation/Operation.java
  service/src/java/org/apache/hive/service/cli/operation/OperationLogManager.java
  service/src/java/org/apache/hive/service/cli/operation/OperationManager.java
  service/src/java/org/apache/hive/service/cli/operation/QueryInfoCache.java
  service/src/java/org/apache/hive/service/cli/session/SessionManager.java
  service/src/test/org/apache/hive/service/cli/operation/TestOperationLogManager.java
Labels: tests passed

#2493 HIVE-25345: Add logging based on new compaction metrics
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2511 HIVE-25361: Allow Iceberg table update columns command
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Labels: tests passed

#2517 HIVE-25368: Code does not build in IDE and a small fix
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Task.java
Labels: tests passed

#2527 HIVE-25307: Hive Server 2 crashes when Thrift library encounters part…
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/security/HadoopThriftAuthBridge.java
Labels: tests passed

#2121 HIVE-24918: Handle failover case during repl dump.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplAck.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/FailoverMetaData.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/ReplicationMetricCollector.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/Metadata.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/Status.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricCollector.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricSink.java
Labels: tests passed

#2480 HIVE-25332: Refactor UDF CAST(<Date string> as DATE)
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFDayOfMonth.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFMonth.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFYear.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDF.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFAddMonths.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLastDay.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMonthsBetween.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFNextDay.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFQuarter.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFToDate.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFLastDay.java
Labels: tests passed

#2522 HIVE-25377: Creating Iceberg table where some columns has comments but the last one does not fails
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#2530 HIVE-25384: Bump ORC to 1.6.9
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#2489 HIVE-25342 : Optimize set_aggr_stats_for for mergeColStats path.
  ql/src/test/queries/clientpositive/autoColumnStats_2.q
  ql/src/test/results/clientpositive/llap/autoColumnStats_2.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdateStat.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#2518 HIVE-25369: Handle Sum0 when rebuilding materialized view incrementally
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRuleBase.java
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_4.q
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_5.q
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_6.q
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_7.q
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_7.q.out
Labels: tests passed

#2474 HIVE-25249: Fix TestWorker
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#2278 HIVE-24945: Support vectorization for lead/lag functions
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/BufferedVectorizedRowBatch.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorAbstractLeadLag.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorBase.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorLag.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorLead.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFGroupBatches.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorSpillBlockContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PTFDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFInfo.java
  ql/src/test/queries/clientpositive/vector_ptf_bounded_start.q
  ql/src/test/queries/clientpositive/vector_ptf_lead_lag.q
  ql/src/test/results/clientpositive/llap/pcs.q.out
  ql/src/test/results/clientpositive/llap/ptf.q.out
  ql/src/test/results/clientpositive/llap/vector_ptf_bounded_start.q.out
  ql/src/test/results/clientpositive/llap/vector_ptf_lead_lag.q.out
  ql/src/test/results/clientpositive/llap/vector_ptf_part_simple.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing_expressions.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing_gby2.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing_navfn.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing_rank.q.out
  ql/src/test/results/clientpositive/llap/vectorized_ptf.q.out
Labels: tests passed

#2222 HIVE-25058: PTF: TimestampValueBoundaryScanner can be optimised during range computation pt2 - isDistanceGreater
  ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/ptf/TestValueBoundaryScanner.java
Labels: tests passed

#2466 HIVE-25320: Purge hive.optimize.sort.dynamic.partition
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-blobstore/src/test/queries/clientpositive/insert_overwrite_dynamic_partitions_merge_move.q
  itests/hive-blobstore/src/test/queries/clientpositive/insert_overwrite_dynamic_partitions_merge_only.q
  itests/hive-blobstore/src/test/queries/clientpositive/insert_overwrite_dynamic_partitions_move_only.q
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/queries/clientpositive/acid_table_stats.q
  ql/src/test/queries/clientpositive/dynpart_merge.q
  ql/src/test/queries/clientpositive/dynpart_sort_opt_bucketing.q
  ql/src/test/queries/clientpositive/dynpart_sort_opt_vectorization.q
  ql/src/test/queries/clientpositive/dynpart_sort_optimization.q
  ql/src/test/queries/clientpositive/dynpart_sort_optimization2.q
  ql/src/test/queries/clientpositive/dynpart_sort_optimization_distribute_by.q
  ql/src/test/queries/clientpositive/materialized_view_partitioned_3.q
  ql/src/test/queries/clientpositive/merge_dynamic_partition.q
  ql/src/test/queries/clientpositive/merge_dynamic_partition2.q
  ql/src/test/queries/clientpositive/mm_dp.q
  ql/src/test/queries/clientpositive/orc_merge10.q
  ql/src/test/queries/clientpositive/orc_merge7.q
  ql/src/test/queries/clientpositive/orc_merge_diff_fs.q
  ql/src/test/queries/clientpositive/orc_merge_incompat2.q
  ql/src/test/queries/clientpositive/schema_evol_orc_acid_part_update.q
  ql/src/test/queries/clientpositive/schema_evol_orc_acid_part_update_llap_io.q
  ql/src/test/queries/clientpositive/temp_table_merge_dynamic_partition.q
  ql/src/test/queries/clientpositive/temp_table_merge_dynamic_partition2.q
  ql/src/test/queries/clientpositive/vector_outer_join_constants.q
Labels: tests passed

#2473 HIVE-25192: Nullify summary for non-native tables
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
Labels: tests passed

#2535 HIVE-25391: Turn off priv synchronizer by default
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hive/service/server/InformationSchemaWithPrivilegeTestBase.java
Labels: tests passed

#2525 HIVE-25380: Remove the Hive Privilege Object for Database in the Read…
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateTableEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/ReadTableEvent.java
Labels: tests passed

#2533 HIVE-25014: Optimise ObjectStore::updateTableColumnStatistics
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#2536 HIVE-25370: Improve SharedWorkOptimizer performance
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/TestSharedWorkOptimizer.java
Labels: tests unstable

#2534 HIVE-25390: Metrics compaction_failed_initiator_ratio and compaction_failed_cleaner_ratio should be counters
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Labels: tests passed

#2519 HIVE-25374: Fix test TestReplicationOnHDFSEncryptedZones
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOnHDFSEncryptedZones.java
Labels: tests passed

#2512 HIVE-25344: Add a possibility to query Iceberg table snapshots based on the timestamp or the snapshot id
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/queries/negative/timetravel_by_time_non_iceberg.q
  iceberg/iceberg-handler/src/test/queries/negative/timetravel_by_version_non_iceberg.q
  iceberg/iceberg-handler/src/test/results/negative/timetravel_by_time_non_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/negative/timetravel_by_version_non_iceberg.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SMBMapJoinOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/MapredLocalTask.java
  ql/src/java/org/apache/hadoop/hive/ql/io/BucketizedHiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QB.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
Labels: tests passed

#2500 Hive-24467: ConditionalTask remove tasks that not selected exists thr…
  ql/src/java/org/apache/hadoop/hive/ql/QueryState.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ConditionalTask.java
Labels: tests passed
