Repository apache/hive, pull requests merged in 2021-09, with the labels that each got.

#2421 HIVE-25277: fix slow partition deletion issue by removing duplicated isEmpty checks.
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests pending

#2549 HIVE-25406: Fetch writeId from insert-only transactional tables
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestFetchWriteIdFromInsertOnlyTables.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SMBMapJoinOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/MapredLocalTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatchCtx.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/BatchToRowReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/BucketIdentifier.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveContextAwareRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/IOContext.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveTableScan.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveRowIsDeletedPropagator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
  ql/src/test/queries/clientpositive/insert_only_writeId_orc.q
  ql/src/test/queries/clientpositive/insert_only_writeId_parquet.q
  ql/src/test/results/clientpositive/llap/insert_only_writeId_orc.q.out
  ql/src/test/results/clientpositive/llap/insert_only_writeId_parquet.q.out
Labels: tests passed

#2568 HIVE-25404 insert merge partitioned
  ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
  ql/src/test/queries/clientpositive/merge_partitioned_insert.q
  ql/src/test/results/clientpositive/llap/merge_partitioned_insert.q.out
Labels: tests passed

#2621 HIVE-25504: Fix HMS C++ Thrift client compilation
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AggrStats.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ColumnStatistics.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CreationMetadata.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/Database.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/EnvironmentContext.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/FileMetadata.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetCatalogsResponse.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetPrincipalsInRoleResponse.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetRoleGrantsForPrincipalResponse.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/HiveObjectRef.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ObjectDictionary.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/Partition.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PartitionListComposingSpec.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PartitionSpecWithSharedSD.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PartitionWithoutSD.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PrincipalPrivilegeSet.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PrivilegeBag.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/SQLAllTableConstraints.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/Schema.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/SerDeInfo.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/SetPartitionsStatsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/SkewedInfo.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/StorageDescriptor.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/Table.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/TruncateTableRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/Type.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AggrStats.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ColumnStatistics.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CreationMetadata.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Database.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/EnvironmentContext.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/FileMetadata.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetCatalogsResponse.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetPrincipalsInRoleResponse.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetRoleGrantsForPrincipalResponse.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/HiveObjectRef.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ObjectDictionary.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Partition.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PartitionListComposingSpec.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PartitionSpecWithSharedSD.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PartitionWithoutSD.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PrincipalPrivilegeSet.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PrivilegeBag.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/SQLAllTableConstraints.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Schema.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/SerDeInfo.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/SetPartitionsStatsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/SkewedInfo.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/StorageDescriptor.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Table.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/TruncateTableRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Type.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed

#2613 Hive 25450: Delta metrics keys should contain database name - 2
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetricsOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HiveSplitGenerator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java
Labels: tests passed

#2609 HIVE-22247. HiveHFileOutputFormat throws FileNotFoundException when partition's task output empty.
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/HiveHFileOutputFormat.java
Labels: tests passed

#2618 HIVE-25500: Switch back to alter_partition(s) in HMS client for Hive 2.3.x
  metastore/src/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: tests unstable

#2616 HIVE-25498: Query with more than 31 count distinct functions returns …
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveExpandDistinctAggregatesRule.java
  ql/src/test/queries/clientpositive/multi_count_distinct.q
  ql/src/test/results/clientpositive/tez/multi_count_distinct.q.out
Labels: tests passed

#2586 HIVE-25453
  data/conf/iceberg/llap/hive-site.xml
  data/conf/iceberg/llap/tez-site.xml
  data/conf/iceberg/tez/hive-site.xml
  data/conf/iceberg/tez/tez-site.xml
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
  iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read.q
  iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read.q.out
  itests/qtest-iceberg/src/test/java/TestIcebergLlapLocalCliDriver.java
  itests/src/test/resources/testconfiguration.properties
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
  llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/decode/ColumnVectorProducer.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java
  serde/src/java/org/apache/hadoop/hive/serde2/ColumnProjectionUtils.java
Labels: tests passed

#2619 HIVE-25502: Cleaner causes data loss when processing aborted txn with DP
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#2635 HIVE-25515: Allow optional "AS" in column aliases in Values clause
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/test/queries/clientpositive/values_alias.q
  ql/src/test/results/clientpositive/llap/values_alias.q.out
Labels: tests passed

#2633 HIVE-25513: Delta metrics collection may cause NPE
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java
Labels: tests passed

#2628 HIVE-24936 - Fix file name parsing and copy file move
  ql/src/java/org/apache/hadoop/hive/ql/exec/AbstractFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ParsedOutputFileName.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/ParsedOutputFileNameTest.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestUtilities.java
Labels: tests passed

#2620 HIVE-25501: Provide a configurable filter for removing useless properties from PartitionDesc objects before MapWork serialization
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestSerializationUtilities.java
Labels: tests passed

#2503 HIVE-25393: Prevent concurrent compaction and DDL operations
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
Labels: tests passed

#2632 HIVE-25512: Merge statement does not enforce check constraints
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestConstraintsMerge.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/results/clientnegative/merge_constraint_notnull.q.out
  ql/src/test/results/clientpositive/llap/check_constraint.q.out
  ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out
  ql/src/test/results/clientpositive/llap/insert_into_default_keyword.q.out
Labels: tests passed

#2637 HIVE-25516: ITestDbTxnManager is broken after HIVE-24120
  pom.xml
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/ITestDbTxnManager.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mariadb.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mssql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Postgres.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
  standalone-metastore/pom.xml
Labels: tests passed

#2644 HIVE-25529: Test reading/writing V2 tables with delete files
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestHelper.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
Labels: tests passed

#2645 HIVE-25527 : LLAP Scheduler task exits with fatal error if the executor node is down.
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
Labels: tests passed

#2612 HIVE-25503: Add cleanup for the duplicate COMPLETED_TXN_COMPONENTS entries
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/AcidHouseKeeperService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Labels: tests passed

#2624 Hive-25460 : Advance the Write ID by default
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLDesc.java
Labels: tests passed

#2575 HIVE-24766: Fix TestScheduledReplication
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
Labels: tests passed

#2652 HIVE-25378: Enable removal of old builds on hive ci
  Jenkinsfile
Labels: tests passed

#2626 HIVE-25508: Partitioned tables created with CTAS queries doesnt have lineage informations
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/lineage5.q
  ql/src/test/results/clientpositive/llap/ctas.q.out
  ql/src/test/results/clientpositive/llap/lineage5.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_authorization_sqlstd.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partition_cluster.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_no_join_opt_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_part_1.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_part_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_ssb_grouping_sets.q.out
  ql/src/test/results/clientpositive/llap/partition_ctas.q.out
  ql/src/test/results/clientpositive/llap/partition_discovery.q.out
  ql/src/test/results/clientpositive/llap/temp_table_partition_ctas.q.out
Labels: tests pending

#2598 HIVE-19647: use bitvectors in IN operators
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/HiveMurmur3Adapter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ColStatistics.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/plan/mapping/TestStatEstimations.java
  ql/src/test/queries/clientpositive/in_bitvector_filter.q
  ql/src/test/results/clientpositive/llap/in_bitvector_filter.q.out
Labels: tests passed

#2608 HIVE-25485: unionall selects
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/BaseJdbcWithMiniLlap.java.orig
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelDecorrelator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveUnionSimpleSelectsToInlineTableRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/union_literals.q
  ql/src/test/results/clientpositive/llap/udf_likeall.q.out
  ql/src/test/results/clientpositive/llap/udf_likeany.q.out
  ql/src/test/results/clientpositive/llap/udf_sort_array_by.q.out
  ql/src/test/results/clientpositive/llap/union_literals.q.out
  ql/src/test/results/clientpositive/llap/vectorized_mapjoin3.q.out
Labels: tests passed

#2651 HIVE-25535: Control cleaning obsolete directories/files of a table via property
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Constant.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed

#2478 HIVE-25331: Create database query doesn't create MANAGEDLOCATION dire…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExclusiveReplica.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/TestMetastoreAuthorizationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/create/CreateDatabaseOperation.java
  ql/src/test/queries/clientpositive/create_database.q
  ql/src/test/results/clientpositive/llap/alter_change_db_location.q.out
  ql/src/test/results/clientpositive/llap/create_database.q.out
  ql/src/test/results/clientpositive/llap/database_location.q.out
  ql/src/test/results/clientpositive/tez/explainanalyze_3.q.out
  ql/src/test/results/clientpositive/tez/explainuser_3.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#2656 HIVE-24579: Incorrect Result For Groupby With Limit
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveAggregateSortLimitRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/topnkey_gby_limit.q
  ql/src/test/results/clientpositive/llap/bucket_groupby.q.out
  ql/src/test/results/clientpositive/llap/filter_union.q.out
  ql/src/test/results/clientpositive/llap/groupby1_limit.q.out
  ql/src/test/results/clientpositive/llap/limit_pushdown.q.out
  ql/src/test/results/clientpositive/llap/limit_pushdown4.q.out
  ql/src/test/results/clientpositive/llap/offset_limit_ppd_optimizer.q.out
  ql/src/test/results/clientpositive/llap/topnkey_gby_limit.q.out
Labels: tests passed

#2667 HIVE-25549: Wrong results for window function with expression in PARTITION BY or ORDER BY clause
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java
  ql/src/test/queries/clientpositive/vector_windowing_row_number.q
  ql/src/test/results/clientpositive/llap/vector_windowing_row_number.q.out
Labels: tests passed
