Repository apache/hive, pull requests merged in 2021-06, with the labels that each got.

#2191 HIVE-24920: TRANSLATED_TO_EXTERNAL tables may write to the same location
  itests/qtest/pom.xml
  ql/src/test/queries/clientnegative/translated_external_rename.q
  ql/src/test/queries/clientpositive/translated_external_rename.q
  ql/src/test/queries/clientpositive/translated_external_rename2.q
  ql/src/test/results/clientnegative/translated_external_rename.q.out
  ql/src/test/results/clientpositive/llap/translated_external_rename.q.out
  ql/src/test/results/clientpositive/llap/translated_external_rename2.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreMetadataTransformer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDefaultTransformer.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestGetPartitions.java
Labels: tests passed

#2316 HIVE-25161: Implement partitioned CTAS for iceberg tables
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  serde/if/serde.thrift
  serde/src/gen/thrift/gen-cpp/serde_constants.cpp
  serde/src/gen/thrift/gen-cpp/serde_constants.h
  serde/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/serde/serdeConstants.java
  serde/src/gen/thrift/gen-php/org/apache/hadoop/hive/serde/Constant.php
  serde/src/gen/thrift/gen-py/org_apache_hadoop_hive_serde/constants.py
  serde/src/gen/thrift/gen-rb/serde_constants.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
Labels: tests passed

#2334 HIVE-25166: Query with multiple count(distinct constant) fails
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelFieldTrimmer.java
  ql/src/test/queries/clientpositive/multi_count_distinct_null.q
  ql/src/test/results/clientpositive/llap/multi_count_distinct_null.q.out
Labels: tests passed

#2338 HIVE-25178 : Reduce number of getPartition calls during loadDynamicPa…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/queries/clientpositive/load_dynamic_partition.q
  ql/src/test/results/clientpositive/llap/load_dynamic_partition.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java
Labels: tests passed

#2322 HIVE-25163 UnsupportedTemporalTypeException when starting llap
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/LlapServiceDriver.java
Labels: tests passed

#2340 HIVE-23756: Added more constraints to the package.jdo file
  standalone-metastore/metastore-server/src/main/resources/package.jdo
Labels: tests passed

#2282 HIVE-25104: Backward incompatible timestamp serialization in Parquet for certain timezones
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/convert/ETypeConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/DataWritableReadSupport.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/ParquetDataColumnReaderFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/write/DataWritableWriteSupport.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/write/DataWritableWriter.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/VectorizedColumnReaderTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/convert/MyConverterParent.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/convert/TestETypeConverter.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampsHive2Compatibility.java
  ql/src/test/queries/clientpositive/parquet_int96_legacy_compatibility_timestamp.q
  ql/src/test/results/clientpositive/llap/materialized_view_parquet.q.out
  ql/src/test/results/clientpositive/llap/parquet_int96_legacy_compatibility_timestamp.q.out
  ql/src/test/results/clientpositive/llap/parquet_stats.q.out
Labels: tests passed

#2302 [HIVE-25183] Inner Join condition parsing error in subquery
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveFilter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelDecorrelator.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/JoinCondTypeCheckProcFactory.java
  ql/src/test/queries/clientnegative/subquery_corr_outer.q
  ql/src/test/queries/clientpositive/subquery_corr_join.q
  ql/src/test/results/clientnegative/subquery_corr_outer.q.out
  ql/src/test/results/clientpositive/llap/subquery_corr_join.q.out
Labels: tests passed

#2336 HIVE-24987: Introduce a exception list to skip incompatible column change check
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestDisallowColChangesExceptionList.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DefaultIncompatibleTableChangeHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreIncompatibleChangeHandler.java
Labels: tests passed

#2296 HIVE-25133. Allow custom configs for database level paths in external table replication.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplExternalTables.java
Labels: tests passed

#2321 HIVE-25165. Generate & track statistics per event type for incremental load in replication metrics.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/NoOpReplStatsTracker.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStateLogWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStatsTracker.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadTasksBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/ReplLogger.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/IncrementalLoadLogger.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/ReplicationMetricCollector.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/Stage.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/StageMapper.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricCollector.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricSink.java
Labels: tests passed

#2345 HIVE-25180: Update netty to 4.1.60.Final
  pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorAssignRow.java
Labels: tests passed

#2353 HIVE-25203: HiveQueryResultSet and client operation are not expected to be closed twice
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  jdbc/src/java/org/apache/hive/jdbc/HiveQueryResultSet.java
  jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
Labels: tests passed

#2286 HIVE-25117: Vector PTF ClassCastException with Decimal64
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
  ql/src/test/queries/clientpositive/vector_ptf_classcast_exception.q
  ql/src/test/results/clientpositive/llap/vector_ptf_classcast_exception.q.out
Labels: tests pending

#2266 HIVE-24663 : Batch process in ColStatsProcessor for partitions
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/test/queries/clientnegative/columnstats_partlvl_dp_lowercase.q
  ql/src/test/queries/clientpositive/columnstats_partlvl_dp.q
  ql/src/test/queries/clientpositive/dynpart_sort_optimization2.q
  ql/src/test/queries/clientpositive/extrapolate_part_stats_partial_ndv.q
  ql/src/test/queries/clientpositive/orc_merge6.q
  ql/src/test/queries/clientpositive/parquet_vectorization_part.q
  ql/src/test/queries/clientpositive/quotedid_alter.q
  ql/src/test/results/clientnegative/columnstats_partlvl_dp_lowercase.q.out
  ql/src/test/results/clientpositive/llap/columnstats_partlvl_dp.q.out
  ql/src/test/results/clientpositive/llap/extrapolate_part_stats_partial_ndv.q.out
  ql/src/test/results/clientpositive/llap/orc_merge6.q.out
  ql/src/test/results/clientpositive/llap/parquet_vectorization_part.q.out
  ql/src/test/results/clientpositive/llap/quotedid_alter.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdateStat.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreListenerNotifier.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDirectSqlUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/StatObjectConverter.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/InjectableBehaviourObjectStore.java
Labels: tests passed

#2333 HIVE-25179: Support all partition transforms for Iceberg in create table
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Constant.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed

#1476 HIVE-24073 : Execution exception in sort-merge semijoin
  ql/src/java/org/apache/hadoop/hive/ql/exec/CommonMergeJoinOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MapRecordSource.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/RecordSource.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/ReduceRecordSource.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConvertJoinMapJoin.java
  ql/src/test/queries/clientpositive/auto_sortmerge_join_10.q
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_10.q.out
  ql/src/test/results/clientpositive/llap/groupby_sort_1_23.q.out
  ql/src/test/results/clientpositive/llap/groupby_sort_skew_1_23.q.out
  ql/src/test/results/clientpositive/llap/subquery_in_having.q.out
Labels: stale, tests passed

#2342 HIVE-25189: Fetch validWriteIdList for tables before table request.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/ParseDriver.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/ParseResult.java
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CacheTableHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#2311 HIVE-25154: Disable StatsUpdaterThread and PartitionManagementTask for db which is being failed over.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUpdaterThread.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartitionManagementTask.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionManagement.java
Labels: tests passed

#2352 HIVE-25201: Remove Caffein shading from Iceberg
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/CachedClientPool.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java
  iceberg/iceberg-shading/pom.xml
Labels: tests passed

#2362 HIVE-25211: Create database throws NPE
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#2348 HIVE-25194: Add support for STORED AS ORC/PARQUET/AVRO for Iceberg
  hbase-handler/src/test/queries/negative/create_table_stored_by_stored_as_failure.q
  hbase-handler/src/test/results/negative/create_table_stored_by_stored_as_failure.q.out
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_stored_as_with_serdeproperties_failure.q
  iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_stored_as_with_tableproperties_failure.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_as_fileformat.q
  iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_stored_as_with_serdeproperties_failure.q.out
  iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_stored_as_with_tableproperties_failure.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
Labels: tests passed

#2366 HIVE-23987: Upgrade arrow version to 0.11.0
  pom.xml
  ql/src/java/org/apache/hadoop/hive/llap/LlapArrowRecordWriter.java
Labels: tests passed

#2308 HIVE-25150 : Tab characters are not removed before decimal conversion similar to space character which is fixed as part of HIVE-24378
  data/files/test_sp_chars_decimal.csv
  ql/src/test/queries/clientpositive/test_decimal.q
  ql/src/test/results/clientpositive/llap/test_decimal.q.out
  storage-api/src/java/org/apache/hadoop/hive/common/type/FastHiveDecimalImpl.java
Labels: tests passed

#2347 HIVE-25195: Store Iceberg write commit and ctas information in QueryState
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergQueryLifeTimeHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Labels: tests passed

#2339 HIVE-25185: Improve Logging On Polling Tez Session from Pool
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPool.java
Labels: tests passed

#2372 HIVE-25220: Query with union fails CBO with OOM
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
Labels: tests passed

#1933 HIVE-24707: Apply Sane Default for Tez Containers as Last Resort
  ql/src/java/org/apache/hadoop/hive/ql/exec/MemoryInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
Labels: tests passed

#2343 HIVE-25138: Auto disable scheduled queries after repeated failures
  ql/src/test/org/apache/hadoop/hive/ql/schq/TestScheduledQueryService.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/QueryState.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/QueryState.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MScheduledQuery.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestMetastoreScheduledQueries.java
Labels: tests passed

#2252 HIVE-25093: date_format() UDF is returning values in UTC time zone only
  common/src/java/org/apache/hadoop/hive/common/type/Date.java
  common/src/java/org/apache/hadoop/hive/common/type/Timestamp.java
  itests/hive-unit/src/test/java/org/apache/hive/service/auth/saml/TestHttpSamlAuthentication.java
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/util/DateTimeMath.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFDateFormat.java
  ql/src/test/queries/clientpositive/udf_date_format.q
  ql/src/test/results/clientpositive/llap/udf_date_format.q.out
Labels: tests passed

#2381 HIVE-25224: Multi insert statements involving tables with different bucketing_versions results in error
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/BucketVersionPopulator.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/TestBucketVersionPopulator.java
  ql/src/test/queries/clientpositive/multi_insert_bucketing_version.q
  ql/src/test/results/clientpositive/llap/multi_insert_bucketing_version.q.out
Labels: tests pending

#2385 HIVE-25238: Make SSL cipher suites configurable for Hive Web UI and HS2
  common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/java/org/apache/hive/http/HttpServer.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  service/src/test/org/apache/hive/service/server/TestHS2HttpServerPamConfiguration.java
Labels: tests passed

#2218 HIVE-25055: Improve the exception handling in HMSHandler
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ExceptionHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestExceptionHandler.java
Labels: tests passed

#2365 HIVE-25204 : Reduce overhead of adding notification log for update partition column statistics.
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdateStat.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreListenerNotifier.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/UpdatePartitionColumnStatEventBatch.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/EventMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageBuilder.java
Labels: tests passed

#2400 HIVE-25257: Incorrect row order validation for query-based MAJOR comp…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFValidateAcidSortOrder.java
Labels: tests passed

#2376 HIVE-25225 : Update column stat throws NPE if direct sql is disabled
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestPartitionStat.java
Labels: tests passed

#2000 HIVE-24804: RANGE with offset PRECEDING/FOLLOWING requires at least one ORDER BY column
  ql/src/java/org/apache/hadoop/hive/ql/parse/WindowingSpec.java
  ql/src/test/queries/clientnegative/ptf_window_boundaries_range_without_order.q
  ql/src/test/results/clientnegative/ptf_window_boundaries_range_without_order.q.out
Labels: tests passed

#2368 HIVE-25222: Fix column name issue with commas
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  serde/src/java/org/apache/hadoop/hive/serde2/ColumnProjectionUtils.java
Labels: tests unstable

#2332 HIVE-25081: Put metrics collection behind a feature flag
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2383 HIVE-25235: Remove ThreadPoolExecutorWithOomHook
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/HookContext.java
  ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveHooks.java
  service/src/java/org/apache/hive/service/cli/session/SessionManager.java
  service/src/java/org/apache/hive/service/cli/thrift/EmbeddedThriftBinaryCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThreadPoolExecutorWithOomHook.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  service/src/java/org/apache/hive/service/server/HiveServer2OomHookRunner.java
  service/src/test/org/apache/hive/service/auth/TestPlainSaslHelper.java
  service/src/test/org/apache/hive/service/cli/session/TestPluggableHiveSessionImpl.java
  service/src/test/org/apache/hive/service/cli/session/TestSessionGlobalInitFile.java
  service/src/test/org/apache/hive/service/cli/thrift/TestThreadPoolExecutorWithOomHook.java
Labels: tests passed

#2379 HIVE-25231. Add an ability to migrate CSV generated to hive table in replstats.
  bin/replstats.sh
Labels: tests passed

#2351 HIVE-25200: Alter table add columns support for Iceberg tables
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#2410 HIVE-25258: Incorrect row order after query-based MINOR compaction
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
Labels: tests passed

#2414 HIVE-25265: Fix TestHiveIcebergStorageHandlerWithEngine
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
Labels: tests passed

#2369 HIVE-25218. Add a replication migration tool for external tables.
  bin/ext/replMigration.sh
  bin/hive
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationMigrationTool.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplicationMigrationTool.java
Labels: tests passed

#2387 HIVE-25240: Query Text based MaterializedView rewrite of subqueries
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveRelOptMaterialization.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveFilter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBExpr.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/masking_mv_by_text_2.q
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_6.q
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_7.q
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_8.q
  ql/src/test/results/clientpositive/llap/masking_mv_by_text_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_6.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_7.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_8.q.out
Labels: tests passed

#2367 HIVE-25217: Move isEligibleForCompaction evaluation under the Initiator thread pool
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
Labels: tests pending

#2417 HIVE-25274: TestLimitOperator fails if default engine is Tez
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorLimitOperator.java
Labels: tests passed

#2356 HIVE-25207. Expose incremental load statistics via JMX.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWorkMBean.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStatsTracker.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/ReplicationMetricCollector.java
Labels: tests passed

#2359 HIVE-25208: Refactor Iceberg commit to the MoveTask/MoveWork
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
Labels: tests passed

#2382 HIVE-25234: Implement ALTER TABLE ... SET PARTITION SPEC to change partitioning on Iceberg tables
  hbase-handler/src/test/results/negative/hbase_ddl.q.out
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractBaseAlterTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
  ql/src/test/results/clientnegative/alter_non_native.q.out
Labels: tests passed

#2415 HIVE-25216
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveIcebergVectorizedRecordReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/VectorizedRowBatchIterator.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapred/AbstractMapredIcebergRecordReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapred/MapredIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_failure.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read.q
  iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_failure.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatchCtx.java
Labels: tests passed

#2238 HIVE-25085: MetaStore Clients no longer shared across sessions.
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
  service/src/java/org/apache/hive/service/cli/session/HiveSessionImpl.java
Labels: tests passed

#2259 HIVE-25101: Remove HBase libraries from Hive distribution
  bin/hive
  common/pom.xml
  druid-handler/pom.xml
  hbase-handler/pom.xml
  itests/hive-unit/pom.xml
  llap-server/pom.xml
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCopyAuxJars.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/LlapServiceCommandLine.java
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/HiveSparkClientFactory.java
Labels: tests passed

#2424 HIVE-25279: Fix q.outs caused by concurrent commits of HIVE-25240 and HIVE-25229
  ql/src/test/results/clientpositive/llap/masking_mv_by_text_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_6.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_7.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_8.q.out
Labels: tests pending

#2390 HIVE-25242. Query performs extremely slow with vectorized.adaptor = chosen
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
  ql/src/test/queries/clientpositive/vector_adaptor_usage_mode.q
  ql/src/test/results/clientpositive/llap/vector_adaptor_usage_mode.q.out
Labels: tests passed

#2391 HIVE-25243: Llap external client - Handle nested values when the parent struct is null
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapVectorArrow.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestMiniLlapVectorArrowWithLlapIODisabled.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
Labels: tests passed

#2402 HIVE-25259: Tweak delta metrics with custom MBean for Prometheus
  common/src/java/org/apache/hadoop/hive/common/metrics/MetricsMBeanImpl.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetricsOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
Labels: tests passed

#2087 HIVE-24901: Re-enable tests in TestBeeLineWithArgs
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestBeeLineWithArgs.java
Labels: tests passed

#2430 HIVE-25291: Update masking_mv_by_text_2.q.out
  ql/src/test/results/clientpositive/llap/masking_mv_by_text_2.q.out
Labels: tests pending

#2409 HIVE-25268: Restore the functionality of date_format UDF
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/util/DateTimeMath.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFDateFormat.java
  ql/src/test/queries/clientpositive/udf_date_format.q
  ql/src/test/results/clientpositive/llap/udf_date_format.q.out
Labels: tests passed

#2429 HIVE-23925: Flaky test TestJdbcWithMiniHS2
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniHS2.java
Labels: tests passed

#2398 HIVE-25254: Upgrade to tez 0.10.1
  pom.xml
Labels: tests passed

#2413 HIVE-25272: READ transactions are getting logged in NOTIFICATION LOG
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
Labels: tests passed

#2404 HIVE-25250: Fix TestHS2ImpersonationWithRemoteMS.testImpersonation
  itests/hive-unit/src/test/java/org/apache/hive/service/TestHS2ImpersonationWithRemoteMS.java
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
Labels: tests passed

#2370 HIVE-25219: Backward incompatible timestamp serialization in Avro for certain timezones
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
  ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroContainerOutputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
  ql/src/test/queries/clientpositive/avro_write_legacy_timestamp.q
  ql/src/test/queries/clientpositive/avro_write_new_timestamp.q
  ql/src/test/results/clientpositive/llap/avro_schema_evolution_native.q.out
  ql/src/test/results/clientpositive/llap/avro_write_legacy_timestamp.q.out
  ql/src/test/results/clientpositive/llap/avro_write_new_timestamp.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroGenericRecordWritable.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerializer.java
  serde/src/test/org/apache/hadoop/hive/serde2/avro/TestAvroDeserializer.java
Labels: tests passed

#2431 HIVE-19707: Enable TestJdbcWithMiniHS2#testHttpRetryOnServerIdleTimeout
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniHS2.java
Labels: tests passed

#2438 HIVE-19616: Enable TestAutoPurgeTables test
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAutoPurgeTables.java
Labels: tests passed

#2320 HIVE-25164: Bootstrap REPL load DDL task in parallel
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLTask.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadTable.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ImportTableDesc.java
Labels: tests passed
