Repository apache/hive, pull requests merged in 2021-11, with the labels that each got.

#2647 HIVE-25522 NullPointerException in TxnHandler
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests failed

#2758 HIVE-25659: Metastore direct sql queries with IN/(NOT IN) should be split based on max parameters allowed by SQL DB.
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestTxnUtils.java
Labels: tests passed

#2760 HIVE-25653: Incorrect results returned by STDDEV, STDDEV_SAMP, STDDEV_POP for floating point data types.
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFStd.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFVariance.java
  ql/src/test/queries/clientpositive/stddev.q
  ql/src/test/results/clientpositive/llap/cbo_rp_windowing_2.q.out
  ql/src/test/results/clientpositive/llap/stddev.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing.q.out
  ql/src/test/results/clientpositive/llap/windowing.q.out
Labels: tests passed

#2765 HIVE-25673: Column pruning fix for MR tasks
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
Labels: tests passed

#2750 Hive 25651
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HashableInputSplit.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HostAffinitySplitLocationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/io/BucketizedHiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/LlapCacheOnlyInputFormatInterface.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestHostAffinitySplitLocationProvider.java
Labels: tests passed

#2724 HIVE-25596: Compress Hive Replication Metrics while storing
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  metastore/scripts/upgrade/hive/hive-schema-4.0.0.hive.sql
  metastore/scripts/upgrade/hive/upgrade-3.1.0-to-4.0.0.hive.sql
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStatsTracker.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/MetricSink.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/ReplicationMetricCollector.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/ReplicationMetric.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/Stage.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDeserialize.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricCollector.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricSink.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricUpdateOnFailure.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFDeserialize.java
  ql/src/test/queries/clientpositive/replication_metrics_ingest.q
  ql/src/test/queries/clientpositive/udf_deserialize.q
  ql/src/test/results/clientpositive/llap/replication_metrics_ingest.q.out
  ql/src/test/results/clientpositive/llap/resourceplan.q.out
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/strict_managed_tables_sysdb.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
  ql/src/test/results/clientpositive/llap/udf_deserialize.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ReplicationMetrics.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ReplicationMetrics.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageDeserializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageFactory.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageSerializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/gzip/DeSerializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/gzip/Serializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MReplicationMetrics.java
  standalone-metastore/metastore-server/src/main/resources/package.jdo
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-3.2.0-to-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-3.2.0-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-3.2.0-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-3.2.0-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-3.2.0-to-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/test/resources/sql/postgres/upgrade-3.1.3000-to-4.0.0.postgres.sql
Labels: tests passed

#2774 HIVE-25683: Close reader in AcidUtils.isRawFormatFile
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
Labels: tests passed

#2741 HIVE-25631: Initiator speed-up: only read compaction history once per…
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
Labels: tests passed

#2754 HIVE-25634: Eclipse compiler bumps into AIOBE during ObjectStore comp…
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests pending

#2776 HIVE-25685: HBaseStorageHandler: ensure that hbase properties are present in final JobConf for Tez
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseStorageHandler.java
  hbase-handler/src/test/org/apache/hadoop/hive/hbase/TestHBaseStorageHandler.java
  hbase-handler/src/test/resources/hbase-site.xml
Labels: tests passed

#2769 HIVE-25681: Drop support for multi-threaded qtest execution via QTestRunnerUtils
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestMTQueries.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestRunnerUtils.java
Labels: tests passed

#2740 HIVE-25636: Bump Xerce2 to 2.12.1.
  pom.xml
Labels: tests passed

#2515 HIVE-25365: Insufficient privileges to show partitions when partition…
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/show/ShowPartitionAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestColumnAccess.java
Labels: tests passed

#2788 HIVE-25697 Upgrade commons-compress to 1.21
  pom.xml
Labels: tests passed

#2782 HIVE-25692: ExceptionHandler may mask checked exceptions
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ExceptionHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestExceptionHandler.java
Labels: tests passed

#2779 HIVE-25690: Fix column reorder detection for Iceberg schema evolution
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSchemaEvolution.java
  iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read.q
  iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
Labels: tests passed

#2763 HIVE-25670: Avoid getTable() calls for foreign key tables not used in…
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/RelOptHiveTable.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseContext.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParsedQueryTables.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QueryTables.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#2526 HIVE-25095: Beeline/hive -e command can't deal with query with traili…
  beeline/src/test/org/apache/hive/beeline/TestBeelineArgParsing.java
  beeline/src/test/org/apache/hive/beeline/cli/TestHiveCli.java
  pom.xml
Labels: tests passed

#2581 HIVE-25443 : Arrow SerDe Cannot serialize/deserialize complex data types When there are more than 1024 values
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Deserializer.java
  ql/src/test/org/apache/hadoop/hive/ql/io/arrow/TestArrowColumnarBatchSerDe.java
Labels: tests passed

#2792 HIVE-25702: Upgrade Iceberg dependency to 0.12.1
  iceberg/pom.xml
Labels: tests passed

#2784 HIVE-25689: Remove deprecated DataUtil from iceberg-handler
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/DataUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out
Labels: tests passed

#2627 HIVE-25509: CLIService.closeOperation should not fail if operation handle is not present
  jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
Labels: tests passed

#2801 HIVE-25714: docker logs commands timeout regularily during testing
  itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/AbstractExternalDB.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/DatabaseRule.java
Labels: tests passed

#2789 HIVE-25700. Prevent deletion of Notification Events post restarts.
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplWithJsonMessageFormat.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#2806 HIVE-25658: Addendum: Fix regex for masking totalSize table propertie…
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_as_fileformat.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_by_iceberg.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_metadata_tables.q
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_unpartitioned_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_with_joins.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_force_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q.out
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_unpartitioned_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out
Labels: tests passed

#2807 HIVE-25727: Iceberg hive catalog should create table object with init…
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
Labels: tests passed

#2567 HIVE-24849 CreateTableDesc() calls isEmpty() after isExternal(); optimize Table.…
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
Labels: tests passed

#2768 HIVE-25679: Use serdeContants collection delim in MultiDelimSerDe
  serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
Labels: tests passed

#2770 HIVE-25680 : Authorize #get_table_meta HiveMetastore Server API to use any of the HiveMetastore Authorization model
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/TestMetastoreClientSideAuthorizationProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#2693 HIVE-25582: Empty result when using offset limit with MR
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/exec/ObjectCache.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ObjectCache.java
  ql/src/test/queries/clientpositive/offset_limit_mr.q
  ql/src/test/results/clientpositive/offset_limit_mr.q.out
Labels: tests passed

#2783 HIVE-23095: NDV might be overestimated for a table with ~70 value
  itests/hive-jmh/src/main/java/org/apache/hive/benchmark/serde/HyperLogLogBench.java
  ql/src/test/results/clientpositive/llap/bucket_map_join_tez2.q.out
  ql/src/test/results/clientpositive/llap/compute_bit_vector.q.out
  ql/src/test/results/clientpositive/llap/compute_stats_date.q.out
  ql/src/test/results/clientpositive/llap/confirm_initial_tbl_stats.q.out
  ql/src/test/results/clientpositive/llap/constraints_explain_ddl.q.out
  ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_2.q.out
  ql/src/test/results/clientpositive/llap/estimate_pkfk_fknulls.q.out
  ql/src/test/results/clientpositive/llap/explainanalyze_2.q.out
  ql/src/test/results/clientpositive/llap/groupby_join_pushdown.q.out
  ql/src/test/results/clientpositive/llap/limit_pushdown.q.out
  ql/src/test/results/clientpositive/llap/limit_pushdown3.q.out
  ql/src/test/results/clientpositive/llap/mapjoin_decimal.q.out
  ql/src/test/results/clientpositive/llap/offset_limit_ppd_optimizer.q.out
  ql/src/test/results/clientpositive/llap/parquet_vectorization_limit.q.out
  ql/src/test/results/clientpositive/llap/partition_explain_ddl.q.out
  ql/src/test/results/clientpositive/llap/prepare_plan.q.out
  ql/src/test/results/clientpositive/llap/vector_left_outer_join.q.out
  ql/src/test/results/clientpositive/llap/vector_llap_text_1.q.out
  ql/src/test/results/clientpositive/llap/vectorization_div0.q.out
  ql/src/test/results/clientpositive/llap/vectorization_input_format_excludes.q.out
  ql/src/test/results/clientpositive/llap/vectorization_limit.q.out
  ql/src/test/results/clientpositive/llap/vectorized_distinct_gby.q.out
  ql/src/test/results/clientpositive/llap/vectorized_nested_mapjoin.q.out
  ql/src/test/results/clientpositive/llap/vectorized_parquet.q.out
  ql/src/test/results/clientpositive/tez/tez_tag.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/common/ndv/hll/HLLConstants.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/common/ndv/hll/HLLSparseRegister.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/common/ndv/hll/HyperLogLog.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/common/ndv/hll/HyperLogLogUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/common/ndv/hll/TestHyperLogLog.java
Labels: tests passed

#2802 HIVE-24390 Spelling serde
  serde/src/java/org/apache/hadoop/hive/serde2/RandomTypeUtil.java
  serde/src/java/org/apache/hadoop/hive/serde2/SerDeStatsStruct.java
  serde/src/java/org/apache/hadoop/hive/serde2/SerDeUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/columnar/ColumnarSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/io/HiveCharWritable.java
  serde/src/java/org/apache/hadoop/hive/serde2/json/HiveJsonReader.java
  serde/src/java/org/apache/hadoop/hive/serde2/json/HiveJsonWriter.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyFactory.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyHiveDecimal.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyTimestamp.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/fast/StringToDouble.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinaryArray.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinarySerDe2.java
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ListObjectsEqualComparer.java
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ObjectInspectorConverters.java
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ObjectInspectorUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/primitive/PrimitiveObjectInspectorUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinaryDataInputStream.java
  serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinaryDataOutputStream.java
  serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinarySerde.java
  serde/src/java/org/apache/hadoop/hive/serde2/thrift/TCTLSeparatedProtocol.java
  serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TimestampLocalTZTypeInfo.java
  serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoUtils.java
  serde/src/test/org/apache/hadoop/hive/serde2/SerdeRandomRowSource.java
  serde/src/test/org/apache/hadoop/hive/serde2/TestJsonSerDe.java
  serde/src/test/org/apache/hadoop/hive/serde2/TestTCTLSeparatedProtocol.java
  serde/src/test/org/apache/hadoop/hive/serde2/avro/TestAvroDeserializer.java
  serde/src/test/org/apache/hadoop/hive/serde2/avro/TestAvroObjectInspectorGenerator.java
  serde/src/test/org/apache/hadoop/hive/serde2/avro/TestAvroSerdeUtils.java
  serde/src/test/org/apache/hadoop/hive/serde2/binarysortable/TestBinarySortableFast.java
  serde/src/test/org/apache/hadoop/hive/serde2/lazy/TestLazySimpleFast.java
  serde/src/test/org/apache/hadoop/hive/serde2/lazybinary/TestLazyBinaryFast.java
  serde/src/test/org/apache/hadoop/hive/serde2/objectinspector/TestObjectInspectorConverters.java
Labels: tests passed

#2764 HIVE-25115: Addendum: Cleaner queue order change
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#2798 HIVE-25721: Outer join result is wrong
  ql/src/java/org/apache/hadoop/hive/ql/exec/JoinUtil.java
  ql/src/test/queries/clientpositive/sort_merge_join.q
  ql/src/test/results/clientpositive/llap/sort_merge_join.q.out
Labels: tests passed

#2781 HIVE-25691: LLAP: ShuffleHandler port should respect value in config
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
  llap-server/src/test/org/apache/hadoop/hive/llap/shufflehandler/TestShuffleHandler.java
Labels: tests passed

#2674 HIVE-25561: Killed task should not commit file.
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
Labels: tests passed

#2813 HIVE-25736: Close ORC readers
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/PostExecOrcFileDump.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/FixAcidKeyIndex.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcFileFormatProxy.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestNewInputOutputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcFile.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcRecordUpdater.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcSerDeStats.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtilities.java
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Labels: tests passed

#2819 HIVE-25741: Close previous writer in proto logger
  ql/src/java/org/apache/hadoop/hive/ql/hooks/HiveProtoLoggingHook.java
Labels: tests passed

#2796 HIVE-25710: Config used to enable non-blocking TRUNCATE is not proper…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#2823 HIVE-25749: Check if RelMetadataQuery.collations() returns null to av…
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveJoin.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/RelFieldTrimmer.java
Labels: tests passed

#2815 HIVE-25734: Wrongly-typed constant in case expression leads to incorrect empty result
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/RexNodeConverter.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/TestHivePointLookupOptimizerRule.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/translator/TestRexNodeConverter.java
  ql/src/test/queries/clientpositive/cbo_case_when_wrong_type.q
  ql/src/test/results/clientpositive/llap/cbo_case_when_wrong_type.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query39.q.out
Labels: tests passed
