Repository apache/hive, pull requests merged in 2021-01, with the labels that each got.

#1779 HIVE-24535: Cleanup AcidUtils.Directory and remove unnecessary filesystem listing
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidDirectory.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcRawRecordMerger.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Labels: tests passed

#1770 HIVE-24571: Redundant code in SemanticAnalyzer.java file
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests failed

#1802 HIVE-24552: Possible HMS connections leak or accumulation in loadDyna…
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Labels: tests passed

#1782 HIVE-24434: Filter out materialized views for rewriting if plan pattern is not allowed
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveRelOptMaterialization.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CBOPlan.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java
  ql/src/test/queries/clientpositive/materialized_view_rewrite_11.q
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_11.q.out
Labels: tests passed

#1807 HIVE-24560: Move Logging and Column Name,Type Parsing to AbstractSerd…
  accumulo-handler/src/java/org/apache/hadoop/hive/accumulo/serde/AccumuloSerDe.java
  contrib/src/java/org/apache/hadoop/hive/contrib/serde2/RegexSerDe.java
  contrib/src/java/org/apache/hadoop/hive/contrib/serde2/TypedBytesSerDe.java
  druid-handler/src/java/org/apache/hadoop/hive/druid/serde/DruidSerDe.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/HCatRecordSerDe.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcSerDe.java
  kafka-handler/src/java/org/apache/hadoop/hive/kafka/KafkaJsonSerDe.java
  kafka-handler/src/java/org/apache/hadoop/hive/kafka/KafkaSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorDeserializeRow.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/ConstantVectorExpression.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSerde.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcStruct.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/serde/ParquetHiveSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/log/syslog/SyslogSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PTFTranslator.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PTFDeserializer.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/VectorVerifyFast.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VerifyFastRow.java
  serde/src/java/org/apache/hadoop/hive/serde2/AbstractEncodingAwareSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/AbstractSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/JsonSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/MetadataTypedColumnsetSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
  serde/src/java/org/apache/hadoop/hive/serde2/RegexSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/binarysortable/BinarySortableSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/columnar/ColumnarSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazySimpleSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/VerifyLazy.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinarySerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/StructTypeInfo.java
  serde/src/test/org/apache/hadoop/hive/serde2/TestJsonSerDe.java
  serde/src/test/org/apache/hadoop/hive/serde2/VerifyFast.java
  serde/src/test/org/apache/hadoop/hive/serde2/avro/TestAvroObjectInspectorGenerator.java
Labels: tests passed

#1829 HIVE-24587: DataFileReader is not closed in AvroGenericRecordReader#extractWriterProlepticFromMetadata
  ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
Labels: tests passed

#1797 HIVE-24541: add config option for default storage handler class
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
  ql/src/test/queries/clientpositive/default_storage_handler.q
  ql/src/test/results/clientpositive/default_storage_handler.q.out
Labels: tests passed

#1830 HIVE-24585
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
Labels: tests passed

#1795 HIVE-24550: Cleanup only transaction information for the current DriverContext
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHiveServer2Acid.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java
Labels: tests passed

#1772 HIVE-24519: Optimize MV: Materialized views should not rebuild when tables are not modified
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
  ql/src/test/queries/clientpositive/materialized_view_rebuild_2.q
  ql/src/test/queries/clientpositive/materialized_view_rebuild_3.q
  ql/src/test/results/clientnegative/materialized_view_authorization_rebuild_no_grant.q.out
  ql/src/test/results/clientnegative/materialized_view_authorization_rebuild_other.q.out
  ql/src/test/results/clientpositive/druid/druidmini_mv.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_cluster.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_3.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_rebuild_dummy.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_distribute_sort.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partition_cluster.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rebuild.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rebuild_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rebuild_3.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_4.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_window.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_cume_dist.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_ntile.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_percentile_disc.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_rank.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_rollup2.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_safety.q.out
Labels: tests passed

#1776 HIVE-24337: Cache delete delta files in LLAP cache
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapInputFormat.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestSearchArgumentImpl.java
Labels: tests passed

#1836 HIVE-24550: Cleanup only transaction information for the current DriverContext
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHiveServer2Acid.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java
Labels: tests passed

#1816 HIVE-24570 Hive on spark tmp file should be delete when driver process finished
  spark-client/src/main/java/org/apache/hive/spark/client/AbstractSparkClient.java
Labels: tests passed

#1773 HIVE-20726: hive.server2.thrift.bind.host is not honored
  service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
  service/src/test/org/apache/hive/service/cli/TestRetryingThriftCLIServiceClient.java
Labels: tests passed

#1814 HIVE-15820: comment at the head of beeline -e
  beeline/src/java/org/apache/hive/beeline/BeeLine.java
  beeline/src/java/org/apache/hive/beeline/Commands.java
  beeline/src/test/org/apache/hive/beeline/TestCommands.java
  beeline/src/test/org/apache/hive/beeline/cli/TestHiveCli.java
  common/src/java/org/apache/hive/common/util/HiveStringUtils.java
  common/src/test/org/apache/hive/common/util/TestHiveStringUtils.java
Labels: tests passed

#1810 HIVE-24565: Implement standard trim function
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseTrim.java
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestSQL11ReservedKeyWordsNegative.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringLTrimCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringLTrimColScalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringRTrimCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringRTrimColScalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringTrimCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringTrimColScalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringTrimColScalarBase.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFBaseTrim.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLTrim.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFRTrim.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFTrim.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorizationContext.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/expressions/TestVectorStringExpressions.java
  ql/src/test/queries/clientpositive/udf_ltrim.q
  ql/src/test/queries/clientpositive/udf_ltrim_vector.q
  ql/src/test/queries/clientpositive/udf_rtrim.q
  ql/src/test/queries/clientpositive/udf_rtrim_vector.q
  ql/src/test/queries/clientpositive/udf_trim.q
  ql/src/test/queries/clientpositive/udf_trim_vector.q
  ql/src/test/results/clientpositive/llap/udf_ltrim.q.out
  ql/src/test/results/clientpositive/llap/udf_ltrim_vector.q.out
  ql/src/test/results/clientpositive/llap/udf_rtrim.q.out
  ql/src/test/results/clientpositive/llap/udf_rtrim_vector.q.out
  ql/src/test/results/clientpositive/llap/udf_trim.q.out
  ql/src/test/results/clientpositive/llap/udf_trim_vector.q.out
  ql/src/test/results/clientpositive/llap/vector_string_concat.q.out
  ql/src/test/results/clientpositive/llap/vector_udf1.q.out
Labels: tests passed

#1756 HIVE-24509 Move show specific codes under DDL and cut MetaDataFormatter classes to pieces
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLOperationContext.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/ShowUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/desc/DescDatabaseFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/desc/DescDatabaseOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/show/ShowDatabasesFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/show/ShowDatabasesOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/showcreate/ShowCreateDatabaseOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/function/desc/DescFunctionOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/function/show/ShowFunctionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/conf/ShowConfOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/privilege/PrivilegeUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/privilege/show/grant/ShowGrantOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/privilege/show/principals/ShowPrincipalsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/privilege/show/rolegrant/ShowRoleGrantOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/transactions/ShowTransactionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/show/ShowColumnsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/show/ShowCreateTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/DescTableFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/JsonDescTableFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/show/properties/ShowTablePropertiesOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/show/status/ShowTableStatusOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/show/status/formatter/JsonShowTableStatusFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/show/status/formatter/ShowTableStatusFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/show/status/formatter/TextShowTableStatusFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/show/tables/ShowTablesFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/show/tables/ShowTablesOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/show/ShowLocksOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/show/ShowPartitionsFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/show/ShowPartitionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/show/ShowMaterializedViewsFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/show/ShowMaterializedViewsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/show/ShowViewsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/workloadmanagement/resourceplan/alter/validate/AlterResourcePlanValidateOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/workloadmanagement/resourceplan/show/ShowResourcePlanOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/workloadmanagement/resourceplan/show/formatter/JsonShowResourcePlanFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/workloadmanagement/resourceplan/show/formatter/ShowResourcePlanFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/workloadmanagement/resourceplan/show/formatter/TextShowResourcePlanFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/formatting/JsonMetaDataFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/formatting/MetaDataFormatUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/formatting/MetaDataFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/formatting/TextMetaDataFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/formatting/TextMetaDataTable.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/formatting/TestJsonRPFormatter.java
Labels: tests passed

#1818 HIVE-24559: Fix some spelling issues
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests failed

#1835 HIVE-24593 Clean up checkstyle violations in ddl
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/add/AlterTableAddConstraintAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/show/ShowDbLocksAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/show/ShowLocksAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/add/AlterTableAddPartitionDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AbstractDropPartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/rename/AlterTableRenamePartitionOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/skewed/AlterTableSetSkewedLocationAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AlterViewAsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/formatting/MapBuilder.java
Labels: tests passed

#1839 HIVE-24602: Retry compaction after configured time
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#1826 HIVE-24581: Remove AcidUtils call from OrcInputformat for non transactional tables
  ql/src/java/org/apache/hadoop/hive/ql/hooks/PostExecOrcFileDump.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidDirectory.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HdfsUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/OriginalDirectory.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidInputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
Labels: tests passed

#1783 HIVE-24539: OrcInputFormat schema generation should respect column delimiter
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/test/queries/clientpositive/comma_in_column_name.q
  ql/src/test/results/clientpositive/llap/comma_in_column_name.q.out
Labels: tests passed

#1842 HIVE-24588: Run tests using specific log4j2 configuration conveniently
  testutils/pom.xml
  testutils/src/java/org/apache/hive/testutils/junit/extensions/Log4jConfig.java
  testutils/src/java/org/apache/hive/testutils/junit/extensions/Log4jConfigExtension.java
  testutils/src/test/java/org/apache/hive/testutils/junit/extensions/TestLog4jConfigExtension.java
  testutils/src/test/resources/test0-log4j2.properties
  testutils/src/test/resources/test1-log4j2.properties
Labels: tests passed

#1831 HIVE-24586: Rename compaction 'attempted' status
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  metastore/scripts/upgrade/hive/hive-schema-4.0.0.hive.sql
  metastore/scripts/upgrade/hive/upgrade-3.1.0-to-4.0.0.hive.sql
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtilities.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/conf/TestMetastoreConf.java
Labels: tests passed

#1851 HIVE-24616: Add Logging to Track Query Status
  jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
Labels: tests passed

#1853 HIVE-24617: Review beeline Driver Scanning Code
  beeline/src/java/org/apache/hive/beeline/BeeLine.java
  beeline/src/java/org/apache/hive/beeline/Commands.java
Labels: tests passed

#1531 HIVE-24203: Implement stats annotation rule for the LateralViewJoinOperator
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/AnnotateWithStatistics.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
  ql/src/test/queries/clientpositive/annotate_stats_lateral_view_join.q
  ql/src/test/results/clientnegative/udf_assert_true.q.out
  ql/src/test/results/clientnegative/udf_assert_true2.q.out
  ql/src/test/results/clientpositive/llap/annotate_stats_lateral_view_join.q.out
  ql/src/test/results/clientpositive/llap/lateral_view.q.out
  ql/src/test/results/clientpositive/llap/lateral_view_cp.q.out
  ql/src/test/results/clientpositive/llap/lateral_view_explode2.q.out
  ql/src/test/results/clientpositive/llap/lateral_view_noalias.q.out
  ql/src/test/results/clientpositive/llap/lateral_view_onview.q.out
  ql/src/test/results/clientpositive/llap/lvj_mapjoin.q.out
  ql/src/test/results/clientpositive/llap/multi_insert_lateral_view.q.out
  ql/src/test/results/clientpositive/llap/nested_column_pruning.q.out
  ql/src/test/results/clientpositive/llap/orc_nested_column_pruning.q.out
  ql/src/test/results/clientpositive/llap/reduce_deduplicate_null_keys.q.out
  ql/src/test/results/clientpositive/llap/select_column_pruning.q.out
  ql/src/test/results/clientpositive/llap/skewjoin_mapjoin6.q.out
  ql/src/test/results/clientpositive/llap/udtf_json_tuple.q.out
  ql/src/test/results/clientpositive/llap/udtf_parse_url_tuple.q.out
  ql/src/test/results/clientpositive/llap/union26.q.out
  ql/src/test/results/clientpositive/llap/unionDistinct_1.q.out
  ql/src/test/results/clientpositive/llap/union_lateralview.q.out
  ql/src/test/results/clientpositive/llap/vector_orc_nested_column_pruning.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing.q.out
  ql/src/test/results/clientpositive/nonmr_fetch.q.out
  ql/src/test/results/clientpositive/skewjoinopt10.q.out
  ql/src/test/results/clientpositive/tez/tez_union_udtf.q.out
Labels: tests passed

#1825 HIVE-24523: Vectorized read path for LazySimpleSerde does not honor the SERDEPROPERTIES for timestamp
  data/files/test_timestamp.csv
  ql/src/test/queries/clientpositive/timestamp_formats.q
  ql/src/test/results/clientpositive/llap/timestamp_formats.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/fast/LazySimpleDeserializeRead.java
Labels: tests passed

#1848 HIVE-24615: Remove unnecessary FileSystem listing from Initiator
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
Labels: tests passed

#1846 HIVE-24611 Remove unnecessary parameter from AbstractAlterTableOperation
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java
Labels: tests passed

#1847 HIVE-24613: Support Values clause without Insert
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestValuesClause.java
  ql/src/test/queries/clientpositive/values.q
  ql/src/test/results/clientpositive/llap/values.q.out
Labels: tests passed

#1679 HIVE-24394: enable printing explain to console at start of query
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
Labels: tests passed

#1786 HIVE-23684: Large underestimation in NDV stats when input and join ca…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
Labels: tests passed

#1859 HIVE-24627: Add Debug Logging to Hive JDBC Connection
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
Labels: tests passed

#1850 HIVE-24589 : Drop catalog failing with deadlock error for Oracle backend dbms.
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-3.2.0-to-4.0.0.oracle.sql
Labels: tests passed

#1861 HIVE-24628: Decimal values are displayed as scientific notation in beeline
  beeline/src/java/org/apache/hive/beeline/Rows.java
Labels: tests passed

#1845 HIVE-24610 Remove superfluous throws IOException from Context
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/io/rcfile/truncate/ColumnTruncateTask.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AcidExportSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ColumnStatsAutoGatherContext.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ColumnStatsSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSQLSchema.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestContext.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezTask.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/physical/TestNullScanTaskDispatcher.java
  ql/src/test/org/apache/hadoop/hive/ql/tool/TestLineageInfo.java
Labels: tests passed

#1869 HIVE-24635: Support Values clause as operand of set operation
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestValuesClause.java
  ql/src/test/queries/clientpositive/values.q
  ql/src/test/results/clientpositive/llap/values.q.out
Labels: tests passed

#1863 HIVE-24632: Replace with null when GenericUDFBaseCompare has a non-interpretable val
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/FunctionHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/HiveFunctionHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java
  ql/src/test/queries/clientpositive/compare_cols_null.q
  ql/src/test/results/clientpositive/llap/compare_cols_null.q.out
Labels: tests passed

#1761 HIVE-24514: UpdateMDatabaseURI does not update managed location URI
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#1862 HIVE-24630: clean up multiple parseDelta in AcidUtils
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMSCKRepairOnAcid.java
Labels: tests passed

#1868 HIVE-24626: LLAP: reader threads could be starvated if all IO elevator threads are busy to enqueue to another readers with full queue
  itests/util/src/main/java/org/apache/hadoop/hive/llap/LlapItUtils.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java
  llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemon.java
Labels: tests passed

#1874 HIVE-24644: QueryResultCache parses the query twice
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#1857 HIVE-24629: Invoke output committer in TezProcessor
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDagUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
Labels: tests passed

#1838 HIVE-24597: Replication with timestamp type partition failing in HA c…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/Utils.java
Labels: tests passed

#1854 HIVE-24623: Wrong FS error during dump for table-level replication wh…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExclusiveReplica.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#1804 HIVE-24558 : Handle update in table level regular expression
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExclusiveReplica.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestTableLevelReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpWork.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AlterTableHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/DumpMetaData.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestReplDumpTask.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplScope.java
Labels: tests passed

#1866 HIVE-14165: Remove unnecessary file listing from FetchOperator
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java
  ql/src/test/queries/clientpositive/exim_04_evolved_parts.q
  ql/src/test/results/clientpositive/llap/exim_04_evolved_parts.q.out
Labels: tests passed

#1817 HIVE-24278: Implement an UDF for throwing exception in arbitrary vertex
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MapredContext.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFEvaluator.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFExceptionInVertex.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFExceptionInVertex.java
  ql/src/test/queries/clientpositive/exception_in_vertex_udf.q
  ql/src/test/results/clientpositive/llap/exception_in_vertex_udf.q.out
  ql/src/test/results/clientpositive/llap/show_functions.q.out
Labels: tests passed

#1724 HIVE-24428: Concurrent add_partitions requests may lead to data loss
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/zookeeper/ZooKeeperHiveLock.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/zookeeper/ZooKeeperHiveLockManager.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestConcurrentDppInserts.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/zookeeper/TestZookeeperLockManager.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Labels: tests passed

#1729 HIVE-24473 Make Hive buildable with HBase 2.x GA versions
  itests/hcatalog-unit/pom.xml
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/hbase/ManyMiniCluster.java
  itests/util/pom.xml
  pom.xml
  ql/pom.xml
Labels: tests passed

#1746 HIVE-24491 : setting custom job name is ineffective if the Tez session pool is configured or in case of session reuse.
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolManager.java
Labels: tests passed

#1887 HIVE-24659: Remove Commons Logger from serde Package
  serde/pom.xml
  serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinaryDataOutputStream.java
  serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinarySerde.java
Labels: tests passed

#1888 HIVE-24660: Remove Commons Logger from jdbc-handler Package
  jdbc-handler/pom.xml
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcRecordWriter.java
Labels: tests passed

#1400 HIVE-18284: Fix NPE when inserting data with 'distribute by' clause with dynpart sort optimization
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/ReduceSinkDeDuplicationUtils.java
  ql/src/test/queries/clientpositive/dynpart_sort_optimization_distribute_by.q
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_distribute_by.q.out
  ql/src/test/results/clientpositive/tez/dynpart_sort_optimization_distribute_by.q.out
Labels: tests passed

#1900 HIVE-24677: Fix typoed vectorization package declaration
  ql/src/gen/vectorization/UDAFTemplates/VectorUDAFComputeBitVector.txt
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFComputeBitVectorHLL.java
Labels: tests passed

#1886 HIVE-24658: Move LogUtil Class to Metastore Server from Common
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/LogUtils.java
  standalone-metastore/pom.xml
Labels: tests passed

#1899 HIVE-24676 : Show locks call failing for postgres RDBMS if the txnId filter is passed
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#1904 HIVE-24680: Disable flaky unionDistinct_1.q test
  ql/src/test/queries/clientpositive/unionDistinct_1.q
Labels: tests pending

#1033 HIVE-23546: Skip authorization when user is a superuser
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestRestrictedList.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/session/TestQueryDisplay.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ExplainSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestSemanticAnalyzer.java
Labels: tests passed

#1686 HIVE-22981: DataFileReader is not closed in AvroGenericRecordReader#e…
  ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
Labels: tests unstable

#1885 HIVE-24656
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java
  ql/src/test/results/clientpositive/llap/analyze_npe.q.out
Labels: tests passed

#1754 HIVE-24500: Bump up the log4j version from 2.12.1 to 2.13.2 to avoid …
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#1865 HIVE-24633: Support CTE with column labels
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QB.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBParseInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientnegative/cte_col_alias.q
  ql/src/test/queries/clientnegative/cte_col_alias_clash.q
  ql/src/test/queries/clientpositive/cte_8.q
  ql/src/test/queries/clientpositive/cte_mat_1.q
  ql/src/test/results/clientnegative/cte_col_alias.q.out
  ql/src/test/results/clientnegative/cte_col_alias_clash.q.out
  ql/src/test/results/clientpositive/llap/cte_8.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_1.q.out
Labels: tests passed

#1901 HIVE-24671: Semijoinremoval should not run into an NPE in case the SJ filter contains an UDF
  ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
  ql/src/test/queries/clientpositive/semijoin_removal_udf.q
  ql/src/test/results/clientpositive/llap/semijoin_removal_udf.q.out
Labels: tests passed

#1695 HIVE-24411: Make ThreadPoolExecutorWithOomHook more awareness of OutO…
  ql/src/java/org/apache/hadoop/hive/ql/hooks/HiveHooks.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
  service/src/java/org/apache/hive/service/cli/thrift/ThreadPoolExecutorWithOomHook.java
  service/src/test/org/apache/hive/service/cli/thrift/TestThreadPoolExecutorWithOomHook.java
Labels: tests passed

#1894 HIVE-24670
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
Labels: tests passed

#1870 HIVE-24637 make Tez progress log interval configurable
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/RenderStrategy.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
Labels: tests passed

#1893 HIVE-24669: Improve FileSystem usage in Hive::loadPartitionInternal
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplAcrossInstancesWithJsonMessageFormat.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HdfsUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
Labels: tests passed

#1891 HIVE-24667: Truncate optimization to avoid unnecessary per partition DB get operations
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Labels: tests passed

#1903 HIVE-24679: Reuse FullDPSpecs in loadDynamicPartitions to avoid double listing
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Labels: tests passed

#1911 HIVE-24683
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
  shims/0.23/src/main/test/org/apache/hadoop/hive/shims/TestHadoop23Shims.java
Labels: tests passed

#1898 HIVE-24675: Handle external table replication for HA with same NS and…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplAcrossInstancesWithJsonMessageFormat.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplExternalTables.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/Utils.java
Labels: tests passed

#1908 HIVE-24345: Re-enable flaky test: TestCleanupService#testEventualClea…
  ql/src/test/org/apache/hadoop/hive/ql/cleanup/TestCleanupService.java
Labels: tests passed

#1811 HIVE-24564: Extend PPD filter transitivity to be able to discover new opportunities
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/ppd/OpProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/ppd/OpWalkerInfo.java
  ql/src/test/results/clientpositive/llap/dynamic_partition_join_noncbo.q.out
  ql/src/test/results/clientpositive/llap/hybridgrace_hashjoin_2.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query17.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query25.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query29.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query95.q.out
  ql/src/test/results/clientpositive/tez/hybridgrace_hashjoin_2.q.out
Labels: tests passed

#1912 HIVE-24678: Add feature toggle to control SWO parallel edge support
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
Labels: tests passed

#1889 HIVE-24661: Do Not Stringify Exception in Logger messages
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcRecordWriter.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/PartitionUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainSQRewriteTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ReplCopyTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ScriptOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Task.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecReducer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/MapRedTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MapRecordSource.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MergeFileRecordProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/history/HiveHistoryImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/io/rcfile/truncate/ColumnTruncateTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SimpleFetchOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/ColStatsProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFAverage.java
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ObjectInspectorUtils.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
Labels: tests passed

#1897 HIVE-24674. Set repl.source.for property in the db if db is under repication
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
Labels: tests passed

#1909 HIVE-24392: Add table id to GetPartitionsByNamesRequest
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetPartitionsByNamesRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetPartitionsByNamesRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed

#1154 HIVE-23728: Run metastore verification tests during precommit
  Jenkinsfile
  standalone-metastore/DEV-README
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/ITestDerby.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/ITestMssql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/DatabaseRule.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Derby.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mssql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Oracle.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Postgres.java
  storage-api/pom.xml
  upgrade-acid/pom.xml
  upgrade-acid/pre-upgrade/pom.xml
Labels: tests passed

#1726 HIVE-24458: Add a method to provide a non-normalized ExpressionTree
  pom.xml
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestConvertAstToSearchArg.java
  ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestSearchArgumentImpl.java
  standalone-metastore/pom.xml
  storage-api/pom.xml
  storage-api/src/java/org/apache/hadoop/hive/common/io/CacheTag.java
  storage-api/src/java/org/apache/hadoop/hive/common/type/CalendarUtils.java
  storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/ExpressionTree.java
  storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/PredicateLeaf.java
  storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/SearchArgument.java
  storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/SearchArgumentImpl.java
  storage-api/src/test/org/apache/hadoop/hive/ql/io/sarg/TestSearchArgumentFactory.java
Labels: tests passed

#1924 HIVE-24636: Memory leak due LogFactory retaining ClassLoaders
  common/src/java/org/apache/hadoop/hive/common/JavaUtils.java
Labels: tests unstable

#1820 HIVE-17155: findConfFile() in HiveConf.java has some issues with the conf path
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests unstable
