Repository apache/hive, pull requests merged in 2021-08, with the labels that each got.

#2277 HIVE-25115: Compaction queue entries may accumulate in "ready for cleaning" state
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#2520 HIVE-25373 : Modify buildColumnStatsDesc to send configured number of stats for updation
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/ColStatsProcessor.java
  ql/src/test/queries/clientpositive/partitioned_table_stats.q
  ql/src/test/results/clientpositive/llap/partitioned_table_stats.q.out
Labels: tests passed

#2529 HIVE-24946: Handle failover case during repl load
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStateLogWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadTasksBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/EximUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/message/AlterDatabaseHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionManagement.java
Labels: tests passed

#2552 HIVE-25367: Fix TestReplicationScenariosAcidTables#testMultiDBTxn
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/TaskRunner.java
Labels: tests passed

#2554 HIVE-25415: Disable auto-assign reviewer on forks
  .github/workflows/auto-assign.yml
Labels: tests pending

#2524 HIVE-25372: Advance write id for all the DDLs
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/owner/AlterTableSetOwnerAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/cluster/AlterTableClusterSortAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/cluster/AlterTableIntoBucketsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/concatenate/AlterTableConcatenateAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/serde/AlterTableSetSerdeAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/serde/AlterTableSetSerdePropsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/set/fileformat/AlterTableSetFileFormatAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnConcatenate.java
Labels: tests passed

#2523 HIVE-25376
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/VectorizedRowBatchIterator.java
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read.q
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
Labels: tests passed

#2225 HIVE-25061: PTF: Improve ValueBoundaryScanner
  ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/ptf/TestBoundaryCache.java
Labels: tests pending

#2475 HIVE-25328: Limit scope of REPLACE COLUMNS for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#2491 HIVE-25341. Reduce FileSystem calls in case drop database cascade.
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/LoadDatabase.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#2558 HIVE-25422
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergComplexTypeWrites.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergMigration.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergPartitions.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSchemaEvolution.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStatistics.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTimeTravel.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTruncateTable.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTypes.java
Labels: tests passed

#2561 HIVE-25394
  iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_pruning.q
  iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_pruning.q.out
Labels: tests passed

#2100 HIVE-24902: Incorrect result after fold CASE into COALESCE
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java
  ql/src/test/queries/clientpositive/constant_prop_coalesce.q
  ql/src/test/results/clientpositive/llap/constant_prop_coalesce.q.out
Labels: tests passed

#2331 HIVE-25170: Fix wrong colExprMap generated by SemanticAnalyzer
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/constant_key_column.q
  ql/src/test/results/clientpositive/llap/constant_key_column.q.out
Labels: tests passed

#2498 HIVE-25350. Replication fails for external tables on setting owner/groups.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyTask.java
Labels: tests passed

#1711 HIVE-24324: Remove deprecated API usage from Avro
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerdeUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/SchemaToTypeInfo.java
Labels: tests unstable, stale

#2556 HIVE-25417 : Null bit vector is not handled while getting the stats for Postgres backend
  ql/src/test/queries/clientpositive/nullBitVectorStats.q
  ql/src/test/results/clientpositive/llap/nullBitVectorStats.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/StatObjectConverter.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MPartitionColumnStatistics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MTableColumnStatistics.java
Labels: tests passed

#2580 HIVE-25423: Add new test driver to automatically launch and load external database (Same as PR#2559, squashed commit for test trigger)
  data/scripts/derby/q_test_extDB_cleanup.derby.sql
  data/scripts/derby/q_test_extDB_init.derby.sql
  data/scripts/mysql/q_test_extDB_cleanup.mysql.sql
  data/scripts/mysql/q_test_extDB_init.mysql.sql
  data/scripts/postgres/q_test_extDB_cleanup.postgres.sql
  data/scripts/postgres/q_test_extDB_init.postgres.sql
  itests/qtest/pom.xml
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniLlapExtDBCliDriver.java
  itests/src/test/resources/testconfiguration.properties
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/AbstractCliConfig.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreCliDriver.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestArguments.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestExternalDB.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/AbstractExternalDB.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/MySQLExternalDB.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/PostgresExternalDB.java
  ql/src/test/queries/clientpositive/dataconnector_mysql.q
  ql/src/test/results/clientpositive/llap/dataconnector_mysql.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MySQLConnectorProvider.java
  testutils/ptest2/conf/deployed/master-mr2.properties
Labels: tests passed

#2550 HIVE-25403: Fixing from_unixtime() in GenericUDFFromUnixTime class so as to consider leap seconds
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFFromUnixTime.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFFromUnixTime.java
  ql/src/test/queries/clientpositive/foldts.q
  ql/src/test/queries/clientpositive/udf5.q
  ql/src/test/results/clientpositive/llap/foldts.q.out
  ql/src/test/results/clientpositive/llap/udf5.q.out
Labels: tests failed

#2577 HIVE-25375
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransformSpec.java
Labels: tests passed

#2576 HIVE-25414 : Optimise Hive::addWriteNotificationLog: Reduce FS call per notification.
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
Labels: tests passed

#2566 HIVE-25433: DistCp job fails with yarn map compatibility mode issue.
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyTask.java
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Labels: tests passed

#2573 HIVE-25438 : Update partition column stats fails with invalid syntax error for MySql
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdateStat.java
Labels: tests passed

#2578 HIVE-25413 : Optimise ObjectStore::alterPartitions to reduce DB calls for getPartitions
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#2540 HIVE-25387: Fix TestMiniLlapLocalCliDriver#replication_metrics_ingest.q
  ql/src/test/queries/clientpositive/replication_metrics_ingest.q
  ql/src/test/results/clientpositive/llap/replication_metrics_ingest.q.out
Labels: tests passed

#2582 [WIP]HIVE-25275: OOM during query planning due to HiveJoinPushTransitivePredicatesRule matching infinitely
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinAddNotNullRule.java
  ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop.q
  ql/src/test/results/clientpositive/llap/cbo_join_transitive_pred_loop.q.out
Labels: tests passed

#2592 HIVE-25462: Disable flaky test jdbc_split_filter.q
  ql/src/test/queries/clientpositive/jdbc_split_filter.q
Labels: tests pending

#2590 HIVE-25458: Unix_timestamp() with string input give wrong result
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFUnixTimeStampString.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFToUnixTimeStamp.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFToUnixTimestamp.java
  ql/src/test/queries/clientpositive/udf5.q
  ql/src/test/queries/clientpositive/udf_unix_timestamp.q
  ql/src/test/queries/clientpositive/vector_unix_timestamp.q
  ql/src/test/results/clientpositive/beeline/udf_unix_timestamp.q.out
  ql/src/test/results/clientpositive/llap/udf5.q.out
  ql/src/test/results/clientpositive/llap/vector_unix_timestamp.q.out
  ql/src/test/results/clientpositive/llap/vectorized_timestamp_funcs.q.out
Labels: tests passed

#2589 HIVE-25457: Implement querying Iceberg table metadata - first draft
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMetadataTables.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java
  iceberg/iceberg-handler/src/test/queries/negative/describe_non_existing_metadata_table.q
  iceberg/iceberg-handler/src/test/queries/negative/query_non_existing_metadata_table.q
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_metadata_tables.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_unpartitioned_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_with_joins.q
  iceberg/iceberg-handler/src/test/results/negative/describe_non_existing_metadata_table.q.out
  iceberg/iceberg-handler/src/test/results/negative/query_non_existing_metadata_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_metadata_tables.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_unpartitioned_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_with_joins.q.out
  metastore/src/java/org/apache/hadoop/hive/metastore/HiveMetaStoreUtils.java
  metastore/src/java/org/apache/hadoop/hive/metastore/SerDeStorageSchemaReader.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/show/ShowCreateTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/serde/AlterTableSetSerdeOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionPruner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UnparseTranslator.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/HiveWrapper.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PartitionDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableDesc.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestUtilities.java
  ql/src/test/results/clientnegative/desc_failure3.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  storage-api/src/java/org/apache/hadoop/hive/common/TableName.java
  storage-api/src/test/org/apache/hadoop/hive/common/TestTableName.java
Labels: tests passed

#2579 HIVE-25441: Incorrect deltas split for sub-compactions when using
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
Labels: tests passed

#2560 HIVE-25408: AlterTableSetOwnerAnalyzer should send Hive Privilege Obj…
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/owner/AlterTableSetOwnerAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/test/results/clientpositive/llap/table_set_owner.q.out
Labels: tests passed

#2591 HIVE-25449: datediff() gives wrong output when run in a tez task with some non-UTC timezone
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateDiffColCol.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateDiffColScalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateDiffScalarCol.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/expressions/TestVectorGenericDateExpressions.java
  ql/src/test/queries/clientpositive/udf_datediff_with_tz.q
  ql/src/test/results/clientpositive/llap/udf_datediff_with_tz.q.out
Labels: tests passed

#2600 HIVE-25477: Clean Up JDBC Code
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/HiveDatabaseMetaData.java
  jdbc/src/java/org/apache/hive/jdbc/HttpRequestInterceptorBase.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
Labels: tests passed

#2479 HIVE-23688: fix Vectorization IndexArrayOutOfBoundsException when read null values in map
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedListColumnReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/TestVectorizedListColumnReader.java
  ql/src/test/queries/clientpositive/parquet_map_null_vectorization.q
  ql/src/test/results/clientpositive/llap/parquet_map_null_vectorization.q.out
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/BytesColumnVector.java
Labels: tests passed

#2602 HIVE-25480: Fix Time Travel with CBO
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSchemaEvolution.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
Labels: tests passed

#2610 HIVE-25482: Add option to enable connectionLeak detection for Hikari …
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
Labels: tests passed
