Repository apache/hive, pull requests merged in 2021-04, with the labels that each got.

#2143 HIVE-24966: RuntimeException in CBO if HMS stats are modified externally
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveConfPlannerContext.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/FilterSelectivityEstimator.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/stats_cbo_1.q
  ql/src/test/results/clientpositive/llap/stats_cbo_1.q.out
Labels: tests passed

#2140 Backport HIVE-22453: Describe table unnecessarily fetches partitions
  ql/src/java/org/apache/hadoop/hive/ql/exec/DDLTask.java
Labels: tests unstable

#2115 HIVE-24932: Create new metric about Initiator / Worker hosts
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Labels: tests passed

#2109 sq_check_count returns boolean
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRemoveSqCountCheck.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFSQCountCheck.java
  ql/src/test/results/clientpositive/llap/cte_mat_6.q.out
  ql/src/test/results/clientpositive/llap/subquery_in.q.out
  ql/src/test/results/clientpositive/llap/subquery_notin.q.out
  ql/src/test/results/clientpositive/llap/subquery_scalar.q.out
  ql/src/test/results/clientpositive/llap/subquery_select.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query54.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query58.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query6.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query54.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query58.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query6.q.out
Labels: tests passed

#2141 HIVE-24965: Describe table partition stats fetch should be configurable
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/test/queries/clientpositive/describe_table.q
  ql/src/test/results/clientpositive/llap/describe_table.q.out
Labels: tests passed

#2146 HIVE-24937 : Fix sync bottleneck in SyslogParser
  ql/src/java/org/apache/hadoop/hive/ql/log/syslog/SyslogParser.java
Labels: tests passed

#2132 HIVE-24955: New metrics about aborted transactions
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2133 HIVE-24953: Set repl.source.for property in the db if db is under replication in incremental dump.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#2157 Backport HIVE-24965: Describe table partition stats fetch should be configurable
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/DDLTask.java
  ql/src/test/queries/clientpositive/describe_table.q
  ql/src/test/results/clientpositive/describe_table.q.out
Labels: tests unstable

#2092 HIVE-24912: Support to add repl.target.for property during incrementa…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Labels: tests passed

#2155 HIVE-24976: CBO: count(distinct) in a window function fails CBO
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/functions/HiveSqlAverageAggFunction.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
  ql/src/test/queries/clientpositive/windowing_distinct.q
  ql/src/test/results/clientpositive/llap/windowing_distinct.q.out
Labels: tests passed

#2136 HIVE-24961. Use database name as default in the mapred job name for replication.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
Labels: tests passed

#2164 HIVE-25000. TestReplWithJsonMessageFormat / TestReplicationScenarios fail in recent precommit tests.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
Labels: tests passed

#1950 HIVE-24746: PTF: TimestampValueBoundaryScanner can be optimised during range computation
  itests/hive-jmh/src/main/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScannerBench.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/ptf/TestValueBoundaryScanner.java
Labels: tests unstable

#2160 HIVE-24993: AssertionError when referencing ROW__ID.writeId
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/row__id_2.q
  ql/src/test/results/clientpositive/llap/row__id_2.q.out
Labels: tests passed

#2168 HIVE-24981
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
  ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigrationControlConfig.java
  ql/src/test/org/apache/hadoop/hive/ql/util/TestHiveStrictManagedMigration.java
  ql/src/test/resources/hsmm/hsmm_cfg_01.yaml
  ql/src/test/resources/hsmm/hsmm_cfg_02.yaml
Labels: tests passed

#2138 HIVE-24958: Create new iceberg-catalog module
  iceberg-catalog/checkstyle/checkstyle-suppressions.xml
  iceberg-catalog/checkstyle/checkstyle.xml
  iceberg-catalog/pom.xml
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/ClientPool.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveClientPool.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreUtil.java
  iceberg-catalog/src/main/java/org/apache/iceberg/hive/RuntimeMetaException.java
  iceberg-catalog/src/test/java/org/apache/iceberg/AssertHelpers.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableBaseTest.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/ScriptRunner.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestClientPool.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveClientPool.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
  iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveTableConcurrency.java
  iceberg-handler/pom.xml
  iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  packaging/pom.xml
  packaging/src/main/assembly/src.xml
  pom.xml
Labels: tests passed

#2063 HIVE-24876: Disable /logconf.jsp page in HS2 web UI if the user doesn…
  service/src/resources/hive-webapps/hiveserver2/logconf.jsp
Labels: tests passed

#2119 HIVE-24854: Incremental MV refresh in presence of update/delete operations
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveRelOptMaterialization.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptMaterializationValidator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttle.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttleImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveTableScan.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/ColumnPropagationException.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveJoinInsertDeleteIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveJoinInsertIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveRowIsDeletedPropagator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/fetch_deleted_rows.q
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_5.q
  ql/src/test/results/clientpositive/llap/fetch_deleted_rows.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out
Labels: tests passed

#2158 HIVE-24985: Create new metrics about locks
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2165 HIVE-25001: Improvement for some debug-logging guards
  llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/SerDeEncodedDataReader.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
Labels: tests pending

#2166 HIVE-24997. HPL/SQL udf doesn't work in tez container mode (amagyar)
  hplsql/src/main/java/org/apache/hive/hplsql/Arguments.java
  hplsql/src/main/java/org/apache/hive/hplsql/Exec.java
  hplsql/src/main/java/org/apache/hive/hplsql/executor/QueryExecutor.java
  hplsql/src/main/java/org/apache/hive/hplsql/udf/Udf.java
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
  service/src/java/org/apache/hive/service/cli/operation/ExecuteStatementOperation.java
Labels: tests passed

#2179 HIVE-25015: Port Iceberg unreleased Hive fixes to the iceberg module
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/CachedClientPool.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/ClientPool.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/ClientPoolImpl.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveClientPool.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestCachedClientPool.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestClientPoolImpl.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveClientPool.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/CatalogLoader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestCatalogs.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestInputFormatReaderDeletes.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSerDe.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerLocalScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/patched-iceberg-api/src/main/java/org/apache/iceberg/exceptions/CommitStateUnknownException.java
  iceberg/patched-iceberg-core/pom.xml
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/BaseTable.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/CatalogProperties.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/SnapshotProducer.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/SnapshotSummary.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/StaticTableOperations.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/TableProperties.java
Labels: tests passed

#2180 HIVE-25016: Error while running repl dump with with db regex
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/EximUtil.java
Labels: tests passed

#2111 HIVE-24928: In case of non-native tables use basic statistics from HiveStorageHandler
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMRTableScan1.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ProcessAnalyzeTable.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/spark/SparkProcessAnalyzeTable.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsNoJobTask.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java
Labels: tests passed

#2175 HIVE-25009: Compaction worker and initiator version check can cause N…
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#2181 HIVE-25017: Fix response in GetLatestCommittedCompaction
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2183 HIVE-25019: Rename metrics that have spaces in the name
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
Labels: tests passed

#2129 Backport HIVE-24851: Fix reader leak in AvroGenericRecordReader to branch-3.1
  ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
Labels: tests unstable

#2171 HIVE-25005: Add abstract class for HMS API interface with default implementation
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/AbstractThriftHiveMetastore.java
Labels: tests unstable

#2188 HIVE-25027: Hide Iceberg module behind a profile
  Jenkinsfile
  packaging/pom.xml
  pom.xml
Labels: tests passed

#2156 HIVE-24980: Add timeout for failed and "not initiated" compaction cleanup
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#2159 HIVE-24986: Support aggregates on columns present in rollups
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientnegative/groupby_cube2.q
  ql/src/test/queries/clientnegative/groupby_rollup1.q
  ql/src/test/queries/clientnegative/groupby_rollup2.q
  ql/src/test/queries/clientpositive/groupby_rollup2.q
  ql/src/test/queries/clientpositive/vector_groupby_rollup2.q
  ql/src/test/results/clientnegative/groupby_cube2.q.out
  ql/src/test/results/clientnegative/groupby_rollup1.q.out
  ql/src/test/results/clientnegative/groupby_rollup2.q.out
  ql/src/test/results/clientpositive/llap/groupby_rollup2.q.out
  ql/src/test/results/clientpositive/llap/vector_groupby_rollup2.q.out
Labels: tests passed

#2167 HIVE-25002: modify condition for target of replication in statsUpdaterThread and PartitionManagementTask
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/LoadDatabase.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUpdaterThread.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartitionManagementTask.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionManagement.java
Labels: tests passed

#2154 HIVE-24978. Optimise number of DROP_PARTITION events created.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AlterTableDropPartitionOperation.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/DropPartitionEvent.java
Labels: tests passed

#2198 HIVE-25038: Increase Iceberg test timeout and remove mr tests
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Labels: tests passed

#1778 HIVE-24524: LLAP ShuffleHandler: upgrade to netty4
  hbase-handler/pom.xml
  hcatalog/core/pom.xml
  hcatalog/hcatalog-pig-adapter/pom.xml
  kryo-registrator/pom.xml
  llap-server/pom.xml
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCopyLocalJars.java
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/FadvisedChunkedFile.java
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/FadvisedFileRegion.java
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
  llap-server/src/test/org/apache/hadoop/hive/llap/shufflehandler/TestShuffleHandler.java
  pom.xml
  ql/pom.xml
  serde/pom.xml
  shims/0.23/pom.xml
  spark-client/pom.xml
  standalone-metastore/pom.xml
  upgrade-acid/pre-upgrade/pom.xml
Labels: stale, tests passed

#2139 HIVE-24954: MetastoreTransformer is disabled during testing
  data/conf/hivemetastore-site.xml
  data/conf/llap/hivemetastore-site.xml
  ql/src/test/queries/clientpositive/translated_external_qopt.q
  ql/src/test/results/clientpositive/llap/translated_external_qopt.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/NonCatCallsWithCatalog.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTxns.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreEventListener.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionManagement.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRetryingHMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Labels: tests passed

#2192 HIVE-25029: Remove travis builds
  .travis.yml
Labels: tests passed

#2190 HIVE-25028: Hive: Select query with IS operator producing unexpected result
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/test/queries/clientpositive/precedence_is.q
  ql/src/test/results/clientnegative/subquery_subquery_chain.q.out
  ql/src/test/results/clientpositive/llap/precedence_is.q.out
  ql/src/test/results/clientpositive/llap/sharedwork.q.out
Labels: tests passed

#2193 HIVE-25010: Create TestIcebergCliDriver and TestIcebergNegativeCliDriver
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  data/conf/iceberg/hive-site.xml
  data/conf/iceberg/tez-site.xml
  iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_failure.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_failure.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table.q.out
  itests/pom.xml
  itests/qtest/pom.xml
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestIcebergCliDriver.java
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestIcebergNegativeCliDriver.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#2177 HIVE-25012: Parsing table alias is failing if query has table properties specified
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#2186 HIVE-24957 HIVE-24999: Inefficient & wrong CBO plans in the presence of subqueries
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/Bug.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/CorrelateProjectExtractor.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/FilterFlattenCorrelatedConditionRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelDecorrelator.java
  ql/src/test/queries/clientpositive/masking_12.q
  ql/src/test/queries/clientpositive/masking_3.q
  ql/src/test/queries/clientpositive/masking_4.q
  ql/src/test/queries/clientpositive/subquery_complex_correlation_predicates.q
  ql/src/test/queries/clientpositive/subquery_in_invalid_intermediate_plan.q
  ql/src/test/queries/clientpositive/subquery_notexists.q
  ql/src/test/queries/clientpositive/subquery_notin.q
  ql/src/test/results/clientpositive/llap/lineage3.q.out
  ql/src/test/results/clientpositive/llap/masking_12.q.out
  ql/src/test/results/clientpositive/llap/masking_3.q.out
  ql/src/test/results/clientpositive/llap/masking_4.q.out
  ql/src/test/results/clientpositive/llap/subquery_ANY.q.out
  ql/src/test/results/clientpositive/llap/subquery_complex_correlation_predicates.q.out
  ql/src/test/results/clientpositive/llap/subquery_corr.q.out
  ql/src/test/results/clientpositive/llap/subquery_in.q.out
  ql/src/test/results/clientpositive/llap/subquery_in_having.q.out
  ql/src/test/results/clientpositive/llap/subquery_in_invalid_intermediate_plan.q.out
  ql/src/test/results/clientpositive/llap/subquery_multi.q.out
  ql/src/test/results/clientpositive/llap/subquery_notexists.q.out
  ql/src/test/results/clientpositive/llap/subquery_notin.q.out
  ql/src/test/results/clientpositive/llap/subquery_notin_having.q.out
  ql/src/test/results/clientpositive/llap/subquery_scalar.q.out
  ql/src/test/results/clientpositive/llap/subquery_select.q.out
  ql/src/test/results/clientpositive/llap/subquery_views.q.out
  ql/src/test/results/clientpositive/llap/tez_smb_reduce_side.q.out
Labels: tests passed

#2173 HIVE-25008: Migrate hive table data into Iceberg format.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/DataUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/test/queries/negative/alter_acid_table_to_iceberg_failure.q
  iceberg/iceberg-handler/src/test/queries/negative/alter_managed_table_to_iceberg_failure.q
  iceberg/iceberg-handler/src/test/queries/positive/alter_multi_part_table_to_iceberg.q
  iceberg/iceberg-handler/src/test/queries/positive/alter_part_table_to_iceberg.q
  iceberg/iceberg-handler/src/test/queries/positive/alter_table_to_iceberg.q
  iceberg/iceberg-handler/src/test/results/negative/alter_acid_table_to_iceberg_failure.q.out
  iceberg/iceberg-handler/src/test/results/negative/alter_managed_table_to_iceberg_failure.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
  itests/qtest/pom.xml
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
Labels: tests passed

#2161 HIVE-25006: Commit Iceberg writes in HiveMetaHook instead of TezAM
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
Labels: tests passed

#2182 HIVE-25018: Create new metrics about Initiator / Cleaner failures
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/ThrowingTxnHandler.java
Labels: tests passed

#2210 HIVE-25051: Callers can access uninitialized MessageBuilder instance causing NPE
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageBuilder.java
Labels: tests passed

#1974 HIVE-24772: Revamp Server Request Error Logging
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbcWithMiniKdc.java
  service/src/java/org/apache/hive/service/cli/HiveSQLException.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
  service/src/test/org/apache/hive/service/cli/TestHiveSQLException.java
Labels: tests passed

#2153 HIVE-23820: [HS2] Send tableId in request for get_table_request API
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreClient.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/IHMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#2197 HIVE-25035. Allow creating single copy tasks for configured paths during external table replication.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplExternalTables.java
Labels: tests passed

#2213 HIVE-25052: Fix issue when inserting empty result set into Iceberg table
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Labels: tests passed

#2212 HIVE-25050: Disable 'hive.metastore.acid.truncate.usebase' config as it's introducing backward incompatible change
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
  ql/src/test/results/clientpositive/llap/acid_stats3.q.out
  ql/src/test/results/clientpositive/llap/check_constraint.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#2206 HIVE-25047: Remove unused fields/methods and deprecated calls in HiveProject
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveProject.java
Labels: tests passed

#2108 HIVE-24914: Improve LLAP scheduling by only traversing hosts with capacity
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
  llap-tez/src/test/org/apache/hadoop/hive/llap/tezplugins/TestLlapTaskSchedulerService.java
Labels: tests passed

#2178 HIVE-25007: Implement insert overwrite for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
Labels: tests passed

#2137 HIVE-24962: Implement partition pruning for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DynamicPartitionPruner.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/DynamicPartitionPruningOptimization.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/DynamicPruningEventDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDynamicPartitionPruner.java
Labels: tests passed

#2123 HIVE-24472: Optimize LlapTaskSchedulerService::preemptTasksFromMap
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
Labels: tests passed

#2215 HIVE-25049: LlapDaemon preemption should not be triggered for same Vertex tasks
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java
  llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorTestHelpers.java
  llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestTaskExecutorService.java
  llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/comparator/TestShortestJobFirstComparator.java
Labels: tests passed

#2196 HIVE-24992: Incremental rebuild of MV having aggregate in presence of delete operation
  ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFieldTrimmerRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveHepExtractRelNodeRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRuleBase.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateInsertDeleteIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateInsertIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveJoinInsertDeleteIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveRowIsDeletedPropagator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/MaterializedViewRewritingRelVisitor.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_6.q
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6.q.out
Labels: tests passed

#2163 HIVE-24998: IS [NOT] DISTINCT FROM failing with SemanticException
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRexExecutorImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ExprNodeConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
  ql/src/test/queries/clientnegative/cbo_fallback_never_semantic_exception.q
  ql/src/test/queries/clientpositive/explainuser_1.q
  ql/src/test/queries/clientpositive/is_distinct_from.q
  ql/src/test/queries/clientpositive/join_is_not_distinct_from.q
  ql/src/test/queries/clientpositive/join_nullsafe.q
  ql/src/test/queries/clientpositive/semijoin6.q
  ql/src/test/queries/clientpositive/tez_union_group_by.q
  ql/src/test/results/clientnegative/cbo_fallback_never_semantic_exception.q.out
  ql/src/test/results/clientpositive/llap/cbo_fallback_always_semantic_exception.q.out
  ql/src/test/results/clientpositive/llap/cbo_fallback_conservative_semantic_exception.q.out
  ql/src/test/results/clientpositive/llap/cbo_fallback_test_semantic_exception.q.out
  ql/src/test/results/clientpositive/llap/compare_cols_null.q.out
  ql/src/test/results/clientpositive/llap/explainuser_1.q.out
  ql/src/test/results/clientpositive/llap/is_distinct_from.q.out
  ql/src/test/results/clientpositive/llap/join_by_range_rule_not_null.q.out
  ql/src/test/results/clientpositive/llap/join_is_not_distinct_from.q.out
  ql/src/test/results/clientpositive/llap/join_nullsafe.q.out
  ql/src/test/results/clientpositive/llap/orc_predicate_pushdown.q.out
  ql/src/test/results/clientpositive/llap/parquet_predicate_pushdown.q.out
  ql/src/test/results/clientpositive/llap/semijoin6.q.out
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/tez_union_group_by.q.out
  ql/src/test/results/clientpositive/llap/udf_equal.q.out
  ql/src/test/results/clientpositive/llap/vector_nullsafe_join.q.out
Labels: tests passed

#2223 HIVE-25059. Alter event is converted to rename during replication.
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AlterTableHandler.java
Labels: tests passed

#2226 HIVE-25064
  iceberg/iceberg-catalog/pom.xml
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/CachedClientPool.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
  iceberg/iceberg-handler/pom.xml
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/DataUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java
  iceberg/iceberg-shading/pom.xml
  iceberg/patched-iceberg-api/pom.xml
  iceberg/patched-iceberg-core/pom.xml
  iceberg/pom.xml
  packaging/pom.xml
Labels: tests passed

#2230 HIVE-25065: Implement ALTER TABLE for setting iceberg table properties
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: tests passed

#2065 HIVE-24201: WorkloadManager can support delayed move if destination pool does not have enough sessions
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/KillMoveTriggerActionHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WmTezSession.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestWorkloadManager.java
Labels: tests pending

#2229 HIVE-24806: Compactor: Initiator should lazy evaluate findUserToRunAs()
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
Labels: tests passed

#2233 HIVE-25076: Get number of write tasks from jobConf for Iceberg commits
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Labels: tests passed
