Repository apache/hive, pull requests merged in 2022-12, with the labels that each got.

#3819 HIVE-26796: Tests in modules dependent on curator-test are skipped silently
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#3799 HIVE-26767: Fix HIVE-24120 to work for custom databases
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
Labels: tests passed

#3827 Increase Split to 22.
  Jenkinsfile
Labels: tests passed

#3813 HIVE-26789: Add UserName in CallerContext for queries.
  cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  service/src/java/org/apache/hive/service/cli/operation/Operation.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
  service/src/java/org/apache/hive/service/cli/operation/hplsql/HplSqlOperation.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShims.java
Labels: tests passed

#3761 HIVE-26737: Subquery returning wrong results when database has materialized views
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HivePlannerContext.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/correlation/CorrelationInfoVisitor.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/correlation/HiveCorrelationInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveFilter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveProject.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBSubQuery.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SubQueryUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/TestCBORuleFiredOnlyOnce.java
  ql/src/test/queries/clientpositive/subquery_with_corr_and_mv.q
  ql/src/test/results/clientpositive/llap/subquery_scalar.q.out
  ql/src/test/results/clientpositive/llap/subquery_with_corr_and_mv.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query32.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query92.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query32.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query92.q.out
Labels: tests passed

#3800 HIVE-26683: Sum windowing function returns wrong value when all nulls.
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFSum.java
  ql/src/test/queries/clientpositive/windowing_sum_following_null.q
  ql/src/test/results/clientpositive/llap/windowing_sum_following_null.q.out
Labels: tests passed

#3828 HIVE-26801: Query based compaction fails on tables having columns with keywords(i.e. row in this case)
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
Labels: tests passed

#3830 Hive26580: SHOW COMPACTIONS should support ordering and limiting functionality in filtering options
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionPoolOnTezTest.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseShowCompactions.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/results/clientpositive/llap/dbtxnmgr_compact1.q.out
  ql/src/test/results/clientpositive/llap/dbtxnmgr_showlocks.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ShowCompactRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3820 HIVE-26692: Check for the expected thrift version before compiling
  pom.xml
Labels: tests passed

#3831 HIVE-26758: Allow use scratchdir for staging final job
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#3741 HIVE-26392 Move StringableMap tests into a dedicated test class
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestStringableList.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestStringableMap.java
Labels: tests passed

#3832 HIVE-26770: Make end of loop compaction logs appear more selectively and reduce code duplication
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#3626 HIVE-26569: Support renewal and recreation of LLAP_TOKENs
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-client/src/java/org/apache/hadoop/hive/llap/security/LlapTokenClient.java
  llap-client/src/java/org/apache/hadoop/hive/llap/security/LlapTokenLocalClientImpl.java
  llap-client/src/java/org/apache/hadoop/hive/llap/tez/LlapProtocolClientProxy.java
  llap-common/src/java/org/apache/hadoop/hive/llap/AsyncPbRpcProxy.java
  llap-common/src/java/org/apache/hadoop/hive/llap/impl/LlapManagementProtocolClientImpl.java
  llap-common/src/java/org/apache/hadoop/hive/llap/security/LlapServerSecurityInfo.java
  llap-common/src/java/org/apache/hadoop/hive/llap/security/SecretManager.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/DefaultLlapTokenManager.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/DummyTokenManager.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapProtocolServerImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapTokenManager.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskCommunicator.java
Labels: tests passed, stale

#3843 HIVE-26817: Set column names in result schema when plan has Values root
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveValues.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/PlanModifierForASTConv.java
  ql/src/test/queries/clientpositive/empty_result.q
  ql/src/test/results/clientpositive/llap/empty_result.q.out
  ql/src/test/results/clientpositive/llap/empty_result_outerjoin.q.out
Labels: tests passed

#3837 HIVE-26811: SharedWorkOptimizer: take the union of virtual columns in mergeable TableScans
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_merge_schema.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_merge_schema.q.out
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
Labels: tests passed

#3823 HIVE-26578: Enable Iceberg storage format for materialized views
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc2.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc2.q.out
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
Labels: tests passed

#3848 HIVE-26821: Fetch task caching should only depend on fetch task conversion
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchTask.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SimpleFetchOptimizer.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
Labels: tests passed

#3545 HIVE-26247: Filter out results 'show connectors' on HMS server-side
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/filtercontext/DataConnectorFilterContext.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestFilterHooks.java
Labels: tests passed, stale

#3821 HIVE-26799: Make authorizations on custom UDFs involved in tables/view configurable.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
  ql/src/test/queries/clientpositive/authorization_functions_in_views.q
  ql/src/test/results/clientpositive/llap/authorization_functions_in_views.q.out
Labels: tests passed

#3567 HIVE-26509: Introduce dynamic leader election in HMS
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/MetastoreHousekeepingLeaderTestBase.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreHousekeepingLeader.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreHousekeepingLeaderEmptyConfig.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreHousekeepingNonLeader.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreLeaseLeader.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreLeaseNonLeader.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUpdaterThread.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/AuditLeaderListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/CMClearer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/CompactorPMF.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/CompactorTasks.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/HostLeaderElection.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/HouseKeepingTasks.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElection.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionContext.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionFactory.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderException.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaseLeaderElection.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/StatsUpdaterTask.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/leader/TestLeaderElection.java
Labels: tests passed

#3865 HIVE-26850: Added columns info of source table for alter view query
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AlterViewAsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateViewAnalyzer.java
Labels: tests passed

#3870 HIVE-26866 : Backport of HIVE-25795
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingLayout.java
Labels: tests unstable

#3862 HIVE-26699: Iceberg: S3 fadvise can hurt JSON parsing significantly in DWX.
  iceberg/iceberg-shading/pom.xml
  iceberg/patched-iceberg-core/pom.xml
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java
Labels: tests passed

#3812 HIVE-26788: Update stats of table/partition using noscan operation when stats autogather is enabled
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#3871 HIVE-26867 : Backport of HIVE-24816
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniDruidCliDriver.java
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniDruidKafkaCliDriver.java
  pom.xml
  ql/src/test/queries/clientpositive/druid_timestamptz2.q
  ql/src/test/queries/clientpositive/druidmini_extractTime.q
  ql/src/test/queries/clientpositive/druidmini_floorTime.q
  ql/src/test/queries/clientpositive/druidmini_mv.q
  ql/src/test/queries/clientpositive/druidmini_test1.q
  ql/src/test/queries/clientpositive/druidmini_test_alter.q
  ql/src/test/queries/clientpositive/druidmini_test_insert.q
  ql/src/test/queries/clientpositive/druidmini_test_ts.q
  standalone-metastore/pom.xml
  testutils/ptest2/pom.xml
Labels: tests unstable

#3811 HIVE-26787: Pushdown Timestamp data type to metastore via directsql/JDO
  ql/src/test/results/clientpositive/llap/temp_table_partition_timestamp.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/Filter.g
Labels: tests passed

#3875 HIVE-26848: Ozone: LOAD data fails in case of move across buckets.
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
  common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
Labels: tests failed

#3876 HIVE-26871: TestCrudCompactorOnTez is flaky after HIVE-26479
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveProtoLoggingHook.java
Labels: tests passed

#3877 HIVE-26873: Whiltelist iceberg configs for sql std authorization
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests passed

#3806 HIVE-26754 - Implement array_distinct UDF to return an array after re…
  data/files/test_null_array.csv
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayDistinct.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArray.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayDistinct.java
  ql/src/test/queries/clientpositive/udf_array_distinct.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_distinct.q.out
Labels: tests passed

#3890 HIVE-26884: Iceberg: V2 Vectorization returns wrong results with deletes.
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
Labels: tests passed

#3885 HIVE-26879: Backport of HIVE-23323: Add qsplits profile
  itests/bin/generate-cli-splits.sh
  itests/qtest-spark/pom.xml
  itests/qtest-spark/src/test/java/org/apache/hadoop/hive/cli/TestMiniSparkOnYarnCliDriver.java
  itests/qtest-spark/src/test/java/org/apache/hadoop/hive/cli/TestSparkCliDriver.java
  itests/qtest/pom.xml
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestCliDriver.java
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestEncryptedHDFSCliDriver.java
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniLlapCliDriver.java
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniLlapLocalCliDriver.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/SplitSupport.java
  itests/util/src/test/java/org/apache/hadoop/hive/cli/control/TestSplitSupport.java
  itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/SplitSupportDummy.java
  itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/split0/SplitSupportDummy.java
  itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/split125/SplitSupportDummy.java
Labels: tests unstable

#3889 HIVE-26883 : Revert "HIVE-21872: Bucketed tables that load data"
  ql/src/java/org/apache/hadoop/hive/ql/parse/spark/SparkCompiler.java
  ql/src/test/queries/clientpositive/auto_sortmerge_join_1.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_11.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_12.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_16.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_2.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_3.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_4.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_5.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_7.q
  ql/src/test/queries/clientpositive/auto_sortmerge_join_8.q
  ql/src/test/queries/clientpositive/bucketcontext_1.q
  ql/src/test/queries/clientpositive/bucketcontext_2.q
  ql/src/test/queries/clientpositive/bucketcontext_3.q
  ql/src/test/queries/clientpositive/bucketcontext_4.q
  ql/src/test/queries/clientpositive/bucketcontext_5.q
  ql/src/test/queries/clientpositive/bucketcontext_6.q
  ql/src/test/queries/clientpositive/bucketcontext_7.q
  ql/src/test/queries/clientpositive/bucketcontext_8.q
  ql/src/test/queries/clientpositive/bucketizedhiveinputformat_auto.q
  ql/src/test/results/clientpositive/bucketcontext_1.q.out
  ql/src/test/results/clientpositive/bucketcontext_2.q.out
  ql/src/test/results/clientpositive/bucketcontext_3.q.out
  ql/src/test/results/clientpositive/bucketcontext_4.q.out
  ql/src/test/results/clientpositive/bucketcontext_5.q.out
  ql/src/test/results/clientpositive/bucketcontext_6.q.out
  ql/src/test/results/clientpositive/bucketcontext_7.q.out
  ql/src/test/results/clientpositive/bucketcontext_8.q.out
  ql/src/test/results/clientpositive/bucketizedhiveinputformat_auto.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_1.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_11.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_12.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_16.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_2.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_3.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_4.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_5.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_7.q.out
  ql/src/test/results/clientpositive/llap/auto_sortmerge_join_8.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_1.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_12.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_16.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_16.q.out_spark
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_2.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_3.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_4.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_5.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_7.q.out
  ql/src/test/results/clientpositive/spark/auto_sortmerge_join_8.q.out
Labels: tests unstable

#3884 HIVE-26878 : Ignore TestJdbcWithMiniLlapVectorArrow
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapArrow.java
Labels: tests unstable

#3892 HIVE-26885: Iceberg: Parquet Vectorized V2 reads fails with NPE.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchIterator.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java
Labels: tests passed

#3815 HIVE-26702: Backport HIVE-17317 (DBCP and HikariCP property configuration support) to 3.2.0.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestRestrictedList.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/datasource/DataSourceProviderFactory.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
Labels: tests unstable
