Repository apache/hive, pull requests merged in 2022-04, with the labels that each got.

#3160 HIVE-26098 : Duplicate path/Jar in hive.aux.jars.path or hive.reloadable.aux.jars.path causing IllegalArgumentException
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/test/queries/clientpositive/whroot_external1.q
  ql/src/test/results/clientpositive/llap/whroot_external1.q.out
Labels: tests passed

#3163 HIVE-26101: Port Iceberg Hive fix - Hive: Avoid recursive listing in HiveCatalog#renameTable
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreUtil.java
Labels: tests passed

#3138 HIVE-26062: Make sure that running 4.0.0-alpha-2 above 4.0.0-alpha-1 …
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreSchemaInfo.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreSchemaInfo.java
Labels: tests passed

#3164 HIVE-26103: Port Iceberg fixes to the iceberg module
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/checkstyle/checkstyle.xml
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveClientPool.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/Deserializer.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSchemaEvolution.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStatistics.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerLocalScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerTimezone.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestIcebergInputFormats.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/iceberg-handler/src/test/queries/positive/alter_multi_part_table_to_iceberg.q
  iceberg/iceberg-handler/src/test/queries/positive/alter_part_table_to_iceberg.q
  iceberg/iceberg-handler/src/test/queries/positive/alter_table_to_iceberg.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_as_fileformat.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_by_iceberg.q
  iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_force_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/truncate_partitioned_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q.out
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out
Labels: tests passed

#3171 HIVE-26109: Upgrade groovy to 2.4.21 due to CVE
  pom.xml
Labels: tests passed

#3166 HIVE-26105 : Show columns shows extra values if column comments contains specific Chinese character
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/show/ShowColumnsOperation.java
  ql/src/test/queries/clientpositive/show_columns.q
  ql/src/test/results/clientpositive/llap/show_columns.q.out
Labels: tests passed

#3174 HIVE-26110
  iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SortedDynPartitionOptimizer.java
Labels: tests passed

#3015 HIVE-25934: Non blocking RENAME PARTITION implementation
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/rename/AlterTableRenamePartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/RenamePartitionRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/RenamePartitionRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#3169 HIVE-25728: ParseException while gathering Column Stats
  ql/src/java/org/apache/hadoop/hive/ql/parse/ColumnStatsSemanticAnalyzer.java
  ql/src/test/queries/clientpositive/columnstats_columnname_parse.q
  ql/src/test/results/clientpositive/llap/columnstats_columnname_parse.q.out
Labels: tests passed

#3177 HIVE-26116: Fix handling of compaction requests originating from aborted dynamic partition queries in Initiator
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
Labels: tests passed

#3178 addendum for HIVE-25967
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java
Labels: tests passed

#3180 HIVE-26118: [Standalone beeline] Jar name mismatch in assembly (Naveen Gangam)
  packaging/src/main/assembly/beeline.xml
Labels: tests unstable

#3158 HIVE-26096: Select on single column MultiDelimitSerDe table throws AIOBE
  ql/src/test/queries/clientpositive/serde_multi_delimit.q
  ql/src/test/results/clientpositive/llap/serde_multi_delimit.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyStruct.java
Labels: tests passed

#3157 HIVE-25492: Major query-based compaction is skipped if partition is empty
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
Labels: tests passed

#3168 HIVE-26093 Deduplicate org.apache.hadoop.hive.metastore.annotation package-info.java
  .gitignore
  pom.xml
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetastoreVersionInfo.java
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/main/resources/saveVersion.sh
  standalone-metastore/pom.xml
Labels: tests passed

#3014 HIVE-25941: Long compilation time of complex query due to analysis fo…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveRelOptMaterialization.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveMaterializedViewASTSubQueryRewriteRexShuttle.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveMaterializedViewASTSubQueryRewriteShuttle.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CBOPlan.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_3.q
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_6.q
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_8.q
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_3.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_8.q.out
Labels: tests passed

#3181 HIVE-26121: Hive transaction rollback should be thread-safe
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHiveServer2Acid.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverState.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
Labels: tests passed

#3202 HIVE-26133: Insert overwrite on Iceberg tables can result in duplicate entries after partition evolution
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
Labels: tests passed

#3211 HIVE-26141: Fix vector_ptf_part_simple_all_datatypes source file.
  data/files/vector_ptf_part_simple_all_datatypes.txt
  ql/src/test/queries/clientpositive/vector_ptf_bounded_start.q
  ql/src/test/results/clientpositive/llap/vector_ptf_bounded_start.q.out
Labels: tests passed

#2555 HIVE-25416 : Hive metastore memory leak because datanucleus-api-jdo bug
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#2993 Hive 25921: Overwrite table metadata for bootstraped tables.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadPartitions.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadTable.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ImportTableDesc.java
Labels: tests passed

#3216 HIVE-26146: Handle missing hive.acid.key.index in the fixacidkeyindex…
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/FixAcidKeyIndex.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcOutputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRecordUpdater.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestFixAcidKeyIndex.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
Labels: tests passed

#3203 HIVE-26137 Optimized transfer of Iceberg residual expressions from AM to execution
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestInputFormatReaderDeletes.java
Labels: tests passed

#3187 HIVE-26074: PTF Vectorization: BoundaryScanner for varchar.
  data/files/vector_ptf_part_simple_all_datatypes.txt
  ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/ptf/TestValueBoundaryScanner.java
  ql/src/test/queries/clientpositive/vector_ptf_bounded_start.q
  ql/src/test/results/clientpositive/llap/vector_ptf_bounded_start.q.out
Labels: tests passed

#3225 HIVE-26156: Iceberg delete writer should handle deleting from old partition specs
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_avro.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_parquet.q.out
Labels: tests passed

#3230 HIVE-26161 Use Hive's ORC dependency version when producing file footer for Iceberg
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
Labels: tests passed

#3238 HIVE-26171: HMSHandler get_all_tables method can not retrieve tables from remote database
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#3236 HIVE-26169: Set non-vectorized mode as default when accessing iceberg tables in avro fileformat
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
Labels: tests passed

#3205 HIVE-26135: Invalid Anti join conversion may cause missing results
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveAntiSemiJoinRule.java
  ql/src/test/queries/clientpositive/antijoin_conversion.q
  ql/src/test/results/clientpositive/llap/antijoin_conversion.q.out
Labels: tests passed

#3176 HIVE-26114: Fix jdbc connection hivesrerver2 using dfs command with prefix space will cause exception
  service/src/java/org/apache/hive/service/cli/operation/HiveCommandOperation.java
  service/src/test/org/apache/hive/service/cli/operation/TestCommandWithSpace.java
Labels: tests passed

#3099 HIVE-26032: Upgrade cron-utils to 9.1.6
  standalone-metastore/pom.xml
Labels: tests passed

#3200 HIVE-26131: Incorrect OutputFormat when describing jdbc connector table
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
Labels: tests passed

#3167 HIVE-25091: Implemented connector provider for MSSQL and Oracle
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/JDBCConnectorProviderFactory.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/DerbySQLConnectorProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MSSQLConnectorProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MySQLConnectorProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/OracleConnectorProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/PostgreSQLConnectorProvider.java
Labels: tests passed

#3250 HIVE-26180: Change MySQLConnectorProvider driver from mariadb to mysql
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MySQLConnectorProvider.java
Labels: tests failed

#3246 HIVE-26160: Materialized View rewrite does not check tables scanned in sub-query expressions
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_9.q
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_9.q.out
Labels: tests passed

#3252 HIVE-25758: OOM due to recursive application of CBO rules (javadoc fix)
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
Labels: tests pending

#3223 HIVE-26155: Create a new connection pool for compaction
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3234 HIVE-26167: QueryStateMap in SessionState is not maintained correctly
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
Labels: tests passed
