Repository apache/hive, pull requests merged in 2022-06, with the labels that each got.

#2978 HIVE-25907: IOW Directory queries fails to write data to final path when query result cache is enabled
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBParseInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/insert_overwrite_directory.q
  ql/src/test/results/clientpositive/llap/insert_overwrite_directory.q.out
Labels: tests passed

#3332 HIVE-26274: No vectorization if query has upper case window function
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
  ql/src/test/queries/clientpositive/vector_ptf_1.q
  ql/src/test/results/clientpositive/llap/llap_smb_ptf.q.out
  ql/src/test/results/clientpositive/llap/semijoin2.q.out
  ql/src/test/results/clientpositive/llap/vector_ptf_1.q.out
Labels: tests passed

#3334 HIVE-25421: Fallback from vectorization when reading Iceberg's time columns
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
Labels: tests passed

#3324 HIVE-26264: Iceberg integration: Fetch virtual columns on demand
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_virtualcol.q
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_mixed.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_virtualcol.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_mixed.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SMBMapJoinOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/MapredLocalTask.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ProjectionPusher.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/FileSinkDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/HiveCustomStorageHandlerUtils.java
  serde/src/java/org/apache/hadoop/hive/serde2/ColumnProjectionUtils.java
Labels: tests passed

#3287 HIVE-26228: Implement Iceberg table rollback feature
  hbase-handler/src/test/results/negative/hbase_ddl.q.out
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergRollback.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTimeTravel.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/iceberg-handler/src/test/queries/positive/rollback_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/rollback_iceberg_table.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractBaseAlterTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
  ql/src/test/results/clientnegative/alter_non_native.q.out
Labels: tests passed

#3337 HIVE-26282: Improve iceberg CTAS error message for unsupported types
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
Labels: tests passed

#3325 HIVE-26267: Addendum to HIVE-26107: perpared statement is not working on Postgres
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3281 HIVE-26217: Make CTAS use Direct Insert Semantics
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnNoBuckets.java
  ql/src/test/queries/clientpositive/ctas_direct.q
  ql/src/test/queries/clientpositive/ctas_direct_with_specified_locations.q
  ql/src/test/queries/clientpositive/ctas_direct_with_suffixed_locations.q
  ql/src/test/queries/clientpositive/ctas_direct_with_transformers.q
  ql/src/test/results/clientpositive/llap/clusterctas.q.out
  ql/src/test/results/clientpositive/llap/ctas.q.out
  ql/src/test/results/clientpositive/llap/ctas_direct.q.out
  ql/src/test/results/clientpositive/llap/ctas_direct_with_specified_locations.q.out
  ql/src/test/results/clientpositive/llap/ctas_direct_with_suffixed_locations.q.out
  ql/src/test/results/clientpositive/llap/ctas_direct_with_transformers.q.out
  ql/src/test/results/clientpositive/llap/semijoin_reddedup.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
Labels: tests passed

#3331 HIVE-26266: Column information is not present in lineage for CTAS whe…
  itests/hive-blobstore/src/test/results/clientpositive/ctas_blobstore_to_blobstore.q.out
  itests/hive-blobstore/src/test/results/clientpositive/ctas_hdfs_to_blobstore.q.out
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/results/clientnegative/ctas_noemptyfolder.q.out
  ql/src/test/results/clientpositive/encrypted/encryption_ctas.q.out
  ql/src/test/results/clientpositive/llap/autoColumnStats_7.q.out
  ql/src/test/results/clientpositive/llap/crtseltbl_serdeprops.q.out
  ql/src/test/results/clientpositive/llap/ctas_direct_with_specified_locations.q.out
  ql/src/test/results/clientpositive/llap/ctas_direct_with_transformers.q.out
  ql/src/test/results/clientpositive/llap/ctas_uses_table_location.q.out
  ql/src/test/results/clientpositive/llap/foldts.q.out
  ql/src/test/results/clientpositive/llap/masking_10.q.out
  ql/src/test/results/clientpositive/llap/masking_9.q.out
  ql/src/test/results/clientpositive/llap/masking_reserved.q.out
  ql/src/test/results/clientpositive/llap/mm_cttas.q.out
  ql/src/test/results/clientpositive/llap/mm_loc_ctas.q.out
  ql/src/test/results/clientpositive/llap/parquet_thrift_array_of_primitives.q.out
  ql/src/test/results/clientpositive/llap/results_cache_temptable.q.out
  ql/src/test/results/clientpositive/llap/stats_partial_size.q.out
  ql/src/test/results/clientpositive/llap/temp_table.q.out
  ql/src/test/results/clientpositive/llap/temp_table_gb1.q.out
  ql/src/test/results/clientpositive/llap/temp_table_join1.q.out
  ql/src/test/results/clientpositive/llap/temp_table_llap_partitioned.q.out
  ql/src/test/results/clientpositive/llap/temp_table_parquet_mixed_partition_formats2.q.out
  ql/src/test/results/clientpositive/llap/temp_table_partition_ctas.q.out
  ql/src/test/results/clientpositive/llap/temp_table_partition_decode_name.q.out
  ql/src/test/results/clientpositive/llap/temp_table_partition_special_char.q.out
  ql/src/test/results/clientpositive/llap/temp_table_subquery1.q.out
  ql/src/test/results/clientpositive/llap/temp_table_truncate.q.out
  ql/src/test/results/clientpositive/llap/vector_tablesample_rows.q.out
Labels: tests passed

#3326 HIVE-26268: Upgrade Snappy to 1.1.8.4
  pom.xml
Labels: tests passed

#3346 HIVE-26285: Overwrite database metadata on original source in optimised failover.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Labels: tests passed

#3103 HIVE-26293: Migrate remaining exclusive DDL operations to EXCL_WRITE lock & bug fixes
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/drop/DropTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/skewed/AlterTableSkewedByAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/drop/DropMaterializedViewAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestParseUtils.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/ThrowingTxnHandler.java
Labels: tests passed

#3351 HIVE-26300: Upgraded Jackson bom version to 2.12.6.1+ to avoid CVE-20…
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#3352 HIVE-26301: Fix ACID tables bootstrap during reverse replication in u…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExclusiveReplica.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#3235 HIVE-26165: Remove READ locks for ACID tables
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Labels: tests passed

#2809 HIVE-25733: Add check-spelling/check-spelling for `serde/`
  .github/actions/spelling/README.md
  .github/actions/spelling/advice.md
  .github/actions/spelling/allow.txt
  .github/actions/spelling/excludes.txt
  .github/actions/spelling/expect.txt
  .github/actions/spelling/only.txt
  .github/actions/spelling/patterns.txt
  .github/actions/spelling/reject.txt
  .github/workflows/spelling.yml
Labels: tests failed

#3354 HIVE-26307: Avoid FS init in FileIO::newInputFile in vectorized Iceberg reads
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
Labels: tests passed

#3253 HIVE-26184: COLLECT_SET with GROUP BY is very slow when some keys are highly skewed
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFMkCollectionEvaluator.java
Labels: tests passed

#3212 HIVE-26142: Extend the hidden conf list with webui keystore pwd
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/test/org/apache/hadoop/hive/conf/TestHiveConf.java
Labels: tests passed, stale

#3340 HIVE-26280: Copy more data into COMPLETED_COMPACTIONS for better supportability
  metastore/scripts/upgrade/hive/hive-schema-4.0.0-alpha-2.hive.sql
  metastore/scripts/upgrade/hive/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.hive.sql
  ql/src/test/results/clientpositive/llap/sysdb.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0-alpha-2.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0-alpha-2.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0-alpha-2.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0-alpha-2.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0-alpha-2.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.postgres.sql
  standalone-metastore/metastore-server/src/test/resources/sql/postgres/upgrade-3.1.3000-to-4.0.0-alpha-2.postgres.sql
Labels: tests passed

#3357 HIVE-25503: Amendment: Null-safe equality comparison
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#3348 HIVE-25879: MetaStoreDirectSql test query should not query the whole DBS table
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#3350 HIVE-26299: Drop data connector with argument ifNotExists(true) should not throw NoSuchObjectException
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
Labels: tests passed

#3329 HIVE-26269 Class cast exception when vectorization is enabled for cer…
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
  ql/src/test/queries/clientpositive/vector_case_when_3.q
  ql/src/test/results/clientpositive/llap/vector_case_when_3.q.out
Labels: tests passed

#3370 HIVE-26321: Upgrade commons-io to 2.11.0 (Naveen Gangam)
  pom.xml
Labels: tests passed

#3361 HIVE-26298: Selecting complex types on migrated iceberg table does not work
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/ParquetSchemaFieldNameVisitor.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergMigration.java
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_parquet.q
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out
Labels: tests passed

#3367 HIVE-26316: Handle dangling open txns on both src & tgt in unplanned failover.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/OptimisedBootstrapUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AbstractEventHandler.java
Labels: tests passed

#3372 HIVE-26177: Amendment: Initialize datanucleus compaction pool only on HMS Leader & pool sizing
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/MetastoreHousekeepingLeaderTestBase.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithReplication.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3369 HIVE-26324: Add one-row-table constraints on NOTIFICATION_SEQUENCE table
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0-alpha-2.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0-alpha-2.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0-alpha-2.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0-alpha-2.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0-alpha-2.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.postgres.sql
Labels: tests passed

#3382 HIVE-26340: Vectorized PTF operator fails if query has upper case window function
  ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
  ql/src/test/queries/clientpositive/vector_ptf_1.q
  ql/src/test/results/clientpositive/llap/vector_ptf_1.q.out
Labels: tests passed

#3376 HIVE-26326: Support enabling background threads when failover is in progress
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionManagement.java
Labels: tests passed

#3380 HIVE-26338: Repl Dump should fail if source database does not exist.
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/Utils.java
Labels: tests passed

#3383 HIVE-26298: Selecting complex types on migrated iceberg table does not work. (addendum)
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
Labels: tests passed

#3344 HIVE-26208: Exception in Vectorization with Decimal64 to Decimal casting
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnArithmeticDecimal64Column.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnArithmeticDecimal64Scalar.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnArithmeticDecimal64ScalarUnscaled.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnBetween.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnCompareDecimal64Column.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnCompareDecimal64Scalar.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnDivideDecimal64Column.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnDivideDecimal64Scalar.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnScaleUp.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ScalarArithmeticDecimal64Column.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ScalarArithmeticDecimal64ColumnUnscaled.txt
  ql/src/gen/vectorization/ExpressionTemplates/Decimal64ScalarCompareDecimal64Column.txt
  ql/src/gen/vectorization/ExpressionTemplates/FilterDecimal64ColumnCompareDecimal64Column.txt
  ql/src/gen/vectorization/ExpressionTemplates/FilterDecimal64ColumnCompareDecimal64Scalar.txt
  ql/src/gen/vectorization/ExpressionTemplates/FilterDecimal64ScalarCompareDecimal64Column.txt
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/CastLongToDecimal64.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/ConvertDecimal64ToDecimal.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/Decimal64ColumnInList.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/FilterDecimal64ColumnBetween.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/FilterDecimal64ColumnInList.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/FilterDecimal64ColumnNotBetween.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ColumnDecimal64Column.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ColumnDecimal64Scalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ScalarDecimal64Column.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ScalarDecimal64Scalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorExpression.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/test/queries/clientpositive/vector_decimal_7.q
  ql/src/test/results/clientpositive/llap/vector_decimal_7.q.out
Labels: tests passed

#3387 HIVE-26341: Replication logs & metrics shows last repl id as 0 when number of events is zero
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadTasksBuilder.java
Labels: tests passed

#3385 HIVE-26240: Add tests for Esri UDFs for Geospatial.
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/test/queries/clientpositive/geospatial_udfs.q
  ql/src/test/results/clientpositive/llap/geospatial_udfs.q.out
  ql/src/test/results/clientpositive/llap/show_functions.q.out
Labels: tests passed

#3395 HIVE-26149: Addendum: Soft-delete materialized views shouldn't be removed immediately from the FS when non-default MetaStoreFilterHook is configured
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Constant.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
Labels: tests passed

#3378 HIVE-26334: Remove misleading bucketing info from DESCRIBE FORMATTED output for Iceberg tables
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q.out
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
Labels: tests passed

#3307 HIVE-26244: Implementing locking for concurrent ctas
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  ql/src/test/queries/clientpositive/acid_locking_ctas.q
  ql/src/test/results/clientpositive/llap/acid_locking_ctas.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/LockRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/LockRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/LockRequestBuilder.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3053 HIVE-25980: Reduce fs calls in HiveMetaStoreChecker.checkTable
  ql/src/test/queries/clientpositive/msck_repair_hive_25980.q
  ql/src/test/results/clientpositive/llap/msck_repair_hive_25980.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
Labels: tests passed

#3404 HIVE-26128: Enabling dynamic runtime filtering in iceberg tables throws exception at runtime
  data/conf/iceberg/tez/tez-site.xml
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java
  iceberg/iceberg-handler/src/test/queries/positive/dynamic_semijoin_reduction.q
  iceberg/iceberg-handler/src/test/results/positive/dynamic_semijoin_reduction.q.out
Labels: tests passed

#3365 HIVE-26265: Option to filter out Txn events during replication.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/ReplicationTestUtils.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationFilterTransactions.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ReplTxnTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AbortTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CommitTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/OpenTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/AbortTxnEvent.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/AbortTxnMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageBuilder.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/JSONAbortTxnMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/events/TestAbortTxnEventDbsUpdated.java
Labels: tests passed

#3402 HIVE-26352: Tez queue access check fails with GSS Exception on Compaction
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/YarnQueueHelper.java
Labels: tests passed

#3401 HIVE-26354: Support expiring snapshots on iceberg table
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergExpireSnapshots.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Labels: tests passed

#3362 HIVE-26319: Iceberg integration: Perform update split early
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterRegistry.java
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_avro.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_unpartitioned_parquet.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Labels: tests passed

#3410 HIVE-26361: Merge statement compile fails if split update is off
  ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
  ql/src/test/queries/clientpositive/sqlmerge.q
  ql/src/test/results/clientpositive/llap/sqlmerge.q.out
Labels: tests passed

#3408 HIVE-26358: Querying metadata tables does not work for Iceberg tables using HADOOP_TABLE
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
Labels: tests passed

#3303 HIVE-26242: Compaction heartbeater improvements
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionHeartbeatService.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/IMetaStoreClientFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionHeartbeatService.java
Labels: tests passed

#3411 HIVE-26365: Remove column statistics collection task from merge statement plan
  ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
  ql/src/test/results/clientnegative/merge_constraint_notnull.q.out
  ql/src/test/results/clientpositive/llap/acid_no_buckets.q.out
  ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_3.q.out
  ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out
  ql/src/test/results/clientpositive/llap/insert_into_default_keyword.q.out
  ql/src/test/results/clientpositive/llap/semijoin_hint.q.out
  ql/src/test/results/clientpositive/llap/sqlmerge.q.out
  ql/src/test/results/clientpositive/llap/sqlmerge_stats.q.out
Labels: tests passed
