Repository apache/hive, pull requests merged in 2022-10, with the labels that each got.

#3612 HIVE-26576: Alter table calls on Iceberg tables can inadvertently change metadata_location
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCommitLock.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/results/negative/alter_acid_table_to_iceberg_failure.q.out
  iceberg/iceberg-handler/src/test/results/negative/alter_managed_table_to_iceberg_failure.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Labels: tests passed

#3555 Improve LDAP auth to support include generic user filters (Naveen Gan…
  service/src/java/org/apache/hive/service/auth/ldap/CustomQueryFilterFactory.java
  service/src/test/org/apache/hive/service/auth/TestLdapAtnProviderWithMiniDS.java
Labels: tests passed

#3615 HIVE-23745: Avoid copying userpayload in task communicator
  llap-common/src/java/org/apache/hadoop/hive/llap/tez/Converters.java
Labels: tests passed

#3603 HIVE-26543: Improve TxnHandler, TxnUtils, CompactionTxnHandler logging
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
Labels: tests passed

#3635 HIVE-26579. Prepare for Zookeeper, Hadoop switching to Reload4j
  accumulo-handler/pom.xml
  beeline/pom.xml
  cli/pom.xml
  common/pom.xml
  contrib/pom.xml
  druid-handler/pom.xml
  hbase-handler/pom.xml
  hcatalog/core/pom.xml
  hcatalog/hcatalog-pig-adapter/pom.xml
  hcatalog/pom.xml
  hcatalog/server-extensions/pom.xml
  hcatalog/webhcat/java-client/pom.xml
  hcatalog/webhcat/svr/pom.xml
  hplsql/pom.xml
  itests/hcatalog-unit/pom.xml
  itests/hive-blobstore/pom.xml
  itests/hive-minikdc/pom.xml
  itests/hive-unit-hadoop2/pom.xml
  itests/hive-unit/pom.xml
  itests/qtest-accumulo/pom.xml
  itests/qtest-iceberg/pom.xml
  itests/qtest-kudu/pom.xml
  itests/qtest/pom.xml
  itests/util/pom.xml
  jdbc-handler/pom.xml
  jdbc/pom.xml
  kudu-handler/pom.xml
  llap-client/pom.xml
  llap-common/pom.xml
  llap-ext-client/pom.xml
  llap-server/pom.xml
  llap-tez/pom.xml
  metastore/pom.xml
  packaging/pom.xml
  packaging/src/main/assembly/bin.xml
  pom.xml
  ql/pom.xml
  serde/pom.xml
  service/pom.xml
  shims/0.23/pom.xml
  shims/common/pom.xml
  shims/scheduler/pom.xml
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/assembly/bin.xml
  storage-api/pom.xml
  streaming/pom.xml
Labels: tests passed

#3638 HIVE-26550 Const struct equality operator throws error when CBO is of…
  ql/src/test/queries/clientpositive/vector_const_struct_equal.q
  ql/src/test/results/clientpositive/llap/vector_const_struct_equal.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ObjectInspectorUtils.java
Labels: tests passed

#3621 HIVE-26564: Separate query live operation log and historical operation log
  ql/src/java/org/apache/hadoop/hive/ql/QueryInfo.java
  service/src/java/org/apache/hive/service/cli/operation/Operation.java
  service/src/java/org/apache/hive/service/cli/operation/OperationLogManager.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
  service/src/java/org/apache/hive/service/cli/session/SessionManager.java
  service/src/test/org/apache/hive/service/cli/operation/TestOperationLogManager.java
  service/src/test/org/apache/hive/service/cli/operation/TestQueryLifeTimeHooksWithSQLOperation.java
  service/src/test/org/apache/hive/service/cli/operation/TestSQLOperationMetrics.java
Labels: tests unstable

#3649 HIVE-26605: Remove reviewer pattern
  .github/assign-by-files.yml
Labels: tests passed

#3643 Upgrade netty to 4.1.77 due to CVE-2022-24823
  pom.xml
Labels: tests passed

#3653 HIVE-26613. Upgrade jettison to 1.5.1 to fix CVE-2022-40149.
  pom.xml
Labels: tests passed

#3648 HIVE-26603: Initiator does not initiate minor compaction for insert-o…
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
Labels: tests passed

#3617 HIVE-26556: Iceberg: Properties set in HiveIcebergSerde are not propagated to jobconf
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  serde/src/java/org/apache/hadoop/hive/serde2/SerDe.java
Labels: tests passed

#3652 HIVE-26614: Fix adding custom jars in Job Classpath.
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
Labels: tests passed

#3646 HIVE-26596: Hive should enforce merge-on-read delete mode is set for Iceberg V2 tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
Labels: tests passed

#3647 HIVE-26583: Make tests running on iceberg-catalog
  iceberg/iceberg-catalog/pom.xml
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java
Labels: tests passed

#3645 HIVE-26471: Addendum: Fix metric computing
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/CompactionMetricData.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Labels: tests passed

#3660 HIVE-26622:upgrade aws-java-sdk to 1.12.132 version
  pom.xml
Labels: tests passed

#3620 HIVE-26620: Remove unused imports for ThriftBinaryCLIService class
  service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
Labels: tests unstable

#3650 HIVE-26608: Iceberg: Allow parquet write properties to iceberg via session conf and Table Properties.
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#3658 HIVE-26617: Remove unused configurations
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCreateUdfFile.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Labels: tests passed

#3661 HIVE-26623: Maintain same columns in COMPACTIONS view present in SYS …
  metastore/scripts/upgrade/hive/hive-schema-4.0.0-alpha-2.hive.sql
  metastore/scripts/upgrade/hive/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.hive.sql
  ql/src/test/results/clientpositive/llap/sysdb.q.out
Labels: tests passed

#3667 HIVE-26556: ADDENDUM: Iceberg: Properties set in HiveIcebergSerde are not propagated to jobconf.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
Labels: tests passed

#3679 HIVE-26635
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
Labels: tests passed

#3625 Hive-26563: Add extra columns in Show Compactions output and sort the output
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionPoolOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/results/clientpositive/llap/dbtxnmgr_compact1.q.out
  ql/src/test/results/clientpositive/llap/dbtxnmgr_showlocks.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactResponseElement.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ShowCompactResponseElement.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnQueries.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3675 HIVE-26639: ConstantVectorExpression and ExplainTask shouldn't rely on default charset
  ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/ConstantVectorExpression.java
  ql/src/test/queries/clientpositive/chinese_utf8_characters.q
  ql/src/test/results/clientpositive/llap/chinese_utf8_characters.q.out
Labels: tests passed

#3674 HIVE-26633: Make Thrift MaxMessageSize configurable
  common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestRemoteHiveMetaStoreKerberos.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestSSLWithMiniKdc.java
  itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
  service/src/java/org/apache/hive/service/cli/thrift/RetryingThriftCLIServiceClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/security/TFilterTransport.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
Labels: tests passed

#3595 HIVE-26045: Detect timed out connections for providers and auto-reconnect
  ql/src/test/queries/clientpositive/dataconnector_mysql.q
  ql/src/test/results/clientpositive/llap/dataconnector_mysql.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/AbstractDataConnectorProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
Labels: tests passed

#3690 HIVE-26651: MultiDelimitSerDe shouldn't rely on default charset when returning the deserialized string
  ql/src/test/queries/clientpositive/chinese_utf8_characters.q
  ql/src/test/results/clientpositive/llap/chinese_utf8_characters.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
Labels: tests passed

#3630 HIVE-26573: Fix ClassCastException issues for Decimal64 vectorization.
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorDeserializeRow.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorSerDeRow.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/VectorRandomRowSource.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/fast/LazySimpleDeserializeRead.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/fast/LazyBinaryDeserializeRead.java
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/Decimal64ColumnVector.java
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/DecimalColumnVector.java
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/IDecimalColumnVector.java
Labels: tests passed

#3695 HIVE-26657: [Iceberg] Filter out the metadata.json file when migrating
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
Labels: tests passed

#3608 HIVE-13353: SHOW COMPACTIONS should support filtering options
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseShowCompactions.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/columnstats/AlterTableUpdateColumnStatistictAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/results/clientpositive/llap/dbtxnmgr_showlocks.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/ThriftHiveMetastore.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ShowCompactRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnQueries.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionState.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#3693 HIVE-26629: Misleading error message with hive.metastore.limit.partit…
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AbstractDropPartitionAnalyzer.java
Labels: tests passed

#3673 HIVE-26632: Update DelegationTokenSecretManager current key ID to pre…
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/TokenStoreDelegationTokenSecretManager.java
Labels: tests passed

#3706 HIVE-26671: Incorrect results with Top N Key optimization
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/topnkey/TopNKeyProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ReduceSinkDesc.java
  ql/src/test/queries/clientpositive/topnkey.q
  ql/src/test/results/clientpositive/llap/topnkey.q.out
Labels: tests passed

#3711 HIVE-26675: Update Iceberg from 0.14.1 to 1.0.0
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveTableConcurrency.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
  iceberg/pom.xml
Labels: tests passed

#3689 HIVE-26647: Implemented deserialization API for commit compaction event
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageDeserializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/JSONMessageDeserializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/gzip/DeSerializer.java
Labels: tests passed

#3539 HIVE-26248: Add data connector authorization on HMS server-side(addendum)
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed, stale
