Repository apache/hive, pull requests merged in 2022-02, with the labels that each got.

#2890 HIVE-25819: Track event id on target cluster with respect to source cluster.
  hcatalog/webhcat/java-client/src/main/java/org/apache/hive/hcatalog/api/repl/ReplicationUtils.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/OptimisedBootstrapUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/LoadDatabase.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadTasksBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/DBSerializer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/FunctionSerializer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/PartitionSerializer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/TableSerializer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/message/AlterDatabaseHandler.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#2970 HIVE-25893: NPE when reading Parquet data because ColumnVector isNull[] is not updated
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedListColumnReader.java
Labels: tests passed

#2976 HIVE-25902 - adding support for vectorized Parquet reads
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/ParquetSchemaFieldNameVisitor.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergPartitions.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
  iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_mixed.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_parquet.q
  iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_mixed.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_mixed.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
Labels: tests passed

#2992 HIVE-25920: Bump Xerce2 to 2.12.2.
  pom.xml
Labels: tests passed

#2994 HIVE-25922: Upgrade to 0.13.0 Iceberg
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestClientPoolImpl.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
  iceberg/iceberg-handler/pom.xml
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/data/FileHelpers.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTimeTravel.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_metadata_tables.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_unpartitioned_table.q.out
  iceberg/patched-iceberg-core/pom.xml
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/CatalogUtil.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/ClientPool.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/ClientPoolImpl.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/jdbc/JdbcClientPool.java
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
  iceberg/pom.xml
Labels: tests passed

#2989 HIVE-25916: Optimise updateCompactionMetricsData
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionMetricsDataStruct.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionMetricsDataStruct.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionMetricsData.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionMetricsDataConverter.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Labels: tests passed

#2842 HIVE-25772: Use ClusteredWriter when writing to Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveFileWriterFactory.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_writes.q
  iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
  iceberg/patched-iceberg-core/pom.xml
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/io/ClusteredWriter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed, stale

#2794 HIVE-25706: ShuffleHandler: Make sure of properly releasing netty reference counted objects
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
Labels: tests pending, stale

#2998 HIVE-25927: Fix DataWritableReadSupport
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/DataWritableReadSupport.java
Labels: tests pending

#2995 HIVE-25926 Move all logging from AcidMetricService to AcidMetricLogger
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricLogger.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/CompactionMetricData.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestCompactionMetricData.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestMultipleWorkerVersionDetection.java
Labels: tests passed

#2839 HIVE-25766: java.util.NoSuchElementException in HiveFilterProjectTran…
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java
  ql/src/test/queries/clientpositive/cbo_filter_proj_transpose_noinputref.q
  ql/src/test/results/clientpositive/llap/cbo_filter_proj_transpose_noinputref.q.out
Labels: tests passed, stale

#2981 HIVE-25898: Compaction txn heartbeating after Worker timeout
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#3005 HIVE-25937: Create view fails when definition contains a materialized view definition
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/create_view_when_mv_exists.q
  ql/src/test/queries/clientpositive/create_view_when_mv_exists2.q
  ql/src/test/results/clientpositive/llap/create_view_when_mv_exists2.q.out
Labels: tests passed

#2991 HIVE-25918: Invalid stats after multi inserting into the same partition
  ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java
  ql/src/test/queries/clientpositive/stats_part_multi_insert.q
  ql/src/test/results/clientpositive/llap/stats_part_multi_insert.q.out
Labels: tests passed

#2999 HIVE-25583: Support parallel load for HastTables - Interfaces
  ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/MapJoinTableContainerSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastBytesHashMap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastBytesHashMultiSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastBytesHashSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastBytesHashTable.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTable.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTableContainerBase.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTableLoader.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashMap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashMapContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashMultiSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashMultiSetContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashSetContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashTable.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastMultiKeyHashMap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastMultiKeyHashMapContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastMultiKeyHashMultiSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastMultiKeyHashMultiSetContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastMultiKeyHashSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastMultiKeyHashSetContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringCommon.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashMap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashMapContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashMultiSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashMultiSetContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashSet.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashSetContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastTableContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/hashtable/VectorMapJoinHashTable.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/optimized/VectorMapJoinOptimizedHashTable.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestVectorMapJoinFastHashTable.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/mapjoin/MapJoinTestConfig.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/CheckFastRowHashMap.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/TestVectorMapJoinFastRowHashMap.java
Labels: tests passed

#3008 HIVE-25942: Upgrade commons-io to 2.8.0 due to CVE-2021-29425
  pom.xml
Labels: tests passed

#2980 HIVE-25895: Bootstrap tables in table_diff during Incremental Load.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/OptimisedBootstrapUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
Labels: tests passed

#3009 HIVE-25912: Drop external table throw NPE if the location set to ROOT…
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java
Labels: tests passed

#3026 HIVE-25955: Partitioned tables migrated to Iceberg aren't cached in LLAP
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
  iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q
  iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
Labels: tests passed

#2881 HIVE-25747: Make a cost base decision when rebuilding materialized views
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveTezModelRelMetadataProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveIncrementalRelMdRowCount.java
Labels: tests passed

#3035 HIVE-25961: Altering partition specification parameters for Iceberg tables are not working
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
Labels: tests passed

#2957 HIVE-25884: Improve rule description for rules defined as subclasses
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterJoinRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveInBetweenExpandRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRewriteToDataSketchesRules.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/jdbc/JDBCExpandExpressionsRule.java
Labels: tests passed

#3016 HIVE-25951: HiveRelMdPredicates extends RelMdPredicates
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveRelMdPredicates.java
Labels: tests passed

#3028 HIVE-25957: Fix password based authentication with SAML enabled
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  service/src/java/org/apache/hive/service/auth/AuthType.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
  service/src/test/org/apache/hive/service/auth/TestAuthType.java
  service/src/test/org/apache/hive/service/cli/thrift/ThriftHttpServletTest.java
Labels: tests passed

#3029 HIVE-25149: Support parallel load for Fast HT implementations
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTableLoader.java
Labels: tests passed

#3030 HIVE-25918: Invalid stats after multi inserting into the same partition
  cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosIncrementalLoadAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMetaStoreClientWithLocalCache.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreClient.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreClientApiArgumentsChecker.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
  ql/src/test/queries/clientpositive/stats_part_multi_insert_acid.q
  ql/src/test/results/clientpositive/llap/stats_part_multi_insert_acid.q.out
  service/src/java/org/apache/hive/service/server/HiveServer2.java
Labels: tests passed

#3032 HIVE-25959: Expose Compaction Observability delta metrics using the JsonReporter
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetricFlags.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/CodahaleMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/JsonFileMetricsReporter.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/JsonReporter.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MapCapableJsonMetricsModule.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MapMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestMetricRegistry.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestMetrics.java
Labels: tests unstable

#3031 HIVE-25960: Fix S3a recursive listing logic.
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
  common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/FileUtils.java
Labels: tests unstable

#2952 HIVE-25874: Slow filter evaluation of nest struct fields in vectorized executions
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFStructField.java
  ql/src/test/queries/clientpositive/vectorization_nested_struct.q
  ql/src/test/results/clientpositive/llap/vectorization_nested_struct.q.out
Labels: tests passed

#3041 HIVE-25967 initial change
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestInputFormatReaderDeletes.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestIcebergInputFormats.java
Labels: tests passed

#3038 HIVE-25964: Create iceberg table with ranger authorization failed with storage URI NullPointerException
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#3037 HIVE-25958: Optimise BasicStatsNoJobTask.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsNoJobTask.java
Labels: tests unstable

#3047 HIVE-25973: Fix JsonReporter and JsonFileMetricsReporter writing the same file
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
Labels: tests passed

#3050 HIVE-25979: Order of Lineage is flaky in qtest output
  ql/src/java/org/apache/hadoop/hive/ql/hooks/PostExecutePrinter.java
  ql/src/test/results/clientpositive/llap/stats_part_multi_insert.q.out
Labels: tests passed
