Repository apache/hive, pull requests merged in 2022-01, with the labels that each got.

#2904 HIVE-25830: Hive::loadPartitionInternal establishes connection often
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Labels: tests passed

#2780 HIVE-25688: Non blocking DROP PARTITION implementation
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AbstractDropPartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AlterTableDropPartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AlterTableDropPartitionDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AlterTableDropPartitionOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AlterViewDropPartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnConcatenate.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnExIm.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnNoBuckets.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/TxnType.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/TxnType.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/LockComponentBuilder.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/PartitionDropOptions.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
  storage-api/src/java/org/apache/hadoop/hive/common/AcidMetaDataFile.java
Labels: tests passed

#2914 HIVE-25841: Improve performance of deleteColumnStatsState
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#2922 HIVE-25818: Values query with order by position clause fails - ADDENDUM: add test
  ql/src/test/queries/clientpositive/order_by_pos.q
  ql/src/test/results/clientpositive/llap/order_by_pos.q.out
Labels: tests passed

#2856 HIVE-25849: Disable insert overwrite for bucket partitioned iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#2873 HIVE-25806: Possible leak in LlapCacheAwareFs - Parquet, LLAP IO
  ql/src/java/org/apache/hadoop/hive/llap/LlapCacheAwareFs.java
Labels: tests passed

#2939 HIVE-25859: load_non_hdfs_path.q fails on master: .1.txt.crc does not exist.
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
Labels: tests pending

#2911 HIVE-25829: Tez exec mode support for credential provider for jobs
  common/pom.xml
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConfUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestHiveCredentialProviders.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDagUtils.java
Labels: tests passed

#2927 HIVE-25854: Port Iceberg Hive fix - ORC vectorization fails after spl…
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/data/GenericAppenderHelper.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestHelper.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
Labels: tests passed

#2772 HIVE-24445: Non blocking DROP TABLE implementation
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/drop/DropTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/drop/DropTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreChecker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/Table.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Table.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/ThrowingTxnHandler.java
  storage-api/src/java/org/apache/hadoop/hive/common/AcidConstants.java
Labels: tests passed

#2917 HIVE-25843: Add flag to disable Iceberg FileIO config serialization
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
Labels: tests passed

#2908 HIVE-25824: Upgrade log4j dependencies to 2.17.0
  bin/hive-config.sh
  druid-handler/pom.xml
  hbase-handler/pom.xml
  jdbc/pom.xml
  llap-server/pom.xml
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/log/NoDeleteRollingFileAppender.java
  service/pom.xml
  testutils/ptest2/pom.xml
Labels: tests unstable

#2931 HIVE-21074
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/FixedBucketPruningOptimizer.java
  ql/src/test/queries/clientpositive/bucketpruning1.q
  ql/src/test/results/clientpositive/llap/bucketpruning1.q.out
  ql/src/test/results/clientpositive/llap/tez_fixed_bucket_pruning.q.out
Labels: tests passed

#2944 HIVE-25637: Hive on Tez: inserting data failing into the non native hive external table managed by kafka storage handler
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezProcessor.java
Labels: tests unstable

#2941 HIVE-25858: DISTINCT with ORDER BY on ordinals fails with NPE
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/order_by_pos.q
  ql/src/test/results/clientpositive/llap/order_by_pos.q.out
Labels: tests passed

#2879 HIVE-25801: Custom queue setting is not honoured by Query based compaction StatsUpdater
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestFetchWriteIdFromInsertOnlyTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnNoBuckets.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#2945 HIVE-25862: Persist the time of last run of the initiator
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Labels: tests passed

#2906 HIVE-24805: Compactor: Initiator shouldn't fetch table details again …
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#2934 HIVE-25646: Thrift metastore URI reverse resolution could fail in some environments
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: tests passed

#2900 HIVE-25828: Remove unused import and method in ParseUtils
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
Labels: tests unstable

#2943 HIVE-25864 : Hive query optimisation creates wrong plan for predicate pushdown with windowing function
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java
  ql/src/test/queries/clientpositive/ppd_windowing3.q
  ql/src/test/results/clientpositive/llap/ppd_windowing3.q.out
Labels: tests passed

#2949 HIVE-25873: Fix nested partition statements in Explain DDL
  ql/src/java/org/apache/hadoop/hive/ql/exec/DDLPlanUtils.java
  ql/src/test/queries/clientpositive/explain_ddl_nested_part.q
  ql/src/test/results/clientpositive/llap/explain_ddl_nested_part.q.out
Labels: tests passed

#2956 HIVE-25881: isEligibleForCompaction should be executed under the custom threadPool
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
Labels: tests passed

#2948 HIVE-25871: Hive should set name mapping table property for migrated …
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergMigration.java
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_table.q
  iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out
Labels: tests passed

#2852 HIVE-25783: Refine standalone-metastore module pom.xml files
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-common/src/main/resources/datanucleus-log4j.properties
  standalone-metastore/metastore-common/src/main/resources/metastore-log4j2.properties
  standalone-metastore/metastore-common/src/main/resources/metastore-site.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/pom.xml
  storage-api/pom.xml
Labels: tests passed

#2958 HIVE-25883: Enhance Compaction Cleaner to skip when there is nothing to do
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
Labels: tests passed

#2961 HIVE-25888: Improve RuleEventLogger to also print input rels in FULL_…
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/RuleEventLogger.java
Labels: tests passed

#2962 HIVE-25889: Increase default value of "metastore.thread.pool.size"
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#2963 Add common HMS props to CTAS as well; Fix vectorization error message…
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
Labels: tests passed

#2965 HIVE-25891: Improve Iceberg error message for unsupported vectorization cases
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
Labels: tests passed

#2959 HIVE-25887 - Add external_table_concatenate.q to testconfiguration.properties.
  itests/src/test/resources/testconfiguration.properties
Labels: tests passed

#2968 HIVE-25777: ACID: Pick the compactor transaction over insert dir
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
Labels: tests passed

#2972 HIVE-24820: MaterializedViewCache enables adding multiple entries of the same Materialization instance
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/update/MaterializedViewUpdateOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java
  ql/src/test/queries/clientpositive/materialized_view_partitioned.q
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
Labels: tests passed

#2975 HIVE-25899: Materialized view registry does not clean dropped views
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java
Labels: tests passed

#2986 HIVE-25906: Clean MaterializedViewCache after q test run
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
Labels: tests passed

#2973 HIVE-25897: Move delta metric collection into AcidMetricsService
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetricFlags.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionMetricsDataRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionMetricsDataRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/LegacyMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/MetricsMBean.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/MetricsMBeanImpl.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/common/Metrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/common/MetricsConstant.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/common/MetricsFactory.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/common/MetricsScope.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/common/MetricsVariable.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/CodahaleMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/CodahaleReporter.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/ConsoleMetricsReporter.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/JmxMetricsReporter.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/JsonFileMetricsReporter.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/MetricVariableRatioGauge.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/Metrics2Reporter.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/MetricsReporting.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/common/metrics/MetricsTestUtils.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/common/metrics/TestLegacyMetrics.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleMetrics.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleReportersConf.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/common/metrics/metrics2/TestMetricVariableRatioGauge.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricLogger.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#2988 HIVE-25914 Fix of Cleaner updates Initiator cycle metric
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
Labels: tests passed
