Repository apache/hive, pull requests merged in 2022-11, with the labels that each got.

#3627 HIVE-25813: Create Table x Like commands based storage handlers fail over is fixed
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  hbase-handler/src/test/results/positive/hbase_queries.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java
  ql/src/test/queries/clientpositive/avro_extschema_insert.q
  ql/src/test/queries/clientpositive/create_like2.q
  ql/src/test/results/clientpositive/llap/avro_extschema_insert.q.out
  ql/src/test/results/clientpositive/llap/create_like.q.out
  ql/src/test/results/clientpositive/llap/create_like2.q.out
  ql/src/test/results/clientpositive/llap/create_like_tbl_props.q.out
  ql/src/test/results/clientpositive/llap/create_like_view.q.out
  ql/src/test/results/clientpositive/llap/partition_discovery.q.out
Labels: tests passed

#3710 HIVE-26670: Track every single HTTP request between beeline and hs2
  beeline/src/main/resources/beeline-log4j2.properties
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/HttpDefaultResponseInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/HttpRequestInterceptorBase.java
  jdbc/src/java/org/apache/hive/jdbc/HttpResponseInterceptorBase.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
  jdbc/src/test/org/apache/hive/jdbc/TestHiveConnection.java
  jdbc/src/test/org/apache/hive/jdbc/TestHttpRequestInterceptor.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
Labels: tests passed

#3681 HIVE-26636 - Adding hyperbolic functions
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFCosh.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFSinh.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFTanh.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/TestUDFMath.java
  ql/src/test/queries/clientpositive/udf_cosh.q
  ql/src/test/queries/clientpositive/udf_sinh.q
  ql/src/test/queries/clientpositive/udf_tanh.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_cosh.q.out
  ql/src/test/results/clientpositive/llap/udf_sinh.q.out
  ql/src/test/results/clientpositive/llap/udf_tanh.q.out
  vector-code-gen/src/org/apache/hadoop/hive/tools/GenVectorCode.java
Labels: tests passed

#3702 HIVE-25585: Put dagId to MDC once it's available in HS2
  common/src/java/org/apache/hadoop/hive/common/LogUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
Labels: tests passed

#3722 HIVE-13288: Confusing exception message in DagUtils.localizeResource
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
Labels: tests passed

#3717 HIVE-26684: Upgrade maven-shade-plugin from 3.4.1 for bug fixes.
  .gitignore
  pom.xml
Labels: tests passed

#3729 HIVE-26705. Fix Typo in hive-kudu-handler.
  kudu-handler/src/java/org/apache/hadoop/hive/kudu/KuduHiveUtils.java
  kudu-handler/src/test/org/apache/hadoop/hive/kudu/TestKuduInputFormat.java
Labels: tests passed

#3733 HIVE-26709: Iceberg: Count(*) fails for V2 tables with delete files.
  ql/pom.xml
Labels: tests passed

#3732 HIVE-26694: Populate file row position information during vectorized Iceberg reads
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchContext.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchIterator.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveIcebergVectorizedRecordReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/RowPositionAwareVectorizedRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/TestVectorizedColumnReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/VectorizedColumnReaderTestBase.java
Labels: tests passed

#3731 HIVE-26707: Iceberg: Write failing due to Ranger Authorization failure.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#3737 HIVE-26696: Implement row iterator for VectorizedRowBatch
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchContext.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveRow.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveStructLike.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveValueConverter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorExtractRow.java
Labels: tests passed

#3740 HIVE-26656:Remove hsqldb dependency in hive due to CVE-2022-41853
  hcatalog/core/pom.xml
  hcatalog/hcatalog-pig-adapter/pom.xml
  hcatalog/pom.xml
  hcatalog/server-extensions/pom.xml
Labels: tests passed

#3700 HIVE-26667: Incompatible expression deserialization against latest HMS
  ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionExpressionForMetastore.java
  ql/src/test/org/apache/hadoop/hive/metastore/TestMetastoreExpr.java
Labels: tests passed

#3644 HIVE-26437: Dump unpartitioned tables in parallel.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-jmh/src/main/java/org/apache/hive/benchmark/ql/exec/DumbTableExport.java
  itests/hive-jmh/src/main/java/org/apache/hive/benchmark/ql/exec/TableAndPartitionExportBench.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ExportTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/ExportJob.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/ExportService.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/PartitionExport.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/TableExport.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestReplDumpTask.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/dump/TestExportService.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
Labels: tests passed

#3750 HIVE-26724: Mask UDF failing with NPE.
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMaskHash.java
  ql/src/test/queries/clientpositive/udf_mask_hash_config.q
  ql/src/test/results/clientpositive/llap/udf_mask_hash_config.q.out
Labels: tests passed

#3747 HIVE-26697: Create vectorized Hive DeleteFilter for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveDeleteFilter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_partitioned_orc.q.out
Labels: tests passed

#3713 HIVE-26677: Constrain available processors to Jetty during test runs …
  pom.xml
Labels: tests passed

#3749 HIVE-26723: Configurable canonical name checking.
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
Labels: tests passed

#3712 HIVE-26666: Filter out compactions by id to minimise expense of db operations
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactRequest.java
Labels: tests passed

#3585 HIVE-26522: Added test for HIVE-22033 regarding delegation token renewal
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
Labels: tests passed, stale

#3587 [WIP] HIVE-26522: Backport of HIVE-22033 and HIVE-26522 to branch-3.1
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/security/TokenStoreDelegationTokenSecretManager.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
Labels: tests unstable, stale

#3586 HIVE-26522: Backport of HIVE-22033 and HIVE-26522 to branch-2.3
  metastore/src/test/org/apache/hadoop/hive/metastore/TestTokenStoreDelegationTokenSecretManager.java
  shims/common/src/main/java/org/apache/hadoop/hive/thrift/TokenStoreDelegationTokenSecretManager.java
Labels: tests unstable, stale

#3734 HIVE-26676: Count distinct in subquery returning wrong results
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/PlanModifierForASTConv.java
  ql/src/test/queries/clientpositive/count_distinct_subquery.q
  ql/src/test/results/clientpositive/llap/count_distinct_subquery.q.out
Labels: tests passed

#3760 HIVE-26736: Authorization failure for nested Views having WITH clause.
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/authorization_nested_views.q
  ql/src/test/results/clientpositive/llap/authorization_nested_views.q.out
Labels: tests passed

#3745 HIVE-26628: Iceberg table is created when running explain ctas command
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_partitioned_orc.q
  iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PartitionDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableDesc.java
Labels: tests passed

#3758 HIVE-26734: Iceberg: Add an option to allow positional delete files without actual row data.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriterTestBase.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_v2_deletes.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_v2_deletes.q.out
Labels: tests passed

#3589 HIVE-26530:HS2 OOM-OperationManager.queryIdOperation does not properl…
  service/src/java/org/apache/hive/service/cli/operation/Operation.java
  service/src/java/org/apache/hive/service/cli/operation/OperationManager.java
Labels: tests unstable

#3753 HIVE-26524: Use Calcite to remove sections of a query plan known never produces rows - ADDENDUM
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveValues.java
Labels: tests passed

#3765 HIVE-26740: HS2 makes direct connections to HMS backend DB due to Compaction/StatsUpdater
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java
Labels: tests passed

#3766 HIVE-26747: Remove implementor from HiveRelNode
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveAggregate.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveAntiJoin.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveExcept.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveFilter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveIntersect.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveJoin.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveProject.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveRelNode.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveSemiJoin.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveSortExchange.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveSortLimit.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveTableFunctionScan.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveTableScan.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveUnion.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/jdbc/HiveJdbcConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewBoxing.java
Labels: tests passed

#3768 [HIVE-26743]backport HIVE-24694
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
Labels: tests unstable

#3769 HIVE-26745: HPL unable to handle Decimal or null values in hplsql mode
  hplsql/src/main/java/org/apache/hive/hplsql/Var.java
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestBeeLineWithArgs.java
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
  service/src/java/org/apache/hive/service/cli/operation/hplsql/HplSqlQueryExecutor.java
Labels: tests passed

#3770 HIVE-26746: Request tracking: change to X-Request-ID header
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
Labels: tests passed

#3723 HIVE-26624: Set repl.background.enable on target after failover compl…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Labels: tests passed

#3738 HIVE-26712: HCatMapReduceTest writes test files in project base directory instead of build directory.
  hcatalog/core/.gitignore
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/HCatMapReduceTest.java
Labels: tests passed

#3752 HIVE-26726: Tinyint column with windowing fn crashes at runtime
  ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
  ql/src/test/queries/clientpositive/windowing_tinyint.q
  ql/src/test/results/clientpositive/llap/windowing_tinyint.q.out
Labels: tests passed

#3715 HIVE-26680: Make CMV use Direct Insert Semantics
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
  ql/src/test/queries/clientpositive/cmv_direct.q
  ql/src/test/queries/clientpositive/cmv_direct_with_specified_locations.q
  ql/src/test/queries/clientpositive/cmv_direct_with_suffixed_locations.q
  ql/src/test/results/clientpositive/llap/cmv_direct.q.out
  ql/src/test/results/clientpositive/llap/cmv_direct_with_specified_locations.q.out
  ql/src/test/results/clientpositive/llap/cmv_direct_with_suffixed_locations.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create.q.out
Labels: tests passed

#3317 HIVE-26243: Add vectorized implementation of the 'ds_kll_sketch' UDAF
  pom.xml
  ql/src/gen/vectorization/UDAFTemplates/VectorUDAFComputeDsKllSketch.txt
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/MapJoinProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/datasketches/kll/KllHistogramEstimator.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/datasketches/kll/KllHistogramEstimatorFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/datasketches/kll/KllUtils.java
  ql/src/test/queries/clientpositive/compute_kll_sketch.q
  ql/src/test/results/clientpositive/llap/compute_kll_sketch.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_cume_dist.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_ntile.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_percentile_disc.q.out
  ql/src/test/results/clientpositive/llap/sketches_materialized_view_rank.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_cume_dist.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_cume_dist_partition_by.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_ntile.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_ntile_partition_by.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_percentile_disc.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_rank.q.out
  ql/src/test/results/clientpositive/llap/sketches_rewrite_rank_partition_by.q.out
  vector-code-gen/src/org/apache/hadoop/hive/tools/GenVectorCode.java
Labels: tests passed

#3783 HIVE-26761: Add result sorting to complex_alias.q
  ql/src/test/queries/clientpositive/complex_alias.q
  ql/src/test/results/clientpositive/llap/complex_alias.q.out
Labels: tests passed

#3782 HIVE-26759: Update SHOW_COMPACTION_QUERY to support postgres HMS
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnQueries.java
Labels: tests passed

#3790 HIVE-26765: Hive Ranger URL policy for insert overwrite directory den…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/fully_qualified_or_relative_location.q
  ql/src/test/results/clientpositive/llap/fully_qualified_or_relative_location.q.out
Labels: tests passed

#3669 HIVE-23754: LLAP, Add LoggingHandler in ShuffleHandler pipeline for better debuggability
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
Labels: tests passed

#3784 HIVE-26484: Add proto3 hivemetastore.proto
  pom.xml
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-common/src/main/protobuf/org/apache/hadoop/hive/metastore/hive_metastore.proto
  standalone-metastore/metastore-common/src/main/protobuf/org/apache/hadoop/hive/metastore/metastore.proto
  standalone-metastore/pom.xml
  standalone-metastore/spotbugs/spotbugs-exclude.xml
Labels: tests passed

#3773 HIVE-26701: Enable metrics for connection pools used by ObjectStore i…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
Labels: tests passed

#3787 HIVE-26763 : Upgraded zookeeper version to latest 3.6.3 and curator to latest 5.2.0
  pom.xml
  ql/src/test/org/apache/hive/testutils/MiniZooKeeperCluster.java
  standalone-metastore/pom.xml
Labels: tests passed

#3774 HIVE-26744 - Add array_max and array_min UDFs
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/AbstractGenericUDFArrayBase.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayMax.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayMin.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestAbstractGenericUDFArrayBase.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayMax.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayMin.java
  ql/src/test/queries/clientpositive/udf_array_max.q
  ql/src/test/queries/clientpositive/udf_array_min.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_max.q.out
  ql/src/test/results/clientpositive/llap/udf_array_min.q.out
Labels: tests passed

#3791 HIVE-26764:Show compaction request should have all filds optional
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ShowCompactRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed

#3808 HIVE-26768: HPLSQL UDF is not working if it is applied on a column of type varchar/char/decimal in a table.
  hplsql/src/main/java/org/apache/hive/hplsql/udf/Udf.java
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Labels: tests passed

#3767 HIVE-26742: Iceberg: Vectorization fails incase of multiple tables in queries.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_mixed.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_multitable.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_parquet.q
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_mixed.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_multitable.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_mixed.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_multitable.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedInputFormatInterface.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
Labels: tests passed

#3810 HIVE-26786: Iceberg: Read queries with copy-on-write failing.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
  iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_partitioned_orc.q
  iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
Labels: tests passed

#3776 HIVE-26753:Upgrade Apache Ivy to 2.5.1 due to CVE-2022-37865, CVE-202…
  hcatalog/hcatalog-pig-adapter/pom.xml
  hcatalog/pom.xml
  pom.xml
Labels: tests passed

#3802 HIVE-26771: Use DDLTask to created Iceberg table when running ctas statement
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
  iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_orc.q
  iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableDesc.java
Labels: tests passed
