Repository apache/hive, pull requests merged in 2022-05, with the labels that each got.

#3261 HIVE-26193: Fix Iceberg partitioned tables null bucket handling
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/GenericUDFIcebergBucket.java
  iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_writes.q
  iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatchCtx.java
Labels: tests passed

#3172 HIVE-26107: Worker shouldn't inject duplicate entries in `ready for cleaning` state into the compaction queue
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestFetchWriteIdFromInsertOnlyTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUpdaterThread.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  ql/src/test/queries/clientpositive/acid_insert_overwrite_update.q
  ql/src/test/queries/clientpositive/dbtxnmgr_compact1.q
  ql/src/test/queries/clientpositive/dbtxnmgr_compact3.q
  ql/src/test/results/clientpositive/llap/acid_insert_overwrite_update.q.out
  ql/src/test/results/clientpositive/llap/dbtxnmgr_compact1.q.out
  ql/src/test/results/clientpositive/llap/dbtxnmgr_compact3.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionResponse.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionResponse.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3258 HIVE-26189: Iceberg metadata query throws exceptions after partition evolution
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
Labels: tests passed

#3262 HIVE-26189: Iceberg metadata query throws exceptions after partition evolution (addendum)
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
Labels: tests passed

#3165 HIVE-26106: Non blocking ADD, DROP CONSTRAINT
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Labels: tests passed

#3122 HIVE-26076: Non blocking ADD PARTITION if not exists
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/add/AbstractAddPartitionAnalyzer.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnAddPartition.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Labels: tests passed

#3251 HIVE-26183: Create delete writer for the UPDATE statements
  iceberg/iceberg-handler/pom.xml
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/FilesForCommit.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergBufferedDeleteWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergUpdateWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergWriterBase.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/data/IcebergGenerics2.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestHelper.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergWriterTestBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergUpdateWriter.java
  iceberg/pom.xml
Labels: tests passed

#3083 HIVE-23391: Non blocking ALTER TABLE add column
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Labels: tests passed

#3089 HIVE-26023: Non blocking REPLACE, RENAME COLUMNS implementation
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Labels: tests passed

#3268 HIVE-26200: Add tests for Iceberg DELETE statements for every supported type
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
Labels: tests passed

#3259 HIVE-26190: Implement create iceberg table with metadata location
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: tests passed

#3265 HIVE-26177: Create a new connection pool for compaction (DataNucleus)
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetaStoreCompactorThread.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java
Labels: tests passed

#3045 HIVE-25969: Unable to reference table column named default
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseDefault.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UnparseTranslator.java
  ql/src/test/queries/clientpositive/insert_into_default_keyword_2.q
  ql/src/test/results/clientpositive/llap/insert_into_default_keyword_2.q.out
Labels: tests passed, stale

#3264 HIVE-26199 Reduce FileSystem init during user impersonation
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/SQLAuthorizationUtils.java
Labels: tests passed

#3278 HIVE-26219 Encapsulate the API change for FileUtils.isActionPermitted…
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
Labels: tests passed

#3275 HIVE-26215: Expose the MIN_HISTORY_LEVEL table through Hive sys database
  metastore/scripts/upgrade/hive/hive-schema-4.0.0-alpha-2.hive.sql
  metastore/scripts/upgrade/hive/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.hive.sql
  ql/src/test/results/clientpositive/llap/resourceplan.q.out
  ql/src/test/results/clientpositive/llap/strict_managed_tables_sysdb.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
Labels: tests passed

#3270 HIVE-26203: Implement alter iceberg table metadata location
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#3255 HIVE-26158: TRANSLATED_TO_EXTERNAL partition tables cannot query partition data after rename table
  ql/src/test/queries/clientpositive/translated_external_rename4.q
  ql/src/test/results/clientpositive/llap/translated_external_rename4.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDefaultTransformer.java
Labels: tests passed

#3269 HIVE-26202: Refactor Iceberg Writers
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveFileWriterFactory.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergBufferedDeleteWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergRecordWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergUpdateWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriterBase.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterRegistry.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriterTestBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/TestHiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/TestHiveIcebergUpdateWriter.java
Labels: tests passed

#3233 HIVE-26071: JWT authentication mechanism for Thrift over HTTP in HiveMetastore
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HmsThriftHttpServlet.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/auth/HttpAuthenticationException.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/auth/jwt/JWTValidator.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/auth/jwt/URLBasedJWKSProvider.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetastoreWithHttpJwt.java
  standalone-metastore/metastore-server/src/test/resources/auth/jwt/jwt-authorized-key.json
  standalone-metastore/metastore-server/src/test/resources/auth/jwt/jwt-unauthorized-key.json
  standalone-metastore/metastore-server/src/test/resources/auth/jwt/jwt-verification-jwks.json
  standalone-metastore/pom.xml
Labels: tests passed

#2378 HIVE-25230: Add position and occurrence to INSTR()
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFInstr.java
  ql/src/test/queries/clientnegative/udf_instr_wrong_args_len2.q
  ql/src/test/queries/clientnegative/udf_instr_wrong_occurrence.q
  ql/src/test/queries/clientpositive/udf_instr.q
  ql/src/test/results/clientnegative/udf_instr_wrong_args_len.q.out
  ql/src/test/results/clientnegative/udf_instr_wrong_args_len2.q.out
  ql/src/test/results/clientnegative/udf_instr_wrong_occurrence.q.out
  ql/src/test/results/clientnegative/udf_instr_wrong_type.q.out
  ql/src/test/results/clientpositive/llap/udf_instr.q.out
Labels: tests passed

#3226 HIVE-26157: Change Iceberg storage handler authz URI to metadata location
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/CustomTestHiveAuthorizerFactory.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Labels: tests passed

#2950 HIVE-25872: Skip tracking of alterDatabase events for replication specific properties
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestReplChangeManager.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestCopyUtils.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestMetaStoreEventListenerInRepl.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOfHiveStreaming.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOnHDFSEncryptedZones.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExclusiveReplica.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTablesMetaDataOnly.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosIncrementalLoadAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithReplication.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniHS2.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/flags/ReplRemoveFirstIncLoadPendFlagOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/LoadDatabase.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadPartitions.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/EximUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/Utils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/PartitionSerializer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/TableSerializer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/message/AlterDatabaseHandler.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/AlterDatabaseEvent.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MDatabase.java
Labels: tests passed

#3290 HIVE-25444
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
Labels: tests passed

#3282 HIVE-26225: Delete operations in ObjectStore.cleanWriteNotificationEvents should be performed in different transactions
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
Labels: tests passed

#3294 HIVE-26231: Generate insert notification events when dynamic partitio…
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/queries/clientpositive/insert_dynamic_partitions_notification_log.q
  ql/src/test/results/clientpositive/llap/insert_dynamic_partitions_notification_log.q.out
Labels: tests passed

#3298 HIVE-26237: Check if replication cause metastore connection leakage
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLOperationContext.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/concatenate/AlterTableConcatenateOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Labels: tests passed

#3306 HIVE-26251: Disable vectorization when querying iceberg metadata tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_unpartitioned_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_with_joins.q
Labels: tests passed

#3313 HIVE-26258: Provide an option for enable locking of external tables
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Labels: tests failed

#3305 HIVE-26235: OR Condition on binary column is returning empty result
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFIn.java
  ql/src/test/queries/clientpositive/udf_in_binary.q
  ql/src/test/results/clientpositive/llap/udf_in_binary.q.out
Labels: tests passed

#3320 HIVE-26261: Fix some issues with Spark engine removal
  ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/MapJoinTableContainerSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
Labels: tests passed

#3266 HIVE-25589: SQL: Implement HAVING/QUALIFY predicates for ROW_NUMBER()=1
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBParseInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientnegative/qualify_no_cbo.q
  ql/src/test/queries/clientnegative/qualify_no_cbo_2.q
  ql/src/test/queries/clientpositive/qualify.q
  ql/src/test/queries/clientpositive/qualify_distinct.q
  ql/src/test/queries/clientpositive/qualify_gby.q
  ql/src/test/results/clientnegative/qualify_no_cbo.q.out
  ql/src/test/results/clientnegative/qualify_no_cbo_2.q.out
  ql/src/test/results/clientpositive/llap/qualify.q.out
  ql/src/test/results/clientpositive/llap/qualify_distinct.q.out
  ql/src/test/results/clientpositive/llap/qualify_gby.q.out
Labels: tests passed

#3322 HIVE-24598: handle null in trim function
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFBaseTrim.java
  ql/src/test/queries/clientpositive/udf_trim.q
  ql/src/test/results/clientpositive/llap/udf_trim.q.out
Labels: tests passed

#3295 HIVE-26233: Problems reading back PARQUET timestamps above 10000 years
  common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java
  ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampsHive2Compatibility.java
Labels: tests passed

#3318 HIVE-26260: Use `Reader.getSchema` instead of deprecated `Reader.getTypes`
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcNewInputFormat.java
Labels: tests passed

#3302 HIVE-26239 Shutdown Hash table load executor service threads when the…
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTableLoader.java
Labels: tests passed

#3328 HIVE-22670: ArrayIndexOutOfBoundsException when vectorized reader is used for reading a parquet file.
  data/files/hive22670.parquet
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedPrimitiveColumnReader.java
  ql/src/test/queries/clientpositive/parquet_vectorization_18.q
  ql/src/test/results/clientpositive/llap/parquet_vectorization_18.q.out
Labels: tests passed

#3300 HIVE-26224: Add support for ESRI GeoSpatial SERDE formats.
  data/files/geo-json.json
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EnclosedBaseJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EnclosedEsriJsonInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EnclosedEsriJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EnclosedGeoJsonInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EnclosedGeoJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EnclosedJsonInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EnclosedJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EsriFeature.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EsriFeatureClass.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EsriField.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EsriFieldType.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/EsriJsonFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/UnenclosedBaseJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/UnenclosedEsriJsonInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/UnenclosedEsriJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/UnenclosedGeoJsonInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/UnenclosedGeoJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/UnenclosedJsonInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/esriJson/UnenclosedJsonRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/esri/serde/EsriJsonSerDe.java
  ql/src/test/org/apache/hadoop/hive/ql/io/esriJson/TestEnclosedEsriJsonRecordReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/esriJson/TestEnclosedGeoJsonRecordReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/esriJson/TestUnenclosedEsriJsonRecordMrv1.java
  ql/src/test/org/apache/hadoop/hive/ql/io/esriJson/TestUnenclosedEsriJsonRecordReader.java
  ql/src/test/org/apache/hadoop/hive/ql/io/esriJson/TestUnenclosedGeoJsonRecordReader.java
  ql/src/test/queries/clientpositive/geospatial_json.q
  ql/src/test/resources/json/sample-geojs-area.json
  ql/src/test/resources/json/sample-study-area.json
  ql/src/test/resources/json/unenclosed-geojs-escape.json
  ql/src/test/resources/json/unenclosed-geojs-simple.json
  ql/src/test/resources/json/unenclosed-geojs-type.json
  ql/src/test/resources/json/unenclosed-json-attrs.json
  ql/src/test/resources/json/unenclosed-json-chars.json
  ql/src/test/resources/json/unenclosed-json-comma.json
  ql/src/test/resources/json/unenclosed-json-esc-points.json
  ql/src/test/resources/json/unenclosed-json-esc1.json
  ql/src/test/resources/json/unenclosed-json-esc2.json
  ql/src/test/resources/json/unenclosed-json-esc3.json
  ql/src/test/resources/json/unenclosed-json-esc4.json
  ql/src/test/resources/json/unenclosed-json-esc5.json
  ql/src/test/resources/json/unenclosed-json-escape.json
  ql/src/test/resources/json/unenclosed-json-geom-first.json
  ql/src/test/resources/json/unenclosed-json-return.json
  ql/src/test/resources/json/unenclosed-json-simple.json
  ql/src/test/results/clientpositive/llap/geospatial_json.q.out
  serde/pom.xml
  serde/src/java/org/apache/hadoop/hive/serde2/esriJson/deserializer/GeometryJsonDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/esriJson/deserializer/GeometryTypeJsonDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/esriJson/deserializer/SpatialReferenceJsonDeserializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/esriJson/serializer/GeometryJsonSerializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/esriJson/serializer/GeometryTypeJsonSerializer.java
  serde/src/java/org/apache/hadoop/hive/serde2/esriJson/serializer/SpatialReferenceJsonSerializer.java
Labels: tests passed
