Repository apache/hive, pull requests merged in 2022-08, with the labels that each got.

#3456 HIVE-26412: Create interface to fetch available slots and add the default implementation
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/AvailableSlotsCalculator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HiveSplitGenerator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezAvailableSlotsCalculator.java
Labels: tests passed

#3473 HIVE-26425: Skip SSL cert verification for downloading JWKS in HS2
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  service/src/java/org/apache/hive/service/auth/jwt/JWTValidator.java
  service/src/java/org/apache/hive/service/auth/jwt/URLBasedJWKSProvider.java
Labels: tests passed

#3279 HIVE-24484: Upgrade Hadoop to 3.3.1 And Tez to 0.10.2
  common/pom.xml
  data/conf/hive-site.xml
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatMultiOutputFormat.java
  hcatalog/webhcat/java-client/src/test/java/org/apache/hive/hcatalog/api/TestHCatClient.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOnHDFSEncryptedZones.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/OperationLoggingAPITestBase.java
  itests/pom.xml
  itests/qtest-druid/pom.xml
  itests/qtest/pom.xml
  llap-common/pom.xml
  llap-server/pom.xml
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/ContainerRunnerImpl.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapTaskReporter.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskRunnerCallable.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapInputFormat.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskCommunicator.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
  llap-tez/src/test/org/apache/hadoop/hive/llap/tezplugins/TestLlapTaskCommunicator.java
  pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/io/RecordReaderWrapper.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/StorageBasedAuthorizationProvider.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/test/queries/clientpositive/acid_table_directories_test.q
  ql/src/test/queries/clientpositive/encryption_load_data_to_encrypted_tables.q
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DefaultIncompatibleTableChangeHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/pom.xml
  storage-api/pom.xml
  storage-api/src/java/org/apache/hadoop/hive/common/ValidReadTxnList.java
  streaming/pom.xml
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Labels: tests passed

#3491 HIVE-26444: Use tez.local.mode.without.network for unit tests
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  ql/src/test/org/apache/hive/testutils/HiveTestEnvSetup.java
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Labels: tests passed

#3482 HIVE-26433: StorageHandler authorization doesn't work with "METASTORE" db type
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcStorageHandler.java
Labels: tests passed

#3488 HIVE-26439: Skip collecting Kafka delegation tokens if PLAINTEXT is set
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
Labels: tests passed

#3502 HIVE-26450: Use a lightweight oracle image
  itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/Oracle.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Oracle.java
Labels: tests passed

#3478 HIVE-22417: Remove stringifyException from MetaStore
  metastore/src/java/org/apache/hadoop/hive/metastore/SerDeStorageSchemaReader.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ReplCopyTask.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AbstractEventHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CreateFunctionHandler.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/StringUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
Labels: tests passed

#3501 HIVE-26448: Improve UnsignedInt128.setV*()
  common/src/java/org/apache/hadoop/hive/common/type/UnsignedInt128.java
  common/src/test/org/apache/hadoop/hive/common/type/TestUnsignedInt128.java
Labels: tests passed

#3492 HIVE-26447: Vectorization: wrong results when filter on repeating map key orc table
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFMapIndexStringScalar.java
  ql/src/test/queries/clientpositive/orc_map_key_repeating.q
  ql/src/test/results/clientpositive/orc_map_key_repeating.q.out
Labels: tests unstable

#3509 HIVE-26447 (addendum): Fix orc_map_key_repeating.q.out location
  ql/src/test/results/clientpositive/llap/orc_map_key_repeating.q.out
Labels: tests passed

#3449 HIVE-26402: HiveSchemaTool does not honor metastore-site.xml
  beeline/src/java/org/apache/hive/beeline/schematool/HiveSchemaTool.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/schematool/MetastoreSchemaTool.java
Labels: tests passed

#3505 HIVE-26452: NPE when converting join to mapjoin and join column referenced more than once
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
Labels: tests passed

#3260 HIVE-26192: JDBC data connector queries occur exception at cbo stage
  ql/src/test/queries/clientpositive/dataconnector_mysql.q
  ql/src/test/results/clientpositive/llap/dataconnector_mysql.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
Labels: tests passed

#3386 HIVE-22193: Graceful Shutdown HiveServer2
  bin/ext/hiveserver2.sh
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestRestrictedList.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/session/TestQueryDisplay.java
  itests/hive-unit/src/test/java/org/apache/hive/service/server/TestGracefulStopHS2.java
  itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java
  service/src/java/org/apache/hive/service/AbstractService.java
  service/src/java/org/apache/hive/service/CompositeService.java
  service/src/java/org/apache/hive/service/Service.java
  service/src/java/org/apache/hive/service/cli/operation/OperationManager.java
  service/src/java/org/apache/hive/service/cli/session/SessionManager.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
Labels: tests passed

#3498 HIVE-24483: Bump protobuf version to 3.7.1 (aarch64 support).
  data/files/datasets/src_hbase/load.hive.sql
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/HiveHBaseTableSnapshotInputFormat.java
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/PutWritable.java
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/ResultWritable.java
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/daemon/rpc/LlapDaemonProtocolProtos.java
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/plugin/rpc/LlapPluginProtocolProtos.java
  pom.xml
  ql/src/gen/protobuf/gen-java/org/apache/hadoop/hive/ql/hooks/proto/HiveHookEvents.java
  ql/src/gen/protobuf/gen-test/org/apache/hadoop/hive/ql/io/protobuf/SampleProtos.java
  ql/src/java/org/apache/tez/dag/history/logging/proto/ProtoMessageWritable.java
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#3511 HIVE-26460: Upgrade Iceberg dependency to 0.14.0
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergRecordWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergRollback.java
  iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_writes.q
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_metadata_tables.q.out
  iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
  iceberg/pom.xml
Labels: tests passed

#3304 HIVE-26246: Filter out results 'show connectors' on HMS client-side
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/AuthorizationMetaStoreFilterHook.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HivePrivilegeObjectUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/DefaultMetaStoreFilterHookImpl.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreFilterHook.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/FilterUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestFilterHooks.java
Labels: tests passed

#3515 HIVE-26466: NullPointerException on HiveQueryLifeTimeHook:checkAndRollbackCTAS
  ql/src/java/org/apache/hadoop/hive/ql/HiveQueryLifeTimeHook.java
Labels: tests passed

#3499 HIVE-26446: HiveProtoLoggingHook fails to populate TablesWritten fiel…
  ql/src/java/org/apache/hadoop/hive/ql/hooks/HiveProtoLoggingHook.java
  ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveProtoLoggingHook.java
Labels: tests passed

#3312 HIVE-26248: Add data connector authorization on HMS server-side
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizableEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterDataConnectorEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateDataConnectorEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropDataConnectorEvent.java
  ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/PreAlterDataConnectorEvent.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/PreDropDataConnectorEvent.java
Labels: tests passed

#3467 HIVE-26415 : Add epoch time in the information_schema.scheduled_executions view
  metastore/scripts/upgrade/hive/hive-schema-4.0.0-alpha-2.hive.sql
  metastore/scripts/upgrade/hive/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.hive.sql
  ql/src/test/results/clientpositive/llap/sysdb.q.out
Labels: tests unstable

#3527 HIVE-26478: Explicitly set Content-Type in QueryProfileServlet
  service/src/java/org/apache/hive/service/servlet/QueryProfileServlet.java
Labels: tests passed

#3533 HIVE-26483: Use DDL_NO_LOCK when running iceberg CTAS query
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#3541 HIVE-26363: converting replLogger time format from epoch to UTC
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/AtlasDumpBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/AtlasDumpEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpFunction.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpTable.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/IncrementalDumpBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/IncrementalDumpEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/IncrementalDumpEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/RangerDumpBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/RangerDumpEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/AtlasLoadBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/AtlasLoadEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadFunction.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadTable.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/DataCopyEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadEnd.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/RangerLoadBegin.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/RangerLoadEnd.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/TestReplStateLogTimeFormat.java
Labels: tests pending

#3489 HIVE-26407: Do not compute statistics if the compaction fails
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#3524 HIVE-26472: Allocate new writeIds during re-compilation
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManagerImpl.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AllocateTableWriteIdsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AllocateTableWriteIdsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#3433 HIVE-26294: Allow substr to take bigint params
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFSubstr.java
  ql/src/test/queries/clientpositive/udf_substr.q
  ql/src/test/results/clientpositive/llap/udf_substr.q.out
  ql/src/test/results/compiler/errors/invalid_function_param2.q.out
Labels: tests passed

#3537 HIVE-26487: Auto-compaction may hang or skip some of the eligible items
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Labels: tests passed

#3528 HIVE-26479: Add ability to set parameters for query-based compaction
  common/src/java/org/apache/hadoop/hive/common/StringableMap.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMRCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactorMRJobQueueConfiguration.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/StringableMap.java
Labels: tests passed

#3525 HIVE-26476: map ORCFILE to ORC while creating an iceberg table
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
  iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out
Labels: tests passed

#3531 HIVE-26481:Cleaner fails with FileNotFoundException
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
  common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HdfsUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/FileOperations.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#3558 HIVE-26506: HiveIcebergVectorizedRecordReader doesn't set the selected array
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveIcebergVectorizedRecordReader.java
  iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q
  iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out
Labels: tests passed

#3529 HIVE-26480: Improve SYS.COMPACTIONS and SYS.TRANSACTIONS views
  metastore/scripts/upgrade/hive/hive-schema-4.0.0-alpha-2.hive.sql
  metastore/scripts/upgrade/hive/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.hive.sql
  ql/src/test/queries/clientpositive/sysdb.q
Labels: tests passed
