Repository apache/hive, pull requests merged in 2023-01, with the labels that each got.

#3872 HIVE-26868: Iceberg: Allow IOW on empty table with Partition Evolution.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
Labels: tests passed

#3795 HIVE-23559: Optimise Hive::moveAcidFiles for cloud storage.
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Labels: tests passed

#3814 HIVE-26790: update protobuf/grpc versions
  pom.xml
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#3614 HIVE-26555 Read-only mode for Hive database
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/EnforceReadOnlyDatabaseHook.java
  ql/src/test/queries/clientnegative/read_only_delete.q
  ql/src/test/queries/clientnegative/read_only_insert.q
  ql/src/test/queries/clientpositive/read_only_hook.q
  ql/src/test/results/clientnegative/read_only_delete.q.out
  ql/src/test/results/clientnegative/read_only_insert.q.out
  ql/src/test/results/clientpositive/llap/read_only_hook.q.out
Labels: tests passed

#3887 HIVE-26875: Preserve query context on transaction conflict
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Labels: tests passed

#3863 HIVE-25707: SchemaTool may leave the metastore in-between upgrade steps
  beeline/src/java/org/apache/hive/beeline/schematool/HiveSchemaTool.java
Labels: tests passed

#3895 HIVE-26890 : Disable TestSSL#testConnectionWrongCertCN (Done as part of HIVE-22621 in master)
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestSSL.java
Labels: tests unstable

#3854 HIVE-26837 CTLT with hive.create.as.external.legacy as true creates m…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestCtltExternalDir.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/ctlt_translate_external.q
  ql/src/test/results/clientpositive/llap/ctlt_translate_external.q.out
Labels: tests passed

#3759 HIVE-26719: Ability to set number of buckets manually
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  metastore/scripts/upgrade/hive/hive-schema-4.0.0.hive.sql
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/concatenate/AlterTableConcatenateAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MRCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/RebalanceQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/results/clientpositive/llap/dbtxnmgr_compact1.q.out
  ql/src/test/results/clientpositive/llap/dbtxnmgr_compact2.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
  ql/src/test/results/clientpositive/tez/acid_vectorization_original_tez.q.out
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionInfoStruct.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionInfoStruct.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-4.0.0-alpha-2-to-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-4.0.0-alpha-2-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-4.0.0-alpha-2-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-4.0.0-alpha-2-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-4.0.0-alpha-2-to-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/test/resources/sql/postgres/upgrade-3.1.3000-to-4.0.0.postgres.sql
Labels: tests passed

#3919 HIVE-26065: fix incorrect metric active_calls_alter_partitions and active_calls_alter_partition
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#3917 HIVE-23622: Fix orc_merge9
  data/files/alltypesorc_voriginal
  ql/src/test/queries/clientpositive/orc_merge9.q
  ql/src/test/results/clientpositive/llap/orc_merge9.q.out
Labels: tests passed

#3902 HIVE-26899 : Backport HIVE-20751 HIVE-23987 Upgrade arrow to 0.11.0 in branch-3
  pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
  ql/src/test/org/apache/hadoop/hive/ql/io/arrow/TestArrowColumnarBatchSerDe.java
Labels: tests unstable

#3912 HIVE-26906 : Backport of HIVE-19313 : TestJdbcWithDBTokenStoreNoDoAs tests are failing (Peter …
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbcWithDBTokenStore.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbcWithDBTokenStoreNoDoAs.java
Labels: tests unstable

#3873 HIVE-26869 : Backport of HIVE-19104: Fix TestHS2ImpersonationWithRemoteMS.testImpersonation
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/cli/TestPermsGrp.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatMultiOutputFormat.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatPartitionPublish.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetaStore.java
Labels: tests unstable

#3913 HIVE-26907 : Backport of HIVE-20741: Disable udaf_context_ngrams.q and udaf_corr.q tests
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
Labels: tests unstable

#3914 HIVE-26909 : Backport of HIVE-20715: Disable test: udaf_histogram_numeric
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
Labels: tests pending

#3888 HIVE-26882: Allow transactional check of Table parameter before altering the Table
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AlterTableRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AlterTableRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Constant.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Labels: tests passed

#3916 HIVE-26903: Compactor threads should gracefully shutdown
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Labels: tests passed

#3926 HIVE-26912: Publish SBOM artifacts
  pom.xml
Labels: tests passed

#3775 HIVE-26718: Enable initiator to schedule rebalancing compactions
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#3908 HIVE-11495: Add aborted reason to transaction information
  ql/src/java/org/apache/hadoop/hive/metastore/SynchronizedMetaStoreClient.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/process/abort/AbortTransactionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AbortTxnRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AbortTxnsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AbortTxnRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AbortTxnsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/protobuf/org/apache/hadoop/hive/metastore/hive_metastore.proto
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/Msck.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnErrorMsg.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
  streaming/src/java/org/apache/hive/streaming/TransactionBatch.java
Labels: tests passed

#3931 HIVE-26917: Upgrade parquet to 1.12.3.
  pom.xml
Labels: tests passed

#3859 HIVE-26840 : Branch 3 netty upgrade to 4.1.69.Final.
  common/pom.xml
  druid-handler/pom.xml
  hbase-handler/pom.xml
  hcatalog/core/pom.xml
  hcatalog/hcatalog-pig-adapter/pom.xml
  hcatalog/webhcat/java-client/pom.xml
  hcatalog/webhcat/svr/pom.xml
  itests/hcatalog-unit/pom.xml
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java
  itests/hive-minikdc/pom.xml
  itests/hive-unit/pom.xml
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestTriggersMoveWorkloadManager.java
  itests/qtest-druid/pom.xml
  itests/qtest/pom.xml
  itests/util/pom.xml
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  jdbc/pom.xml
  llap-server/pom.xml
  llap-tez/pom.xml
  metastore/pom.xml
  packaging/pom.xml
  pom.xml
  ql/pom.xml
  serde/pom.xml
  shims/common/pom.xml
  spark-client/src/test/java/org/apache/hive/spark/client/TestSparkClient.java
  standalone-metastore/pom.xml
Labels: tests failed

#3763 HIVE-26558 Small test fix in TestReplicationOptimisedBootstrap to mak…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
Labels: tests passed

#3933 HIVE-26913: HiveVectorizedReader::parquetRecordReader should reuse footer information.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/ParquetSchemaFieldNameVisitor.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/parquet/ParquetFooterInputFromCache.java
  iceberg/iceberg-shading/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/VectorizedParquetInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/ParquetRecordReaderWrapper.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
Labels: tests passed

#3921 HIVE-22628: Add locks and transactions tables from sys db to information_schema
  metastore/scripts/upgrade/hive/hive-schema-4.0.0.hive.sql
  ql/src/test/queries/clientpositive/sysdb.q
  ql/src/test/results/clientpositive/llap/resourceplan.q.out
  ql/src/test/results/clientpositive/llap/strict_managed_tables_sysdb.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
Labels: tests passed

#3899 HIVE-26860: Entries in HMS tables are not deleted upon drop partition table with skewed columns
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#3943 HIVE-26882: Allow transactional check of Table parameter before altering the Table (#3888) (Peter Vary reviewed by Prasanth Jayachandran and Szehon Ho)
  standalone-metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/src/gen/thrift/gen-php/metastore/Types.php
  standalone-metastore/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/src/main/thrift/hive_metastore.thrift
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Labels: tests unstable

#3944 HIVE-26882: Allow transactional check of Table parameter before altering the Table (#3888) (Peter Vary reviewed by Prasanth Jayachandran and Szehon Ho)
  standalone-metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/src/gen/thrift/gen-php/metastore/Types.php
  standalone-metastore/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/src/main/thrift/hive_metastore.thrift
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Labels: tests unstable

#3946 HIVE-26882: Allow transactional check of Table parameter before altering the Table (#3888) (Peter Vary reviewed by Prasanth Jayachandran and Szehon Ho)
  metastore/if/hive_metastore.thrift
  metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  metastore/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  metastore/src/gen/thrift/gen-php/metastore/Types.php
  metastore/src/gen/thrift/gen-py/hive_metastore/constants.py
  metastore/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  metastore/src/java/org/apache/hadoop/hive/metastore/DefaultPartitionExpressionProxy.java
  metastore/src/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  metastore/src/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  metastore/src/java/org/apache/hadoop/hive/metastore/RawStore.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/ConstraintBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/DatabaseBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/FunctionBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/GrantRevokePrivilegeRequestBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/HiveObjectPrivilegeBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/HiveObjectRefBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/IndexBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/PartitionBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/PrivilegeGrantInfoBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/RoleBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/SQLForeignKeyBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/SQLPrimaryKeyBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/StorageDescriptorBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/TableBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/utils/SecurityUtils.java
  metastore/src/test/org/apache/hadoop/hive/metastore/client/MetaStoreFactoryForTests.java
  metastore/src/test/org/apache/hadoop/hive/metastore/client/TestDatabases.java
  metastore/src/test/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/AbstractMetaStoreService.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/ClusterMetaStoreForTests.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/EmbeddedMetaStoreForTests.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/MiniHMS.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/RemoteMetaStoreForTests.java
Labels: tests pending

#3947 HIVE-26882: Allow transactional check of Table parameter before altering the Table (#3888) (Peter Vary reviewed by Prasanth Jayachandran and Szehon Ho)
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  metastore/if/hive_metastore.thrift
  metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  metastore/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  metastore/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  metastore/src/gen/thrift/gen-php/metastore/Types.php
  metastore/src/gen/thrift/gen-py/hive_metastore/constants.py
  metastore/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  metastore/src/java/org/apache/hadoop/hive/metastore/DefaultPartitionExpressionProxy.java
  metastore/src/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  metastore/src/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  metastore/src/java/org/apache/hadoop/hive/metastore/RawStore.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/ConstraintBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/DatabaseBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/FunctionBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/GrantRevokePrivilegeRequestBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/HiveObjectPrivilegeBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/HiveObjectRefBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/IndexBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/PartitionBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/PrivilegeGrantInfoBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/RoleBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/SQLForeignKeyBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/SQLPrimaryKeyBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/StorageDescriptorBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/client/builder/TableBuilder.java
  metastore/src/java/org/apache/hadoop/hive/metastore/hbase/HBaseStore.java
  metastore/src/java/org/apache/hadoop/hive/metastore/utils/SecurityUtils.java
  metastore/src/test/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  metastore/src/test/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
  metastore/src/test/org/apache/hadoop/hive/metastore/client/MetaStoreFactoryForTests.java
  metastore/src/test/org/apache/hadoop/hive/metastore/client/TestDatabases.java
  metastore/src/test/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/AbstractMetaStoreService.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/ClusterMetaStoreForTests.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/EmbeddedMetaStoreForTests.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/MiniHMS.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/RemoteMetaStoreForTests.java
Labels: tests unstable

#3937 HIVE-26927: Iceberg: Add support for set_current_snapshotid.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSetCurrentSnapshot.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Labels: tests passed

#3940 HIVE-26936: Floating point zero and signed zero comparison as a part of join predicate is considered as not equal.
  ql/src/java/org/apache/hadoop/hive/ql/exec/HiveWritableComparator.java
  ql/src/test/queries/clientpositive/join_cond_zero_comp_negativezero.q
  ql/src/test/results/clientpositive/llap/join_cond_zero_comp_negativezero.q.out
Labels: tests passed

#3952 HIVE-26944: FileSinkOperator shouldn't check for compactiontable for …
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
Labels: tests passed

#3920 HIVE-26911: Renaming a translated external table with a specified loc…
  ql/src/test/queries/clientpositive/rename_translated_external_table.q
  ql/src/test/results/clientpositive/llap/rename_translated_external_table.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
Labels: tests passed

#3788 HIVE-26597: Fix unsetting of db property repl.target.for in ReplicationSemanticAnalyzer
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
Labels: tests passed

#3935 HIVE-26717: Query based Rebalance compaction on insert-only tables
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#3953 HIVE-26943 : Fix NPE during Optimised Bootstrap when db is dropped
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Labels: tests pending

#3928 HIVE-26915: Disable TestCodahaleMetrics.testFileReporting flaky
  common/src/test/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleMetrics.java
Labels: tests unstable

#3936 HIVE-26924: Alter materialized view enable rewrite throws SemanticException for source iceberg table
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rewrite/AlterMaterializedViewRewriteAnalyzer.java
Labels: tests passed

#3716 HIVE-26681:Remove dom4j: flexible XML framework for Java from hive
  service/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#3934 HIVE-26922: Deadlock when rebuilding Materialized view stored by Iceberg
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc2.q
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc3.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc2.q.out
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc3.q.out
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/StorageHandlerMock.java
Labels: tests passed

#3736 HIVE-26711 The very first REPL Load should make the Target Database read-only.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplWithReadOnlyHook.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
Labels: tests passed

#3780 HIVE-26598: Fix unsetting of db params for optimized bootstrap when r…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpWork.java
Labels: tests passed, stale

#3882 HIVE-26802 Create qtest that runs the queries that query-based compac…
  itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniLlapLocalCompactorCliDriver.java
  itests/src/test/resources/testconfiguration.properties
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/AbstractCliConfig.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreCliDriver.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestArguments.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
  ql/src/test/queries/clientpositive/compaction_query_based.q
  ql/src/test/queries/clientpositive/compaction_query_based_clustered.q
  ql/src/test/queries/clientpositive/compaction_query_based_clustered_minor.q
  ql/src/test/queries/clientpositive/compaction_query_based_insert_only.q
  ql/src/test/queries/clientpositive/compaction_query_based_insert_only_minor.q
  ql/src/test/queries/clientpositive/compaction_query_based_minor.q
  ql/src/test/results/clientpositive/llap/compaction_query_based.q.out
  ql/src/test/results/clientpositive/llap/compaction_query_based_clustered.q.out
  ql/src/test/results/clientpositive/llap/compaction_query_based_clustered_minor.q.out
  ql/src/test/results/clientpositive/llap/compaction_query_based_insert_only.q.out
  ql/src/test/results/clientpositive/llap/compaction_query_based_insert_only_minor.q.out
  ql/src/test/results/clientpositive/llap/compaction_query_based_minor.q.out
Labels: tests passed

#3915 HIVE-26908 - Disable Initiator on HMS instance at the same time enabl…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/MetastoreHousekeepingLeaderTestBase.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactorBase.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/CompactorTasks.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/AcidHouseKeeperService.java
Labels: tests passed

#3910 HIVE-26904: commitCompaction of query-based compaction should not fail when tmp table dirs are already cleaned up
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
Labels: tests passed

#3939 HIVE-26925: MV with iceberg storage format fails when contains 'PARTITIONED ON' clause due to column number/types difference.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc2.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc2.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Labels: tests passed

#3951 HIVE-26942 : Prevent updation of "repl.target.last.id" when RESUME action initiated
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#3964 HIVE-26955: Select query fails when decimal column data type is change…
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/convert/ETypeConverter.java
  ql/src/test/queries/clientpositive/parquet_alter_column_type.q
  ql/src/test/results/clientpositive/llap/parquet_alter_column_type.q.out
Labels: tests passed

#3967 HIVE-26967: Deadlock when enabling/disabling Materialized view stored by Iceberg
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc2.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc2.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rewrite/AlterMaterializedViewRewriteAnalyzer.java
Labels: tests passed

#3962 HIVE-26928: LlapIoImpl::getParquetFooterBuffersFromCache throws excep…
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
  iceberg/iceberg-handler/src/test/queries/positive/llap_cache_disabled.q
  iceberg/iceberg-handler/src/test/results/positive/llap_cache_disabled.q.out
  llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
Labels: tests passed

#3922 HIVE-26453: INSERT ... VALUES with BINARY type returns error
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeConstantDesc.java
  ql/src/test/queries/clientpositive/insert_cast_binary.q
  ql/src/test/results/clientpositive/llap/insert_cast_binary.q.out
Labels: tests passed

#3900 HIVE-26895 : Backport of HIVE-22899: Make sure qtests clean up copied files from test directories
  ql/src/test/queries/clientnegative/strict_managed_tables4.q
  ql/src/test/queries/clientpositive/avro_add_column_extschema.q
  ql/src/test/queries/clientpositive/avro_alter_table_update_columns.q
  ql/src/test/queries/clientpositive/avro_tableproperty_optimize.q
  ql/src/test/queries/clientpositive/avrotblsjoin.q
  ql/src/test/queries/clientpositive/compustat_avro.q
  ql/src/test/queries/clientpositive/stats_noscan_2.q
  ql/src/test/results/clientpositive/avro_add_column_extschema.q.out
  ql/src/test/results/clientpositive/avro_alter_table_update_columns.q.out
  ql/src/test/results/clientpositive/avro_tableproperty_optimize.q.out
  ql/src/test/results/clientpositive/avrotblsjoin.q.out
  ql/src/test/results/clientpositive/compustat_avro.q.out
  ql/src/test/results/clientpositive/spark/stats_noscan_2.q.out
  ql/src/test/results/clientpositive/stats_noscan_2.q.out
Labels: tests unstable

#3971 HIVE-26969 : Backport of HIVE-20074: Disable TestTriggersWorkloadManager as it is unstable
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestTriggersWorkloadManager.java
Labels: tests pending

#3972 HIVE-26970 : Fixes for some test failures with LLAP Driver
  ql/src/test/results/clientpositive/llap/results_cache_2.q.out
  ql/src/test/results/clientpositive/llap/sharedwork.q.out
  ql/src/test/results/clientpositive/llap/subquery_views.q.out
  testutils/ptest2/src/main/resources/log4j2.properties
  testutils/ptest2/src/test/resources/log4j2.properties
Labels: tests unstable

#3883 HIVE-24404: Invoke getUserName before getMSC to avoid metastore client connection been closed and retry
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Labels: tests passed

#3965 HIVE-26950: Iceberg: (CTLT) Create external table like V2 table is not preserving table properties.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/positive/ctlt_iceberg.q
  iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Labels: tests passed

#3836 HIVE-23891: UNION ALL and multiple task attempts can cause file duplication
  ql/src/java/org/apache/hadoop/hive/ql/exec/AbstractFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/io/rcfile/truncate/ColumnTruncateMapper.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestFileSinkOperator.java
Labels: tests passed

#3801 HIVE-22977: Merge delta files instead of running a query in major/min…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionPoolOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Compactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorContext.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorPipeline.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MRCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MergeCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/OrcFileMerger.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/RebalanceQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#3822 HIVE-26793: Create a new configuration to override 'no compaction' for tables
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics2.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactorBase.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator2.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
Labels: tests passed

#3976 HIVE-26976: Failure in direct SQL processing do not undo the changes made to database before fallback to JDO
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Labels: tests passed

#3985 HIVE-26989 Fix predicate pushdown for Timestamp with TZ
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerTimezone.java
  ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java
Labels: tests passed

#3696 HIVE-26661: Support partition filter for char and varchar types on Hive metastore
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
Labels: tests passed

#3817 HIVE-26794: Explore retiring TxnHandler#connPoolMutex idle connections
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
Labels: tests passed

#3963 HIVE-26599: Registering Tables metric during second cycle of optimise…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#3955 HIVE-26947: Handle compaction.Worker sleep for err cases to avoid high frequency connection respawning to HMS
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Labels: tests passed

#3945 HIVE-26991 - Typos in hive-exec
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLTask.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AbstractCreateViewAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ScheduledQueryAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#3941 HIVE-26939 : Changed placement policy from NODE to node
  llap-server/src/main/resources/templates.py
Labels: tests passed

#3975 HIVE-26973 : Test fixes for subquery_subquery_chain.q
  ql/src/test/results/clientnegative/subquery_subquery_chain.q.out
Labels: tests unstable

#3974 HIVE-26972 : orc_map_key_repeating.q failing due to wrong directory structure being commited in HIVE-26819
  ql/src/test/results/clientpositive/orc_map_key_repeating.q.out
Labels: tests unstable

#3984 HIVE-26933: Cleanup dump directory for eventId which was failed in previous dump cycle
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#3991 HIVE-26600: Handle failover during optimized bootstrap
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#3988 HIVE-26995: Iceberg: Enhance time travel syntax with expressions
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTimeTravel.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#3980 HIVE-26974: Iceberg: CTL from iceberg table should copy partition fields correctly.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/positive/ctlt_iceberg.q
  iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
Labels: tests passed

#3893 HIVE-26774 - Implement array_slice UDF to get the subset of elements from an array (subarray)
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/AbstractGenericUDFArrayBase.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArraySlice.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArraySlice.java
  ql/src/test/queries/clientpositive/udf_array_slice.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_slice.q.out
Labels: tests passed

#3993 HIVE-26980: Creation of materialized view stored by Iceberg fails if …
  iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_orc.q
  iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_orc.q.out
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#4001 HIVE-26793: Create a new configuration to override "no compaction" for tables
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Constant.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Labels: tests passed
