Repository apache/hive, pull requests merged in 2023-09, with the labels that each got.

#4622 HIVE-27632: Added annotation for decimal64 support for coalesce
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFCoalesce.java
  ql/src/test/queries/clientpositive/vector_coalesce.q
  ql/src/test/results/clientpositive/llap/vector_coalesce.q.out
Labels: tests passed

#4631 HIVE-21213: Acid table bootstrap replication needs to handle director…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/CopyUtils.java
Labels: tests passed

#4536 HIVE-27539: Drop renamed external table fails when hive.metastore.try.direct.sql.ddl is disabled
  ql/src/test/queries/clientpositive/alter_table_column_stats.q
  ql/src/test/results/clientpositive/llap/alter_table_column_stats.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
Labels: tests passed

#4584 HIVE-27605 : Backport of HIVE-19661 to branch-3
  LICENSE
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFRegExp.java
Labels: tests passed

#4662 HIVE-27667: Fix get partitions with max_parts
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#4643 HIVE-27657: Change hive.fetch.task.conversion.threshold default value
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests passed

#4571 HIVE-27627: Iceberg: Insert into/overwrite partition support
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_into_partition.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_into_partition_transforms.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_into_partition_with_evolution.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_overwrite_partition.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_overwrite_partition_transforms.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition_transforms.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition_with_evolution.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_overwrite_partition.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_overwrite_partition_transforms.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/DummyPartition.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#4646 HIVE-27659: Make partition order configurable if the metastore does not return all partitions
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#4572 HIVE-27525:Ease the write permissions on external table during create table operation
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateTableEvent.java
  ql/src/test/queries/clientpositive/auth_create_ext_table_1.q
  ql/src/test/results/clientpositive/llap/auth_create_ext_table_1.q.out
Labels: tests passed

#4667 HIVE-27665: Change HMS PartitionFilter to allow backticks surrounding…
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/PartFilterVisitor.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/PartitionFilter.g4
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartFilterExprUtil.java
Labels: tests passed

#4448 HIVE-27461: HiveMetaStoreAuthorizer lost the root cause of checkPrivileges
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
Labels: tests passed

#4621 HIVE-27113: Increasing default for hive.thrift.client.max.message.size to 2GB
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestRemoteHiveMetaStoreKerberos.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestSSLWithMiniKdc.java
  service/src/java/org/apache/hive/service/cli/thrift/RetryingThriftCLIServiceClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#4671 HIVE-21213: Update integration test to mark compactions as complete i…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
Labels: tests passed

#4666 HIVE-27661: Auth mode inferred from the Authorization header
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestIsAuthTypeEnabled.java
  jdbc/src/java/org/apache/hive/jdbc/HttpBasicAuthInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/HttpKerberosRequestInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/HttpRequestInterceptorBase.java
  jdbc/src/java/org/apache/hive/jdbc/HttpTokenAuthInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/jwt/HttpJwtAuthRequestInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/saml/HttpSamlAuthRequestInterceptor.java
  service/src/java/org/apache/hive/service/auth/AuthType.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
  service/src/test/org/apache/hive/service/auth/TestAuthType.java
Labels: tests passed

#4511 HIVE-27480: OFFSET without ORDER BY generates wrong results
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientnegative/strict_offset_without_orderby.q
  ql/src/test/queries/clientnegative/strict_offset_without_orderby2.q
  ql/src/test/queries/clientpositive/offset_limit_without_order_by.q
  ql/src/test/results/clientnegative/strict_offset_without_orderby.q.out
  ql/src/test/results/clientnegative/strict_offset_without_orderby2.q.out
  ql/src/test/results/clientpositive/llap/limit_join_transpose.q.out
  ql/src/test/results/clientpositive/llap/offset_limit_ppd_optimizer.q.out
  ql/src/test/results/clientpositive/llap/offset_limit_without_order_by.q.out
  ql/src/test/results/clientpositive/llap/parquet_vectorization_offset_limit.q.out
  ql/src/test/results/clientpositive/llap/vector_windowing_order_null.q.out
  ql/src/test/results/clientpositive/llap/vectorization_offset_limit.q.out
Labels: tests passed

#4641 HIVE-27654: Iceberg: Cherry-Pick commit to a branch.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCherryPick.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Labels: tests passed

#4635 HIVE-26127: Insert overwrite throws FileNotFound when destination partition is deleted
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Labels: tests passed

#4665 HIVE-27669: Hive Acid CTAS fails incremental if no of rows inserted is > INT_MAX
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
Labels: tests passed

#4663 HIVE-27668 : Backport of HIVE-21126 to branch-3
  llap-ext-client/src/java/org/apache/hadoop/hive/llap/LlapBaseInputFormat.java
Labels: tests passed

#4659 HIVE-27388: Backport of HIVE-23058: Compaction task reattempt fails with FileAlreadyExistsExc…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
Labels: tests passed

#4661 HIVE-27666: Backport of HIVE-22903 : Vectorized row_number() resets the row number after one batch in case of constant expression in partition clause
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java
  ql/src/test/queries/clientpositive/vector_windowing_row_number.q
  ql/src/test/results/clientpositive/vector_windowing_row_number.q.out
Labels: tests passed

#4680 HIVE-27670: Failed to build the image locally on Apple silicon
  packaging/src/docker/README.md
  packaging/src/docker/build.sh
  packaging/src/docker/entrypoint.sh
Labels: tests passed

#4630 HIVE-17350: metrics errors when retrying HS2 startup
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/CodahaleMetrics.java
  standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleReportersConf.java
Labels: tests passed

#4633 HIVE-27648: CREATE TABLE with CHECK constraint fails with SemanticException
  parser/src/java/org/apache/hadoop/hive/ql/parse/Quotation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/ConstraintsUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UnparseTranslator.java
  ql/src/test/queries/clientpositive/quotedid_basic.q
  ql/src/test/queries/clientpositive/quotedid_basic_standard.q
  ql/src/test/results/clientnegative/check_constraint_aggregate.q.out
  ql/src/test/results/clientnegative/check_constraint_max_length.q.out
  ql/src/test/results/clientnegative/check_constraint_nonboolean_expr.q.out
  ql/src/test/results/clientnegative/check_constraint_qual_name.q.out
  ql/src/test/results/clientnegative/check_constraint_temporary_udf.q.out
  ql/src/test/results/clientnegative/check_constraint_window_fun.q.out
  ql/src/test/results/clientpositive/llap/check_constraint.q.out
  ql/src/test/results/clientpositive/llap/quotedid_basic.q.out
  ql/src/test/results/clientpositive/llap/quotedid_basic_standard.q.out
  ql/src/test/results/clientpositive/llap/show_create_table.q.out
Labels: tests passed

#4642 HIVE-27656: Upgrade jansi.version to 2.4.0
  pom.xml
Labels: tests passed

#4673 HIVE-27322: Iceberg: metadata location overrides can cause data breach.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#4695 Revert "HIVE-27113: Increasing default for hive.thrift.client.max.message.size to 2GB"
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestRemoteHiveMetaStoreKerberos.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestSSLWithMiniKdc.java
  service/src/java/org/apache/hive/service/cli/thrift/RetryingThriftCLIServiceClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#4363 HIVE-24606: Multi-stage materialized CTEs can lose intermediate data
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/cte_mat_10.q
  ql/src/test/queries/clientpositive/cte_mat_8.q
  ql/src/test/queries/clientpositive/cte_mat_9.q
  ql/src/test/results/clientpositive/llap/cte_mat_10.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_8.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_9.q.out
Labels: tests passed, stale

#4115 HIVE-27138: Extend RSOp to compute filterTag if it has child MapJoinOp
  ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/MapJoinBytesTableContainer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConvertJoinMapJoin.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/FiltertagAppenderProc.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/FullOuterMapJoinOptimization.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFBaseArithmetic.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFBaseNumeric.java
  ql/src/test/queries/clientpositive/mapjoin_filter_on_outerjoin_tez.q
  ql/src/test/results/clientpositive/llap/fullouter_mapjoin_1_optimized.q.out
  ql/src/test/results/clientpositive/llap/mapjoin_filter_on_outerjoin_tez.q.out
  ql/src/test/results/clientpositive/llap/vector_fullouter_mapjoin_1_fast.q.out
  ql/src/test/results/clientpositive/llap/vector_fullouter_mapjoin_1_optimized.q.out
  ql/src/test/results/clientpositive/llap/vector_fullouter_mapjoin_1_optimized_passthru.q.out
  ql/src/test/results/clientpositive/llap/vector_outer_join_constants.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query97.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinaryStruct.java
Labels: tests passed

#4697 HIVE-27558: HBase table query does not push BETWEEN predicate to storage layer
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseStorageHandler.java
  hbase-handler/src/test/queries/positive/hbase_between_pushdown.q
  hbase-handler/src/test/results/positive/hbase_between_pushdown.q.out
Labels: tests passed

#4691 HIVE-27675: Support keystore/truststore types for hive/zookeeper i…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/tool/ZooKeeperStorage.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/security/ZooKeeperTokenStoreTestBase.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestRestrictedList.java
  itests/hive-unit/src/test/java/org/apache/hive/service/server/InformationSchemaWithPrivilegeTestBase.java
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
  jdbc/src/java/org/apache/hive/jdbc/ZooKeeperHiveClientHelper.java
  llap-client/src/java/org/apache/hadoop/hive/registry/impl/ZkRegistryBase.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/SSLZookeeperFactory.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/ZooKeeperHiveHelper.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/MetastoreDelegationTokenManager.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/ZooKeeperTokenStore.java
Labels: tests passed

#4686 HIVE-27644 : Backport of HIVE-17917, HIVE-21457, HIVE-22582
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveContextAwareRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSplit.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
  ql/src/test/queries/clientpositive/acid_vectorization_original.q
  ql/src/test/results/clientpositive/llap/acid_vectorization_original.q.out
Labels: tests passed

#4651 HIVE-27664: AlterTableSetLocationAnalyzer threw a confusing exception…
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/set/location/AlterTableSetLocationAnalyzer.java
  ql/src/test/results/clientnegative/alter_table_wrong_location.q.out
Labels: tests passed

#4548 HIVE-27564 : Add log for ZooKeeperTokenStore to trace the lifecycle of tokenPath
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/ZooKeeperTokenStore.java
Labels: tests passed

#4702 HIVE-27694: Include HiveIcebergSerDe in the default list of serdes us…
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#4706 HIVE-27696: Docker build from source should include iceberg profile.
  packaging/src/docker/build.sh
Labels: tests passed

#4708 HIVE-27698 : Backport of HIVE-22398: Remove legacy code that can cause issue with new Yarn releases
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit-hadoop2/src/test/java/org/apache/hive/jdbc/TestSchedulerQueue.java
  service/src/java/org/apache/hive/service/cli/session/HiveSessionImpl.java
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/SchedulerShim.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/ShimLoader.java
  shims/scheduler/src/main/java/org/apache/hadoop/hive/schshim/FairSchedulerShim.java
Labels: tests passed

#4729 HIVE-27715 : Backport of HIVE-25235: Remove ThreadPoolExecutorWithOomHook to branch-3
  service/src/java/org/apache/hive/service/cli/session/SessionManager.java
  service/src/java/org/apache/hive/service/cli/thrift/EmbeddedThriftBinaryCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThreadPoolExecutorWithOomHook.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  service/src/test/org/apache/hive/service/auth/TestPlainSaslHelper.java
  service/src/test/org/apache/hive/service/cli/session/TestPluggableHiveSessionImpl.java
  service/src/test/org/apache/hive/service/cli/session/TestSessionGlobalInitFile.java
Labels: tests passed

#4730 HIVE-21100: Allow flattening of table subdirectories resulted when using TEZ engine and UNION clause.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  common/src/test/org/apache/hive/common/util/MockFileSystem.java
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestMoveTask.java
  ql/src/test/queries/clientpositive/flatten_union_subdir.q
  ql/src/test/results/clientpositive/tez/flatten_union_subdir.q.out
Labels: tests passed

#4629 HIVE-27646: Iceberg: Retry query when concurrent write queries fail due to conflicting writes
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestOptimisticRetry.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteOnWriteConflictPlugin.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecutionStrategyType.java
Labels: tests passed

#4732 HIVE-27716: Precommit: Save log files for first 10 failures
  Jenkinsfile
Labels: tests unstable

#4735 HIVE-27711: Iceberg: Allow creating a branch from tag name
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergBranchExec.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergBranchOperation.java
  iceberg/iceberg-handler/src/test/queries/positive/alter_table_create_branch.q
  iceberg/iceberg-handler/src/test/results/positive/alter_table_create_branch.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/AlterTableCreateSnapshotRefAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableSnapshotRefSpec.java
Labels: tests passed

#4736 HIVE-27721 : Backport of HIVE-23396: Many fixes and improvements to stabilize tests to branch-3
  common/src/test/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleMetrics.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveRemote.java
  service/src/test/org/apache/hive/service/cli/session/TestSessionManagerMetrics.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestMarkPartition.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/client/MetaStoreClientTest.java
Labels: tests passed

#4660 HIVE-27377: Backport of HIVE-24803: WorkloadManager doesn't update allocation and metrics after Kill Trigger action
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestWMMetricsWithTrigger.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java
Labels: tests passed

#4742 HIVE-27711: Iceberg: Allow creating a branch from tag name - ADDENDUM
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergBranchExec.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergBranchOperation.java
Labels: tests passed

#4737 HIVE-27722 : Added org.bouncycastle as dependency to branch-3
  hcatalog/pom.xml
  itests/hive-unit/pom.xml
  itests/qtest-spark/pom.xml
  kryo-registrator/pom.xml
  pom.xml
  ql/pom.xml
  spark-client/pom.xml
Labels: tests passed

#4745 HIVE-27727: Materialized view query rewrite fails if query has decimal derived aggregate
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveTypeSystemImpl.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFSum.java
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_11.q
  ql/src/test/results/clientpositive/llap/decimal_precision.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_11.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6.q.out
  ql/src/test/results/clientpositive/llap/vector_decimal_precision.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query13.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query13.q.out
Labels: tests passed

#4723 HIVE-27736: Remove PowerMock from itests-jmh and upgrade mockito
  itests/hive-jmh/pom.xml
  itests/hive-jmh/src/main/java/org/apache/hive/benchmark/vectorization/mapjoin/load/AbstractHTLoadBench.java
Labels: tests passed

#4725 HIVE-27705 : Remove PowerMock from service (hive-service) and upgrade…
  service/pom.xml
  service/src/test/org/apache/hive/service/auth/ldap/TestChainFilter.java
Labels: tests passed

#4721 HIVE-27701: Remove PowerMock from llap-client
  llap-client/pom.xml
  llap-client/src/test/org/apache/hadoop/hive/llap/registry/impl/TestLlapZookeeperRegistryImpl.java
  llap-client/src/test/org/apache/hadoop/hive/registry/impl/TestZookeeperUtils.java
Labels: tests passed

#4672 HIVE-27672: Iceberg: Truncate partition support
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTruncateTable.java
  iceberg/iceberg-handler/src/test/queries/negative/truncate_iceberg_table_with_partition_spec.q
  iceberg/iceberg-handler/src/test/queries/negative/truncate_table_partition_spec_with_part_evolution.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_truncate_partition.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_truncate_partition_with_evolution.q
  iceberg/iceberg-handler/src/test/results/negative/truncate_iceberg_table_with_partition_spec.q.out
  iceberg/iceberg-handler/src/test/results/negative/truncate_table_partition_spec_with_part_evolution.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_truncate_partition.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_truncate_partition_with_evolution.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AcidExportSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SplitUpdateSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TransformSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
  serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoUtils.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: tests passed

#4747 HIVE-27729: Iceberg: Check Iceberg type in AlterTableExecuteAnalyzer
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergRollback.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Labels: tests passed

#4556 HIVE-27573: Backport of HIVE-21799 to branch-3
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/DynamicPartitionPruningOptimization.java
  ql/src/test/queries/clientpositive/dynamic_semijoin_reduction_on_aggcol.q
  ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_on_aggcol.q.out
Labels: tests passed

#4384 HIVE-27406: CompactionTxnHandler cleanup
  pom.xml
  ql/pom.xml
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java
  service/pom.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/ContextNode.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetaWrapperException.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/ProxyTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/AbortedTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/CheckFailedCompactionsHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/CleanTxnToWriteIdTableFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/CompactionCandidateHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/CompactionMetricsDataHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/FindColumnsWithStatsHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/FindPotentialCompactionsFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/GetCompactionInfoHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/InsertCompactionInfoCommand.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/MarkCleanedFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/MinUncommittedTxnIdHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/NextCompactionFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/PurgeCompactionHistoryFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/ReadyToCleanAbortHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/ReadyToCleanHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/RemoveCompactionMetricsDataCommand.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/RemoveDuplicateCompleteTxnComponentsCommand.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/TopCompactionMetricsDataPerTypeFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/impl/UpdateCompactionMetricsDataFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/MultiDataSourceJdbcResource.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/ParameterizedCommand.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/ParameterizedQuery.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/QueryHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/TransactionContext.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/TransactionContextManager.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/TransactionalFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/retryhandling/RetryPropagation.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/retryhandling/SqlRetry.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/retryhandling/SqlRetryCallProperties.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/retryhandling/SqlRetryFunction.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/retryhandling/SqlRetryHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
  standalone-metastore/pom.xml
Labels: tests passed

#4722 HIVE-27704 : Remove PowerMock from jdbc-handler and upgrade mockito to 4.11
  jdbc-handler/pom.xml
  jdbc-handler/src/test/java/org/apache/hive/storage/jdbc/TestJdbcInputFormat.java
Labels: tests passed

#4756 HIVE-27752: Remove DagUtils duplicate class
  ql/src/java/org/apache/hadoop/hive/ql/exec/DagUtils.java
Labels: tests pending

#4628 HIVE-27649: Support ORDER BY clause in subqueries with set operators
  parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
  parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseDriver.java
Labels: tests passed

#4692 HIVE-27687 Logger variable should be static final as its creation takes more time in query compilation
  contrib/src/java/org/apache/hadoop/hive/contrib/serde2/RegexSerDe.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java
  kafka-handler/src/java/org/apache/hadoop/hive/kafka/KafkaSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/AbstractEncodingAwareSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/AbstractSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/RegexSerDe.java
Labels: tests unstable
