Repository apache/hive, pull requests merged in 2023-03, with the labels that each got.

#4010 HIVE-27012:Remove JavaEWAH dependency from HIVE to fix CVEs.
  lib/README
  pom.xml
  ql/pom.xml
Labels: tests passed

#4085 HIVE-15826: Add 'serialization.encoding' To All SerDes
  contrib/src/java/org/apache/hadoop/hive/contrib/serde2/RegexSerDe.java
  contrib/src/test/queries/clientpositive/serde_regex.q
  contrib/src/test/results/clientpositive/serde_regex.q.out
  data/files/opencsv-data.txt
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java
  ql/src/test/queries/clientpositive/json_serde1.q
  ql/src/test/queries/clientpositive/serde_opencsv.q
  ql/src/test/queries/clientpositive/serde_regex.q
  ql/src/test/results/clientpositive/llap/json_serde1.q.out
  ql/src/test/results/clientpositive/llap/serde_opencsv.q.out
  ql/src/test/results/clientpositive/llap/serde_regex.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
  serde/src/java/org/apache/hadoop/hive/serde2/RegexSerDe.java
Labels: tests passed

#4072 [HIVE-27062] Disable flaky test TestRpc
  spark-client/src/test/java/org/apache/hive/spark/client/rpc/TestRpc.java
Labels: tests unstable

#4096 HIVE-27117: Fix compaction related flaky tests
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests pending

#4098 HIVE-27122: Use Caffeine for caching metadata objects in Compactor threads
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/FSRemover.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetaStoreCompactorThread.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetadataCache.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/TaskHandler.java
Labels: tests passed

#4077 HIVE-26735: Ability to sort the data during rebalancing compaction
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionPoolOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/concatenate/AlterTableConcatenateAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/RebalanceQueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionInfoStruct.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/TxnType.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionInfoStruct.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/TxnType.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnQueries.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-4.0.0-alpha-2-to-4.0.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-4.0.0-alpha-2-to-4.0.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-4.0.0-alpha-2-to-4.0.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-4.0.0-alpha-2-to-4.0.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-4.0.0-alpha-2-to-4.0.0.postgres.sql
  standalone-metastore/metastore-server/src/test/resources/sql/postgres/upgrade-3.1.3000-to-4.0.0.postgres.sql
Labels: tests passed

#4084 HIVE-27107 : Fix improper metrics count for RESUME/RESET workflow
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Labels: tests passed

#4100 HIVE-27123 : In PRE_OPTIMIZED_BOOTSTRAP operation, Load side stores dump_execution_id as -1
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/OptimisedBootstrapUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWorkMBean.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/DumpMetaData.java
Labels: tests passed

#4083 HIVE-27106. Improve TezSessionPoolManager#getSession Log.
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolManager.java
Labels: tests passed

#4088 HIVE-27013: Iceberg: Provide an option to enable iceberg manifest caching for all catalogs.
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestCatalogs.java
Labels: tests passed

#4054 HIVE-27074: Make IMetaStoreClient extends AutoCloseable
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
Labels: tests passed

#4092 HIVE-27116: HS2 need to send owner info for UDFs in the HivePrivilege…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestCreateUdfEntities.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/function/AbstractFunctionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/Entity.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/ReadEntity.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
  ql/src/test/results/clientpositive/llap/authorization_functions_in_views.q.out
Labels: tests passed

#4104 HIVE-27129: Add enhanced support for Hive Metastore Client http support
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetastoreHttpHeaders.java
Labels: tests passed

#4079 HIVE-27101: Support incremental materialized view rebuild when Iceberg source tables have insert operation only.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc2.q
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc4.q
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc5.q
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc6.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc2.q.out
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc4.q.out
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc5.q.out
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc6.q.out
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/SerializableTable.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/VirtualColumn.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveTableScan.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAugmentSnapshotMaterializationRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HivePushdownSnapshotFilterRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QB.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBSystemVersion.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
  storage-api/src/java/org/apache/hadoop/hive/common/type/SnapshotContext.java
Labels: tests passed

#4105 HIVE-27130: Add metrics to report the size of data replicated/copied
  common/src/java/org/apache/hadoop/hive/common/DataCopyStatistics.java
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
  common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java
  itests/hive-unit-hadoop2/src/test/java/org/apache/hadoop/hive/common/TestFileUtils.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosIncrementalLoadAcidTables.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/CopyTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ReplCopyTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/CopyUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/ReplicationMetricCollector.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/Metadata.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/TestCopyUtils.java
  ql/src/test/results/clientpositive/llap/replication_metrics_ingest.q.out
Labels: tests passed

#4067 HIVE-27087: Fix TestMiniSparkOnYarnCliDriver test failures on branch-3
  itests/qtest-spark/pom.xml
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
  pom.xml
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestMetrics.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/testutils/CapturingLogAppender.java
  standalone-metastore/src/test/resources/log4j2.properties
Labels: tests unstable

#4118 HIVE-27137: Remove HIVE_IN_TEST_ICEBERG flag
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  data/conf/iceberg/llap/hive-site.xml
  data/conf/iceberg/tez/hive-site.xml
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Labels: tests passed

#3996 HIVE-26999:Upgrade MySQL Connector Java due to security CVE
  itests/qtest/pom.xml
  pom.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#4117 HIVE-27140 : Set HADOOP_PROXY_USER cause hiveMetaStoreClient close everytime
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#4119 HIVE-27141: Iceberg: Add more iceberg table metadata
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMetadataTables.java
  iceberg/iceberg-handler/src/test/queries/positive/describe_iceberg_metadata_tables.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_unpartitioned_table.q
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_metadata_tables.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_unpartitioned_table.q.out
Labels: tests unstable

#4109 HIVE-27160: Iceberg: Optimise delete (entire) data from table
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/test/queries/positive/delete_all_iceberg.q
  iceberg/iceberg-handler/src/test/results/positive/delete_all_iceberg.q.out
  ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
Labels: tests passed

#4112 HIVE-22813: Hive query fails if table location is in remote EZ and it's readonly
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShims.java
Labels: tests passed

#4127 HIVE-27153 : Revert "HIVE-20182: Backport HIVE-20067 to branch-3"
  ql/src/test/queries/clientpositive/mm_all.q
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/events/InsertEvent.java
Labels: tests unstable

#4129 HIVE-27148: Disable flaky test TestJdbcGenericUDTFGetSplits
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcGenericUDTFGetSplits.java
Labels: tests unstable

#4125 HIVE-27151 : Revert "HIVE-21685: Wrong simplification in query with multiple IN cl…
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java
  ql/src/test/queries/clientpositive/multi_in_clause.q
  ql/src/test/results/clientpositive/llap/multi_in_clause.q.out
Labels: tests unstable

#4076 HIVE-27097: Improve the retry strategy for MetaStore client and server
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/tools/schematool/TestSchemaToolCatalogOps.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRetriesInRetryingHMSHandler.java
Labels: tests passed

#4126 HIVE-27152 : Revert "HIVE-21388: Constant UDF is not pushed to JDBCStorage Handler…
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveSqlFunction.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
  ql/src/test/queries/clientpositive/current_date_timestamp.q
  ql/src/test/results/clientpositive/llap/current_date_timestamp.q.out
Labels: tests unstable

#4028 HIVE-25032: Optimise PartitionManagementTask
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestMsckDropPartitionsInBatches.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_constants.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Constant.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/constants.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_constants.rb
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/Msck.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MsckPartitionExpressionProxy.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartitionIterable.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartitionManagementTask.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/client/builder/GetPartitionProjectionsSpecBuilder.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionManagement.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
Labels: tests passed

#4148 HIVE-27171: Backport HIVE-20680 to branch-3
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/events/filesystem/DatabaseEventsIterator.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/InjectableBehaviourObjectStore.java
Labels: tests unstable

#4143 HIVE-27167: Upgrade guava version in standalone-metastore and storage-api module
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/Util.java
  standalone-metastore/pom.xml
  storage-api/pom.xml
Labels: tests passed

#4151 HIVE-27154: Backport HIVE-20953 to branch-3
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionTask.java
Labels: tests unstable

#4153 HIVE-27175: Backport HIVE-20897 to branch-3
  service/src/java/org/apache/hive/service/cli/OperationStatus.java
  service/src/java/org/apache/hive/service/cli/operation/Operation.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIServiceClient.java
Labels: tests unstable

#4152 HIVE-27174 : Disabled sysdb.q
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
Labels: tests passed

#4021 HIVE-26800 : Backport HIVE-21462 to branch-3: Upgrading SQL server backed metastore when changing data type
  standalone-metastore/src/main/sql/mssql/upgrade-2.1.0-to-2.2.0.mssql.sql
  standalone-metastore/src/main/sql/mssql/upgrade-2.3.0-to-3.0.0.mssql.sql
  standalone-metastore/src/main/sql/mssql/upgrade-3.0.0-to-3.1.0.mssql.sql
Labels: tests passed

#4027 HIVE-27033 : Backport of HIVE-23044: Make sure Cleaner doesn't delete delta directories for running queries
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
Labels: tests passed

#4164 HIVE-27179: HS2 WebUI throws NPE when JspFactory loaded from jetty-runner
  pom.xml
  service/pom.xml
  service/src/java/org/apache/hive/service/server/HiveServer2.java
Labels: tests passed

#4172 HIVE-26949: Backport HIVE-26071 to branch-3
  standalone-metastore/pom.xml
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HmsThriftHttpServlet.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/auth/HttpAuthenticationException.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/auth/jwt/JWTValidator.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/auth/jwt/URLBasedJWKSProvider.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetastoreWithHttpJwt.java
  standalone-metastore/src/test/resources/auth/jwt/jwt-authorized-key.json
  standalone-metastore/src/test/resources/auth/jwt/jwt-unauthorized-key.json
  standalone-metastore/src/test/resources/auth/jwt/jwt-verification-jwks.json
Labels: tests passed
