Repository apache/hive, pull requests merged in 2023-06, with the labels that each got.

#4373 HIVE-27392: Use String instead of Long for file length in HadoopInputFile.
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java
Labels: tests passed

#4353 HIVE-24240: Implement missing features in UDTFStatsRule
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
  ql/src/test/results/clientpositive/llap/annotate_stats_lateral_view_join.q.out
Labels: tests passed

#4331 HIVE-27352: Support both LDAP and Kerberos Auth in HS2
  itests/hive-minikdc/pom.xml
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestHS2AuthMechsWithMiniKdc.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestHS2JWTWithMiniKdc.java
  itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestHiveAuthFactory.java
  itests/hive-minikdc/src/test/resources/auth.jwt/jwt-authorized-key.json
  itests/hive-minikdc/src/test/resources/auth.jwt/jwt-unauthorized-key.json
  itests/hive-minikdc/src/test/resources/auth.jwt/jwt-verification-jwks.json
  itests/hive-unit/pom.xml
  itests/pom.xml
  jdbc/src/java/org/apache/hive/jdbc/HttpBasicAuthInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/HttpKerberosRequestInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/HttpRequestInterceptorBase.java
  jdbc/src/java/org/apache/hive/jdbc/HttpTokenAuthInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/jwt/HttpJwtAuthRequestInterceptor.java
  jdbc/src/java/org/apache/hive/jdbc/saml/HttpSamlAuthRequestInterceptor.java
  service/src/java/org/apache/hive/service/auth/AuthType.java
  service/src/java/org/apache/hive/service/auth/HiveAuthFactory.java
  service/src/java/org/apache/hive/service/auth/saml/HiveSamlUtils.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
  service/src/java/org/apache/hive/service/server/HS2ActivePassiveHARegistry.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
  service/src/test/org/apache/hive/service/auth/TestAuthType.java
  service/src/test/org/apache/hive/service/cli/thrift/ThriftHttpServletTest.java
Labels: tests passed

#4358 HIVE-27378: Backport of HIVE-19133: HS2 WebUI phase-wise performance metrics not showing correctly
  common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHs2Metrics.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingAPIWithMr.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingAPIWithTez.java
  itests/hive-unit/src/test/java/org/apache/hive/service/cli/session/TestQueryDisplay.java
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
Labels: tests passed

#4387 HIVE-27408: Parquet file opened for reading stats is never closed
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/write/ParquetRecordWriterWrapper.java
Labels: tests passed

#4376 HIVE-27393: Upgrade ant to 1.10.13 to fix CVE's
  pom.xml
Labels: tests passed

#4334 HIVE-27353: Show saved snapshot of materialized view source tables
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc2.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc2.q.out
  iceberg/iceberg-handler/src/test/results/positive/show_iceberg_materialized_views.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
  ql/src/test/results/clientpositive/llap/masking_mv.q.out
  ql/src/test/results/clientpositive/llap/masking_mv_by_text.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_cluster.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_acid.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window_2.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_describe.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_distribute_sort.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_parquet.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partition_cluster.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
  ql/src/test/results/clientpositive/llap/show_materialized_views.q.out
Labels: tests passed

#4293 HIVE-27317: Temporary (local) session files cleanup improvements
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/session/TestClearDanglingScratchDir.java
  ql/src/java/org/apache/hadoop/hive/ql/session/ClearDanglingScratchDir.java
Labels: tests passed

#4359 HIVE-27379: Backport HIVE-22566 : Drop table involved in materialized view leaves the table in inconsistent state
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/queries/clientnegative/drop_table_used_by_mv2.q
  ql/src/test/results/clientnegative/drop_table_used_by_mv.q.out
  ql/src/test/results/clientnegative/drop_table_used_by_mv2.q.out
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
Labels: tests passed

#4367 HIVE-27387: Backport of HIVE-23046: Separate housekeeping thread from initiator flag
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed

#4395 HIVE-27409: Iceberg: table with EXTERNAL type can not use statistics to optimize the query - ADDENDUM
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_avro.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_unpartitioned_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_avro.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_unpartitioned_parquet.q.out
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/DynamicPartitionPruningOptimization.java
Labels: tests passed

#4292 HIVE-27302: Iceberg: Suport write to iceberg branch
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/queries/negative/write_iceberg_branch_negative.q
  iceberg/iceberg-handler/src/test/queries/positive/write_iceberg_branch.q
  iceberg/iceberg-handler/src/test/results/negative/write_iceberg_branch_negative.q.out
  iceberg/iceberg-handler/src/test/results/positive/write_iceberg_branch.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionPruner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/HiveTableName.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/QBParseInfo.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
  ql/src/test/results/clientnegative/desc_failure3.q.out
  storage-api/src/java/org/apache/hadoop/hive/common/TableName.java
  storage-api/src/test/org/apache/hadoop/hive/common/TestTableName.java
Labels: tests passed

#4316 HIVE-27337: Trim the starting and trailing white spaces in HMS for cr…
  hbase-handler/src/test/results/positive/hbase_viewjoins.q.out
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestAcidTableSetup.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
  ql/src/test/queries/clientpositive/create_table.q
  ql/src/test/queries/clientpositive/translated_external_alter.q
  ql/src/test/results/clientnegative/alter_view_as_select_with_partition.q.out
  ql/src/test/results/clientnegative/unset_view_property.q.out
  ql/src/test/results/clientpositive/create_table.q.out
  ql/src/test/results/clientpositive/llap/alter_view_as_select.q.out
  ql/src/test/results/clientpositive/llap/create_table.q.out
  ql/src/test/results/clientpositive/llap/dbtxnmgr_ddl1.q.out
  ql/src/test/results/clientpositive/llap/dbtxnmgr_query5.q.out
  ql/src/test/results/clientpositive/llap/explain_ddl.q.out
  ql/src/test/results/clientpositive/llap/explain_dependency.q.out
  ql/src/test/results/clientpositive/llap/explain_logical.q.out
  ql/src/test/results/clientpositive/llap/ppd_deterministic_expr.q.out
  ql/src/test/results/clientpositive/llap/subquery_notin.q.out
  ql/src/test/results/clientpositive/llap/translated_external_alter.q.out
  ql/src/test/results/clientpositive/llap/unset_table_view_property.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
Labels: tests passed

#4313 HIVE-27332: Add retry backoff mechanism for abort cleanup
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/AbortedTxnCleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/CompactionCleaner.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/TaskHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/TaskHandlerFactory.java
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestAbortCleanupUsingCompactionCycle.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestAbortCleanupUsingCompactionCycleWithMinHistoryWriteId.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/handler/TestAbortedTxnCleaner.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionType.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionType.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/protobuf/org/apache/hadoop/hive/metastore/hive_metastore.proto
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
Labels: tests passed

#4379 HIVE-27293 Vectorization: Incorrect results with nvl for ORC table
  data/files/esource.txt
  ql/src/test/queries/clientpositive/vectorization_nvl.q
  ql/src/test/results/clientpositive/llap/vectorization_nvl.q.out
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/Decimal64ColumnVector.java
Labels: tests passed

#4391 HIVE-27416: ClassCastException for string to decimal64 conversion
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/CastStringToDecimal.java
  ql/src/test/queries/clientpositive/vector_string_decimal64.q
  ql/src/test/results/clientpositive/llap/vector_string_decimal64.q.out
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/IDecimalColumnVector.java
Labels: tests passed

#4377 HIVE-27394: Upgrade commons dependency to fix CVE
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#4399 Revert "HIVE-27317: Temporary (local) session files cleanup improvements"
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/session/TestClearDanglingScratchDir.java
  ql/src/java/org/apache/hadoop/hive/ql/session/ClearDanglingScratchDir.java
Labels: tests passed

#4404 HIVE-24485: Make the slow-start behavior tunable
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/LlapDecider.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezWork.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ReduceWork.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/TezEdgeProperty.java
Labels: tests passed

#4322 HIVE-27340: ThreadPool in HS2 over HTTP should respect the customized…
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Labels: tests passed

#4394 HIVE-27417: Remove Filter.g and unnecessary antlr3 dependency
  metastore/pom.xml
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartFilterExprUtil.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/Filter.g
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartFilterExprUtil.java
  standalone-metastore/pom.xml
Labels: tests passed

#4360 HIVE-27375: fix map join cache reuse
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/TestSharedWorkOptimizer.java
Labels: tests passed

#4402 HIVE-27436: Iceberg: Alter table schema fails when partition spec contains columns not in the lower registry
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q
  iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_parquet.q
  iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_parquet.q.out
Labels: tests passed

#4378 HIVE-27391: Refactor Calcite node generation from lateral views
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveOptimizeInlineArrayTableFunctionRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/relnodegen/LateralViewPlan.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/FunctionHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/HiveFunctionHelper.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/type/TestHiveFunctionHelper.java
  ql/src/test/queries/clientpositive/tablevalues.q
  ql/src/test/results/clientpositive/llap/tablevalues.q.out
Labels: tests passed

#4400 HIVE-27425:Upgrade Nimbus-JOSE-JWT to 9.31 due to CVEs
  service/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#4330 HIVE-27349: Move HMS call to get stored procedure out of Udf
  hplsql/src/main/java/org/apache/hive/hplsql/Exec.java
  hplsql/src/main/java/org/apache/hive/hplsql/HplValidationException.java
  hplsql/src/main/java/org/apache/hive/hplsql/udf/Udf.java
  hplsql/src/test/java/org/apache/hive/hplsql/udf/TestHplsqlUdf.java
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Labels: tests passed

#4410 HIVE-27332: Addendum: Add retry backoff mechanism for abort cleanup
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
Labels: tests passed

#4407 HIVE-27430: Upgrade Antlr in hplsql to 4.9.3
  bin/ext/hplsql.sh
  hplsql/pom.xml
  hplsql/src/main/java/org/apache/hive/hplsql/Exec.java
  hplsql/src/test/results/local/invalid_syntax.out.txt
  pom.xml
Labels: tests passed

#4429 HIVE-27447: Iceberg: Queries failing due to FileSystem close errors due to column statistics.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
Labels: tests passed

#4420 HIVE-27443: Remove duplicate dependency from pom to avoid maven warnings
  itests/hive-jmh/pom.xml
Labels: tests passed

#4434 HIVE-27450: Fix for CVE-2023-34455
  pom.xml
Labels: tests passed

#4137 HIVE-27113: Increasing default for hive.thrift.client.max.message.siz…
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  service/src/java/org/apache/hive/service/cli/thrift/RetryingThriftCLIServiceClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests unstable

#4439 HIVE-27251 : Backport of HIVE-22121 to branch-3
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/FixedBucketPruningOptimizer.java
  ql/src/test/queries/clientpositive/tez_fixed_bucket_pruning.q
  ql/src/test/results/clientpositive/llap/tez_fixed_bucket_pruning.q.out
Labels: tests passed

#4424 HIVE-24286: Render date and time with progress of Hive on Tez
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/RenderStrategy.java
Labels: tests passed

#4352 HIVE-27368: Vectorization: ArrayIndexOutOfBoundsException when map key vector has repeating values
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFMapIndexStringScalar.java
Labels: tests passed

#4426 HIVE-27441: Iceberg: CTLT with source table as Hive managed table fails with "The table must be stored using an ACID compliant format"
  iceberg/iceberg-handler/src/test/queries/positive/ctlt_iceberg.q
  iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/convert/AlterTableConvertOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#4392 HIVE-27244: Iceberg: Implement LOAD data for unpartitioned table via Append API.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_load_data.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_load_data.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/LoadTableDesc.java
Labels: tests passed

#4323 HIVE-27344: Add a null check in RecordReaderImpl.close()
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/RecordReaderImpl.java
Labels: tests passed

#4403 HIVE-27317: Temporary (local) session files cleanup improvements
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/session/TestClearDanglingScratchDir.java
  ql/src/java/org/apache/hadoop/hive/ql/session/ClearDanglingScratchDir.java
Labels: tests passed

#4417 HIVE-27439: Support Decimal(precision, scale) format
  serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoUtils.java
  serde/src/test/org/apache/hadoop/hive/serde2/typeinfo/TestTypeInfoUtils.java
Labels: tests passed

#4090 HIVE-27112 - implement array_except UDF in Hive
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayExcept.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayExcept.java
  ql/src/test/queries/clientpositive/udf_array_except.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_except.q.out
Labels: tests passed

#4346 HIVE-26832: Implement SHOW PARTITIONS for Iceberg Tables
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/test/queries/negative/show_partitions_negative_test.q
  iceberg/iceberg-handler/src/test/queries/positive/show_partitions_test.q
  iceberg/iceberg-handler/src/test/results/negative/show_partitions_negative_test.q.out
  iceberg/iceberg-handler/src/test/results/positive/show_partitions_test.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/show/ShowPartitionsOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Labels: tests passed

#4257 HIVE-27284: Make HMSHandler proxy pluggable
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/JavaUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AbstractHMSHandlerProxy.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandlerProxyFactory.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRetriesInRetryingHMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/conf/TestMetastoreConf.java
Labels: tests passed

#4432 HIVE-23831: Introduce a threshold to turn on or off auto-parallelism …
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java
Labels: tests passed

#4348 HIVE-27355: Iceberg: Create table can be slow due to file listing for…
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java
Labels: tests passed

#4291 Hive-27306: port iceberg catalog changes
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  iceberg/iceberg-catalog/pom.xml
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/CachedClientPool.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCommitLock.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveHadoopUtil.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveLock.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveVersion.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/LockException.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreLock.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreUtil.java
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/NoLock.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/AssertHelpers.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/TestHelpers.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/ScriptRunner.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestCachedClientPool.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveClientPool.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
  iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestLoadHiveCatalog.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergObjectInspector.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestCatalogs.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestInputFormatReaderDeletes.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestDeserializer.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergObjectInspector.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveVectorizedReader.java
  iceberg/iceberg-handler/src/test/queries/positive/show_partitions_test.q
  iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_metadata_tables.q.out
  iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
  iceberg/iceberg-handler/src/test/results/positive/show_partitions_test.q.out
  iceberg/pom.xml
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreInitListener.java
Labels: tests passed

#4453 HIVE-27245: Iceberg: Implement LOAD data for partitioned tables via Append API.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_load_data.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_load_data.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/LoadTableDesc.java
Labels: tests failed
