Repository apache/hive, pull requests merged in 2023-08, with the labels that each got.

#4477 HIVE-27050: Restrict reducer extrapolation to contain number of small…
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java
Labels: tests passed

#4341 HIVE-27360: Iceberg: Don't create the redundant MANAGED location when creating table without EXTERNAL keyword
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/results/positive/col_stats.q.out
  iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_all_iceberg.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_v2_deletes.q.out
  iceberg/iceberg-handler/src/test/results/positive/use_basic_stats_from_iceberg.q.out
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
Labels: tests passed

#4523 HIVE-27540 : Fixed orc_merge10.q test
  ql/src/test/results/clientpositive/orc_merge10.q.out
Labels: tests passed

#4522 HIVE-27508 : Backport of HIVE-21584 to branch-3.1
  beeline/src/java/org/apache/hive/beeline/Commands.java
  common/src/java/org/apache/hadoop/hive/common/JavaUtils.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/FunctionLocalizer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/AddToClassPathAction.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecMapper.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecReducer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkRecordHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/RecordProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestAddToClassPathAction.java
  spark-client/src/main/java/org/apache/hive/spark/client/SparkClientUtilities.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
Labels: tests unstable

#4510 HIVE-27236: Iceberg:DROP BRANCH SQL implementation
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergBranchExec.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergBranchOperation.java
  iceberg/iceberg-handler/src/test/queries/negative/alter_table_drop_branch_negative.q
  iceberg/iceberg-handler/src/test/queries/positive/alter_table_create_branch.q
  iceberg/iceberg-handler/src/test/results/negative/alter_table_drop_branch_negative.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_create_branch.q.out
  iceberg/iceberg-handler/src/test/results/positive/alter_table_create_tag.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/AlterTableCreateSnapshotRefAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/AlterTableDropSnapshotRefAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/AlterTableSnapshotRefDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/AlterTableSnapshotRefOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/branch/drop/AlterTableDropBranchAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableSnapshotRefSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
Labels: tests passed

#4495 HIVE-27508 : Backport of HIVE-21584 to branch-3
  beeline/src/java/org/apache/hive/beeline/Commands.java
  common/src/java/org/apache/hadoop/hive/common/JavaUtils.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/FunctionLocalizer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/AddToClassPathAction.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecMapper.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecReducer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkRecordHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/RecordProcessor.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestAddToClassPathAction.java
  spark-client/src/main/java/org/apache/hive/spark/client/SparkClientUtilities.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
Labels: tests passed

#4526 HIVE-27543 : Backport of HIVE-24039 : Update jquery version to mitigate CVE-2020-11023 (#1403)
  service/src/resources/hive-webapps/static/js/jquery.min.js
Labels: tests passed

#4549 HIVE-27565: Fix NPE when dropping table in HiveQueryLifeTimeHook::checkAndRollbackCTAS
  ql/src/java/org/apache/hadoop/hive/ql/HiveQueryLifeTimeHook.java
Labels: tests passed

#4421 HIVE-27444: Limit items processed by Initiator/Cleaner
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Labels: tests passed

#4547 HIVE-27563: Add typeof UDF
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFTypeOf.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFTypeOf.java
  ql/src/test/queries/clientpositive/udf_typeof.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_typeof.q.out
Labels: tests passed

#4546 HIVE-27562: Iceberg: Fetching virtual columns failing.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_virtualcol.q
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_virtualcol.q.out
Labels: tests passed

#4513 HIVE-27523 - Implement array_union UDF in Hive
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayUnion.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayUnion.java
  ql/src/test/queries/clientpositive/udf_array_union.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_union.q.out
Labels: tests passed

#4558 HIVE-27575: MASK_HASH UDF generate a log per row
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMaskHash.java
Labels: tests passed

#4562 HIVE-27579: Backport HIVE-18433: Upgrade version of com.fasterxml.jackson
  common/pom.xml
  druid-handler/pom.xml
  druid-handler/src/java/org/apache/hadoop/hive/druid/DruidStorageHandlerUtils.java
  hcatalog/core/pom.xml
  hcatalog/server-extensions/pom.xml
  hcatalog/webhcat/svr/pom.xml
  itests/hive-blobstore/pom.xml
  pom.xml
  ql/pom.xml
  spark-client/pom.xml
  testutils/ptest2/pom.xml
  testutils/ptest2/src/main/java/org/apache/hive/ptest/api/client/PTestClient.java
  testutils/ptest2/src/main/java/org/apache/hive/ptest/execution/JIRAService.java
Labels: tests failed

#4568 HIVE-27396: Add the -strict flag for Thrift generation
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#4563 HIVE-27581: Upgrade jackson from 2.9.4 to 2.12.0
  pom.xml
  testutils/ptest2/pom.xml
Labels: tests failed

#4565 HIVE-27582: Do not cache HBase table input format in FetchOperator
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java
Labels: tests passed

#4521 HIVE-26751 : Backport of HIVE-24201 to branch-3
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/KillMoveTriggerActionHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WmTezSession.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestWorkloadManager.java
Labels: tests passed

#4525 HIVE-27542: Backport HIVE-25659 to branch-3
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/txn/TestTxnUtils.java
Labels: tests passed

#4528 HIVE-27545: Backport of HIVE-22273 to branch-3
  common/src/java/org/apache/hadoop/hive/common/FileUtils.java
Labels: tests passed

#4530 HIVE-27547 : Backport of HIVE-22219 to branch-3
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/LlapStatusServiceDriver.java
Labels: tests passed

#4533 HIVE-27550 : Backport of HIVE-22113 to branch-3
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskRunnerCallable.java
Labels: tests passed

#4534 HIVE-27551 : Backport of HIVE-22208 to branch-3
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/masking_reserved.q
  ql/src/test/results/clientpositive/masking_reserved.q.out
Labels: tests passed

#4537 HIVE-27554: added control to JDBCBrowser client URL
  jdbc/src/java/org/apache/hive/jdbc/saml/HiveJdbcBrowserClient.java
  jdbc/src/java/org/apache/hive/jdbc/saml/HiveJdbcSamlRedirectStrategy.java
  jdbc/src/java/org/apache/hive/jdbc/saml/IJdbcBrowserClient.java
  jdbc/src/test/org/apache/hive/jdbc/saml/TestSSOControl.java
Labels: tests passed

#4545 HIVE-27586: Parse dates from strings ignoring trailing (potentialy) invalid chars
  common/src/java/org/apache/hadoop/hive/common/type/Date.java
  common/src/test/org/apache/hive/common/util/TestDateParser.java
  ql/src/test/queries/clientpositive/check_constraint.q
  ql/src/test/results/clientpositive/llap/check_constraint.q.out
Labels: tests passed

#4561 HIVE-27578: Refactor genJoinRelNode to use genAllRexNode instead of g…
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/JoinTypeCheckCtx.java
Labels: tests passed

#4276 HIVE-27304: Exclude CTAS condition while forming storage handler url …
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
  ql/src/test/queries/clientpositive/authorization_privilege_objects.q
  ql/src/test/results/clientpositive/llap/authorization_privilege_objects.q.out
Labels: tests passed

#4542 HIVE-27560: [2.3] Enhancing compatibility with Guava
  common/src/java/org/apache/hadoop/hive/common/JvmMetricsInfo.java
  common/src/java/org/apache/hadoop/hive/common/JvmPauseMonitor.java
  common/src/java/org/apache/hive/common/guava/Objects.java
  common/src/java/org/apache/hive/common/guava/SameThreadExecutorUtil.java
  common/src/java/org/apache/hive/common/guava/Stopwatch.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/io/TestHadoopFileStatus.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestServiceDiscovery.java
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreCliDriver.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/SQLStdHiveAuthorizationValidatorForTest.java
  itests/util/src/main/java/org/apache/hadoop/hive/util/ElapsedTimeLoggingWrapper.java
  llap-client/src/java/org/apache/hadoop/hive/llap/tez/LlapProtocolClientProxy.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/AMReporter.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapTaskReporter.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskRunnerCallable.java
  llap-server/src/java/org/apache/hadoop/hive/llap/metrics/LlapDaemonCacheInfo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/metrics/LlapDaemonExecutorInfo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/metrics/LlapDaemonIOInfo.java
  llap-server/src/java/org/apache/hadoop/hive/llap/metrics/LlapDaemonJvmInfo.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
  llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/metrics/LlapTaskSchedulerInfo.java
  metastore/src/java/org/apache/hadoop/hive/metastore/hbase/TephraHBaseConnection.java
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/hooks/LineageLogger.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMetaStoreChecker.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/SubstitutionVisitor.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveRelMdPredicates.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSpec.java
  service/src/java/org/apache/hive/service/cli/session/SessionManager.java
  shims/common/src/main/java/org/apache/hadoop/hive/io/HdfsUtils.java
  spark-client/src/main/java/org/apache/hive/spark/client/MetricsCollection.java
Labels: tests failed

#4599 HIVE-27619 : Backport of HIVE-12371: Adding a timeout connection parameter for JDBC
  jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
Labels: tests passed

#4551 HIVE-27237: Iceberg: DROP TAG SQL implementation
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTagExec.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTagOperation.java
  iceberg/iceberg-handler/src/test/queries/positive/alter_table_create_tag.q
  iceberg/iceberg-handler/src/test/results/positive/alter_table_create_tag.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/tag/drop/AlterTableDropTagAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
Labels: tests passed

#4576 HIVE-27592: Remove mockito from root pom.xml
  accumulo-handler/pom.xml
  cli/pom.xml
  common/pom.xml
  druid-handler/pom.xml
  hbase-handler/pom.xml
  hcatalog/pom.xml
  iceberg/pom.xml
  itests/hive-jmh/pom.xml
  itests/hive-minikdc/pom.xml
  itests/hive-unit/pom.xml
  jdbc/pom.xml
  kafka-handler/pom.xml
  llap-common/pom.xml
  llap-server/pom.xml
  llap-tez/pom.xml
  pom.xml
  ql/pom.xml
  shims/0.23/pom.xml
  shims/common/pom.xml
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/metastore-server/pom.xml
Labels: tests passed

#4581 HIVE-27602 : Backport of HIVE-21915 to branch-3
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java
  ql/src/test/queries/clientpositive/tez_union_udtf.q
  ql/src/test/results/clientpositive/tez/tez_union_udtf.q.out
Labels: tests passed

#4527 HIVE-27544: Backport of HIVE-22120 to branch-3
  data/files/tjoin3.txt
  data/files/tjoin4.txt
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorLimitOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/VectorMapJoinOuterGenerateResultOperator.java
  ql/src/test/queries/clientpositive/vector_left_outer_join3.q
  ql/src/test/results/clientpositive/llap/vector_left_outer_join3.q.out
Labels: tests passed

#4579 HIVE-27600: Reduce filesystem calls in OrcFileMergeOperator
  ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java
Labels: tests passed

#4604 HIVE-27622: Backport of HIVE-26078: Upgrade gson to 2.8.9 (Ashish Sharma, reviewed by Adesh Rao)
  pom.xml
Labels: tests passed

#4582 HIVE-27603 : Backport of HIVE-22498 to branch-3
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/tools/MetastoreSchemaTool.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/tools/SchemaToolCommandLine.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/tools/SchemaToolTaskMergeCatalog.java
Labels: tests passed

#4587 HIVE-27608 : Backport of HIVE-22106: Remove cross-query synchronization for the partition-eval
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartExprEvalUtils.java
Labels: tests passed

#4588 HIVE-27609 : Backport of HIVE-22115 to branch-3
  ql/src/java/org/apache/hadoop/hive/ql/log/LogDivertAppender.java
Labels: tests passed

#4594 HIVE-27614 : Backport of HIVE-21009: Adding ability for user to set bind user
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  service/pom.xml
  service/src/java/org/apache/hive/service/auth/LdapAuthenticationProviderImpl.java
  service/src/test/org/apache/hive/service/auth/TestLdapAuthenticationProviderImpl.java
  service/src/test/resources/creds/test.jceks
Labels: tests passed

#4600 HIVE-27620 : Backport of HIVE-25945: Upgrade H2 database version to 2.1.210
  pom.xml
Labels: tests passed

#4603 HIVE-27621: Backport of HIVE-25697: Upgrade commons-compress to 1.21
  pom.xml
Labels: tests passed

#4605 HIVE-27623: Backport of HIVE-26081: Upgrade ant to 1.10.9 (Ashish Sharma, reviewed by Adesh Rao)
  pom.xml
Labels: tests passed

#4555 HIVE-27572: Backport of HIVE-21296 to branch-3
  ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
  ql/src/test/queries/clientpositive/partition_varchar1.q
  ql/src/test/results/clientpositive/partition_varchar1.q.out
Labels: tests passed

#4554 HIVE-27571: Backport of HIVE-18702 to branch-3
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/test/queries/clientpositive/insert_overwrite.q
  ql/src/test/results/clientpositive/llap/insert_overwrite.q.out
Labels: tests passed

#4553 HIVE-27570: Backport of HIVE-21815 to branch-3
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
Labels: tests passed

#4552 HIVE-27569: Backport of HIVE-22405 to branch-3
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/DateColumnVector.java
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/TimestampColumnVector.java
  storage-api/src/test/org/apache/hadoop/hive/ql/exec/vector/TestDateColumnVector.java
  storage-api/src/test/org/apache/hadoop/hive/ql/exec/vector/TestTimestampColumnVector.java
Labels: tests passed

#4406 HIVE-27303: Set correct output name to ReduceSink when there is a SMB join after Union
  ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezWork.java
  ql/src/test/queries/clientpositive/smb_join_after_union.q
  ql/src/test/results/clientpositive/llap/smb_join_after_union.q.out
Labels: tests passed

#4575 HIVE-27589: Iceberg: Branches of Merge/Update statements should be committed atomically
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_atomic_merge_update.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_atomic_merge_update.q.out
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Labels: tests passed

#4535 HIVE-27552 : Backport of HIVE-22360, HIVE-20619 to branch-3
  data/files/t11_csv_serde.csv
  data/files/t1_multi_delimit.csv
  data/files/t2_multi_delimit.csv
  data/files/t3_multi_delimit.csv
  ql/src/test/queries/clientpositive/serde_multi_delimit.q
  ql/src/test/results/clientpositive/serde_multi_delimit.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyStruct.java
Labels: tests passed

#4595 HIVE-27615 : Backport of HIVE-21280 to branch-3
  ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
Labels: tests passed

#4598 HIVE-27618 : Backport of HIVE-25446 to branch-3
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTable.java
Labels: tests passed

#4570 HIVE-27585 Upgrade kryo serialization lib to latest version
  iceberg/pom.xml
  pom.xml
Labels: tests passed

#4613 HIVE-27631: Fix CCE when set fs.hdfs.impl other than DistributedFileSystem
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Labels: tests passed

#4592 HIVE-27613 : Backport of HIVE-22204: Beeline option to show/not show execution report
  beeline/src/java/org/apache/hive/beeline/BeeLineOpts.java
  beeline/src/java/org/apache/hive/beeline/Commands.java
  beeline/src/main/resources/BeeLine.properties
  beeline/src/test/org/apache/hive/beeline/TestBeelineArgParsing.java
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestBeeLineWithArgs.java
Labels: tests passed

#4597 HIVE-27617 : Backport of HIVE-18284 to branch-3
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/ReduceSinkDeDuplicationUtils.java
  ql/src/test/queries/clientpositive/dynpart_sort_optimization_distribute_by.q
  ql/src/test/results/clientpositive/dynpart_sort_optimization_distribute_by.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_distribute_by.q.out
  ql/src/test/results/clientpositive/tez/dynpart_sort_optimization_distribute_by.q.out
Labels: tests passed

#4408 HIVE-27431: Clean invalid properties in test moduel
  data/conf/hive-site-old.xml
  data/conf/hive-site.xml
  data/conf/iceberg/llap/hive-site.xml
  data/conf/iceberg/tez/hive-site.xml
  data/conf/llap/hive-site.xml
  data/conf/rlist/hive-site.xml
  data/conf/tez/hive-site.xml
  itests/hive-blobstore/src/test/resources/hive-site.xml
Labels: tests passed

#4586 HIVE-27607 : Backport of HIVE-21182: Skip setting up hive scratch dir during planning
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#4601 HIVE-27595: replaced cartesian-product table filtering by sort + binary search
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/AuthorizationMetaStoreFilterHook.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HivePrivilegeObjectUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
  ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
  ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestTablePermissionFilterAlgos.java
Labels: tests passed

#4625 HIVE-27645: Refactor assertFalse(equals()) using assertNotEquals & @Test(excepted) using assertThrows
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
Labels: tests failed

#4578 HIVE-27599: ConvertAstToSearchArg improvement with output and typo in comments
  ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java
Labels: tests passed

#4627 HIVE-27630: Iceberg: Fast forward branch.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/queries/negative/fastforward_iceberg_branch_conflict.q
  iceberg/iceberg-handler/src/test/queries/positive/fastforward_iceberg_branch.q
  iceberg/iceberg-handler/src/test/results/negative/fastforward_iceberg_branch_conflict.q.out
  iceberg/iceberg-handler/src/test/results/positive/fastforward_iceberg_branch.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Labels: tests passed

#4617 HIVE-22961: Drop function in Hive should not send request for drop database to Ranger plugin
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestCreateUdfEntities.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/function/AbstractFunctionAnalyzer.java
  ql/src/test/results/clientnegative/create_function_nonexistent_class.q.out
  ql/src/test/results/clientnegative/create_function_nonudf_class.q.out
  ql/src/test/results/clientnegative/drop_database_cascade.q.out
  ql/src/test/results/clientnegative/udf_local_resource.q.out
  ql/src/test/results/clientnegative/udf_nonexistent_resource.q.out
  ql/src/test/results/clientpositive/llap/authorization_create_func1.q.out
  ql/src/test/results/clientpositive/llap/authorization_functions_in_views.q.out
  ql/src/test/results/clientpositive/llap/check_constraint.q.out
  ql/src/test/results/clientpositive/llap/create_func1.q.out
  ql/src/test/results/clientpositive/llap/llap_udf.q.out
  ql/src/test/results/clientpositive/udf_using.q.out
Labels: tests passed

#4449 HIVE-27463: Non-daemon thread prevents HMS from exiting when failed t…
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Labels: tests passed

#4520 HIVE-27536: Merge task must be invoked after optimisation for external CTAS queries
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/io/merge/MergeFileWork.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ConditionalResolverMergeFiles.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestFileSinkOperator.java
  ql/src/test/queries/clientpositive/merge_ctas.q
  ql/src/test/results/clientpositive/llap/merge_ctas.q.out
Labels: tests passed

#4497 HIVE-23680 : TestDbNotificationListener is unstable
  itests/hcatalog-unit/pom.xml
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationCleanup.java
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestTransactionalDbNotificationListener.java
Labels: tests passed

#4590 HIVE-27611 : Backport of HIVE-22168 to branch-3
  ql/src/java/org/apache/hadoop/hive/llap/LlapCacheAwareFs.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/encoded/EncodedReaderImpl.java
Labels: tests passed

#4451 HIVE-22618: Fix checkstyle violations for ParseUtils
  ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
  ql/src/test/org/apache/hadoop/hive/ql/parse/TestParseUtils.java
Labels: tests passed

#4612 HIVE-27628 - implement array_remove UDF in Hive
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayRemove.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayRemove.java
  ql/src/test/queries/clientpositive/udf_array_remove.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_remove.q.out
Labels: tests passed

#4634 HIVE-27652: Fix flakyness caused by CompactorOnTezTest#getRelatedTezEvent
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
Labels: tests passed

#4564 HIVE-27580: Backport HIVE-20071: Migrate to jackson 2.x and prevent usage
  common/src/java/org/apache/hadoop/hive/common/jsonexplain/tez/Vertex.java
  common/src/java/org/apache/hive/http/JMXJsonServlet.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONAddPartitionMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONAlterIndexMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONAlterPartitionMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONAlterTableMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONCreateDatabaseMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONCreateFunctionMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONCreateIndexMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONCreateTableMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONDropDatabaseMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONDropFunctionMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONDropIndexMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONDropPartitionMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONDropTableMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONInsertMessage.java
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/messaging/json/JSONMessageDeserializer.java
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/JsonBuilder.java
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/SimpleWebException.java
  hcatalog/webhcat/svr/src/test/java/org/apache/hive/hcatalog/templeton/TestDesc.java
  hcatalog/webhcat/svr/src/test/java/org/apache/hive/hcatalog/templeton/TestWebHCatE2e.java
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/LlapStatusServiceDriver.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/services/impl/LlapWebServices.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/PartitionFiles.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONAddPartitionMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONAlterIndexMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONAlterPartitionMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONAlterTableMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONCreateDatabaseMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONCreateFunctionMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONCreateIndexMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONCreateTableMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONDropDatabaseMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONDropFunctionMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONDropIndexMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONDropPartitionMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONDropTableMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONInsertMessage.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONMessageDeserializer.java
  metastore/src/java/org/apache/hadoop/hive/metastore/messaging/json/JSONMessageFactory.java
  metastore/src/test/org/apache/hadoop/hive/metastore/messaging/json/JSONMessageDeserializerTest.java
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/QueryDisplay.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/formatting/JsonMetaDataFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/EximUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFJson.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFJSONTuple.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/TypeInfoToSchema.java
  service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
  service/src/test/org/apache/hive/service/cli/CLIServiceTest.java
Labels: tests failed

#4550 HIVE-27566: Fix some yarn cluster options for tests
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Labels: tests passed
