Repository apache/hive, pull requests merged in 2024-02, with the labels that each got.

#4984 HIVE-27984: Support backward compatibility of hms thrift struct about column stats
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/ColumnStatsUpdateTask.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/ColStatsProcessor.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
  standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ColumnStatistics.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetPartitionsByNamesRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetTableRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PartitionsStatsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/SetPartitionsStatsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/TableStatsRequest.java
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ColumnStatistics.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetPartitionsByNamesRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetTableRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PartitionsStatsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/SetPartitionsStatsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/TableStatsRequest.php
  standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
  standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#5048 HIVE-27938: Iceberg: Fix java.lang.ClassCastException during vectoriz…
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/HiveIdentityPartitionConverters.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_partition_vectorized_read.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_partition_vectorized_read.q.out
Labels: tests passed

#4740 HIVE-27637: Compare highest write ID of compaction records when tryin…
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/handler/TestAbortedTxnCleaner.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/queries/ReadyToCleanAbortHandler.java
Labels: tests passed

#5058 Revert "HIVE-27637: Compare highest write ID of compaction records when trying to perform abort cleanup (#4740) (Zsolt Miskolczi reviewed by Attila Turoczy, Sourabh Badhya)"
  ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/handler/TestAbortedTxnCleaner.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/queries/ReadyToCleanAbortHandler.java
Labels: tests pending

#5040 HIVE-28038: Disable fallback to jdo for DeadlineException
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Labels: tests passed

#5003 HIVE-27958: Refactor DirectSqlUpdatePart class
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdatePart.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/retry/SqlRetryHandler.java
Labels: tests passed

#5061 HIVE-28052: Iceberg: Major QB Compaction fails with ClassNotFoundException: org.springframework.core.ErrorCoded
  pom.xml
  ql/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5057 HIVE-28054: SemanticException for join condition in subquery
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
  ql/src/test/queries/clientpositive/subquery_join.q
  ql/src/test/results/clientpositive/llap/subquery_join.q.out
Labels: tests passed

#5068 HIVE-28057: Iceberg: Branches with non-lowercase characters can't be accessed.
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergBranchOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#4991 HIVE-27992: Upgrade to tez 0.10.3
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QOutProcessor.java
  pom.xml
  ql/src/test/results/clientnegative/broken_pipe.q.out
  ql/src/test/results/clientnegative/cachingprintstream.q.out
  ql/src/test/results/clientnegative/script_broken_pipe3.q.out
  ql/src/test/results/clientnegative/script_error.q.out
  ql/src/test/results/clientnegative/stack_trace.q.out
Labels: tests passed

#5074 HIVE-27850: Addendum: Add DB name in Iceberg Major compaction query t…
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergMajorQueryCompactor.java
Labels: tests passed

#5053 HIVE-28050: Disable Incremental non aggregated materialized view rebuild in presence of delete operations
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveJoinInsertDeleteIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_12.q
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_5.q
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_8.q
  ql/src/test/queries/clientpositive/materialized_view_join_rebuild.q
  ql/src/test/queries/clientpositive/materialized_view_repeated_rebuild.q
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_12.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_8.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_join_rebuild.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_repeated_rebuild.q.out
Labels: tests passed

#5078 HIVE-26445: Use tez.local.mode.without.network for qtests
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Labels: tests passed

#4970 HIVE-27022 - Split removeDuplicateCompletedTxnComponents away from Ac…
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestTimedOutTxnNotificationLogging.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/HouseKeepingTasks.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/service/AcidHouseKeeperService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/service/AcidOpenTxnsCounterService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/service/AcidTxnCleanerService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/service/CompactionHouseKeeperService.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/conf/TestMetastoreConf.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestAcidTxnCleanerService.java
  streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Labels: tests passed

#5028 HIVE-27980: Hive Iceberg Compaction: add support for OPTIMIZE TABLE s…
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_optimize_table_unpartitioned.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_optimize_table_unpartitioned.q.out
  itests/src/test/resources/testconfiguration.properties
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
Labels: tests passed

#5046 HIVE-28043 : Upgrade ZooKeeper to 3.8.3
  hcatalog/webhcat/svr/pom.xml
  jdbc/pom.xml
  kafka-handler/pom.xml
  llap-client/pom.xml
  llap-tez/pom.xml
  pom.xml
  ql/pom.xml
  shims/common/pom.xml
  standalone-metastore/metastore-common/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5071 HIVE-28065: Upgrade Bouncy castle to bcprov-jdk18on 1.77
  pom.xml
  service/pom.xml
Labels: tests passed

#4938 HIVE-27950: STACK UDTF returns wrong results when # of argument is no…
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFStack.java
  ql/src/test/queries/clientnegative/udtf_stack_not_constant.q
  ql/src/test/queries/clientnegative/udtf_stack_null.q
  ql/src/test/queries/clientnegative/udtf_stack_wrong_type1.q
  ql/src/test/queries/clientpositive/udtf_stack.q
  ql/src/test/results/clientnegative/udtf_stack_not_constant.q.out
  ql/src/test/results/clientnegative/udtf_stack_null.q.out
  ql/src/test/results/clientnegative/udtf_stack_wrong_type1.q.out
  ql/src/test/results/clientpositive/llap/allcolref_in_udf.q.out
  ql/src/test/results/clientpositive/llap/udtf_stack.q.out
Labels: tests passed

#5080 HIVE-28071: Sync jetty version across modules
  itests/qtest-druid/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5090 HIVE-28081: Code refine on ClearDanglingScratchDir::removeLocalTmpFiles
  ql/src/java/org/apache/hadoop/hive/ql/session/ClearDanglingScratchDir.java
Labels: tests passed

#5047 HIVE-28015: Iceberg: Add identifier-field-ids support in Hive
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Labels: tests passed

#5038 HIVE-27778: Alter table command gives error after computer stats is r…
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Labels: tests passed

#4863 HIVE-26435: HMS Summary changes.
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/tools/metatool/TestHiveMetaTool.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/SQLGenerator.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/HiveMetaTool.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/HiveMetaToolCommandLine.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/IcebergReflector.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/IcebergTableMetadataHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/MetaToolTaskMetadataSummary.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/MetadataTableSummary.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/tools/metatool/TestHiveMetaToolCommandLine.java
Labels: tests passed

#4943 HIVE-27924: Incremental rebuild goes wrong when inserts and deletes overlap between the source tables
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/HCatRecordReader.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateInsertDeleteIncrementalRewritingRule.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveRowIsDeletedPropagator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/InputRefShifter.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/MaterializedViewRewritingRelVisitor.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestHiveAugmentMaterializationRule.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestHiveAugmentSnapshotMaterializationRule.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestHivePushdownSnapshotFilterRule.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestHiveRowIsDeletedPropagator.java
  ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestRuleBase.java
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_6_aggr_2joins.q
  ql/src/test/queries/clientpositive/materialized_view_create_rewrite_6_aggr_3joins.q
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6_aggr_2joins.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6_aggr_3joins.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_9.q.out
Labels: tests passed

#5064 HIVE-28056: Bump com.jayway.jsonpath:json-path from 2.8.0 to 2.9.0
  pom.xml
Labels: tests passed

#5085 HIVE-28078: TestTxnDbUtil should generate csv files when we query the metastore database
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
Labels: tests passed

#4540 HIVE-27556: Add Unit Test for KafkaStorageHandlerInfo
  kafka-handler/src/test/org/apache/hadoop/hive/kafka/KafkaStorageHandlerInfoTest.java
Labels: tests passed

#5024 HIVE-28021: Iceberg: Attempting to create a table with a percent symbol fails
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreLock.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Labels: tests passed

#5082 HIVE-27845:Upgrade protobuf to 3.24.4 to fix CVEs
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/daemon/rpc/LlapDaemonProtocolProtos.java
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/plugin/rpc/LlapPluginProtocolProtos.java
  pom.xml
  ql/src/gen/protobuf/gen-java/org/apache/hadoop/hive/ql/hooks/proto/HiveHookEvents.java
  ql/src/gen/protobuf/gen-test/org/apache/hadoop/hive/ql/io/protobuf/SampleProtos.java
  standalone-metastore/pom.xml
Labels: tests passed

#5089 HIVE-28080: Propagate statistics from a source table to the materialized CTE
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/cte_mat_11.q
  ql/src/test/results/clientpositive/llap/cte_3.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_10.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_11.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_3.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_4.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_5.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_6.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_8.q.out
  ql/src/test/results/clientpositive/llap/cte_mat_9.q.out
Labels: tests passed

#5100 HIVE-27850: Iceberg: Addendum 2: Set runAs user in CompactionInfo.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergCompactionService.java
Labels: tests passed

#5097 HIVE-28090: Correct desc of `hive.metastore.disallow.incompatible.col.type.changes` of `HiveConf.java`
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests passed

#5088 HIVE-28084: Iceberg: COW fix for Merge operation
  iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_unpartitioned.q
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out
  ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteMergeRewriter.java
Labels: tests passed

#3824 HIVE-25972: HIVE_VECTORIZATION_USE_ROW_DESERIALIZE in hiveconf.java imply default value is false，in fact the default value is 'true'
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests passed, stale

#5103 HIVE-28093: Re-execute DAG in case of NoCurrentDAGException
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezRuntimeException.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java
  ql/src/test/org/apache/hadoop/hive/ql/reexec/TestReExecuteLostAMQueryPlugin.java
Labels: tests passed
