Repository apache/hive, pull requests merged in 2024-03, with the labels that each got.

#5084 HIVE-27490: HPL/SQL says it support default value for parameters but not considering them when no value is passed
  hplsql/src/main/java/org/apache/hive/hplsql/functions/InMemoryFunctionRegistry.java
  hplsql/src/test/results/local/arity.out.txt
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Labels: tests passed

#4959 HIVE-27775: DirectSQL and JDO results are different when fetching par…
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
  ql/src/test/queries/clientpositive/partition_timestamp3.q
  ql/src/test/results/clientpositive/llap/partition_timestamp3.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/PartFilterVisitor.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestPartFilterExprUtil.java
Labels: tests passed

#5081 HIVE-28073: Upgrade jackson version to 2.16.1
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5113 HIVE-18586: (2.3) Upgrade Derby to 10.14.1.0
  core/src/test/java/org/apache/hive/hcatalog/DerbyPolicy.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/DerbyPolicy.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/cli/TestPermsGrp.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatPartitionPublish.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/package-info.java
  hcatalog/webhcat/java-client/src/test/java/org/apache/hive/hcatalog/api/TestHCatClient.java
  metastore/src/test/org/apache/hadoop/hive/metastore/TestHiveMetaStoreGetMetaConf.java
  metastore/src/test/org/apache/hadoop/hive/metastore/TestHiveMetaStorePartitionSpecs.java
Labels: tests failed

#5111 HIVE-28102: Iceberg: Invoke validateDataFilesExist for RowDelta operations.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/FilesForCommit.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergCopyOnWriteRecordWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergDeleteWriter.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/TestHiveIcebergDeleteWriter.java
Labels: tests passed

#5086 HIVE-28076: Selecting data from a bucketed table with decimal column type throwing NPE.
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/FixedBucketPruningOptimizer.java
  ql/src/test/queries/clientpositive/bucket_decimal_col_select.q
  ql/src/test/results/clientpositive/llap/bucket_decimal_col_select.q.out
Labels: tests passed

#5115 HIVE-27172: (2.3) Add the HMS client connection timeout config
  common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  metastore/src/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  metastore/src/test/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java
Labels: tests failed

#5107 HIVE-27925: Addendum: HiveConf: unify ConfVars enum and use underscore for better readability
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStatistics.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/hooks/TestHs2Hooks.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/tools/metatool/TestHiveMetaTool.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactorBase.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMRCompactorOnTez.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniHS2.java
  itests/hive-unit/src/test/java/org/apache/hive/service/auth/jwt/TestHttpJwtAuthentication.java
  itests/hive-unit/src/test/java/org/apache/hive/service/auth/saml/TestHttpSamlAuthentication.java
  itests/hive-unit/src/test/java/org/apache/hive/service/server/TestGracefulStopHS2.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/add/AbstractAddPartitionAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/concatenate/AlterTableConcatenateAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/ColumnStatsSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/StatsFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java
  ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/TestFileSinkOperator.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
  ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java
Labels: tests passed

#4653 HIVE-27663 - implement array_position UDF in Hive
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/AbstractGenericUDFArrayBase.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayPosition.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayPosition.java
  ql/src/test/queries/clientpositive/udf_array_position.q
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_position.q.out
Labels: tests passed, stale

#5109 HIVE-28100. Fix Some Typos in CachedStore.
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
Labels: tests passed

#5054 HIVE-28051: LLAP: cleanup local folders on startup and periodically
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LocalDirCleaner.java
  llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemon.java
Labels: tests passed

#5106 HIVE-28098: Fails to copy empty column statistics of materialized CTE
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/cte_mat_11.q
  ql/src/test/results/clientpositive/llap/cte_mat_11.q.out
Labels: tests passed

#4761 HIVE-27653: Iceberg: Add conflictDetectionFilter to validate concurre…
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerStub.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestConflictingDataFiles.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestUtilPhaser.java
Labels: tests passed

#4820 HIVE-27746: Hive Metastore should send single AlterPartitionEvent wit…
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
  ql/src/java/org/apache/hadoop/hive/ql/cache/results/QueryResultsCache.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AlterPartitionsHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/EventHandlerFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/message/TableHandler.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreEventListener.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreListenerNotifier.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/AlterPartitionsEvent.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/AlterPartitionsMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/EventMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageBuilder.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageDeserializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/JSONAlterPartitionsMessage.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/JSONMessageDeserializer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/gzip/DeSerializer.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/events/TestAlterPartitionsEvent.java
Labels: tests passed

#4883 HIVE-27897 : Backport of HIVE-22373, HIVE-25553, HIVE-23561, HIVE-24321, HIVE-22856, HIVE-22973, HIVE-21729, HIVE-23022, HIVE-23034, HIVE-22221, HIVE-23230
  accumulo-handler/src/java/org/apache/hadoop/hive/accumulo/serde/AccumuloSerDe.java
  contrib/src/java/org/apache/hadoop/hive/contrib/serde2/TypedBytesSerDe.java
  data/files/datatypes.txt
  druid-handler/src/java/org/apache/hadoop/hive/druid/serde/DruidSerDe.java
  hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseSerDe.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/HCatRecordSerDe.java
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java
  itests/custom-serde/src/main/java/org/apache/hadoop/hive/serde2/CustomSerDe1.java
  itests/custom-serde/src/main/java/org/apache/hadoop/hive/serde2/CustomSerDe2.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/AbstractTestJdbcGenericUDTFGetSplits.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/BaseJdbcWithMiniLlap.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcGenericUDTFGetSplits.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcGenericUDTFGetSplits2.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapArrow.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapRow.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapVectorArrow.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestNewGetSplitsFormat.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/cbo_rp_TestJdbcDriver2.java
  itests/test-serde/src/main/java/org/apache/hadoop/hive/serde2/TestSerDe.java
  jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcSerDe.java
  llap-client/src/java/org/apache/hadoop/hive/llap/LlapInputSplit.java
  llap-ext-client/src/java/org/apache/hadoop/hive/llap/LlapArrowBatchRecordReader.java
  llap-ext-client/src/java/org/apache/hadoop/hive/llap/LlapArrowRowRecordReader.java
  llap-ext-client/src/java/org/apache/hadoop/hive/llap/LlapBaseInputFormat.java
  pom.xml
  ql/src/java/org/apache/hadoop/hive/llap/LlapArrowRecordWriter.java
  ql/src/java/org/apache/hadoop/hive/llap/WritableByteChannelAdapter.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/AbstractFileMergeOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Deserializer.java
  ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
  ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSerde.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/serde/ParquetHiveSerDe.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits2.java
  ql/src/test/org/apache/hadoop/hive/ql/io/arrow/TestArrowColumnarBatchSerDe.java
  ql/src/test/results/clientpositive/show_functions.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/AbstractSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/JsonSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/MetadataTypedColumnsetSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/NullStructSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
  serde/src/java/org/apache/hadoop/hive/serde2/RegexSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/TypedSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/binarysortable/BinarySortableSerDe.java
  serde/src/java/org/apache/hadoop/hive/serde2/thrift/ThriftJDBCBinarySerDe.java
Labels: tests passed

#5114 HIVE-28104. (2.3) Move HTTP related methods from Utils to HttpUtils in shims
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/Main.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/HttpUtils.java
  shims/common/src/main/java/org/apache/hadoop/hive/shims/Utils.java
Labels: tests failed

#5132 [HIVE-28123] Add Generated Protobuf code for 3.24.4 Upgrade
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/daemon/rpc/LlapDaemonProtocolProtos.java
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/plugin/rpc/LlapPluginProtocolProtos.java
  ql/src/gen/protobuf/gen-java/org/apache/hadoop/hive/ql/hooks/proto/HiveHookEvents.java
  ql/src/gen/protobuf/gen-test/org/apache/hadoop/hive/ql/io/protobuf/SampleProtos.java
Labels: tests passed

#5127 HIVE-28119: Iceberg: Allow insert clause with a column list in Merge query not_matched condition
  iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_partitioned.q
  iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_unpartitioned.q
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out
  ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteMergeRewriter.java
Labels: tests passed

#5140 HIVE-28134: Improve SecureCmdDoAs.
  ql/src/java/org/apache/hadoop/hive/ql/exec/SecureCmdDoAs.java
Labels: tests passed

#5133 HIVE-28111: FSCountersSummary is only printed when LLAP IO is enabled
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
Labels: tests passed

#5076 HIVE-28069: Iceberg: Implement Merge task functionality for Iceberg tables
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMergeTaskProperties.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_merge_files.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_merge_files.q.out
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/ConditionalResolverMergeFiles.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MergeTaskProperties.java
Labels: tests passed

#5148 HIVE-27467. (2.3) NOTICE files use incorrect wording "developed by" instead of "developed at"
  NOTICE
  storage-api/NOTICE
Labels: tests failed

#5149 HIVE-27468: (2.3) Restore original license in PriorityBlockingDeque
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/PriorityBlockingDeque.java
  pom.xml
Labels: tests failed

#5146 HIVE-25665. (2.3) Checkstyle LGPL files must not be in the release sources/binaries
  checkstyle/checkstyle-noframes-sorted.xsl
Labels: tests failed

#5152 HIVE-28142: Fix flakyness in acid_bloom_filter_orc_file_dump
  ql/src/test/queries/clientpositive/acid_bloom_filter_orc_file_dump.q
Labels: tests passed

#5112 HIVE-28099: Fix logging in HMS benchmarks
  standalone-metastore/metastore-tools/metastore-benchmarks/README.md
  standalone-metastore/metastore-tools/metastore-benchmarks/pom.xml
Labels: tests passed

#5134 HIVE-28087: Iceberg: Timestamp partition columns with transforms are not correctly sorted during insert
  data/files/query-hive-28087.csv
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergDay.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergHour.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergMonth.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergYear.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_clustered.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_clustered.q.out
  itests/src/test/resources/testconfiguration.properties
  serde/src/java/org/apache/hadoop/hive/serde2/io/TimestampLocalTZWritable.java
  serde/src/java/org/apache/hadoop/hive/serde2/io/TimestampWritableV2.java
Labels: tests passed

#4755 HIVE-27751 Log Query Compilation summary in an accumulated way
  common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java
  ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
  ql/src/java/org/apache/hadoop/hive/ql/QueryCompilationSummaryHook.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/test/queries/clientpositive/querycompilesummaryhook.q
  ql/src/test/results/clientpositive/llap/querycompilesummaryhook.q.out
Labels: tests passed

#5144 HIVE-28139: Upgrade to datasketches 1.2.0
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5121 HIVE-27671 - Implement array_append UDF to append an element to array
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayAppend.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayAppend.java
  ql/src/test/queries/clientnegative/udf_array_append_1.q
  ql/src/test/queries/clientnegative/udf_array_append_2.q
  ql/src/test/queries/clientpositive/udf_array_append.q
  ql/src/test/results/clientnegative/udf_array_append_1.q.out
  ql/src/test/results/clientnegative/udf_array_append_2.q.out
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_append.q.out
Labels: tests passed

#5138 HIVE-28130: Iceberg: Add support for Rename Branch.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergBranchExec.java
  iceberg/iceberg-handler/src/test/queries/positive/rename_iceberg_branch.q
  iceberg/iceberg-handler/src/test/results/positive/rename_iceberg_branch.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/branch/rename/AlterTableRenameSnapshotRefAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableSnapshotRefSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
Labels: tests passed

#5162 HIVE-28069: Addendum: Iceberg: Implement Merge task functionality for Iceberg tables - Add serde properties for CTAS and CMV
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_merge_files.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_merge_files.q.out
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
Labels: tests passed

#5155 HIVE-28129 Execute statement doesnot report the correct query string information
  ql/src/java/org/apache/hadoop/hive/ql/parse/ExecuteStatementAnalyzer.java
  ql/src/test/results/clientpositive/llap/prepare_plan.q.out
  ql/src/test/results/clientpositive/llap/prepare_plan_partition_pruning.q.out
Labels: tests passed

#5063 HIVE-28062: Optimize get_partitions_by_names in direct sql
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestMetaStoreLimitPartitionRequest.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#5151 HIVE-25054: (2.3) Drop vulnerable jodd-core dependency
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/DateTimeStamp.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/JDateTime.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/JDateTimeDefault.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/JulianDateStamp.java
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/TimeUtil.java
  service/src/resources/hive-webapps/hiveserver2/hiveserver2.jsp
Labels: tests failed

#5079 HIVE-28028: Remove duplicated proto reader/writer classes introduced in HIVE-19288
  itests/hive-unit/pom.xml
  pom.xml
  ql/pom.xml
  ql/src/java/org/apache/tez/dag/history/logging/proto/DatePartitionedLogger.java
  ql/src/java/org/apache/tez/dag/history/logging/proto/ProtoMessageReader.java
  ql/src/java/org/apache/tez/dag/history/logging/proto/ProtoMessageWritable.java
  ql/src/java/org/apache/tez/dag/history/logging/proto/ProtoMessageWriter.java
  ql/src/java/org/apache/tez/dag/history/logging/proto/package-info.java
Labels: tests passed
