Repository apache/hive, pull requests merged in 2024-06, with the labels that each got.

#5260 HIVE-28276: Iceberg:Make Iceberg split threads configurable when table scanning
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
Labels: tests passed

#5245 HIVE-28254: CBO (Calcite Return Path): Multiple DISTINCT leads to wrong results
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/opconventer/HiveGBOpConvUtil.java
  ql/src/test/queries/clientpositive/cbo_rp_groupby3_noskew_multi_distinct.q
  ql/src/test/results/clientpositive/llap/cbo_rp_groupby3_noskew_multi_distinct.q.out
  ql/src/test/results/clientpositive/llap/count.q.out
Labels: tests passed

#5098 HIVE-28091: Remove invalid long datatype in ColumnStatsUpdateTask
  ql/src/java/org/apache/hadoop/hive/ql/exec/ColumnStatsUpdateTask.java
Labels: tests passed

#5234 HIVE-28244: Add SBOM for storage-api and standalone-metastore modules
  standalone-metastore/pom.xml
  storage-api/pom.xml
Labels: tests passed

#5278 HIVE-27847: Casting NUMERIC types to TIMESTAMP is prohibited
  data/conf/hive-site.xml
  hbase-handler/src/test/queries/positive/hbase_timestamp.q
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFTimestamp.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/expressions/TestVectorFilterCompare.java
  ql/src/test/queries/clientnegative/strict_numeric_to_timestamp_conversion.q
  ql/src/test/queries/clientpositive/non_strict_numeric_to_timestamp_conversion.q
  ql/src/test/queries/clientpositive/udf_configurable.q
  ql/src/test/results/clientnegative/strict_numeric_to_timestamp_conversion.q.out
  ql/src/test/results/clientpositive/tez/non_strict_numeric_to_timestamp_conversion.q.out
  ql/src/test/results/clientpositive/tez/udf_configurable.q.out
Labels: tests passed

#5265 HIVE-27498: Support custom delimiter in SkippingTextInputFormat
  data/files/header_footer_table_4/0003.txt
  ql/src/java/org/apache/hadoop/hive/ql/io/SkippingTextInputFormat.java
  ql/src/test/queries/clientpositive/file_with_delimiter.q
  ql/src/test/results/clientpositive/llap/file_with_delimiter.q.out
Labels: tests passed

#5281 HIVE-28305: ProfileServlet: add html to output formats and prepare for profiler 3.0
  common/src/java/org/apache/hive/http/ProfileServlet.java
Labels: tests passed

#5269 HIVE-28286: Add filtering support for get_table_metas (Naveen Gangam)
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
Labels: tests passed

#5271 HIVE-28291: Fix Partition spec is incorrect in getPartitionsByFilter RPC
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Labels: tests passed

#5289 HIVE-28312: Save query error message on Driver level
  ql/src/java/org/apache/hadoop/hive/ql/Driver.java
  ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
  ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java
  ql/src/test/org/apache/hadoop/hive/ql/TestDriver.java
Labels: tests passed

#5285 HIVE-28309: fixed Task Execution Summary duration is not displayed
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/RenderStrategy.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
Labels: tests passed

#5282 HIVE-28306: Iceberg: Return new scan after applying column project parameter
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java
Labels: tests passed

#5293 HIVE-28323: Iceberg: Allow reading tables irrespective whether they were created with hive engined enabled or not.
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q
  iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
Labels: tests passed

#5298 HIVE-28325: Slow compilation without owner information with Ranger au…
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HivePrivilegeObject.java
  ql/src/test/results/clientpositive/llap/authorization_privilege_objects.q.out
Labels: tests passed

#5304 HIVE-28324: HIVE_CLUSTER_ID in env: unified way to mark a cluster
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/StartMiniHS2Cluster.java
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java
  pom.xml
  ql/src/java/org/apache/hadoop/hive/ql/ServiceContext.java
  ql/src/test/org/apache/hadoop/hive/ql/TestServiceContext.java
  service/src/java/org/apache/hive/service/server/HiveServer2.java
Labels: tests passed

#5296 HIVE-28330: Fix a typo in the example output of UDFHex
  ql/src/java/org/apache/hadoop/hive/ql/udf/UDFHex.java
  ql/src/test/results/clientpositive/llap/udf_hex.q.out
Labels: tests passed

#5280 HIVE-28304: Replace org.apache.log4j.Logger with org.slf4j.Logger
  accumulo-handler/src/test/org/apache/hadoop/hive/accumulo/TestHiveAccumuloHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/esri/HiveGeometryOIHelper.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/esri/ST_GeometryRelational.java
Labels: tests passed

#5206 HIVE-28205: Implement direct sql for get_partitions_ps_with_auth api
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/Util.java
Labels: tests passed

#5276 HIVE-28299: Iceberg: Optimize show partitions through column projection
  common/src/java/org/apache/hadoop/hive/conf/Constants.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
Labels: tests failed

#5314 HIVE-28324: HIVE_CLUSTER_ID in env: unified way to mark a cluster - addendum empty string default
  ql/src/java/org/apache/hadoop/hive/ql/ServiceContext.java
Labels: tests passed

#5292 HIVE-28307: Fast return when database exists and IF NOT EXISTS clause…
  ql/src/java/org/apache/hadoop/hive/ql/ddl/database/create/CreateDatabaseAnalyzer.java
  ql/src/test/results/clientpositive/llap/database.q.out
Labels: tests passed

#5320 HIVE-28348: TransactionalKafkaWriterTest hangs in precommit
  kafka-handler/src/test/org/apache/hadoop/hive/kafka/TransactionalKafkaWriterTest.java
Labels: tests pending

#5248 HIVE-28256: Iceberg: Major QB Compaction on partition level with evol…
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergCompactionService.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergMajorQueryCompactor.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_single_partition_with_evolution.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_single_partition_with_evolution2.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_single_partition.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_single_partition_with_evolution.q.out
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_single_partition_with_evolution2.q.out
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
Labels: tests passed

#5317 HIVE-28275: Iceberg: Add support for 'If Not Exists' and 'or Replace' for Create Tag.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergSnapshotRefExec.java
  iceberg/iceberg-handler/src/test/queries/positive/alter_table_create_tag.q
  iceberg/iceberg-handler/src/test/results/positive/alter_table_create_tag.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
Labels: tests passed

#5299 HIVE-28326: Fix StageIDsRearranger
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/StageIDsRearranger.java
  ql/src/test/results/clientpositive/llap/manyViewJoin.q.out
Labels: tests passed

#5270 HIVE-26018: Produce the same result for UNIQUEJOIN regardless of execution engine
  ql/src/java/org/apache/hadoop/hive/ql/exec/CommonJoinOperator.java
  ql/src/test/queries/clientpositive/uniquejoin2.q
  ql/src/test/results/clientpositive/llap/uniquejoin2.q.out
Labels: tests passed

#5324 HIVE-28352: Schematool fails to upgradeSchema on dbType=hive
  standalone-metastore/metastore-server/src/main/sql/hive/upgrade-3.1.0-to-4.0.0-alpha-1.hive.sql
  standalone-metastore/metastore-server/src/main/sql/hive/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.hive.sql
  standalone-metastore/metastore-server/src/main/sql/hive/upgrade-4.0.0-alpha-2-to-4.0.0-beta-1.hive.sql
  standalone-metastore/metastore-server/src/main/sql/hive/upgrade-4.0.0-beta-1-to-4.0.0.hive.sql
  standalone-metastore/metastore-server/src/main/sql/hive/upgrade-4.0.0-to-4.1.0.hive.sql
  standalone-metastore/metastore-server/src/main/sql/hive/upgrade.order.hive
Labels: tests passed

#5310 HIVE-28338: Client connection count is not correct in HiveMetaStore#close
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestHiveMetaStoreClient.java
Labels: tests passed

#5325 HIVE-28353: Iceberg: Reading *Files Metadata table files if the column is of TIMESTAMP type.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_metadata_table.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_metadata_table.q.out
Labels: tests passed
