Repository apache/hive, pull requests merged in 2024-04, with the labels that each got.

#5175 HIVE-28167: Full table deletion fails when converting to truncate for Iceberg and ACID tables
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  iceberg/iceberg-handler/src/test/queries/positive/delete_all_iceberg.q
  iceberg/iceberg-handler/src/test/results/positive/delete_all_iceberg.q.out
  ql/src/java/org/apache/hadoop/hive/ql/parse/DeleteSemanticAnalyzer.java
  ql/src/test/results/clientpositive/llap/delete_all_non_partitioned.q.out
  ql/src/test/results/clientpositive/llap/delete_all_partitioned.q.out
  ql/src/test/results/clientpositive/llap/insert_update_delete.q.out
Labels: tests passed

#5179 HIVE-28172: Iceberg: Truncate should work for V1 tables with partition evolution.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/negative/truncate_table_partition_spec_with_part_evolution.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_truncate_partition_with_evolution.q
  iceberg/iceberg-handler/src/test/results/negative/truncate_table_partition_spec_with_part_evolution.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_truncate_partition_with_evolution.q.out
Labels: tests passed

#5173 HIVE-28166: Iceberg: Truncate on branch operates on the main table.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/positive/truncate_iceberg_branch.q
  iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_branch.q.out
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/HiveTableName.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Labels: tests passed

#5118 HIVE-28037: Run multiple Qtest with Postgres
  itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreCliDriver.java
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestMetaStoreHandler.java
Labels: tests passed

#5161 HIVE-28148 - Implement array_compact UDF to remove all nulls from an …
  ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayCompact.java
  ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayCompact.java
  ql/src/test/queries/clientnegative/udf_array_compact_1.q
  ql/src/test/queries/clientpositive/udf_array_compact.q
  ql/src/test/results/clientnegative/udf_array_compact_1.q.out
  ql/src/test/results/clientpositive/llap/show_functions.q.out
  ql/src/test/results/clientpositive/llap/udf_array_compact.q.out
Labels: tests passed

#5136 HIVE-28126: Use added record count in cost model when rebuilding materialized view stored by iceberg
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc4.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc4.q.out
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc7.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveIncrementalRelMdRowCount.java
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_7.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_nulls.q.out
  storage-api/src/java/org/apache/hadoop/hive/common/type/SnapshotContext.java
Labels: tests passed

#4744 HIVE-27725: Remove redundant columns in TAB_COL_STATS and PART_COL_STATS tables
  metastore/scripts/upgrade/hive/hive-schema-4.1.0.hive.sql
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java
  ql/src/test/queries/clientpositive/sysdb.q
  ql/src/test/results/clientpositive/llap/constraints_explain_ddl.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdatePart.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/StatObjectConverter.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MPartitionColumnStatistics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MTableColumnStatistics.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/schematool/SchemaToolTaskMoveDatabase.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/schematool/SchemaToolTaskMoveTable.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/queries/FindColumnsWithStatsHandler.java
  standalone-metastore/metastore-server/src/main/resources/package.jdo
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.1.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-4.0.0-to-4.1.0.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.1.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-4.0.0-to-4.1.0.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.1.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-4.0.0-to-4.1.0.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.1.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-4.0.0-to-4.1.0.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.1.0.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-4.0.0-to-4.1.0.postgres.sql
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/Util.java
Labels: tests passed

#5039 HIVE-28036: Move checkLock method to TestTxnDbUtil
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
  ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
  ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
Labels: tests passed

#4954 HIVE-27957: Better error message for STORED BY
  ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
  ql/src/test/queries/clientnegative/create_table_stored_by_invalid1.q
  ql/src/test/queries/clientnegative/create_table_stored_by_invalid2.q
  ql/src/test/queries/clientnegative/create_table_stored_by_invalid3.q
  ql/src/test/results/clientnegative/create_table_stored_by_invalid1.q.out
  ql/src/test/results/clientnegative/create_table_stored_by_invalid2.q.out
  ql/src/test/results/clientnegative/create_table_stored_by_invalid3.q.out
Labels: tests passed

#5166 HIVE-28154: Throw friendly exception if the table does not support partition transform
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#5193 HIVE-28153: Flaky test TestConflictingDataFiles.testMultiFiltersUpdate
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestConflictingDataFiles.java
Labels: tests passed

#5139 HIVE-28133: Log the original exception in HiveIOExceptionHandlerUtil#handleRecordReaderException
  shims/common/src/main/java/org/apache/hadoop/hive/io/HiveIOExceptionHandlerUtil.java
Labels: tests passed

#5143 HIVE-28127: Exception when rebuilding materialized view with calculated columns on iceberg sources
  iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc5.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc5.q.out
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/MaterializedViewASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/NativeAcidMaterializedViewASTBuilder.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/NonNativeAcidMaterializedViewASTBuilder.java
Labels: tests passed

#5178 HIVE-28199: Fix docker issues with Hive 3.1.3 on Mac.
  packaging/src/docker/Dockerfile
  packaging/src/docker/docker-compose.yml
Labels: tests unstable

#5190 HIVE-28131: Iceberg: Add support for Replace Branch.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergBranchExec.java
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSnapshotOperations.java
  iceberg/iceberg-handler/src/test/queries/positive/replace_iceberg_branch.q
  iceberg/iceberg-handler/src/test/results/positive/replace_iceberg_branch.q.out
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/branch/replace/AlterTableReplaceBranchRefAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableSnapshotRefSpec.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/HiveOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/Operation2Privilege.java
Labels: tests unstable

#5200 HIVE-28203: Fix qtest mv_iceberg_orc5.q
  iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc5.q.out
Labels: tests passed

#4998 HIVE-26339: HIVE-26047 Related LIKE pattern issues
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/AbstractFilterStringColLikeStringScalar.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/FilterStringColLikeStringScalar.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/vector/expressions/TestVectorStringExpressions.java
Labels: tests passed

#5197 HIVE-28121: Use direct SQL for transactional altering table parameter (#5129)
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Labels: tests passed

#5203 HIVE-28121: Use direct SQL for transactional altering table parameter
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
  standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Labels: tests passed

#5185 HIVE-28188:Upgrade Postgres to 42.7.3 to target CVE-2024-1597
  beeline/src/test/org/apache/hive/beeline/TestBeelineArgParsing.java
  packaging/src/docker/README.md
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5123 HIVE-28077: Iceberg: Major QB Compaction on partition level
  common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergMajorQueryCompactor.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_single_partition.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_single_partition.q.out
  itests/src/test/resources/testconfiguration.properties
  ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/PartitionUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/service/CompactionExecutorFactory.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Labels: tests passed

#5211 HIVE-28210: Print Tez summary by default in tests
  data/conf/hive-site.xml
  data/conf/iceberg/llap/hive-site.xml
  data/conf/iceberg/tez/hive-site.xml
  data/conf/llap/hive-site.xml
  data/conf/perf/tpcds30tb/tez/hive-site.xml
  data/conf/tez/hive-site.xml
  packaging/src/docker/conf/hive-site.xml
Labels: tests passed

#5212 HIVE-28212: MiniHS2: use a base folder which is more likely writable on the local FS
  itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java
Labels: tests passed

#5220 HIVE-28226: Split Replication Commands from HiveParser.g.
  parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g
  parser/src/java/org/apache/hadoop/hive/ql/parse/ReplClauseParser.g
Labels: tests passed

#5214 HIVE-28217: Make default port effective
  jdbc/src/java/org/apache/hive/jdbc/Utils.java
  jdbc/src/test/org/apache/hive/jdbc/TestHiveConnection.java
Labels: tests passed

#5191 HIVE-28196: Preserve column stats when applying UDF upper/lower
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLower.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFUpper.java
  ql/src/test/queries/clientpositive/stats_uppper_lower.q
  ql/src/test/results/clientpositive/llap/groupby_grouping_sets_pushdown1.q.out
  ql/src/test/results/clientpositive/llap/reduce_deduplicate_extended.q.out
  ql/src/test/results/clientpositive/llap/stats_uppper_lower.q.out
  ql/src/test/results/clientpositive/llap/vector_udf1.q.out
  ql/src/test/results/clientpositive/llap/vectorized_string_funcs.q.out
  ql/src/test/results/clientpositive/nonmr_fetch.q.out
  ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query24.q.out
Labels: tests passed

#5204 HIVE-28121. (2.3) Use direct SQL for transactional altering table parameter
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
  metastore/src/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  metastore/src/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  metastore/src/java/org/apache/hadoop/hive/metastore/ObjectStore.java
  metastore/src/java/org/apache/hadoop/hive/metastore/RawStore.java
  metastore/src/java/org/apache/hadoop/hive/metastore/hbase/HBaseStore.java
  metastore/src/test/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
  metastore/src/test/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
  metastore/src/test/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
  metastore/src/test/org/apache/hadoop/hive/metastore/minihms/AbstractMetaStoreService.java
Labels: tests failed

#5221 HIVE-28227: Change the description of HIVE_OPTIMIZE_METADATA_DELETE config
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests passed

#5227 HIVE-20016: (2.3) Concurrency issue on SessionState setupAuth
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
Labels: tests failed
