Repository apache/hive, pull requests merged in 2024-01, with the labels that each got.

#4937 HIVE-27951: hcatalog dynamic partitioning fails with partition alread…
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/FileOutputCommitterContainer.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatDynamicPartitioned.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatExternalDynamicPartitioned.java
Labels: tests unstable

#4972 HIVE-27969: Add verbose logging for schema initialisation and metastore service in docker container
  packaging/src/docker/README.md
  packaging/src/docker/entrypoint.sh
Labels: tests passed

#4907 HIVE-27916: Increase tez.am.resource.memory.mb for TestIcebergCliDrver to 512MB
  data/conf/iceberg/tez/tez-site.xml
Labels: tests passed

#4977 HIVE-27978: Tests in hive-unit module are not running again
  itests/hive-unit/pom.xml
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestTimedOutTxnNotificationLogging.java
Labels: tests passed

#4901 HIVE-27911 : Drop database query failing with Invalid ACL Exception
  llap-client/src/java/org/apache/hadoop/hive/llap/registry/impl/LlapZookeeperRegistryImpl.java
  llap-client/src/java/org/apache/hadoop/hive/registry/impl/ZkRegistryBase.java
  llap-client/src/test/org/apache/hadoop/hive/llap/registry/impl/TestLlapZookeeperRegistryImpl.java
Labels: tests passed

#4920 HIVE-27937: Clarifying comments and xml configs around tez container size
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  data/conf/iceberg/llap/hive-site.xml
  data/conf/iceberg/llap/tez-site.xml
  data/conf/iceberg/tez/hive-site.xml
  data/conf/iceberg/tez/tez-site.xml
  data/conf/llap/hive-site.xml
  data/conf/llap/tez-site.xml
  data/conf/tez/tez-site.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezAvailableSlotsCalculator.java
Labels: tests passed

#4860 HIVE-27857: Do not check write permission while dropping external table or partition
  ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Labels: tests passed

#4958 HIVE-27988: Don't convert FullOuterJoin + filter to MapJoin
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/MapJoinProcessor.java
  ql/src/test/results/clientpositive/llap/mapjoin_filter_on_outerjoin_tez.q.out
  ql/src/test/results/clientpositive/llap/vector_outer_join_constants.q.out
Labels: tests passed

#4994 HIVE-27977: Fix ordering flakiness in TestHplSqlViaBeeLine
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Labels: tests passed

#4979 HIVE-27951: hcatalog dynamic partitioning fails with partition already exist error when exist parent partitions path
  hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/FileOutputCommitterContainer.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatDynamicPartitioned.java
  hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatExternalDynamicPartitioned.java
Labels: tests passed

#4976 HIVE-27974: Fix flaky test - TestReplicationMetricCollector.testSuccessStageFailure
  ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricCollector.java
Labels: tests passed

#4989 HIVE-27989: Wrong database name in MetaException from MetastoreDefaultTransformer.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDefaultTransformer.java
Labels: tests passed

#4015 HIVE-27023: Add setting to prevent tez session from being opened duri…
  cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
Labels: tests passed

#4965 HIVE-27492: HPL/SQL built-in functions like sysdate not working
  hplsql/src/main/antlr4/org/apache/hive/hplsql/Hplsql.g4
  hplsql/src/main/java/org/apache/hive/hplsql/Exec.java
  hplsql/src/main/java/org/apache/hive/hplsql/Var.java
  hplsql/src/main/java/org/apache/hive/hplsql/functions/BuiltinFunctions.java
  hplsql/src/main/java/org/apache/hive/hplsql/functions/FunctionDatetime.java
  hplsql/src/main/java/org/apache/hive/hplsql/functions/FunctionMisc.java
  hplsql/src/main/java/org/apache/hive/hplsql/functions/FunctionString.java
  hplsql/src/test/java/org/apache/hive/hplsql/TestHplsqlLocal.java
  hplsql/src/test/queries/local/cast.sql
  hplsql/src/test/queries/local/cast2.sql
  hplsql/src/test/queries/local/coalesce.sql
  hplsql/src/test/queries/local/concat.sql
  hplsql/src/test/queries/local/create_function3.sql
  hplsql/src/test/queries/local/create_function4.sql
  hplsql/src/test/queries/local/date.sql
  hplsql/src/test/queries/local/expr.sql
  hplsql/src/test/queries/local/if2.sql
  hplsql/src/test/queries/local/instr.sql
  hplsql/src/test/queries/local/interval.sql
  hplsql/src/test/queries/local/length.sql
  hplsql/src/test/queries/local/lower.sql
  hplsql/src/test/queries/local/mult_div.sql
  hplsql/src/test/queries/local/nvl.sql
  hplsql/src/test/queries/local/replace.sql
  hplsql/src/test/queries/local/timestamp.sql
  hplsql/src/test/queries/local/timestamp_iso.sql
  hplsql/src/test/queries/local/trim.sql
  hplsql/src/test/results/local/add.out.txt
  hplsql/src/test/results/local/cast.out.txt
  hplsql/src/test/results/local/cast2.out.txt
  hplsql/src/test/results/local/coalesce.out.txt
  hplsql/src/test/results/local/date.out.txt
  hplsql/src/test/results/local/declare.out.txt
  hplsql/src/test/results/local/expr.out.txt
  hplsql/src/test/results/local/instr.out.txt
  hplsql/src/test/results/local/interval.out.txt
  hplsql/src/test/results/local/invalid_syntax.out.txt
  hplsql/src/test/results/local/length.out.txt
  hplsql/src/test/results/local/lower.out.txt
  hplsql/src/test/results/local/nvl.out.txt
  hplsql/src/test/results/local/replace.out.txt
  hplsql/src/test/results/local/sub.out.txt
  hplsql/src/test/results/local/timestamp.out.txt
  hplsql/src/test/results/local/timestamp_iso.out.txt
  hplsql/src/test/results/local/to_char.out.txt
  hplsql/src/test/results/local/to_timestamp.out.txt
  hplsql/src/test/results/local/trim.out.txt
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Labels: tests passed

#4948 HIVE-27955: Missing Postgres driver when start services from Docker c…
  packaging/src/docker/README.md
  packaging/src/docker/docker-compose.yml
Labels: tests failed

#4968 HIVE-27406: Addendum: Query runtime optimization
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/commands/RemoveDuplicateCompleteTxnComponentsCommand.java
Labels: tests passed

#4996 HIVE-21520: Query 'Submit plan' time reported is incorrect
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
Labels: tests passed

#5011 HIVE-28001: Fix the flaky test TestLeaderElection
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionContext.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionFactory.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaseLeaderElection.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/leader/TestLeaderElection.java
Labels: tests failed

#5009 HIVE-27749: Addendum: Fix INSERT query
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0-alpha-2.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0-beta-1.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0-beta-2.mysql.sql
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/tools/schematool/TestSchemaToolForMetastore.java
Labels: tests unstable

#4831 HIVE-27827: Improve performance of direct SQL implement for getPartitionsByFilter
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java
  standalone-metastore/metastore-server/src/main/sql/derby/hive-schema-4.0.0-beta-2.derby.sql
  standalone-metastore/metastore-server/src/main/sql/derby/upgrade-4.0.0-beta-1-to-4.0.0-beta-2.derby.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/hive-schema-4.0.0-beta-2.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mssql/upgrade-4.0.0-beta-1-to-4.0.0-beta-2.mssql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/hive-schema-4.0.0-beta-2.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/mysql/upgrade-4.0.0-beta-1-to-4.0.0-beta-2.mysql.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/hive-schema-4.0.0-beta-2.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/oracle/upgrade-4.0.0-beta-1-to-4.0.0-beta-2.oracle.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0-beta-2.postgres.sql
  standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-4.0.0-beta-1-to-4.0.0-beta-2.postgres.sql
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java
  standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java
  standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
Labels: tests passed

#4995 HIVE-27994: Optimize renaming the partitioned table
  ql/src/test/queries/clientpositive/rename_table.q
  ql/src/test/results/clientpositive/llap/rename_table.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdatePart.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/StatObjectConverter.java
Labels: tests passed

#4981 HIVE-27960:Invalid function error when using custom udaf
  data/files/datasets/temp_udaf/load.hive.sql
  ql/src/java/org/apache/hadoop/hive/ql/exec/Registry.java
  ql/src/test/queries/clientpositive/ptf_register_use.q
  ql/src/test/results/clientpositive/llap/ptf_register_use.q.out
Labels: tests passed

#4978 HIVE-27979: HMS alter_partitions log adds table name
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
Labels: tests passed

#5013 HIVE-28008: Missing try-with-resources in ParquetHiveSerDe
  ql/src/java/org/apache/hadoop/hive/ql/io/parquet/serde/ParquetHiveSerDe.java
Labels: tests passed

#5005 HIVE-27489: HPL/SQL does not support table aliases on column names in loops.
  hplsql/src/main/java/org/apache/hive/hplsql/Stmt.java
  itests/hive-unit/pom.xml
  itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Labels: tests passed

#5015 HIVE-28009: Shared work optimizer ignores schema merge setting in case of virtual column difference
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_unpartitioned.q.out
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
  ql/src/test/queries/clientpositive/sharedwork_virtualcol_schema_merge.q
  ql/src/test/results/clientpositive/llap/sharedwork_virtualcol_schema_merge.q.out
Labels: tests passed

#4988 HIVE-27991: Utilise FanoutWriters when inserting records in an Iceberg table when the records are unsorted
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergRecordWriter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java
  iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/DynamicPartitionCtx.java
  ql/src/java/org/apache/hadoop/hive/ql/security/authorization/HiveCustomStorageHandlerUtils.java
Labels: tests passed

#4999 HIVE-26713: StringExpr ArrayIndexOutOfBoundsException with LIKE '%xxx%'
  data/files/control_characters.txt
  ql/src/test/queries/clientpositive/like_control_characters.q
  ql/src/test/results/clientpositive/llap/like_control_characters.q.out
  storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/StringExpr.java
  storage-api/src/test/org/apache/hadoop/hive/ql/exec/vector/expressions/TestStringExpr.java
Labels: tests passed

#5016 HIVE-28016: Iceberg: NULL column values handling in COW mode
  iceberg/iceberg-handler/src/test/queries/positive/delete_iceberg_copy_on_write_unpartitioned.q
  iceberg/iceberg-handler/src/test/queries/positive/delete_iceberg_mixed.q
  iceberg/iceberg-handler/src/test/queries/positive/delete_iceberg_unpartitioned_parquet.q
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_copy_on_write_unpartitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_mixed.q.out
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_unpartitioned_parquet.q.out
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_unpartitioned.q.out
  ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteDeleteRewriter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteMergeRewriter.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteUpdateRewriter.java
Labels: tests passed

#4927 HIVE-27942: Missing aux jar errors during LLAP launch
  llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCopyAuxJars.java
Labels: tests passed

#5017 HIVE-28005: Remove upgrade-acid module
  packaging/src/main/assembly/src.xml
  pom.xml
  upgrade-acid/pom.xml
  upgrade-acid/pre-upgrade/pom.xml
  upgrade-acid/pre-upgrade/src/main/java/org/apache/hadoop/hive/upgrade/acid/CloseableThreadLocal.java
  upgrade-acid/pre-upgrade/src/main/java/org/apache/hadoop/hive/upgrade/acid/CompactTablesState.java
  upgrade-acid/pre-upgrade/src/main/java/org/apache/hadoop/hive/upgrade/acid/CompactionMetaInfo.java
  upgrade-acid/pre-upgrade/src/main/java/org/apache/hadoop/hive/upgrade/acid/NamedForkJoinWorkerThreadFactory.java
  upgrade-acid/pre-upgrade/src/main/java/org/apache/hadoop/hive/upgrade/acid/PreUpgradeTool.java
  upgrade-acid/pre-upgrade/src/main/java/org/apache/hadoop/hive/upgrade/acid/RunOptions.java
  upgrade-acid/pre-upgrade/src/test/java/org/apache/hadoop/hive/upgrade/acid/TestCloseableThreadLocal.java
  upgrade-acid/pre-upgrade/src/test/java/org/apache/hadoop/hive/upgrade/acid/TestPreUpgradeTool.java
  upgrade-acid/pre-upgrade/src/test/java/org/apache/hadoop/hive/upgrade/acid/TestRunOptions.java
Labels: tests passed

#5006 HIVE-27993 : Netty4 ShuffleHandler: should use 1 boss thread
  llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
Labels: tests passed

#5030 HIVE-28030: LLAP util code refactor
  llap-common/src/java/org/apache/hadoop/hive/llap/security/LlapSignerImpl.java
Labels: tests passed

#4905 HIVE-27914: Fix the missing partitions judgement in drop_partitions_req
  ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#5023 HIVE-28020: Iceberg: Upgrade iceberg version to 1.4.3
  iceberg/patched-iceberg-core/pom.xml
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/PartitionsTable.java
  iceberg/pom.xml
Labels: tests passed

#5018 HIVE-28017: Add generated protobuf code.
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/daemon/rpc/LlapDaemonProtocolProtos.java
  llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/plugin/rpc/LlapPluginProtocolProtos.java
  ql/src/gen/protobuf/gen-java/org/apache/hadoop/hive/ql/hooks/proto/HiveHookEvents.java
  ql/src/gen/protobuf/gen-test/org/apache/hadoop/hive/ql/io/protobuf/SampleProtos.java
Labels: tests passed

#5007 HIVE-28000: Fix scenarios where 'not in' gives incorrect results due to type coercion
  ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java
  ql/src/test/queries/clientpositive/not_in_scenarios.q
  ql/src/test/results/clientpositive/llap/in_coercion.q.out
  ql/src/test/results/clientpositive/llap/not_in_scenarios.q.out
  ql/src/test/results/clientpositive/llap/orc_llap_counters.q.out
Labels: tests passed
