Repository apache/hive, pull requests merged in 2025-05, with the labels that each got.

#5799 HIVE-28920: Unstable tests due to unixtimestamp() and constant folding
  ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_1.q
  ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_10.q
  ql/src/test/queries/clientpositive/partition_unix_timestamp.q
  ql/src/test/results/clientpositive/llap/cbo_join_transitive_pred_loop_1.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_10.q.out
  ql/src/test/results/clientpositive/llap/partition_unix_timestamp.q.out
Labels: tests passed

#5769 HIVE-28903: Skip deleting archived path when drop partition/table
  ql/src/test/queries/clientpositive/archive_drop.q
  ql/src/test/results/clientpositive/llap/archive_drop.q.out
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Labels: tests passed

#5788 HIVE-28934: PlanUtils.configureJobPropertiesForStorageHandler should use hive session configuration.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
Labels: tests passed

#5800 HIVE-28653: Jetty version disclosure in Hive
  common/src/java/org/apache/hive/http/HttpServer.java
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/Main.java
  itests/hive-unit/src/test/java/org/apache/hive/service/TestHttpServices.java
  service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Labels: tests passed

#5797 HIVE-28937: Static analysis issues fixed in shell scripts
  packaging/src/docker/build.sh
  packaging/src/docker/entrypoint.sh
Labels: tests unstable

#5801 HIVE-28924: Drop hive.optimize.join.disjunctive.transitive.predicates.pushdown and related logic
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinPushTransitivePredicatesRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_1.q
  ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_2.q
  ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_3.q
  ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_4.q
Labels: tests passed

#5798 HIVE-28938: Error in LATERAL VIEW with non native tables due to prese…
  hbase-handler/src/test/results/positive/hbase_queries.q.out
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_explain_formatted.q
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_multiple_lateral_views.q
  iceberg/iceberg-handler/src/test/results/positive/iceberg_explain_formatted.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_multiple_lateral_views.q.out
  kudu-handler/src/test/results/positive/kudu_complex_queries.q.out
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#5810 Add catalog name for CommitCompaction and ALLOC_WRITE_ID events while…
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
Labels: tests passed

#5806 HIVE-28946:Upgrade commons-io to 2.16.1
  pom.xml
Labels: tests passed

#5812 HIVE-28953: Remove HiveMetaStoreClientPreCatalog
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestCatalogNonDefaultSvr.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestCatalogOldClient.java
Labels: tests passed

#5807 HIVE-28947: Add ability to specify Compaction options in stats updater of compactor
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java
  ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestStatsUpdater.java
  ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/entities/CompactionInfo.java
Labels: tests passed

#5781 HIVE-28917: NPE in merge statement when checking nullability of joini…
  iceberg/iceberg-handler/src/test/queries/positive/merge_with_null_check_on_joining_col.q
  iceberg/iceberg-handler/src/test/results/positive/merge_with_null_check_on_joining_col.q.out
  ql/src/java/org/apache/hadoop/hive/ql/Context.java
Labels: tests passed

#5815 HIVE-28917: NPE in merge statement when checking nullability of joining column in matched clause - ADDENDUM
  iceberg/iceberg-handler/src/test/results/positive/merge_with_null_check_on_joining_col.q.out
Labels: tests pending

#5809 HIVE-28869: added --add-opens JVM options to support JDK 9 or higher.
  common/src/java/org/apache/hadoop/hive/common/JavaVersionUtils.java
  hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/tool/TempletonControllerJob.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecDriver.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
Labels: tests passed

#5813 HIVE-28789: Session-level metrics from Tez sessions
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolManager.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolManagerMetrics.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
  ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezSessionPoolManagerMetrics.java
Labels: tests passed

#5811 HIVE-28949: TestDbNotificationListener#createDatabase fails intermittently due to different createTime
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java
Labels: tests failed

#5789 HIVE-25948: Optimize Iceberg writes by directing records either to Clustered or Fanout writer
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMergeTaskProperties.java
  iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_partitioned_orc.q
  iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out
  ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/DynamicPartitionCtx.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/FileSinkDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/plan/MergeTaskProperties.java
Labels: tests passed

#5820 HIVE-28955: Tests using HiveConfForTest and Tez engine consume large amounts of disk space
  common/src/test/org/apache/hadoop/hive/conf/HiveConfForTest.java
Labels: tests passed

#5792 HIVE-28935: Iceberg: fix partition filtering condition in compaction query
  iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergQueryCompactor.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_minor_compaction_bucket.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_minor_compaction_bucket.q.out
  itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestIcebergCompactorOnTez.java
  itests/src/test/resources/testconfiguration.properties
Labels: tests passed

#5808 HIVE-28948: Drop obsolete ROWOFFSET virtual column and related code
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  hcatalog/src/test/e2e/templeton/deployers/config/hive/hive-site.mysql.xml
  ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/VirtualColumn.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/lineage/OpProcFactory.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/TableMask.java
Labels: tests passed

#5818 HIVE-28958: Tez job failed with: NoClassDefFoundError: org/locationtech/jts/geom/Geometry
  pom.xml
  ql/pom.xml
Labels: tests passed

#5826 HIVE-28968: In CI use dedicated project-local .m2 directory for storing maven artifacts
  Jenkinsfile
  pom.xml
Labels: tests passed

#5803 HIVE-28944: Mask File, data sizes in tests
  iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
  iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
  itests/util/src/main/java/org/apache/hadoop/hive/ql/QOutProcessor.java
  itests/util/src/test/java/org/apache/hadoop/hive/ql/TestQOutProcessor.java
  ql/src/test/results/clientnegative/table_nonprintable_negative.q.out
  ql/src/test/results/clientpositive/beeline/create_merge_compressed.q.out
  ql/src/test/results/clientpositive/erasurecoding/erasure_explain.q.out
  ql/src/test/results/clientpositive/erasurecoding/erasure_simple.q.out
  ql/src/test/results/clientpositive/llap/alter_merge.q.out
  ql/src/test/results/clientpositive/llap/alter_merge_orc.q.out
  ql/src/test/results/clientpositive/llap/alter_merge_stats.q.out
  ql/src/test/results/clientpositive/llap/alter_merge_stats_orc.q.out
  ql/src/test/results/clientpositive/llap/authorization_load.q.out
  ql/src/test/results/clientpositive/llap/autoColumnStats_6.q.out
  ql/src/test/results/clientpositive/llap/create_merge_compressed.q.out
  ql/src/test/results/clientpositive/llap/cttl.q.out
  ql/src/test/results/clientpositive/llap/exim_01_nonpart.q.out
  ql/src/test/results/clientpositive/llap/exim_02_part.q.out
  ql/src/test/results/clientpositive/llap/exim_04_all_part.q.out
  ql/src/test/results/clientpositive/llap/exim_05_some_part.q.out
  ql/src/test/results/clientpositive/llap/exim_06_one_part.q.out
  ql/src/test/results/clientpositive/llap/exim_16_part_external.q.out
  ql/src/test/results/clientpositive/llap/exim_17_part_managed.q.out
  ql/src/test/results/clientpositive/llap/exim_18_part_external.q.out
  ql/src/test/results/clientpositive/llap/exim_19_00_part_external_location.q.out
  ql/src/test/results/clientpositive/llap/exim_19_part_external_location.q.out
  ql/src/test/results/clientpositive/llap/exim_20_part_managed_location.q.out
  ql/src/test/results/clientpositive/llap/explainuser_1.q.out
  ql/src/test/results/clientpositive/llap/load_fs.q.out
  ql/src/test/results/clientpositive/llap/load_fs2.q.out
  ql/src/test/results/clientpositive/llap/load_overwrite.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_drop.q.out
  ql/src/test/results/clientpositive/llap/merge_dynamic_partition.q.out
  ql/src/test/results/clientpositive/llap/merge_dynamic_partition2.q.out
  ql/src/test/results/clientpositive/llap/merge_dynamic_partition3.q.out
  ql/src/test/results/clientpositive/llap/orc_merge1.q.out
  ql/src/test/results/clientpositive/llap/orc_merge10.q.out
  ql/src/test/results/clientpositive/llap/orc_merge2.q.out
  ql/src/test/results/clientpositive/llap/orc_merge3.q.out
  ql/src/test/results/clientpositive/llap/orc_merge4.q.out
  ql/src/test/results/clientpositive/llap/partition_wise_fileformat.q.out
  ql/src/test/results/clientpositive/llap/partition_wise_fileformat3.q.out
  ql/src/test/results/clientpositive/llap/repl_2_exim_basic.q.out
  ql/src/test/results/clientpositive/llap/repl_3_exim_metadata.q.out
  ql/src/test/results/clientpositive/llap/repl_4_exim_nocolstat.q.out
  ql/src/test/results/clientpositive/llap/show_tablestatus.q.out
  ql/src/test/results/clientpositive/llap/table_nonprintable.q.out
  ql/src/test/results/clientpositive/llap/temp_table_external.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition2.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition3.q.out
  ql/src/test/results/clientpositive/llap/temp_table_partition_wise_fileformat.q.out
  ql/src/test/results/clientpositive/tez/acid_vectorization_original_tez.q.out
  ql/src/test/results/clientpositive/tez/flatten_union_subdir.q.out
Labels: tests passed

#5824 HIVE-28962: Prevent committing outputs if an exception was thrown in the Tez processor
  ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
Labels: tests passed

#5711 HIVE-28841: Rename hive.metastore.catalog.* to hive.metastore.iceberg.catalog.*
  standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Labels: tests passed
