Repository apache/hive, pull requests merged in 2025-02, with the labels that each got.

#5036 HIVE-27855: Create external tables for Hive and Tez protologging events
  beeline/src/java/org/apache/hive/beeline/schematool/HiveSchemaTool.java
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestRestrictedList.java
  ql/src/test/results/clientpositive/llap/resourceplan.q.out
  ql/src/test/results/clientpositive/llap/strict_managed_tables_sysdb.q.out
  ql/src/test/results/clientpositive/llap/sysdb.q.out
  standalone-metastore/metastore-server/src/main/sql/hive/hive-schema-4.1.0.hive.sql
  standalone-metastore/metastore-server/src/main/sql/hive/upgrade-4.0.0-to-4.1.0.hive.sql
Labels: tests passed

#5626 HIVE-28729: Apply nulls order setting in Reduce Sink operator of join branches
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveInsertExchange4JoinRule.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
  ql/src/test/queries/clientpositive/cbo_rp_null_order.q
  ql/src/test/results/clientpositive/llap/cbo_rp_null_order.q.out
Labels: tests passed

#5632 HIVE-24110: NullPointerException occurs in some UDFs
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFCharacterLength.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLength.java
  ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFOctetLength.java
Labels: tests passed

#5631 HIVE-25043: Support custom UDF in Vectorized mode
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
Labels: tests passed

#5584 HIVE-28673: Fix issues in JSON SerDe implementations related to Decimal
  data/files/jsonserde.txt
  ql/src/test/queries/clientpositive/json_serde3.q
  ql/src/test/results/clientpositive/llap/json_serde3.q.out
  serde/src/java/org/apache/hadoop/hive/serde2/json/HiveJsonReader.java
Labels: tests passed

#5620 HIVE-28704: Upgrade pac4j core and opensamlv3 and exclude Javax.json
  pom.xml
  service/pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5617 HIVE-28622: Duplicate Entries in TXN_WRITE_NOTIFICATION_LOG Due to Oracle's Handling of Empty Strings
  hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
Labels: tests passed

#5625 HIVE-28730:Upgrade aws-java-sdk to 1.12.720
  pom.xml
Labels: tests passed

#5500 HIVE-28191: Upgrade Hadoop Version to 3.4.1
  common/src/java/org/apache/hadoop/hive/common/JvmMetrics.java
  itests/hcatalog-unit/pom.xml
  itests/hive-unit/src/test/java/org/apache/hive/service/auth/jwt/TestHttpJwtAuthentication.java
  itests/util/pom.xml
  itests/util/src/main/java/org/apache/hadoop/hive/hbase/HBaseTestSetup.java
  pom.xml
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/MetaToolTaskListExtTblLocs.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetastoreWithHttpJwt.java
  standalone-metastore/pom.xml
  storage-api/pom.xml
Labels: tests passed

#5582 HIVE-28668: Hive should emit fewer events for truncate table operation
  itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/message/TruncatePartitionHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AlterHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
Labels: tests passed

#5629 HIVE-28437: Add documentation for initializing the system schemas for HiveServer2 for Docker Image
  packaging/src/docker/README.md
  packaging/src/docker/entrypoint.sh
Labels: tests failed

#5614 HIVE-28705: Fix Data Inconsistency due to missing 'IS NOT? TRUE/FALSE' parsing in Partition Filter Pruning
  ql/src/test/queries/clientpositive/casewhen_isnot_boolean_partition.q
  ql/src/test/results/clientpositive/llap/casewhen_isnot_boolean_partition.q.out
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/PartFilterVisitor.java
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/PartitionFilter.g4
Labels: tests passed

#5640 HIVE-28751: Upgrade curator version from 5.2.0 to 5.7.1 to fix CVE-2023-2976
  pom.xml
  standalone-metastore/pom.xml
Labels: tests passed

#5622 HIVE-28727: Iceberg: Refactor IcebergTableUtil.toPartitionData
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
  iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partition_evolution.q
  iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution.q.out
Labels: tests passed

#5639 HIVE-28749: The default hikaricp.leakDetectionThreshold is not valid
  standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
Labels: tests passed

#5644 HIVE-28764: Iceberg: Throw Exception in case of Drop Partition on transformed column.
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  iceberg/iceberg-handler/src/test/queries/negative/iceberg_drop_partition_tranform_column.q
  iceberg/iceberg-handler/src/test/results/negative/iceberg_drop_partition_tranform_column.q.out
Labels: tests passed

#5638 HIVE-28748: Docker: Redirect daemon's logs to STDOUT
  packaging/src/docker/conf/hive-log4j2.properties
  packaging/src/docker/conf/hive-site.xml
Labels: tests passed

#5544 HIVE-28626: Display MoveTask/StatsTask duration on the query summary
  common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
  ql/src/java/org/apache/hadoop/hive/ql/exec/StatsTask.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
  ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java
Labels: tests passed

#5643 HIVE-28763: Iceberg: Support functions while expiring snapshots.
  iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergExpireSnapshots.java
  parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
  ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#5627 HIVE-28732: Sorted dynamic partition optimization does not apply hive.default.nulls.last
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition_transforms.q.out
  iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_overwrite_partition.q.out
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_partitioned_orc.q.out
  iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_partitioned.q.out
  iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_merge_mixed.q.out
  itests/hive-blobstore/src/test/results/clientpositive/insert_into_dynamic_partitions.q.out
  itests/hive-blobstore/src/test/results/clientpositive/insert_overwrite_dynamic_partitions.q.out
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/SortedDynPartitionOptimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/util/NullOrdering.java
  ql/src/test/results/clientpositive/llap/autoColumnStats_6.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_opt_bucketing.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_opt_vectorization.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_acid.q.out
  ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_acid2.q.out
  ql/src/test/results/clientpositive/llap/expanding_multivaluecolvector.q.out
  ql/src/test/results/clientpositive/llap/infer_bucket_sort_num_buckets.q.out
  ql/src/test/results/clientpositive/llap/insert_overwrite_preemption.q.out
  ql/src/test/results/clientpositive/llap/load_data_using_job.q.out
  ql/src/test/results/clientpositive/llap/load_dyn_part5.q.out
  ql/src/test/results/clientpositive/llap/load_static_ptn_into_bucketed_table.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
  ql/src/test/results/clientpositive/llap/materialized_view_partitioned_3.q.out
  ql/src/test/results/clientpositive/llap/merge_dynamic_partition.q.out
  ql/src/test/results/clientpositive/llap/merge_dynamic_partition2.q.out
  ql/src/test/results/clientpositive/llap/merge_dynamic_partition3.q.out
  ql/src/test/results/clientpositive/llap/mm_dp.q.out
  ql/src/test/results/clientpositive/llap/murmur_hash_migration2.q.out
  ql/src/test/results/clientpositive/llap/orc_merge10.q.out
  ql/src/test/results/clientpositive/llap/orc_merge2.q.out
  ql/src/test/results/clientpositive/llap/orc_merge7.q.out
  ql/src/test/results/clientpositive/llap/orc_merge_diff_fs.q.out
  ql/src/test/results/clientpositive/llap/orc_merge_incompat2.q.out
  ql/src/test/results/clientpositive/llap/partition_ctas.q.out
  ql/src/test/results/clientpositive/llap/partition_explain_ddl.q.out
  ql/src/test/results/clientpositive/llap/partitions_cols_dedup.q.out
  ql/src/test/results/clientpositive/llap/rcfile_merge2.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition2.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition3.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition4.q.out
  ql/src/test/results/clientpositive/llap/temp_table_merge_dynamic_partition5.q.out
  ql/src/test/results/clientpositive/llap/temp_table_partition_ctas.q.out
  ql/src/test/results/clientpositive/llap/union_remove_17.q.out
Labels: tests passed

#5646 HIVE-28769: Fix test: query_history.q.
  ql/src/test/results/clientpositive/llap/query_history.q.out
Labels: tests pending

#5636 HIVE-28417: Bump Log4j2 to 2.24.3
  data/conf/hive-log4j2.properties
  llap-server/pom.xml
  llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/QueryTracker.java
  llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemonLogging.java
  pom.xml
  standalone-metastore/metastore-server/pom.xml
  standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java
  standalone-metastore/pom.xml
Labels: tests passed

#5660 HIVE-28779: Add ozone filesystem to the exim uri schema whitelist.
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Labels: tests passed

#5650 HIVE-28774 Refactor NullOrder usage in iceberg write oder function
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
  ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/sortoder/SortFieldDesc.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#5647 HIVE-28768: Remove hardcoded post exec hooks
  common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
  data/conf/hive-site.xml
  data/conf/iceberg/llap/hive-site.xml
  data/conf/iceberg/tez/hive-site.xml
  data/conf/llap/hive-site.xml
  data/conf/mr/hive-site.xml
  data/conf/rlist/hive-site.xml
  data/conf/tez/hive-site.xml
  itests/hive-blobstore/src/test/resources/hive-site.xml
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/Optimizer.java
  ql/src/java/org/apache/hadoop/hive/ql/optimizer/lineage/Generator.java
  ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Labels: tests passed

#5642 HIVE-28759: Hive Query History - records are failed to be written due to iceberg worker pools shut down
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
  iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
  iceberg/patched-iceberg-core/pom.xml
  iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/SnapshotProducer.java
  ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
  ql/src/java/org/apache/hadoop/hive/ql/queryhistory/repository/IcebergRepository.java
Labels: tests passed
